# Bibliotheque + lecture Excel

In [1]:
import pandas as pd 
import numpy as np 
import os
import re
import datetime
from collections import defaultdict
import zipfile
from datetime import datetime, timedelta
from pathlib import Path

In [2]:
df = pd.read_excel('AGING_Ceinture_Montre (avec groupe).xlsx',sheet_name=None)

C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
df.keys()

dict_keys(['APHM', 'CAEN', 'POITIERS', 'ROUEN', 'LAVERAN', 'LPC', 'SAINTE-MARGUERITE', 'CGD', 'CERCA', 'Effectifs ceinture', 'Effectifs montre', 'CODEBOOK '])

# Vérification blocs

In [4]:
def convertir_heure_excel_ou_texte(x):
    if pd.isna(x):
        return pd.NaT
    if isinstance(x, (int, float)):
        # Excel stocke l'heure comme fraction de jour
        return pd.to_datetime(x, unit="D", origin="1899-12-30")
    s = str(x).strip().replace("h", ":")  # gère '13h58'
    try:
        return pd.to_datetime(s, format="%H:%M:%S")  # ajoute secondes
    except Exception:
        try:
            return pd.to_datetime(s, format="%H:%M")     # fallback H:M
        except Exception:
            try:
                return pd.to_datetime(s)                 # Pandas devine le format
            except Exception:
                return pd.NaT

In [5]:
def analyser_feuille_bloc(
    df,
    nom_feuille,
    col_debut,
    col_fin,
    nom_bloc
):
    print(f"\n--- Feuille : {nom_feuille} | {nom_bloc} ---")

    col_id = "Numero_inclusion"

    # ===============================
    # 🔧 DEBUG : normalisation ID
    # ===============================
    df = df.copy()
    df[col_id] = df[col_id].astype(str).str.upper().str.strip()

    # ==========================================================
    # 1️⃣ RÈGLES SPÉCIFIQUES CANDIDATS
    # ==========================================================
    REGLES_CANDIDATS = {
        ("CAEN", "bloc3", "0303PAR"): {"col_debut": "heure_rappel_cond_v2"},

        ("CAEN", "bloc3", "0305LCR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2S", "0314CDS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0314CDS"): {"col_debut": "heure_fluence_sem_v2"},
        
        ("CAEN", "bloc2S", "0335JMS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0335JMS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc3", "0339NPR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2S", "0346GLS"): { "col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0346GLS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2R", "0353LNR"): { "col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0353LNR"): {"col_debut": "heure_fluence_sem_v2"},

        ("POITIERS", "bloc2S", "0414PJS"): {"col_fin": "heure_fluence_sem_v2"},
        ("POITIERS", "bloc3", "0414PJS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CGD", "bloc2S", "0902SIS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CGD", "bloc3", "0902SIS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CGD", "bloc3", "0905SLR"): {"col_debut": "heure_nback_v2"},

        ("CGD", "bloc3", "0906DNR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CERCA", "bloc3", "0414PVR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0419SRR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0420MCR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc2S", "0421ACS"): {"col_fin": "heure_nback_v2"},
        ("CERCA", "bloc3", "0421ACS"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0423RMR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0424BLR"): {"col_debut": "heure_nback_v2"},
    }


    # ==========================================================
    # 2️⃣ INITIALISATION COLONNES
    # ==========================================================
    df["_col_debut"] = col_debut
    df["_col_fin"] = col_fin

    # ==========================================================
    # 3️⃣ RÈGLES GLOBALES
    # ==========================================================
    if nom_feuille == "SAINTE-MARGUERITE" and nom_bloc == "bloc2S":
        df["_col_fin"] = "heure_nback_v2"

    if nom_feuille == "SAINTE-MARGUERITE" and nom_bloc == "bloc3":
        df["_col_debut"] = "heure_nback_v2"

    # ==========================================================
    # 4️⃣ RÈGLES SPÉCIFIQUES (écrasent le global)
    # ==========================================================
    print("\n🔎 Vérification règles spécifiques :")

    for (centre, bloc, candidat), regle in REGLES_CANDIDATS.items():

        if centre != nom_feuille or bloc != nom_bloc:
            continue

        mask = df[col_id] == candidat

        if mask.any():
            print(f"🔧 Règle appliquée pour {candidat}")
            if "col_debut" in regle:
                df.loc[mask, "_col_debut"] = regle["col_debut"]
            if "col_fin" in regle:
                df.loc[mask, "_col_fin"] = regle["col_fin"]
        else:
            print(f"⚠️ {candidat} non trouvé dans cette feuille")

    # ==========================================================
    # 6️⃣ CONVERSION HEURES
    # ==========================================================
    df["_debut_ts"] = df.apply(
        lambda r: convertir_heure_excel_ou_texte(r[r["_col_debut"]]),
        axis=1
    )

    df["_fin_ts"] = df.apply(
        lambda r: convertir_heure_excel_ou_texte(r[r["_col_fin"]]),
        axis=1
    )

    # ==========================================================
    # 7️⃣ CALCUL DURÉE
    # ==========================================================
    col_duree = f"duree_{nom_bloc}"
    col_rejet = f"rejeter_{nom_bloc}"

    df[col_duree] = (df["_fin_ts"] - df["_debut_ts"]).dt.total_seconds() / 60
    df.loc[df[col_duree] < 0, col_duree] += 24 * 60

    # ==========================================================
    # 8️⃣ STATISTIQUES
    # ==========================================================
    mask_manquant = df[col_duree].isna()
    mask_valide = df[col_duree].notna() & (df[col_duree] > 0)

    moyenne = df.loc[mask_valide, col_duree].mean()
    ecart_type = df.loc[mask_valide, col_duree].std()

    print(f"\nMoyenne = {moyenne:.2f} min")
    print(f"Écart-type = {ecart_type:.2f} min")

    borne_inf = moyenne - 2 * ecart_type

    df[col_rejet] = 0
    df.loc[mask_manquant, col_rejet] = 2

    mask_rejet = df[col_duree] < borne_inf

    if nom_bloc == "bloc1":
        mask_rejet = mask_rejet | (df[col_duree] < 10)

    df.loc[mask_valide & mask_rejet, col_rejet] = 1

    # ==========================================================
    # 9️⃣ DEBUG CANDIDATS PROBLÉMATIQUES
    # ==========================================================
    print("\n🔎 DEBUG Candidats spécifiques :")

    candidats_test = [r[2] for r in REGLES_CANDIDATS.keys()]
    candidats_test = list(set(candidats_test))

    print(
        df.loc[
            df[col_id].isin(candidats_test),
            [col_id, col_duree, col_rejet]
        ]
    )

    # ==========================================================
    # 10️⃣ NETTOYAGE
    # ==========================================================
    df = df.drop(columns=["_col_debut", "_col_fin", "_debut_ts", "_fin_ts"])

    print(f"\nRésumé {col_rejet} :")
    print(df[col_rejet].value_counts().sort_index())

    return {
        "df": df,
        "moyenne": moyenne,
        "ecart_type": ecart_type,
        "rejets": {
            "manquant": df.loc[df[col_rejet] == 2, col_id].tolist(),
            "rejetes": df.loc[df[col_rejet] == 1, col_id].tolist()
        }
    }

## Bloc 1

In [6]:
feuilles = [
    'APHM', 'CAEN', 'POITIERS', 'ROUEN',
    'LAVERAN', 'LPC', 'SAINTE-MARGUERITE',
    'CGD', 'CERCA'
]

resultats_bloc1 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc1[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_montre_v2",   
        col_fin="heure_fin_anamnese_v2",        
        nom_bloc="bloc1"
    )

============================================================

--- Feuille : APHM | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 24.92 min
Écart-type = 10.54 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    25
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 19.05 min
Écart-type = 7.06 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
2           0303PAR         23.0              0
4           0305LCR         14.0              0
16          0314CDS         20.0              0
34          0335JMS         20.0              0
38          0339NPR         23.0              0
47          0346GLS         26.0              0
51          0353LNR         20.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    54
1     2
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 30.27 min
Écart-type = 7.98 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
13          0414PJS         32.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    15
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 24.93 min
Écart-type = 8.01 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
2     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 20.20 min
Écart-type = 4.82 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 14.47 min
Écart-type = 5.56 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    37
1     7
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 17.50 min
Écart-type = 6.80 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    6
1    2
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 24.40 min
Écart-type = 17.62 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc1  rejeter_bloc1
2          0902SIS         29.0              0
3          0906DNR         53.0              0
5          0905SLR         12.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc1 ---

🔎 Vérification règles spécifiques :

Moyenne = 170.78 min
Écart-type = 457.08 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
12          0414PVR         14.0              0
20          0419SRR         10.0              0
21          0420MCR         36.0              0
23          0421ACS         14.0              0
27          0423RMR         15.0              0
29          0424BLR         19.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
1     4
2    22
Name: count, dtype: int64

## Bloc 2

### Avec vidéo: de heure_rlri16imm_debut_V2 à heure_rappel_cond_v2

In [7]:
resultats_bloc2_R = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2_R[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_V2",  
        col_fin= "heure_rappel_cond_v2" ,  # Beaucoup de rejet car tous les S ont des NV car pas vu la vidéo         
        nom_bloc="bloc2R"
    )

============================================================

--- Feuille : APHM | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 44.92 min
Écart-type = 7.48 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    13
2    12
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2R ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0353LNR

Moyenne = 39.39 min
Écart-type = 5.17 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
2           0303PAR          43.0               0
4           0305LCR          44.0               0
16          0314CDS           NaN               2
34          0335JMS           NaN               2
38          0339NPR          34.0               0
47          0346GLS           NaN               2
51          0353LNR          39.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    27
1     1
2    28
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 41.80 min
Écart-type = 4.97 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
13          0414PJS           NaN               2

Résumé rejeter_bloc2R :
rejeter_bloc2R
0     5
2    10
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 37.71 min
Écart-type = 3.50 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    7
2    8
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 42.00 min
Écart-type = 10.71 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 39.44 min
Écart-type = 6.93 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    25
2    19
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 35.50 min
Écart-type = 3.32 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    4
2    4
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 46.67 min
Écart-type = 6.43 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc2R  rejeter_bloc2R
2          0902SIS           NaN               2
3          0906DNR          54.0               0
5          0905SLR          44.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    3
2    3
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2R ---

🔎 Vérification règles spécifiques :

Moyenne = 41.55 min
Écart-type = 6.22 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
12          0414PVR          43.0               0
20          0419SRR          34.0               0
21          0420MCR          36.0               0
23          0421ACS           NaN               2
27          0423RMR          42.0               0
29          0424BLR          39.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    11
2    29
Name: count, dtype: int64

resultats_bloc2_R

### Sans vidéo: de heure_rlri16imm_debut_V2 à heure_nback_v2

In [8]:
resultats_bloc2_S = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2_S[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_V2",
        col_fin="heure_nback_v2 (consigne)",
        nom_bloc="bloc2S"
    )

============================================================

--- Feuille : APHM | bloc2S ---

🔎 Vérification règles spécifiques :

Moyenne = 46.44 min
Écart-type = 9.26 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    25
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0314CDS
🔧 Règle appliquée pour 0335JMS
🔧 Règle appliquée pour 0346GLS

Moyenne = 40.08 min
Écart-type = 7.35 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
2           0303PAR           NaN               2
4           0305LCR           NaN               2
16          0314CDS          54.0               0
34          0335JMS          53.0               0
38          0339NPR           NaN               2
47          0346GLS          40.0               0
51          0353LNR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    49
1     2
2     5
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PJS

Moyenne = 47.60 min
Écart-type = 7.54 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
13          0414PJS          49.0               0

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    15
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2S ---

🔎 Vérification règles spécifiques :

Moyenne = 40.27 min
Écart-type = 6.83 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2S ---

🔎 Vérification règles spécifiques :

Moyenne = 41.80 min
Écart-type = 9.86 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2S ---

🔎 Vérification règles spécifiques :

Moyenne = 38.23 min
Écart-type = 6.31 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    44
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2S ---

🔎 Vérification règles spécifiques :

Moyenne = 42.12 min
Écart-type = 7.36 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0902SIS

Moyenne = 40.25 min
Écart-type = 6.13 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc2S  rejeter_bloc2S
2          0902SIS          34.0               0
3          0906DNR           NaN               2
5          0905SLR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    4
2    2
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0421ACS

Moyenne = 41.72 min
Écart-type = 5.93 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
12          0414PVR           NaN               2
20          0419SRR           NaN               2
21          0420MCR           NaN               2
23          0421ACS          36.0               0
27          0423RMR           NaN               2
29          0424BLR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    18
2    22
Name: count, dtype: int64

## Bloc 3

In [9]:
resultats_bloc3 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc3[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_nback_v2 (consigne)", 
        col_fin="heure_fin_tests_v2",        
        nom_bloc="bloc3"
    )

============================================================

--- Feuille : APHM | bloc3 ---

🔎 Vérification règles spécifiques :

Moyenne = 48.84 min
Écart-type = 8.85 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    24
1     1
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0303PAR
🔧 Règle appliquée pour 0305LCR
🔧 Règle appliquée pour 0314CDS
🔧 Règle appliquée pour 0335JMS
🔧 Règle appliquée pour 0339NPR
🔧 Règle appliquée pour 0346GLS
🔧 Règle appliquée pour 0353LNR

Moyenne = 43.02 min
Écart-type = 10.68 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
2           0303PAR         22.0              0
4           0305LCR         40.0              0
16          0314CDS         19.0              1
34          0335JMS         18.0              1
38          0339NPR         29.0              0
47          0346GLS         25.0              0
51          0353LNR         21.0              1

Résumé rejeter_bloc3 :
rejeter_bloc3
0    52
1     3
2     1
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PJS

Moyenne = 49.80 min
Écart-type = 10.28 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
13          0414PJS         22.0              1

Résumé rejeter_bloc3 :
rejeter_bloc3
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc3 ---

🔎 Vérification règles spécifiques :

Moyenne = 46.60 min
Écart-type = 8.76 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc3 ---

🔎 Vérification règles spécifiques :

Moyenne = 46.60 min
Écart-type = 6.31 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc3 ---

🔎 Vérification règles spécifiques :

Moyenne = 44.84 min
Écart-type = 5.81 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    44
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc3 ---

🔎 Vérification règles spécifiques :

Moyenne = 44.50 min
Écart-type = 8.21 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0902SIS
🔧 Règle appliquée pour 0905SLR
🔧 Règle appliquée pour 0906DNR

Moyenne = 43.17 min
Écart-type = 13.41 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc3  rejeter_bloc3
2          0902SIS         17.0              0
3          0906DNR         44.0              0
5          0905SLR         48.0              0

Résumé rejeter_bloc3 :
rejeter_bloc3
0    6
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PVR
🔧 Règle appliquée pour 0419SRR
🔧 Règle appliquée pour 0420MCR
🔧 Règle appliquée pour 0421ACS
🔧 Règle appliquée pour 0423RMR
🔧 Règle appliquée pour 0424BLR

Moyenne = 48.33 min
Écart-type = 4.93 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
12          0414PVR         49.0              0
20          0419SRR         42.0              0
21          0420MCR         46.0              0
23          0421ACS         43.0              0
27          0423RMR         50.0              0
29          0424BLR         49.0              0

Résumé rejeter_bloc3 :
rejeter_bloc3
0    23
1     1
2    16
Name: count, dtype: int64

resultats_bloc3

# Nombre de candidats qui passent toutes les conditions

In [10]:
'''
Un candidat est conservé si nous pouvons calculer la durée de tous ses blocs et si celles-ci respectent les conditions suivantes :
    - bloc 1 > 10 min
    - bloc2 et bloc 3 > mean - 2σ min
'''
    
def candidats_valides_tous_blocs_depuis_resultats(
    feuille,
    resultats_blocs,
    col_id="Numero_inclusion"
):
    """
    resultats_blocs = dict {
        "bloc1": resultats_bloc1,
        "bloc2S": resultats_bloc2_S,
        "bloc2R": resultats_bloc2_R,
        "bloc3": resultats_bloc3
    }
    """

    # Récupération du df de référence (bloc1 par ex)
    df_ref = resultats_blocs["bloc1"][feuille]["df"].copy()

    colonnes_rejet = []

    # Ajouter chaque colonne de rejet depuis chaque bloc
    for nom_bloc, res_bloc in resultats_blocs.items():
        col_rejet = f"rejeter_{nom_bloc}"
        if col_rejet not in res_bloc[feuille]["df"].columns:
            print(f"Colonne manquante : {col_rejet} dans {feuille}")
            return None

        df_ref[col_rejet] = res_bloc[feuille]["df"][col_rejet]
        colonnes_rejet.append(col_rejet)

    # Condition : tout à 0
    mask_valide = (df_ref[colonnes_rejet] == 0).all(axis=1)

    candidats_ok = df_ref.loc[mask_valide, col_id].tolist()
    candidats_rejetes = df_ref.loc[~mask_valide, col_id].tolist()

    print(f"\n=== {feuille} ===")
    print(f"Candidats valides sur TOUS les blocs : {len(candidats_ok)}")

    print("Liste des candidats conservés :")
    for pid in candidats_ok:
        print(f" - {pid}")

    return {
        "nb_valides": len(candidats_ok),
        "valides": candidats_ok,
        "rejetes": candidats_rejetes,
    }

In [11]:
resultats_globaux = {}

colonnes_blocs = [
    "rejeter_bloc1",
    "rejeter_bloc2S",
    "rejeter_bloc2R",
    "rejeter_bloc3"
]

for feuille in feuilles:
    print("\n" + "=" * 70)
    print(f"Analyse globale – Feuille : {feuille}")

    # ===== Base : bloc 1 =====
    df_global = resultats_bloc1[feuille]["df"][
        ["Numero_inclusion", "Condition", "rejeter_bloc1"]
    ].copy()

    # ===== Fusion bloc 2S =====
    df_global = df_global.merge(
        resultats_bloc2_S[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2S"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 2R =====
    df_global = df_global.merge(
        resultats_bloc2_R[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2R"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 3 =====
    df_global = df_global.merge(
        resultats_bloc3[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc3"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Affichage debug AVANT filtre =====
    print("\n📊 df_global AVANT fillna et filtres :")
    display(df_global)

    # ===== Sécurité : NaN → rejet (2) =====
    df_global[colonnes_blocs] = df_global[colonnes_blocs].fillna(2)

    # ===== Filtrage conditionnel S / R =====
    mask_S = (
        (df_global["Condition"] == "Standard") &
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2S"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    mask_R = (
        (df_global["Condition"] == "Réduction de la menace") &
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2R"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    mask_valide = mask_S | mask_R

    # ===== Extraction =====
    candidats_valides = df_global.loc[
        mask_valide, "Numero_inclusion"
    ].tolist()

    candidats_rejetes = df_global.loc[
        ~mask_valide, "Numero_inclusion"
    ].tolist()

    # ===== Résumés =====
    print(f"\nNombre total de candidats : {len(df_global)}")
    print(f"Candidats VALIDES (selon Condition) : {len(candidats_valides)}")
    print(f"Candidats REJETÉS : {len(candidats_rejetes)}")

    print("\nCandidats valides par condition :")
    print(df_global.loc[mask_valide, "Condition"].value_counts())

    print("\nListe des candidats valides :")
    for pid in candidats_valides:
        print(f" - {pid}")

    # ===== Stockage =====
    resultats_globaux[feuille] = {
        "df": df_global,
        "valides": candidats_valides,
        "rejetes": candidats_rejetes,
        "n_valides": len(candidats_valides),
        "n_rejetes": len(candidats_rejetes),
    }

======================================================================
Analyse globale – Feuille : APHM

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0101CAR,Réduction de la menace,0,0,0,0
1,0102PCR,Réduction de la menace,0,0,0,0
2,0103SHS,Standard,0,0,2,0
3,0105PNR,Réduction de la menace,0,0,0,0
4,0104FJS,Standard,0,0,2,0
5,0106JLS,Standard,0,0,2,0
6,0107DSS,Standard,0,0,2,0
7,0108BFS,Standard,0,0,2,0
8,0109GSS,Standard,0,0,2,0
9,0110LPR,Réduction de la menace,0,0,0,0
10,0111MNR,Réduction de la menace,0,0,0,0
11,0112BSR,Réduction de la menace,0,0,0,0
12,0113BMR,Réduction de la menace,0,0,0,0
13,0114LMS,Standard,0,0,2,0
14,0115CJR,Réduction de la menace,0,0,0,0
15,0116VAR,Réduction de la menace,0,0,0,0
16,0117POS,Standard,0,0,2,0
17,0118TNS,Standard,0,0,2,0
18,0119LJS,Standard,0,0,2,0
19,0120LCR,Réduction de la menace,0,0,0,0
20,0121MJR,Réduction de la menace,0,0,0,0
21,0122BDS,Standard,0,0,2,1
22,0123RMS,Standard,0,0,2,0
23,0124BAR,Réduction de la menace,0,0,0,0
24,0125BMR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 25
Candidats VALIDES (selon Condition) : 24
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Réduction de la menace    13
Standard                  11
Name: count, dtype: int64

Liste des candidats valides :
 - 0101CAR
 - 0102PCR
 - 0103SHS
 - 0105PNR
 - 0104FJS
 - 0106JLS
 - 0107DSS
 - 0108BFS
 - 0109GSS
 - 0110LPR
 - 0111MNR
 - 0112BSR
 - 0113BMR
 - 0114LMS
 - 0115CJR
 - 0116VAR
 - 0117POS
 - 0118TNS
 - 0119LJS
 - 0120LCR
 - 0121MJR
 - 0123RMS
 - 0124BAR
 - 0125BMR

======================================================================
Analyse globale – Feuille : CAEN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0301GNR,Réduction de la menace,0,0,0,0
1,0302ZMR,Réduction de la menace,0,0,0,0
2,0303PAR,Réduction de la menace,0,2,0,0
3,0304VMR,Réduction de la menace,0,0,0,0
4,0305LCR,Réduction de la menace,0,2,0,0
5,0307SMR,Réduction de la menace,0,0,0,0
6,0306MDR,Réduction de la menace,0,0,0,0
7,0308RGR,Réduction de la menace,0,0,0,0
8,0309DBS,Standard,0,0,2,0
9,0311CJS,Standard,0,0,2,0
10,0310ACS,Standard,0,0,2,0
11,0315VCS,Standard,0,0,2,0
12,0318PMS,Standard,0,0,2,0
13,0313FPR,Réduction de la menace,0,0,0,0
14,0312JMS,Standard,0,0,2,0
15,0316TMS,Standard,0,0,2,0
16,0314CDS,Standard,0,0,2,1
17,0317LGS,Standard,0,0,2,0
18,0319LJS,Standard,0,0,2,0
19,0320DGS,Standard,0,0,2,0
20,0321DRR,Réduction de la menace,0,0,0,0
21,0323RFS,Standard,0,0,2,0
22,0322RMS,Standard,0,0,2,0
23,0324LMR,Réduction de la menace,0,0,0,0
24,0325LCR,Réduction de la menace,0,0,0,0
25,0327IAR,Réduction de la menace,0,0,0,0
26,0326BJR,Réduction de la menace,0,0,0,0
27,0328MPR,Réduction de la menace,0,0,0,0
28,0330RTR,Réduction de la menace,0,0,0,0
29,0329NMR,Réduction de la menace,0,0,0,0
30,0331GRS,Standard,0,0,2,0
31,0332MCR,Réduction de la menace,0,0,0,0
32,0333MMS,Standard,0,0,2,0
33,0334TVS,Standard,0,0,2,0
34,0335JMS,Standard,0,0,2,1
35,0336CBS,Standard,0,0,2,0
36,0337BFS,Standard,0,0,2,0
37,0338JBS,Standard,1,1,2,0
38,0339NPR,Réduction de la menace,0,2,0,0
39,0340BAR,Réduction de la menace,1,2,1,2
40,0341LJS,Standard,0,0,2,0
41,0342VNS,Standard,0,0,2,0
42,0343PAS,Standard,0,0,2,0
43,0344DBS,Standard,0,1,2,0
44,0345LAR,Réduction de la menace,0,0,0,0
45,0349LLS,Standard,0,0,2,0
46,0347DMR,Réduction de la menace,0,0,0,0
47,0346GLS,Standard,0,0,2,0
48,0348GCR,Réduction de la menace,0,0,0,0
49,0350MYR,Réduction de la menace,0,0,0,0
50,0351FIR,Réduction de la menace,0,0,0,0
51,0353LNR,Réduction de la menace,0,2,0,1
52,0352RNR,Réduction de la menace,0,0,0,0
53,0354GKR,Réduction de la menace,0,0,0,0
54,0355BAS,Standard,0,0,2,0
55,0356DMS,Standard,0,0,2,0

Nombre total de candidats : 56
Candidats VALIDES (selon Condition) : 50
Candidats REJETÉS : 6

Candidats valides par condition :
Condition
Réduction de la menace    26
Standard                  24
Name: count, dtype: int64

Liste des candidats valides :
 - 0301GNR
 - 0302ZMR
 - 0303PAR
 - 0304VMR
 - 0305LCR
 - 0307SMR
 - 0306MDR
 - 0308RGR
 - 0309DBS
 - 0311CJS
 - 0310ACS
 - 0315VCS
 - 0318PMS
 - 0313FPR
 - 0312JMS
 - 0316TMS
 - 0317LGS
 - 0319LJS
 - 0320DGS
 - 0321DRR
 - 0323RFS
 - 0322RMS
 - 0324LMR
 - 0325LCR
 - 0327IAR
 - 0326BJR
 - 0328MPR
 - 0330RTR
 - 0329NMR
 - 0331GRS
 - 0332MCR
 - 0333MMS
 - 0334TVS
 - 0336CBS
 - 0337BFS
 - 0339NPR
 - 0341LJS
 - 0342VNS
 - 0343PAS
 - 0345LAR
 - 0349LLS
 - 0347DMR
 - 0346GLS
 - 0348GCR
 - 0350MYR
 - 0351FIR
 - 0352RNR
 - 0354GKR
 - 0355BAS
 - 0356DMS

======================================================================
Analyse globale – Feuille : POITIERS

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0401TSS,Standard,0,0,2,0
1,0402LLS,Standard,0,0,2,0
2,0403DCR,Réduction de la menace,0,0,0,0
3,0405FCR,Réduction de la menace,0,0,0,0
4,0404CYS,Standard,0,0,2,0
5,0406MCS,Standard,0,0,2,0
6,0407LJR,Réduction de la menace,0,0,0,0
7,0408BCS,Standard,0,0,2,0
8,0409PHR,Réduction de la menace,0,0,0,0
9,0410PGS,Standard,0,0,2,0
10,0413HFS,Standard,0,0,2,0
11,0411VES,Standard,0,0,2,0
12,0412ANS,Standard,0,0,2,0
13,0414PJS,Standard,0,0,2,1
14,0415VMR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 14
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Standard                  9
Réduction de la menace    5
Name: count, dtype: int64

Liste des candidats valides :
 - 0401TSS
 - 0402LLS
 - 0403DCR
 - 0405FCR
 - 0404CYS
 - 0406MCS
 - 0407LJR
 - 0408BCS
 - 0409PHR
 - 0410PGS
 - 0413HFS
 - 0411VES
 - 0412ANS
 - 0415VMR

======================================================================
Analyse globale – Feuille : ROUEN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0501MBS,Standard,0,0,2,0
1,0502LIR,Réduction de la menace,0,0,0,0
2,0503LCR,Réduction de la menace,0,0,0,0
3,0504BCS,Standard,0,0,2,0
4,0505PPR,Réduction de la menace,0,0,0,0
5,0506VMS,Standard,0,0,2,0
6,0508SRR,Réduction de la menace,0,0,0,0
7,0507BDS,Standard,0,0,2,0
8,0509LGS,Standard,0,0,2,0
9,0510DFS,Standard,0,0,0,0
10,0511LCS,Standard,0,0,2,0
11,0512RCR,Réduction de la menace,0,0,0,0
12,0513EBS,Standard,0,0,2,0
13,0514LPS,Standard,2,0,2,0
14,0515FAR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 14
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Standard                  8
Réduction de la menace    6
Name: count, dtype: int64

Liste des candidats valides :
 - 0501MBS
 - 0502LIR
 - 0503LCR
 - 0504BCS
 - 0505PPR
 - 0506VMS
 - 0508SRR
 - 0507BDS
 - 0509LGS
 - 0510DFS
 - 0511LCS
 - 0512RCR
 - 0513EBS
 - 0515FAR

======================================================================
Analyse globale – Feuille : LAVERAN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0626MCS,Standard,0,0,2,0
1,0628DMR,Réduction de la menace,0,0,0,0
2,0630RJR,Réduction de la menace,0,0,0,0
3,0629TCR,Réduction de la menace,0,0,0,0
4,0631LHR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 5
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 0

Candidats valides par condition :
Condition
Réduction de la menace    4
Standard                  1
Name: count, dtype: int64

Liste des candidats valides :
 - 0626MCS
 - 0628DMR
 - 0630RJR
 - 0629TCR
 - 0631LHR

======================================================================
Analyse globale – Feuille : LPC

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0101EMS,Standard,0,0,2,0
1,0102EMS,Standard,1,0,2,0
2,0103BPS,Standard,0,0,2,0
3,0104IBS,Standard,0,0,2,0
4,0105HAR,Réduction de la menace,1,0,0,0
5,0106DJR,Réduction de la menace,0,0,0,0
6,0107LER,Réduction de la menace,1,0,0,0
7,0108MMS,Standard,1,0,2,0
8,0109MJR,Réduction de la menace,0,0,0,0
9,0110RMS,Standard,0,0,2,0
10,0111TAS,Standard,1,0,2,0
11,0112DRR,Réduction de la menace,1,0,0,0
12,0113DGR,Réduction de la menace,0,0,0,0
13,0114MLR,Réduction de la menace,0,0,0,0
14,0115MHR,Réduction de la menace,0,0,0,0
15,0116CNR,Réduction de la menace,0,0,0,0
16,0117MSR,Réduction de la menace,0,0,0,0
17,0118TMS,Standard,0,0,2,0
18,0119BIR,Réduction de la menace,0,0,0,0
19,0120ANS,Standard,0,0,2,0
20,0121RPS,Standard,0,0,2,0
21,0122VCR,Réduction de la menace,0,0,0,0
22,0123GVS,Standard,0,0,2,0
23,0124PAS,Standard,0,0,2,0
24,0125AMR,Réduction de la menace,1,0,0,0
25,0126VLR,Réduction de la menace,0,0,0,0
26,0127CMS,Standard,0,0,2,0
27,0128ALS,Standard,0,0,2,0
28,0129APR,Réduction de la menace,0,0,0,0
29,0130FAR,Réduction de la menace,0,0,0,0
30,0131CPS,Standard,0,0,2,0
31,0132GAR,Réduction de la menace,0,0,0,0
32,0133BPS,Standard,0,0,2,0
33,0134IFR,Réduction de la menace,0,0,0,0
34,0135KLS,Standard,0,0,2,0
35,0136CJR,Réduction de la menace,0,0,0,0
36,0137BMS,Standard,0,0,2,0
37,0138NWR,Réduction de la menace,0,0,0,0
38,0139BMR,Réduction de la menace,0,0,0,0
39,0140LMR,Réduction de la menace,0,0,0,0
40,0141HJR,Réduction de la menace,0,0,0,0
41,0142LLS,Standard,0,0,2,0
42,0143EBR,Réduction de la menace,0,0,0,0
43,0144ZGR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 44
Candidats VALIDES (selon Condition) : 37
Candidats REJETÉS : 7

Candidats valides par condition :
Condition
Réduction de la menace    21
Standard                  16
Name: count, dtype: int64

Liste des candidats valides :
 - 0101EMS
 - 0103BPS
 - 0104IBS
 - 0106DJR
 - 0109MJR
 - 0110RMS
 - 0113DGR
 - 0114MLR
 - 0115MHR
 - 0116CNR
 - 0117MSR
 - 0118TMS
 - 0119BIR
 - 0120ANS
 - 0121RPS
 - 0122VCR
 - 0123GVS
 - 0124PAS
 - 0126VLR
 - 0127CMS
 - 0128ALS
 - 0129APR
 - 0130FAR
 - 0131CPS
 - 0132GAR
 - 0133BPS
 - 0134IFR
 - 0135KLS
 - 0136CJR
 - 0137BMS
 - 0138NWR
 - 0139BMR
 - 0140LMR
 - 0141HJR
 - 0142LLS
 - 0143EBR
 - 0144ZGR

======================================================================
Analyse globale – Feuille : SAINTE-MARGUERITE

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0801HDR,Réduction de la menace,0,0,0,0
1,0802LAS,Standard,0,0,2,0
2,0804GOR,Réduction de la menace,0,0,0,0
3,0803DPS,Standard,1,0,2,0
4,0805BMS,Standard,0,0,2,0
5,0806KHS,Standard,1,0,2,0
6,0807OMR,Réduction de la menace,0,0,0,0
7,0808PJR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 8
Candidats VALIDES (selon Condition) : 6
Candidats REJETÉS : 2

Candidats valides par condition :
Condition
Réduction de la menace    4
Standard                  2
Name: count, dtype: int64

Liste des candidats valides :
 - 0801HDR
 - 0802LAS
 - 0804GOR
 - 0805BMS
 - 0807OMR
 - 0808PJR

======================================================================
Analyse globale – Feuille : CGD

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0901SMR,Réduction de la menace,0,0,0,0
1,0903DJS,Standard,2,0,2,0
2,0902SIS,Standard,0,0,2,0
3,0906DNR,Réduction de la menace,0,2,0,0
4,0904KJS,Standard,0,0,2,0
5,0905SLR,Réduction de la menace,0,2,0,0

Nombre total de candidats : 6
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Réduction de la menace    3
Standard                  2
Name: count, dtype: int64

Liste des candidats valides :
 - 0901SMR
 - 0902SIS
 - 0906DNR
 - 0904KJS
 - 0905SLR

======================================================================
Analyse globale – Feuille : CERCA

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0401BDS,Standard,2,2,2,2
1,0402TFR,Réduction de la menace,2,2,2,2
2,0404DER,Réduction de la menace,2,2,2,2
3,0405RCR,Réduction de la menace,2,2,2,2
4,0406BBS,Standard,2,2,2,2
5,0407HMS,Standard,2,2,2,2
6,0408SJS,Standard,2,2,2,2
7,0409HCR,Réduction de la menace,2,2,2,2
8,0410FMS,Standard,2,2,2,2
9,0411NPR,Réduction de la menace,2,2,2,2
10,0412CMS,Standard,2,2,2,2
11,0413MMR,Réduction de la menace,0,0,0,0
12,0414PVR,Réduction de la menace,0,2,0,0
13,0415HJS,Standard,0,0,2,0
14,0416CPR,Réduction de la menace,1,0,0,0
15,0417FAS,Standard,0,0,2,0
16,0417KMS,Standard,0,0,2,0
17,0418MPR,Réduction de la menace,0,0,0,0
18,0418TJR,Réduction de la menace,0,0,0,0
19,0419CHR,Réduction de la menace,1,2,0,2
20,0419SRR,Réduction de la menace,0,2,0,0
21,0420MCR,Réduction de la menace,0,2,0,0
22,0420LMR,Réduction de la menace,0,0,0,0
23,0421ACS,Standard,0,0,2,0
24,0422LVR,Réduction de la menace,2,2,2,2
25,0422WCS,Standard,0,0,2,0
26,0423SVS,Standard,2,2,2,2
27,0423RMR,Réduction de la menace,0,2,0,0
28,0424GMS,Standard,2,2,2,2
29,0424BLR,Réduction de la menace,0,2,0,0
30,0425CDS,Standard,2,2,2,0
31,0426DGS,Standard,2,2,2,0
32,0432CGS,Standard,2,0,2,2
33,0433RMR,Réduction de la menace,2,0,2,0
34,0434GPS,Standard,2,0,2,0
35,0809VJR,Réduction de la menace,1,0,2,0
36,0810LCR,Réduction de la menace,1,0,2,1
37,0812DMS,Standard,2,0,2,0
38,0813PJS,Standard,2,0,2,0
39,0811MCS,Standard,2,0,2,0

Nombre total de candidats : 40
Candidats VALIDES (selon Condition) : 14
Candidats REJETÉS : 26

Candidats valides par condition :
Condition
Réduction de la menace    9
Standard                  5
Name: count, dtype: int64

Liste des candidats valides :
 - 0413MMR
 - 0414PVR
 - 0415HJS
 - 0417FAS
 - 0417KMS
 - 0418MPR
 - 0418TJR
 - 0419SRR
 - 0420MCR
 - 0420LMR
 - 0421ACS
 - 0422WCS
 - 0423RMR
 - 0424BLR

In [12]:
total_valides = sum(
    res["n_valides"] for res in resultats_globaux.values()
)

print("=" * 70)
print(f"✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : {total_valides}")

======================================================================
✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : 169

# 169 candidats retenus

# Recherche des candidats et téléchargement de leur fichier EDA V2

In [13]:
import pandas as pd

# Afficher toutes les lignes
pd.set_option('display.max_rows', None)

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

# Afficher toute la largeur de chaque colonne
pd.set_option('display.max_colwidth', None)

## APHM

In [14]:
# ===== Racine des patients =====
racine_aphm = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"

# ===== Candidats valides =====
candidats_aphm = [c.upper() for c in resultats_globaux["APHM"]["valides"]]

# ===== Mapping PID → Condition =====
df_conditions = resultats_globaux["APHM"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
df_conditions["Condition"] = df_conditions["Condition"].astype(str)
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

rows = []

for root, dirs, files in os.walk(racine_aphm):

    if not any("V2" in d.upper() for d in root.split(os.sep)):
        continue

    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():  
            continue

        chemin = os.path.join(root, f)

        # ===== Numero_inclusion = dossier juste après la racine =====
        rel_path = os.path.relpath(chemin, racine_aphm)
        parts = rel_path.split(os.sep)
        pid_trouve = parts[0].upper()

        if pid_trouve not in candidats_aphm:
            continue

        # ===== Timestamp Unix (dossier juste avant EDA.csv) =====
        folder = os.path.basename(os.path.dirname(chemin))
        timestamp_match = re.match(r"(\d+)_", folder)
        timestamp_unix = int(timestamp_match.group(1)) if timestamp_match else None

        # ===== Conversion Unix → date locale =====
        date_eda = datetime.datetime.fromtimestamp(timestamp_unix) if timestamp_unix else None

        # ===== Condition =====
        condition = dict_condition.get(pid_trouve)
        if condition is None:
            print(f"⚠️ Condition manquante pour {pid_trouve} → ignoré")
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Condition": condition,
            "Feuille": "APHM",
            "Timestamp_unix": timestamp_unix,
            "Date_eda": date_eda
        })

# ===== DataFrame complet =====
df_aphm = pd.DataFrame(rows, columns=["Numero_inclusion", "Chemin", "Condition", "Feuille", "Timestamp_unix", "Date_eda"])

# ===== Suppression des doublons =====
if not df_aphm.empty:
    df_aphm_final = (
        df_aphm
        .assign(priorite_montre=df_aphm["Chemin"].str.contains("MONTRE", case=False))
        .sort_values(["Numero_inclusion", "priorite_montre"], ascending=[True, False])
        .drop_duplicates(subset="Numero_inclusion", keep="first")
        .drop(columns="priorite_montre")
        .reset_index(drop=True)
    )
else:
    df_aphm_final = df_aphm.copy()

print(f"Candidats attendus APHM : {len(candidats_aphm)}")
print(f"Fichiers EDA APHM V2 retenus : {len(df_aphm_final)}")

display(df_aphm_final)

Candidats attendus APHM : 24
Fichiers EDA APHM V2 retenus : 24

,Numero_inclusion,Chemin,Condition,Feuille,Timestamp_unix,Date_eda
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 06-07-2018 V2\Montre 0101CAR\1530858300_A01093\EDA.csv,Réduction de la menace,APHM,1530858300,2018-07-06 08:25:00
1,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 09-07-2018 V2\Montre 0102PCR\1531119483_A01093\EDA.csv,Réduction de la menace,APHM,1531119483,2018-07-09 08:58:03
2,0103SHS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0103SHS\0103SHS 10-09-2018 V2\Montre 0103SHS\1536563089_A01093\EDA.csv,Standard,APHM,1536563089,2018-09-10 09:04:49
3,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 29-11-2018 V2\Montre 0104FJS\1543476632_A01093\EDA.csv,Standard,APHM,1543476632,2018-11-29 08:30:32
4,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 10-12-2018 V2\Montre 0105PNR\1544426613_A01093\EDA.csv,Réduction de la menace,APHM,1544426613,2018-12-10 08:23:33
5,0106JLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0106JLS\0106JLS 03-01-2019 V2\Montre 0106JLS\1546500427_A01093\EDA.csv,Standard,APHM,1546500427,2019-01-03 08:27:07
6,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 14-01-2019 V2\Montre 0107DSS\1547450742_A01093\EDA.csv,Standard,APHM,1547450742,2019-01-14 08:25:42
7,0108BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0108BFS\0108BFS 17-01-2019 V2\Montre 0108BFS\1547711087_A01093\EDA.csv,Standard,APHM,1547711087,2019-01-17 08:44:47
8,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 18-02-2019 V2\Montre 0109GSS\1550476660_A01093\EDA.csv,Standard,APHM,1550476660,2019-02-18 08:57:40
9,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 26-02-2019 V2\Montre 0110LPR\1551167333_A01093\EDA.csv,Réduction de la menace,APHM,1551167333,2019-02-26 08:48:53
10,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 28-02-2019 V2\Montre 0111MNR\1551341044_A01093\EDA.csv,Réduction de la menace,APHM,1551341044,2019-02-28 09:04:04
11,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR 06-06-2019 V2\Montre 0112BSR\1559802681_A01093\EDA.csv,Réduction de la menace,APHM,1559802681,2019-06-06 08:31:21
12,0113BMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0113BMR\0113BMR 20-06-2019 V2\Montre 0113BMR\1561011593_A01093\EDA.csv,Réduction de la menace,APHM,1561011593,2019-06-20 08:19:53
13,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS 27-06-2019 V2\Montre 0114LMS\1561617443_A01093\EDA.csv,Standard,APHM,1561617443,2019-06-27 08:37:23
14,0115CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0115CJR\0115CJR 27-08-2019 V2\Montre 0115CJR\1566887219_A01093\EDA.csv,Réduction de la menace,APHM,1566887219,2019-08-27 08:26:59
15,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR 29-08-2019 V2\Montre 0116VAR\1567060805_A01093\EDA.csv,Réduction de la menace,APHM,1567060805,2019-08-29 08:40:05
16,0117POS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0117POS\0117POS 05-09-2019 V2\Montre 0117POS\1567664747_A01093\EDA.csv,Standard,APHM,1567664747,2019-09-05 08:25:47
17,0118TNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0118TNS\0118TNS 01-10-2019 V2\Montre 0118TNS\1569911840_A01093\EDA.csv,Standard,APHM,1569911840,2019-10-01 08:37:20
18,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS 07-11-2019 V2\Montre 0119LJS\1573112319_A01093\EDA.csv,Standard,APHM,1573112319,2019-11-07 08:38:39
19,0120LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0120LCR\0120LCR 06-12-2019 V2\Montre 0120LCR\1575617159_A01093\EDA.csv,Réduction de la menace,APHM,1575617159,2019-12-06 08:25:59
20,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR 12-12-2019 V2\Montre 0121MJR\1576137833_A01093\EDA.csv,Réduction de la menace,APHM,1576137833,2019-12-12 09:03:53
21,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS 20-12-2019 V2\Montre 0123 RMS\1576827353_A01093\EDA.csv,Standard,APHM,1576827353,2019-12-20 08:35:53
22,0124BAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0124BAR\V2\montre\1578386536_A01093\EDA.csv,Réduction de la menace,APHM,1578386536,2020-01-07 09:42:16
23,0125BMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0125BMR\V2\MONTRE\1578997658_A01093\EDA.csv,Réduction de la menace,APHM,1578997658,2020-01-14 11:27:38

## CAEN

In [15]:
# ===== Racine et candidats CAEN =====
racine_caen = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN"
candidats_caen = [c.upper().replace(" ", "") for c in resultats_globaux["CAEN"]["valides"]]

# ===== DataFrame Excel =====
df_excel_caen = df['CAEN'][["Numero_inclusion", "Condition", "Date_v2"]].copy()
df_excel_caen["Numero_inclusion"] = df_excel_caen["Numero_inclusion"].str.upper().str.replace(" ", "")
df_excel_caen["Condition"] = df_excel_caen["Condition"].astype(str)
df_excel_caen["Date_v2"] = pd.to_datetime(df_excel_caen["Date_v2"], dayfirst=True).dt.date

# ===== Dictionnaires pour lookup rapide =====
dict_condition = dict(zip(df_excel_caen["Numero_inclusion"], df_excel_caen["Condition"]))
dict_date_v2 = dict(zip(df_excel_caen["Numero_inclusion"], df_excel_caen["Date_v2"]))

# ===== Paths forcés pour candidats spécifiques =====
paths_forces = {
    "0306MDR": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1557145160_A012950306 MDR\EDA.csv",
    "0356DMS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1663832640_A012950356DMS\EDA.csv",
    "0305LCR":r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1556179294_A01295 0305 LCR\EDA.csv"
}
paths_forces = {k: os.path.normpath(v).upper() for k, v in paths_forces.items()}

# ===== Pattern PID dans le chemin (hors paths forcés) =====
patterns_candidats = {
    pid: re.compile(rf"\b{pid}\b", re.IGNORECASE)
    for pid in candidats_caen if pid not in paths_forces
}

rows = []

# ===== Parcours des fichiers =====
for root, dirs, files in os.walk(racine_caen):
    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_norm = os.path.normpath(chemin).upper()

        # ===== Vérification regex pour candidats normaux =====
        pid_trouve = None
        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                pid_trouve = pid
                break

        # ===== Vérification chemins forcés =====
        if chemin_norm in paths_forces.values():
            pid_trouve = [k for k, v in paths_forces.items() if v == chemin_norm][0]

        if not pid_trouve:
            continue

        # ===== Timestamp Unix =====
        folder = os.path.basename(os.path.dirname(chemin))
        match = re.match(r"(\d+)_A\d+\s*(.+)", folder)
        timestamp_unix = int(match.group(1)) if match else None
        date_eda = datetime.datetime.fromtimestamp(timestamp_unix).date() if timestamp_unix else None

        # ===== Condition et date Excel =====
        condition = dict_condition.get(pid_trouve)
        date_v2_excel = dict_date_v2.get(pid_trouve)

        # ===== Filtre date sauf pour chemins forcés =====
        if chemin_norm not in paths_forces.values() and date_eda and date_v2_excel:
            if date_eda > date_v2_excel:
                continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Condition": condition,
            "Feuille": "CAEN",
            "Timestamp_unix": timestamp_unix,
            "Date_eda": date_eda,
            "Date_v2_excel": date_v2_excel
        })

# ===== DataFrame complet =====
df_caen = pd.DataFrame(rows)

# ===== Suppression des doublons =====
if not df_caen.empty:
    df_caen_final = df_caen.groupby("Numero_inclusion", as_index=False)\
                           .apply(lambda x: x.loc[x['Date_eda'].idxmin()])\
                           .reset_index(drop=True)
else:
    df_caen_final = df_caen.copy()

print(f"Candidats attendus CAEN : {len(candidats_caen)}")
print(f"Fichiers EDA CAEN V2 retenus : {len(df_caen_final)}")
display(df_caen_final)

# ===== Affichage des candidats manquants =====
candidats_trouves = set(df_caen_final["Numero_inclusion"].tolist())
candidats_manquants = sorted(set(candidats_caen) - candidats_trouves)

if candidats_manquants:
    print("\n⚠️ Candidats manquants dans l'extraction :")
    for c in candidats_manquants:
        print(f" - {c}")
else:
    print("\n✅ Tous les candidats ont été trouvés")

Candidats attendus CAEN : 50
Fichiers EDA CAEN V2 retenus : 49

C:\Users\judupont\AppData\Local\Temp\ipykernel_50772\2733414304.py:93: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.loc[x['Date_eda'].idxmin()])\

,Numero_inclusion,Chemin,Condition,Feuille,Timestamp_unix,Date_eda,Date_v2_excel
0,0301GNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0301GNR\Montre\1547630037_A01295 0301GNR\EDA.csv,Réduction de la menace,CAEN,1547630037,2019-01-16,2019-01-16
1,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0302ZMR\montre\1548318959_A01295 0302 ZMR\EDA.csv,Réduction de la menace,CAEN,1548318959,2019-01-24,2019-01-24
2,0303PAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0303PAR\Montre\1552553872_A01295 0303 PAR\EDA.csv,Réduction de la menace,CAEN,1552553872,2019-03-14,2019-03-14
3,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0304VMR\Montre\1553502969_A01295 0304 VMR\EDA.csv,Réduction de la menace,CAEN,1553502969,2019-03-25,2019-03-25
4,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1556179294_A01295 0305 LCR\EDA.csv,Réduction de la menace,CAEN,1556179294,2019-04-25,2019-04-25
5,0306MDR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1557145160_A012950306 MDR\EDA.csv,Réduction de la menace,CAEN,1557145160,2019-05-06,2019-05-06
6,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1557735741_A01295 0307SMR\EDA.csv,Réduction de la menace,CAEN,1557735741,2019-05-13,2019-05-13
7,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1561452848_A01295 0308RGR\EDA.csv,Réduction de la menace,CAEN,1561452848,2019-06-25,2019-06-25
8,0309DBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1561634352_A01295 0309DBS\EDA.csv,Standard,CAEN,1561634352,2019-06-27,2019-06-27
9,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1562140652_A01295 0310ACS\EDA.csv,Standard,CAEN,1562140652,2019-07-03,2019-07-03
10,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1562153876_A01295 0311CJS\EDA.csv,Standard,CAEN,1562153876,2019-07-03,2019-07-03
11,0312JMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1563782337_A01295 0312JMS\EDA.csv,Standard,CAEN,1563782337,2019-07-22,2019-07-22
12,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1563884804_A01295 0313FPR\EDA.csv,Réduction de la menace,CAEN,1563884804,2019-07-23,2019-07-23
13,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567064965_A01295 0315VCS\EDA.csv,Standard,CAEN,1567064965,2019-08-29,2019-08-29
14,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567496846_A01295 0316TMS\EDA.csv,Standard,CAEN,1567496846,2019-09-03,2019-09-03
15,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567669152_A01295 0317LGS\EDA.csv,Standard,CAEN,1567669152,2019-09-05,2019-09-05
16,0318PMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567758189_A01295 0318PMS\EDA.csv,Standard,CAEN,1567758189,2019-09-06,2019-09-06
17,0320DGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1569917948_A01295 0320DGS\EDA.csv,Standard,CAEN,1569917948,2019-10-01,2019-10-01
18,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1570523646_A01295 0321DRR\EDA.csv,Réduction de la menace,CAEN,1570523646,2019-10-08,2019-10-08
19,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1570697421_A01295 0322RMS\EDA.csv,Standard,CAEN,1570697421,2019-10-10,2019-10-10
20,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1572945137_A01295 0323RFS\EDA.csv,Standard,CAEN,1572945137,2019-11-05,2019-11-05
21,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1573207008_A01295 0324LMR\EDA.csv,Réduction de la menace,CAEN,1573207008,2019-11-08,2019-11-08
22,0325LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1573809796_A01295 0325LCR\EDA.csv,Réduction de la menace,CAEN,1573809796,2019-11-15,2019-11-15
23,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1574413338_A01295 0326BJR\EDA.csv,Réduction de la menace,CAEN,1574413338,2019-11-22,2019-11-22
24,0327IAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1574672184_A01295 0327IAR\EDA.csv,Réduction de la menace,CAEN,1574672184,2019-11-25,2019-11-25
25,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1575535612_A01295 0328MPR\EDA.csv,Réduction de la menace,CAEN,1575535612,2019-12-05,2019-12-05
26,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1580201554_A01295 0329NMR\EDA.csv,Réduction de la menace,CAEN,1580201554,2020-01-28,2020-01-28
27,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1580460885_A01295 0330RTR\EDA.csv,Réduction de la menace,CAEN,1580460885,2020-01-31,2020-01-31
28,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1581429283_A01295 0331GRS\EDA.csv,Standard,CAEN,1581429283,2020-02-11,2020-02-11
29,0332MCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1583485073_A01295 0332MCR\EDA.csv,Réduction de la menace,CAEN,1583485073,2020-03-06,2020-03-06
30,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1601019503_A01295 0333MMS\EDA.csv,Standard,CAEN,1601019503,2020-09-25,2020-09-25
31,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1601538039_A01295 0334TVS\EDA.csv,Standard,CAEN,1601538039,2020-10-01,2020-10-01
32,0336CBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1602834220_A01295 0336CBS\EDA.csv,Standard,CAEN,1602834220,2020-10-16,2020-10-16
33,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1606206251_A01295 0337BFS\EDA.csv,Standard,CAEN,1606206251,2020-11-24,2020-11-24
34,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1614242134_A01295 0339NPR\EDA.csv,Réduction de la menace,CAEN,1614242134,2021-02-25,2021-02-25
35,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1621237386_A01295 0341LJS\EDA.csv,Standard,CAEN,1621237386,2021-05-17,2021-05-17
36,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1622533024_A01295 0342VNS\EDA.csv,Standard,CAEN,1622533024,2021-06-01,2021-06-01
37,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1623137842_A01295 0343PAS\EDA.csv,Standard,CAEN,1623137842,2021-06-08,2021-06-08
38,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643287622_A01295 0345LAR\EDA.csv,Réduction de la menace,CAEN,1643287622,2022-01-27,2022-01-27
39,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643358334_A01295 0346GLS\EDA.csv,Standard,CAEN,1643358334,2022-01-28,2022-01-28
40,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643619887_A01295 0347DMR\EDA.csv,Réduction de la menace,CAEN,1643619887,2022-01-31,2022-01-31
41,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643707290_A01295 0348GCR\EDA.csv,Réduction de la menace,CAEN,1643707290,2022-02-01,2022-02-01
42,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1645433839_A01295 0349LLS\EDA.csv,Standard,CAEN,1645433839,2022-02-21,2022-02-21
43,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1647593250_A01295 0350MYR\EDA.csv,Réduction de la menace,CAEN,1647593250,2022-03-18,2022-03-18
44,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1648198966_A01295 0351FIR\EDA.csv,Réduction de la menace,CAEN,1648198966,2022-03-25,2022-03-25
45,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1650009653_A01295 0352RNR\EDA.csv,Réduction de la menace,CAEN,1650009653,2022-04-15,2022-04-15
46,0354GKR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1656315057_A01295 0354GKR\EDA.csv,Réduction de la menace,CAEN,1656315057,2022-06-27,2022-06-27
47,0355BAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1656575009_A01295 0355BAS\EDA.csv,Standard,CAEN,1656575009,2022-06-30,2022-06-30
48,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1663832640_A012950356DMS\EDA.csv,Standard,CAEN,1663832640,2022-09-22,2022-09-22

⚠️ Candidats manquants dans l'extraction :
 - 0319LJS

## POITIERS

In [16]:
# ===== Racine POITIERS =====
racine_poitiers = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY"

# ===== Candidats valides =====
candidats_poitiers = [
    c.upper().replace(" ", "")
    for c in resultats_globaux["POITIERS"]["valides"]
]

# ===== Dictionnaire Numero_inclusion → Condition =====
df_conditions = resultats_globaux["POITIERS"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = (
    df_conditions["Numero_inclusion"]
    .str.upper()
    .str.replace(" ", "")
)

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== Regex POITIERS  =====
# ex : 0401TSS → match "0401 TS"
patterns_candidats = {
    pid: re.compile(
        rf"{pid[:4]}\s*-?\s*{pid[4:6]}",
        re.IGNORECASE
    )
    for pid in candidats_poitiers
}

fichiers_par_candidat = defaultdict(list)

for root, dirs, files in os.walk(racine_poitiers):

    if "V2" not in root.upper():
        continue

    for f in files:
        if f.upper() != "EDA.CSV":
            continue

        chemin = os.path.join(root, f)

        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                fichiers_par_candidat[pid].append(chemin)
                break

# ===== Sélection finale + DataFrame =====
rows = []

for pid, fichiers in fichiers_par_candidat.items():

    fichiers = sorted(set(fichiers))  # sécurité doublons exacts

    # priorité MONTRE (logique équivalente à CEINTURE)
    montre = [f for f in fichiers if "montre" in f.lower()]
    chemin_final = montre[0] if montre else fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Condition": dict_condition.get(pid),
        "Feuille": "POITIERS"
    })

df_poitiers_final = pd.DataFrame(rows)

# ===== Affichage =====
print(f"Candidats attendus POITIERS : {len(candidats_poitiers)}")
print(f"Fichiers EDA POITIERS V2 retenus : {len(df_poitiers_final)}")

manquants = sorted(
    set(candidats_poitiers) - set(df_poitiers_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats POITIERS sont présents")

display(df_poitiers_final)

Candidats attendus POITIERS : 14
Fichiers EDA POITIERS V2 retenus : 13
⚠️ Candidats manquants : ['0409PHR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V2\0401TSS- montre\EDA.csv,Standard,POITIERS
1,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS- V2\0402LLS- montre\EDA.csv,Standard,POITIERS
2,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V2\0403DCR- montre\EDA.csv,Réduction de la menace,POITIERS
3,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404CYS-V2\0404YC-montre\EDA.csv,Standard,POITIERS
4,0405FCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0405 FC\0405 FCR-V2\0405FCR- montre\EDA.csv,Réduction de la menace,POITIERS
5,0406MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0406 MC\0406 MCS-V2\0406MCS-montre\EDA.csv,Standard,POITIERS
6,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V2\0407LJ-montre\EDA.csv,Réduction de la menace,POITIERS
7,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC V2\0408BC-montre\EDA.csv,Standard,POITIERS
8,0410PGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0410 PG\0410 PGS - V2\montre\0410PGS\EDA.csv,Standard,POITIERS
9,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V2\0411VE montre\EDA.csv,Standard,POITIERS
10,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V2\0412AN montre\EDA.csv,Standard,POITIERS
11,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS-V2\0413HF montre\EDA.csv,Standard,POITIERS
12,0415VMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0415 VM\0415 VMR-V2\0415VMR-montre V2\EDA.csv,Réduction de la menace,POITIERS

## ROUEN

In [17]:
# ===== Racine ROUEN =====
racine_rouen = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER"

# ===== Candidats valides =====
candidats_rouen = [c.upper() for c in resultats_globaux["ROUEN"]["valides"]]

# ===== Dictionnaire Numero_inclusion → Condition =====
df_conditions = resultats_globaux["ROUEN"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

# ===== Patterns candidats : 05-09, 05-11, etc =====
patterns_candidats = {
    pid: re.compile(rf"\b{pid[:2]}-{pid[2:4]}\b", re.IGNORECASE)
    for pid in candidats_rouen
}

rows = []

# ===== Parcours fichiers =====
for root, dirs, files in os.walk(racine_rouen):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue

        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        pid_trouve = None
        for pid, pat in patterns_candidats.items():
            if pat.search(chemin_upper):
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid_trouve),
            "Feuille": "ROUEN"
        })

# ===== DataFrame final =====
df_rouen_final = pd.DataFrame(rows)

# ===== Suppression des doublons =====
df_rouen_final = (
    df_rouen_final
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# ===== Affichage =====
print(f"Candidats attendus ROUEN : {len(candidats_rouen)}")
print(f"Fichiers EDA ROUEN V2 retenus : {len(df_rouen_final)}")

manquants = sorted(set(candidats_rouen) - set(df_rouen_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats ROUEN manquants :", manquants)
else:
    print("✅ Tous les candidats ROUEN sont présents")

display(df_rouen_final)

Candidats attendus ROUEN : 14
Fichiers EDA ROUEN V2 retenus : 14
✅ Tous les candidats ROUEN sont présents

,Numero_inclusion,Chemin,Condition,Feuille
0,0501MBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-01-MB-S\V2\montre 05-01MBS V2\EDA.csv,Standard,ROUEN
1,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V2\MONTRE\EDA.csv,Réduction de la menace,ROUEN
2,0503LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-03-LC-R\V2\MONTRE\EDA.csv,Réduction de la menace,ROUEN
3,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V2\montre 05-04-BC -S V2\1556006396_A012E9\EDA.csv,Standard,ROUEN
4,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V2\MONTRE\EDA.csv,Réduction de la menace,ROUEN
5,0506VMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-06-VM-S\V2\MONTRE05-06-VM-S\EDA.csv,Standard,ROUEN
6,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V2\MONTRE\EDA - Copie.csv,Standard,ROUEN
7,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V2\MONTRE\EDA.csv,Réduction de la menace,ROUEN
8,0509LGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-09-LC-S\V2\MONTRE\EDA.csv,Standard,ROUEN
9,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V2\MONTRE\1582188586_A012E9\EDA.csv,Standard,ROUEN
10,0511LCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-11-LC-S\05-11-LC-S-V2\MONTRE\EDA[1].csv,Standard,ROUEN
11,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V2\MONTRE\EDA.csv,Réduction de la menace,ROUEN
12,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V2\MONTRE\EDA.csv,Standard,ROUEN
13,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V2\MONTRE\1661413271_A012E9\EDA.csv,Réduction de la menace,ROUEN

## LAVERAN

In [18]:
# ===== Racine LAVERAN =====
racine_laveran = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"
)

# ===== Candidats attendus =====
candidats_laveran = [c.upper() for c in resultats_globaux["LAVERAN"]["valides"]]

# ===== Dictionnaire Numero_inclusion → Condition =====
df_conditions = resultats_globaux["LAVERAN"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_laveran):

    if "V2" not in root.upper():
        continue

    for f in files:

        # ===== CSV EDA uniquement =====
        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)

        # ===== Numero_inclusion = 1er dossier après la racine =====
        rel_path = os.path.relpath(chemin, racine_laveran)
        pid = rel_path.split(os.sep)[0].upper()

        if pid not in candidats_laveran:
            continue

        rows.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid),
            "Feuille": "LAVERAN"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
    # DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_laveran = pd.DataFrame(rows)

df_laveran_final = (
    df_laveran
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LAVERAN : {len(candidats_laveran)}")
print(f"Fichiers EDA LAVERAN retenus : {len(df_laveran_final)}")

manquants = sorted(
    set(candidats_laveran) - set(df_laveran_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LAVERAN manquants :", manquants)
else:
    print("✅ Tous les candidats LAVERAN sont présents")

display(df_laveran_final)

OK [0626MCS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V2\montre\1579594311_A01093\EDA.csv
OK [0628DMR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0628DMR\V2\montre\1580375472_A01093\EDA.csv
OK [0629TCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\V2\montre\1580805647_A01093\EDA.csv
OK [0630RJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V2\montre\1582190668_A01093\EDA.csv
OK [0631LHR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\V2\montre\1582624540_A01093\EDA.csv

====================================
Candidats attendus LAVERAN : 5
Fichiers EDA LAVERAN retenus : 5
✅ Tous les candidats LAVERAN sont présents

,Numero_inclusion,Chemin,Condition,Feuille
0,0626MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V2\montre\1579594311_A01093\EDA.csv,Standard,LAVERAN
1,0628DMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0628DMR\V2\montre\1580375472_A01093\EDA.csv,Réduction de la menace,LAVERAN
2,0629TCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\V2\montre\1580805647_A01093\EDA.csv,Réduction de la menace,LAVERAN
3,0630RJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V2\montre\1582190668_A01093\EDA.csv,Réduction de la menace,LAVERAN
4,0631LHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\V2\montre\1582624540_A01093\EDA.csv,Réduction de la menace,LAVERAN

## LPC

In [20]:
# ===== Racine LPC =====
racine_lpc = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LNSC\DESHAYES\DESHAYES\DATA_Aging"
)

# ===== Candidats attendus =====
candidats_lpc = [c.upper() for c in resultats_globaux["LPC"]["valides"]]

# ===== CORRECTIONS MANUELLES ARBORESCENCE → EXCEL =====
CORRESPONDANCE_IDS = {
    "0117MSR": "0117MMR" 
}
CORRESPONDANCE_INVERSE = {v: k for k, v in CORRESPONDANCE_IDS.items()}

# ===== Dictionnaire Numero_inclusion → Condition =====
df_conditions = resultats_globaux["LPC"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_lpc):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)

        rel_path = os.path.relpath(chemin, racine_lpc)
        pid_arbo = rel_path.split(os.sep)[0].upper()

        pid_excel = CORRESPONDANCE_INVERSE.get(pid_arbo, pid_arbo)

        if pid_excel not in candidats_lpc:
            continue

        # =================================================
        # DEBUG TEMPS : UNIX (PATH) vs DATE FICHIER
        # =================================================
        try:
            dossier_montre = os.path.basename(os.path.dirname(chemin))
            ts_unix = int(dossier_montre.split("_")[0])
            date_unix = datetime.datetime.fromtimestamp(ts_unix)
        except Exception:
            date_unix = None

        date_fichier = datetime.datetime.fromtimestamp(
            os.path.getmtime(chemin)
        )

        print(
            f"🕒 {pid_excel} | "
            f"UNIX path = {date_unix} | "
            f"CSV modif = {date_fichier}"
        )

        # =================================================
        # ENREGISTREMENT
        # =================================================
        rows.append({
            "Numero_inclusion": pid_excel,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid_excel),
            "Feuille": "LPC"
        })

        print(f"OK [{pid_excel}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_lpc_final = (
    pd.DataFrame(rows)
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LPC : {len(candidats_lpc)}")
print(f"Fichiers EDA LPC retenus : {len(df_lpc_final)}")

manquants = sorted(set(candidats_lpc) - set(df_lpc_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC sont présents")

display(df_lpc_final)

🕒 0101EMS | UNIX path = None | CSV modif = 2026-01-19 12:23:02.562823
OK [0101EMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Montre\EDA.csv
🕒 0101EMS | UNIX path = 2019-01-22 10:10:40 | CSV modif = 2026-02-19 10:52:16.145401
OK [0101EMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Montre\1548148240_A01115\EDA.csv
🕒 0103BPS | UNIX path = None | CSV modif = 2026-01-19 12:23:01.787221
OK [0103BPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Montre\EDA.csv
🕒 0103BPS | UNIX path = 2018-12-11 10:08:34 | CSV modif = 2026-02-19 10:52:16.256335
OK [0103BPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Montre\1544519314_A01115\EDA.csv
🕒 0104IBS | UNIX path = None | CSV modif = 2026-01-19 12:23:01.201204
OK [0104IBS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Montre\EDA.csv
🕒 0104IBS | UNIX path = 2018-11-28 09:58:49 | CSV modif = 2026-02-19 10:52:16.334084
OK [0104IBS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Montre\1543395529_A01115\EDA.csv
🕒 0106DJR | UNIX path = 2018-12-19 10:05:17 | CSV modif = 2026-02-19 10:52:16.443657
OK [0106DJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0106DJR\V2\Montre\1545210317_A01115\EDA.csv
🕒 0109MJR | UNIX path = None | CSV modif = 2026-01-19 12:22:58.556859
OK [0109MJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Montre\EDA.csv
🕒 0109MJR | UNIX path = 2018-12-13 09:39:06 | CSV modif = 2026-02-19 10:52:16.634758
OK [0109MJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Montre\1544690346_A01115\EDA.csv
🕒 0110RMS | UNIX path = None | CSV modif = 2026-01-19 12:22:57.986836
OK [0110RMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Montre\EDA.csv
🕒 0110RMS | UNIX path = 2018-12-14 09:37:00 | CSV modif = 2026-02-19 10:52:16.718415
OK [0110RMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Montre\1544776620_A01115\EDA.csv
🕒 0113DGR | UNIX path = None | CSV modif = 2026-01-19 12:22:56.309450
OK [0113DGR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Montre\EDA.csv
🕒 0113DGR | UNIX path = 2018-11-27 09:40:50 | CSV modif = 2026-02-19 10:52:16.941663
OK [0113DGR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Montre\1543308050_A01115\EDA.csv
🕒 0114MLR | UNIX path = None | CSV modif = 2026-01-19 12:22:55.263799
OK [0114MLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Montre\EDA.csv
🕒 0114MLR | UNIX path = 2019-01-07 10:02:08 | CSV modif = 2026-02-19 10:52:17.074093
OK [0114MLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Montre\1546851728_A01115\EDA.csv
🕒 0115MHR | UNIX path = None | CSV modif = 2026-01-19 12:22:55.185204
OK [0115MHR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\Montre\EDA.csv
🕒 0115MHR | UNIX path = 2019-01-11 09:41:23 | CSV modif = 2026-02-19 10:52:17.118406
OK [0115MHR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\Montre\1547196083_A01115\EDA.csv
🕒 0116CNR | UNIX path = None | CSV modif = 2026-01-19 12:22:53.887233
OK [0116CNR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Montre\EDA.csv
🕒 0116CNR | UNIX path = 2019-01-10 09:46:11 | CSV modif = 2026-02-19 10:52:17.194769
OK [0116CNR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Montre\1547109971_A01115\EDA.csv
🕒 0117MSR | UNIX path = None | CSV modif = 2026-01-19 12:22:53.206625
OK [0117MSR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Montre\EDA.csv
🕒 0117MSR | UNIX path = 2019-01-14 09:46:11 | CSV modif = 2026-02-19 10:52:17.282096
OK [0117MSR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Montre\1547455571_A01115\EDA.csv
🕒 0118TMS | UNIX path = None | CSV modif = 2026-01-19 12:22:52.541132
OK [0118TMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Montre\EDA.csv
🕒 0118TMS | UNIX path = 2019-01-16 09:40:22 | CSV modif = 2026-02-19 10:52:17.366375
OK [0118TMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Montre\1547628022_A01115\EDA.csv
🕒 0119BIR | UNIX path = None | CSV modif = 2026-01-19 12:22:51.923344
OK [0119BIR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Montre\EDA.csv
🕒 0119BIR | UNIX path = 2019-01-28 09:35:15 | CSV modif = 2026-02-19 10:52:17.443460
OK [0119BIR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Montre\1548664515_A01115\EDA.csv
🕒 0120ANS | UNIX path = None | CSV modif = 2026-01-19 12:22:51.353098
OK [0120ANS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Montre\EDA.csv
🕒 0120ANS | UNIX path = 2019-02-04 09:44:20 | CSV modif = 2026-02-19 10:52:17.528525
OK [0120ANS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Montre\1549269860_A01115\EDA.csv
🕒 0121RPS | UNIX path = None | CSV modif = 2026-01-19 12:22:50.798697
OK [0121RPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Montre\EDA.csv
🕒 0121RPS | UNIX path = 2019-01-23 09:28:00 | CSV modif = 2026-02-19 10:52:17.608985
OK [0121RPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Montre\1548232080_A01115\EDA.csv
🕒 0122VCR | UNIX path = None | CSV modif = 2026-01-19 12:22:50.070393
OK [0122VCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Montre\EDA.csv
🕒 0122VCR | UNIX path = 2019-02-01 09:36:49 | CSV modif = 2026-02-19 10:52:17.693603
OK [0122VCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Montre\1549010209_A01115\EDA.csv
🕒 0123GVS | UNIX path = None | CSV modif = 2026-01-19 12:22:49.500247
OK [0123GVS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Montre\EDA.csv
🕒 0123GVS | UNIX path = 2019-02-08 09:27:47 | CSV modif = 2026-02-19 10:52:17.782829
OK [0123GVS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Montre\1549614467_A01115\EDA.csv
🕒 0124PAS | UNIX path = None | CSV modif = 2026-01-19 12:22:48.976557
OK [0124PAS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Montre\EDA.csv
🕒 0124PAS | UNIX path = 2019-02-15 10:28:20 | CSV modif = 2026-02-19 10:52:17.858705
OK [0124PAS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Montre\1550222900_A01115\EDA.csv
🕒 0126VLR | UNIX path = None | CSV modif = 2026-01-19 12:22:47.851099
OK [0126VLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Montre\EDA.csv
🕒 0126VLR | UNIX path = 2019-03-08 09:37:56 | CSV modif = 2026-02-19 10:52:17.995795
OK [0126VLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Montre\1552034276_A01115\EDA.csv
🕒 0127CMS | UNIX path = None | CSV modif = 2026-01-19 12:22:47.280053
OK [0127CMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Montre\EDA.csv
🕒 0127CMS | UNIX path = 2019-02-21 09:36:22 | CSV modif = 2026-02-19 10:52:18.073828
OK [0127CMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Montre\1550738182_A01115\EDA.csv
🕒 0128ALS | UNIX path = None | CSV modif = 2026-01-19 12:22:46.692447
OK [0128ALS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Montre\EDA.csv
🕒 0128ALS | UNIX path = 2019-03-13 09:42:14 | CSV modif = 2026-02-19 10:52:18.145774
OK [0128ALS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Montre\1552466534_A01115\EDA.csv
🕒 0129APR | UNIX path = None | CSV modif = 2026-01-19 12:22:45.979169
OK [0129APR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Montre\EDA.csv
🕒 0129APR | UNIX path = 2019-03-14 09:45:51 | CSV modif = 2026-02-19 10:52:18.227054
OK [0129APR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Montre\1552553151_A01115\EDA.csv
🕒 0130FAR | UNIX path = None | CSV modif = 2026-01-19 12:22:45.172371
OK [0130FAR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0130FAR\V2\Montre\EDA.csv
🕒 0130FAR | UNIX path = 2019-05-03 10:37:58 | CSV modif = 2026-02-19 10:52:18.337231
OK [0130FAR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0130FAR\V2\Montre\1556872678_A01115\EDA.csv
🕒 0131CPS | UNIX path = 2019-12-09 10:03:31 | CSV modif = 2026-02-19 10:52:18.375944
OK [0131CPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0131CPS\V2\Montre\1575882211_A01115\EDA.csv

====================================
Candidats attendus LPC : 37
Fichiers EDA LPC retenus : 24
⚠️ Candidats LPC manquants : ['0132GAR', '0133BPS', '0134IFR', '0135KLS', '0136CJR', '0137BMS', '0138NWR', '0139BMR', '0140LMR', '0141HJR', '0142LLS', '0143EBR', '0144ZGR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Montre\1548148240_A01115\EDA.csv,Standard,LPC
1,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Montre\1544519314_A01115\EDA.csv,Standard,LPC
2,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Montre\1543395529_A01115\EDA.csv,Standard,LPC
3,0106DJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0106DJR\V2\Montre\1545210317_A01115\EDA.csv,Réduction de la menace,LPC
4,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Montre\1544690346_A01115\EDA.csv,Réduction de la menace,LPC
5,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Montre\1544776620_A01115\EDA.csv,Standard,LPC
6,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Montre\1543308050_A01115\EDA.csv,Réduction de la menace,LPC
7,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Montre\1546851728_A01115\EDA.csv,Réduction de la menace,LPC
8,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\Montre\1547196083_A01115\EDA.csv,Réduction de la menace,LPC
9,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Montre\1547109971_A01115\EDA.csv,Réduction de la menace,LPC
10,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Montre\1547455571_A01115\EDA.csv,Réduction de la menace,LPC
11,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Montre\1547628022_A01115\EDA.csv,Standard,LPC
12,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Montre\1548664515_A01115\EDA.csv,Réduction de la menace,LPC
13,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Montre\1549269860_A01115\EDA.csv,Standard,LPC
14,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Montre\1548232080_A01115\EDA.csv,Standard,LPC
15,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Montre\1549010209_A01115\EDA.csv,Réduction de la menace,LPC
16,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Montre\1549614467_A01115\EDA.csv,Standard,LPC
17,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Montre\1550222900_A01115\EDA.csv,Standard,LPC
18,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Montre\1552034276_A01115\EDA.csv,Réduction de la menace,LPC
19,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Montre\1550738182_A01115\EDA.csv,Standard,LPC
20,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Montre\1552466534_A01115\EDA.csv,Standard,LPC
21,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Montre\1552553151_A01115\EDA.csv,Réduction de la menace,LPC
22,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0130FAR\V2\Montre\1556872678_A01115\EDA.csv,Réduction de la menace,LPC
23,0131CPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0131CPS\V2\Montre\1575882211_A01115\EDA.csv,Standard,LPC

In [21]:
# ===== Racines =====
racines = [
    r"C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire",
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo"
]

# ===== Candidats LPC partie 2 =====
candidats_lpc2 = [
    c.upper() for c in resultats_globaux["LPC"]["valides"][24:]
]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["LPC"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for racine in racines:

    print(f"\n--- Scan de : {racine}")

    for root, dirs, files in os.walk(racine):

        root_upper = root.upper()

        if not re.search(r'(^|[^A-Z0-9])V2([^A-Z0-9]|$)', root_upper):
            continue

        if "MONTRE" not in root_upper:
            continue

        for f in files:

            # ===== uniquement EDA.csv =====
            if f.upper() != "EDA.CSV":
                continue

            chemin = os.path.join(root, f)
            chemin_upper = chemin.upper()

            # ===== identification PID =====
            pid_trouve = None
            for c in candidats_lpc2:
                if c in chemin_upper:
                    pid_trouve = c
                    break

            if not pid_trouve:
                print("❌ PID NON TROUVÉ :", chemin)
                continue

            # =================================================
            # DEBUG TEMPS : UNIX (dossier) vs DATE fichier
            # =================================================
            dossier_parent = os.path.basename(os.path.dirname(chemin))
            ts_unix = None
            date_unix_str = "None"

            if "_" in dossier_parent:
                try:
                    ts_unix = int(dossier_parent.split("_")[0])
                    date_unix_str = datetime.datetime.fromtimestamp(
                        ts_unix
                    ).strftime("%Y-%m-%d %H:%M:%S")
                except Exception:
                    pass

            date_fichier_str = datetime.datetime.fromtimestamp(
                os.path.getmtime(chemin)
            ).strftime("%Y-%m-%d %H:%M:%S")

            print(
                f"🕒 PID={pid_trouve} | "
                f"Dossier='{dossier_parent}' | "
                f"UNIX path={date_unix_str} | "
                f"CSV modif={date_fichier_str}"
            )

            rows.append({
                "Numero_inclusion": pid_trouve,
                "Chemin": chemin,
                "Condition": dict_condition.get(pid_trouve),
                "Feuille": "LPC"
            })

            print(f"OK [{pid_trouve}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
print("\nDEBUG rows length :", len(rows))

if rows:
    df_lpc2_final = (
        pd.DataFrame(rows)
        .sort_values("Chemin")
        .drop_duplicates(subset="Numero_inclusion", keep="first")
        .reset_index(drop=True)
    )
else:
    df_lpc2_final = pd.DataFrame(
        columns=["Numero_inclusion", "Chemin", "Condition", "Feuille"]
    )

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LPC (partie 2) : {len(candidats_lpc2)}")
print(f"Fichiers EDA retenus              : {len(df_lpc2_final)}")

manquants = sorted(
    set(candidats_lpc2) - set(df_lpc2_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC partie 2 sont présents")

display(df_lpc2_final)

--- Scan de : C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire

--- Scan de : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0101EMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0101EMS\V2\Montre\1548148240_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0102BJS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0102BJS\V2\Montre\1545125104_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0103EMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0103EMS\V2\Montre\1544000743_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0105AER\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0105AER\V2\Montre\1543826532_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0106HQR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0106HQR\V2\Montre\0106HQR\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0107GLS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0107GLS\V2\Montre\1548405774_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0108BPS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0108BPS\V2\Montre\1544519314_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0109IBS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0109IBS\V2\Montre\1543395529_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0110HAR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0110HAR\V2\Montre\1542961835_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0112LER\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0112LER\V2\Montre\1543479990_A01115_0107LER_V2\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0113MMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0113MMS\V2\Montre\1548320338_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0114MJR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0114MJR\V2\Montre\1544690346_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0115RMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0115RMS\V2\Montre\1544776620_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0116TAS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0116TAS\V2\Montre\1547023222_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0117DRR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0117DRR\V2\Montre\1549442174_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0118DGR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0118DGR\V2\Montre\1543308050_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0119MLR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0119MLR\V2\Montre\1546851728_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0120MHR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0120MHR\V2\Montre\1547196083_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0121CNR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0121CNR\V2\Montre\1547109971_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0122MMR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0122MMR\V2\Montre\1547455571_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0123TMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0123TMS\V2\Montre\1547628022_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0124BIR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0124BIR\V2\Montre\1548664515_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0125BMR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0125BMR\V2\Montre\1547800679_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0126ANS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0126ANS\V2\Montre\1549269860_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0127RPS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0127RPS\V2\Montre\1548232080_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0128VCR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0128VCR\V2\Montre\1549010209_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0129GVS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0129GVS\V2\Montre\1549614467_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V2\Montre\1556872678_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130MAS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130MAS\V2\Montre\1551429190_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131CPS0156CPS\V2\Montre\1575882211_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131PAS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131PAS\V2\Montre\1550222900_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132AMR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132AMR\V2\Montre\1549874243_A01115\EDA.csv
🕒 PID=0132GAR | Dossier='1582102629_A01115' | UNIX path=2020-02-19 09:57:09 | CSV modif=2026-02-19 10:52:52
OK [0132GAR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Montre\1582102629_A01115\EDA.csv
🕒 PID=0133BPS | Dossier='1582707829_A01115' | UNIX path=2020-02-26 10:03:49 | CSV modif=2026-02-19 10:52:52
OK [0133BPS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Montre\1582707829_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133VLR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133VLR\V2\Montre\1552034276_A01115\EDA.csv
🕒 PID=0134IFR | Dossier='1583224544_A01115' | UNIX path=2020-03-03 09:35:44 | CSV modif=2026-02-19 10:52:52
OK [0134IFR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\montre\1583224544_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135FCS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135FCS\V2\Montre\1550479103_A01115\EDA.csv
🕒 PID=0135KLS | Dossier='1614757320_A01115' | UNIX path=2021-03-03 08:42:00 | CSV modif=2026-02-19 10:52:53
OK [0135KLS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\montre\1614757320_A01115\EDA.csv
🕒 PID=0136CJR | Dossier='1617350469_A01115' | UNIX path=2021-04-02 10:01:09 | CSV modif=2026-02-19 10:52:53
OK [0136CJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\MONTRE\1617350469_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136SAS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136SAS\V2\Montre\1550651521_A01115\EDA.csv
🕒 PID=0137BMS | Dossier='1618214285_A01115' | UNIX path=2021-04-12 09:58:05 | CSV modif=2026-02-19 10:52:53
OK [0137BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\MONTRE\1618214285_A01115\EDA.csv
🕒 PID=0137BMS | Dossier='1618214285_A01115 (1)' | UNIX path=2021-04-12 09:58:05 | CSV modif=2026-02-19 10:52:53
OK [0137BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\MONTRE\1618214285_A01115 (1)\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137CMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137CMS\V2\Montre\1550738182_A01115\EDA.csv
🕒 PID=0138NWR | Dossier='1622621441_A01115' | UNIX path=2021-06-02 10:10:41 | CSV modif=2026-02-19 10:52:53
OK [0138NWR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\montre\1622621441_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138RMR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138RMR\V2\Montre\1549961276_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0139LCR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0139LCR\V2\Montre\1550565202_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0140MMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0140MMS\V2\Montre\1550826079_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0141ACR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0141ACR\V2\Montre\1551170316_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0142NFR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0142NFR\V2\Montre\1551342871_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0143BCR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0143BCR\V2\Montre\1551862132_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144SNS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144SNS\V2\Montre\1551947225_A01115\EDA.csv
🕒 PID=0144ZGR | Dossier='1656489854_A01115' | UNIX path=2022-06-29 10:04:14 | CSV modif=2026-02-19 10:52:54
OK [0144ZGR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\montre\1656489854_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0145GPR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0145GPR\V2\Montre\1553244048_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0146CAR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0146CAR\V2\Montre\1551775145_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0147ALS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0147ALS\V2\Montre\1552466534_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0148APR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0148APR\V2\Montre\1552553151_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0149CAS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0149CAS\V2\Montre\1551687059_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0150MAR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0150MAR\V2\Montre\1558079860_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0151SSS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0151SSS\V2\Montre\1556886220_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0151SSS\V2\Montre\1556886220_A01115 (1)\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0152RER\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0152RER\V2\Montre\1557230945_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0152RER\V2\Montre\1557230945_A01115 (1)\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0153RDS\V2\Montre\EDA.csv

,Numero_inclusion,Chemin,Condition,Feuille
0,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Montre\1582102629_A01115\EDA.csv,Réduction de la menace,LPC
1,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Montre\1582707829_A01115\EDA.csv,Standard,LPC
2,0134IFR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\montre\1583224544_A01115\EDA.csv,Réduction de la menace,LPC
3,0135KLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\montre\1614757320_A01115\EDA.csv,Standard,LPC
4,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\MONTRE\1617350469_A01115\EDA.csv,Réduction de la menace,LPC
5,0137BMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\MONTRE\1618214285_A01115 (1)\EDA.csv,Standard,LPC
6,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\montre\1622621441_A01115\EDA.csv,Réduction de la menace,LPC
7,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\montre\1656489854_A01115\EDA.csv,Réduction de la menace,LPC
8,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V2 0140LMR\MONTRE\1642063125_A01115\EDA.csv,Réduction de la menace,LPC
9,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR V2\montre\1651050086_A01115\EDA.csv,Réduction de la menace,LPC

## SAINTE-MARGUERITE

In [22]:
# ===== Racine Sainte-Marguerite =====
racine_sm = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite"

# ===== Candidats attendus =====
candidats_sm = [c.upper() for c in resultats_globaux["SAINTE-MARGUERITE"]["valides"]]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["SAINTE-MARGUERITE"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

# ===== Liste pour stocker les fichiers EDA =====
rows = []

# =========================================================
# BOUCLE SUR LES ZIP avec filtre V2
# =========================================================
for root, dirs, files in os.walk(racine_sm):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".zip"):
            continue

        chemin_zip = os.path.join(root, f)
        chemin_upper = chemin_zip.upper()

        # ===== Cherche Numer_inclusion comme sous-chaîne =====
        pid_trouve = None
        for c in candidats_sm:
            if c in chemin_upper:
                pid_trouve = c
                break

        if not pid_trouve:
            print(f"❌ PID NON TROUVÉ : {chemin_zip}")
            continue

        # ===== Dézipper dans le dossier du ZIP lui-même =====
        try:
            with zipfile.ZipFile(chemin_zip, 'r') as zf:
                # Cherche uniquement les fichiers EDA CSV
                eda_files = [name for name in zf.namelist() if "EDA" in name.upper() and name.lower().endswith(".csv")]

                if not eda_files:
                    print(f"❌ Pas de fichier EDA dans : {chemin_zip}")
                    continue

                for eda_name in eda_files:
                    # Extraction directement dans le dossier contenant le ZIP
                    zf.extract(eda_name, root)
                    eda_path = os.path.join(root, eda_name)

                    rows.append({
                        "Numero_inclusion": pid_trouve,
                        "Chemin": eda_path,
                        "Condition": dict_condition.get(pid_trouve),
                        "Feuille": "SAINTE-MARGUERITE"
                    })

                    print(f"✅ EDA extrait [{pid_trouve}] :", eda_path)

        except zipfile.BadZipFile:
            print(f"❌ ZIP corrompu : {chemin_zip}")

# =========================================================
# DATAFRAME FINAL
# =========================================================
df_sm = pd.DataFrame(rows)

# Suppression des doublons
df_sm = df_sm.drop_duplicates(subset="Numero_inclusion", keep="first").reset_index(drop=True)

print(f"\nNombre de fichiers EDA extraits Sainte-Marguerite : {len(df_sm)}")
display(df_sm)

✅ EDA extrait [0801HDR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V2\MONTRE_0801HDR_V2\EDA.csv
✅ EDA extrait [0802LAS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V2\MONTRE_0802LAS_V2\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS - V2\MONTRE_0803DPS_V2\1650010647_A01115(1).zip
✅ EDA extrait [0804GOR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR - V2\MONTRE_0804GOR_V2\EDA.csv
✅ EDA extrait [0805BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V2\MONTRE_0805BMS_V2\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\V2\0806KHS - V2\MONTRE_0806KHS_V2\1654155713_A01115.zip
✅ EDA extrait [0807OMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V2\0807OMR - V2\MONTRE_0807OMR_V2\EDA.csv
✅ EDA extrait [0808PJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0808PJR\0808PJR-V2\montre\EDA.csv

Nombre de fichiers EDA extraits Sainte-Marguerite : 6

,Numero_inclusion,Chemin,Condition,Feuille
0,0801HDR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V2\MONTRE_0801HDR_V2\EDA.csv,Réduction de la menace,SAINTE-MARGUERITE
1,0802LAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V2\MONTRE_0802LAS_V2\EDA.csv,Standard,SAINTE-MARGUERITE
2,0804GOR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR - V2\MONTRE_0804GOR_V2\EDA.csv,Réduction de la menace,SAINTE-MARGUERITE
3,0805BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V2\MONTRE_0805BMS_V2\EDA.csv,Standard,SAINTE-MARGUERITE
4,0807OMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V2\0807OMR - V2\MONTRE_0807OMR_V2\EDA.csv,Réduction de la menace,SAINTE-MARGUERITE
5,0808PJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0808PJR\0808PJR-V2\montre\EDA.csv,Réduction de la menace,SAINTE-MARGUERITE

## CGD

In [24]:
# ===== Racine CGD =====
racine_cgd = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD"
)

# ===== Candidats attendus =====
candidats_cgd = [
    c.upper() for c in resultats_globaux["CGD"]["valides"]
]

# ===== Dictionnaire Numero_inclusion → Condition =====
df_conditions = resultats_globaux["CGD"]["df"][
    ["Numero_inclusion", "Condition"]
].copy()

df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows_cgd = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_cgd):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification =====
        pid = None
        for c in candidats_cgd:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_cgd.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid),
            "Feuille": "CGD"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_cgd = pd.DataFrame(rows_cgd)

df_cgd = (
    df_cgd
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CGD : {len(candidats_cgd)}")
print(f"Fichiers EDA retenus   : {len(df_cgd)}")

manquants = sorted(
    set(candidats_cgd) - set(df_cgd["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CGD sont présents")

display(df_cgd)

OK [0902SIS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS_V2\MONTRE 0102SIS_V2\1652946369_A01115(1)\EDA.csv
OK [0904KJS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS - V2\MONTRE_0904KJS_V2\1656317741_A01115(3)\EDA.csv
OK [0905SLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V2\montre\1656922153_A01115\EDA.csv
OK [0906DNR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0906DNR\0906DNR_V2\montre\1657095308_A01115\EDA.csv

====================================
Candidats attendus CGD : 5
Fichiers EDA retenus   : 4
⚠️ Candidats manquants : ['0901SMR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0902SIS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS_V2\MONTRE 0102SIS_V2\1652946369_A01115(1)\EDA.csv,Standard,CGD
1,0904KJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS - V2\MONTRE_0904KJS_V2\1656317741_A01115(3)\EDA.csv,Standard,CGD
2,0905SLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V2\montre\1656922153_A01115\EDA.csv,Réduction de la menace,CGD
3,0906DNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0906DNR\0906DNR_V2\montre\1657095308_A01115\EDA.csv,Réduction de la menace,CGD

## CERCA

In [26]:
# ===== Racine CERCA =====
racine_cerca = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS"

# ===== Candidats CERCA =====
candidats_cerca = [c.upper() for c in resultats_globaux['CERCA']['valides']]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux['CERCA']['df'][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

# ===== Liste pour stocker les fichiers EDA =====
rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_cerca):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== Identification =====
        pid_trouve = None
        for c in candidats_cerca:
            if c in chemin_upper:
                pid_trouve = c
                break

        if not pid_trouve:
            print(f"❌ PID NON TROUVÉ : {chemin}")
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid_trouve),
            "Feuille": "CERCA"
        })

        print(f"✅ EDA trouvé [{pid_trouve}] :", chemin)

# =========================================================
# DATAFRAME 
# =========================================================
df_cerca_final = pd.DataFrame(rows)
df_cerca_final = df_cerca_final.drop_duplicates(subset="Numero_inclusion", keep="first").reset_index(drop=True)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CERCA : {len(candidats_cerca)}")
print(f"Fichiers EDA retenus CERCA : {len(df_cerca_final)}")

manquants = sorted(set(candidats_cerca) - set(df_cerca_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CERCA sont présents")

display(df_cerca_final)

❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0402TFR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0411NPR\V2\Montre\EDA.csv
✅ EDA trouvé [0413MMR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0413MMR\V2\Montre\EDA.csv
✅ EDA trouvé [0415HJS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0415HJS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0416CPR\V2\Montre\EDA.csv
✅ EDA trouvé [0417FAS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0417FAS\V2\Montre\EDA.csv
✅ EDA trouvé [0418MPR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0418MPR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0419CHR\V2\Montre\EDA.csv
✅ EDA trouvé [0420MCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0420MCR\V2\Montre\EDA.csv
✅ EDA trouvé [0421ACS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0421ACS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0407HMS\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V2\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V2\Montre\EDA.csv
✅ EDA trouvé [0414PVR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0414PVR\V2\Montre\EDA.csv

====================================
Candidats attendus CERCA : 14
Fichiers EDA retenus CERCA : 7
⚠️ Candidats manquants : ['0417KMS', '0418TJR', '0419SRR', '0420LMR', '0422WCS', '0423RMR', '0424BLR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0413MMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0413MMR\V2\Montre\EDA.csv,Réduction de la menace,CERCA
1,0415HJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0415HJS\V2\Montre\EDA.csv,Standard,CERCA
2,0417FAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0417FAS\V2\Montre\EDA.csv,Standard,CERCA
3,0418MPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0418MPR\V2\Montre\EDA.csv,Réduction de la menace,CERCA
4,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0420MCR\V2\Montre\EDA.csv,Réduction de la menace,CERCA
5,0421ACS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0421ACS\V2\Montre\EDA.csv,Standard,CERCA
6,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0414PVR\V2\Montre\EDA.csv,Réduction de la menace,CERCA

## CONCATENATION

In [27]:
# ===== Liste des DataFrames par feuille =====
dfs = [
    df_aphm_final,  
    df_caen_final,
    df_poitiers_final,     
    df_rouen_final,
    df_laveran_final,
    df_lpc_final,         
    df_lpc2_final,
    df_sm,          
    df_cgd,         
    df_cerca_final      
]

# ===== Normalisation des colonnes =====
for i, df in enumerate(dfs):
    if "PID" in df.columns:
        df.rename(columns={"PID": "Numero_inclusion"}, inplace=True)
    # Assurer que la colonne Condition existe
    if "Condition" not in df.columns:
        df["Condition"] = None
    # On garde uniquement les colonnes essentielles
    df = df[["Numero_inclusion", "Chemin", "Feuille", "Condition"]]
    dfs[i] = df

# ===== Concatenation =====
df_global = pd.concat(dfs, ignore_index=True)

# ===== Suppression des doublons par Numero_inclusion =====
# On garde le premier fichier détecté par candidat (priorité ceinture déjà appliquée)
df_global = df_global.drop_duplicates(subset=["Numero_inclusion"], keep="first")

# ===== Tri par Numero_inclusion =====
df_global = df_global.sort_values("Numero_inclusion").reset_index(drop=True)

# ===== Résumé =====
print(f"Total candidats uniques : {df_global['Numero_inclusion'].nunique()}")
print(f"Total fichiers conservés : {len(df_global)}")
display(df_global)

Total candidats uniques : 156
Total fichiers conservés : 156

,Numero_inclusion,Chemin,Feuille,Condition
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 06-07-2018 V2\Montre 0101CAR\1530858300_A01093\EDA.csv,APHM,Réduction de la menace
1,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Montre\1548148240_A01115\EDA.csv,LPC,Standard
2,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 09-07-2018 V2\Montre 0102PCR\1531119483_A01093\EDA.csv,APHM,Réduction de la menace
3,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Montre\1544519314_A01115\EDA.csv,LPC,Standard
4,0103SHS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0103SHS\0103SHS 10-09-2018 V2\Montre 0103SHS\1536563089_A01093\EDA.csv,APHM,Standard
5,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 29-11-2018 V2\Montre 0104FJS\1543476632_A01093\EDA.csv,APHM,Standard
6,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Montre\1543395529_A01115\EDA.csv,LPC,Standard
7,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 10-12-2018 V2\Montre 0105PNR\1544426613_A01093\EDA.csv,APHM,Réduction de la menace
8,0106DJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0106DJR\V2\Montre\1545210317_A01115\EDA.csv,LPC,Réduction de la menace
9,0106JLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0106JLS\0106JLS 03-01-2019 V2\Montre 0106JLS\1546500427_A01093\EDA.csv,APHM,Standard
10,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 14-01-2019 V2\Montre 0107DSS\1547450742_A01093\EDA.csv,APHM,Standard
11,0108BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0108BFS\0108BFS 17-01-2019 V2\Montre 0108BFS\1547711087_A01093\EDA.csv,APHM,Standard
12,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 18-02-2019 V2\Montre 0109GSS\1550476660_A01093\EDA.csv,APHM,Standard
13,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Montre\1544690346_A01115\EDA.csv,LPC,Réduction de la menace
14,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 26-02-2019 V2\Montre 0110LPR\1551167333_A01093\EDA.csv,APHM,Réduction de la menace
15,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Montre\1544776620_A01115\EDA.csv,LPC,Standard
16,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 28-02-2019 V2\Montre 0111MNR\1551341044_A01093\EDA.csv,APHM,Réduction de la menace
17,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR 06-06-2019 V2\Montre 0112BSR\1559802681_A01093\EDA.csv,APHM,Réduction de la menace
18,0113BMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0113BMR\0113BMR 20-06-2019 V2\Montre 0113BMR\1561011593_A01093\EDA.csv,APHM,Réduction de la menace
19,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Montre\1543308050_A01115\EDA.csv,LPC,Réduction de la menace
20,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS 27-06-2019 V2\Montre 0114LMS\1561617443_A01093\EDA.csv,APHM,Standard
21,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Montre\1546851728_A01115\EDA.csv,LPC,Réduction de la menace
22,0115CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0115CJR\0115CJR 27-08-2019 V2\Montre 0115CJR\1566887219_A01093\EDA.csv,APHM,Réduction de la menace
23,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\Montre\1547196083_A01115\EDA.csv,LPC,Réduction de la menace
24,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Montre\1547109971_A01115\EDA.csv,LPC,Réduction de la menace
25,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR 29-08-2019 V2\Montre 0116VAR\1567060805_A01093\EDA.csv,APHM,Réduction de la menace
26,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Montre\1547455571_A01115\EDA.csv,LPC,Réduction de la menace
27,0117POS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0117POS\0117POS 05-09-2019 V2\Montre 0117POS\1567664747_A01093\EDA.csv,APHM,Standard
28,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Montre\1547628022_A01115\EDA.csv,LPC,Standard
29,0118TNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0118TNS\0118TNS 01-10-2019 V2\Montre 0118TNS\1569911840_A01093\EDA.csv,APHM,Standard
30,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Montre\1548664515_A01115\EDA.csv,LPC,Réduction de la menace
31,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS 07-11-2019 V2\Montre 0119LJS\1573112319_A01093\EDA.csv,APHM,Standard
32,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Montre\1549269860_A01115\EDA.csv,LPC,Standard
33,0120LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0120LCR\0120LCR 06-12-2019 V2\Montre 0120LCR\1575617159_A01093\EDA.csv,APHM,Réduction de la menace
34,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR 12-12-2019 V2\Montre 0121MJR\1576137833_A01093\EDA.csv,APHM,Réduction de la menace
35,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Montre\1548232080_A01115\EDA.csv,LPC,Standard
36,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Montre\1549010209_A01115\EDA.csv,LPC,Réduction de la menace
37,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Montre\1549614467_A01115\EDA.csv,LPC,Standard
38,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS 20-12-2019 V2\Montre 0123 RMS\1576827353_A01093\EDA.csv,APHM,Standard
39,0124BAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0124BAR\V2\montre\1578386536_A01093\EDA.csv,APHM,Réduction de la menace
40,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Montre\1550222900_A01115\EDA.csv,LPC,Standard
41,0125BMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0125BMR\V2\MONTRE\1578997658_A01093\EDA.csv,APHM,Réduction de la menace
42,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Montre\1552034276_A01115\EDA.csv,LPC,Réduction de la menace
43,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Montre\1550738182_A01115\EDA.csv,LPC,Standard
44,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Montre\1552466534_A01115\EDA.csv,LPC,Standard
45,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Montre\1552553151_A01115\EDA.csv,LPC,Réduction de la menace
46,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0130FAR\V2\Montre\1556872678_A01115\EDA.csv,LPC,Réduction de la menace
47,0131CPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0131CPS\V2\Montre\1575882211_A01115\EDA.csv,LPC,Standard
48,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Montre\1582102629_A01115\EDA.csv,LPC,Réduction de la menace
49,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Montre\1582707829_A01115\EDA.csv,LPC,Standard
50,0134IFR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\montre\1583224544_A01115\EDA.csv,LPC,Réduction de la menace
51,0135KLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\montre\1614757320_A01115\EDA.csv,LPC,Standard
52,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\MONTRE\1617350469_A01115\EDA.csv,LPC,Réduction de la menace
53,0137BMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\MONTRE\1618214285_A01115 (1)\EDA.csv,LPC,Standard
54,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\montre\1622621441_A01115\EDA.csv,LPC,Réduction de la menace
55,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V2 0140LMR\MONTRE\1642063125_A01115\EDA.csv,LPC,Réduction de la menace
56,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR V2\montre\1651050086_A01115\EDA.csv,LPC,Réduction de la menace
57,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\montre\1656489854_A01115\EDA.csv,LPC,Réduction de la menace
58,0301GNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0301GNR\Montre\1547630037_A01295 0301GNR\EDA.csv,CAEN,Réduction de la menace
59,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0302ZMR\montre\1548318959_A01295 0302 ZMR\EDA.csv,CAEN,Réduction de la menace
60,0303PAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0303PAR\Montre\1552553872_A01295 0303 PAR\EDA.csv,CAEN,Réduction de la menace
61,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0304VMR\Montre\1553502969_A01295 0304 VMR\EDA.csv,CAEN,Réduction de la menace
62,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1556179294_A01295 0305 LCR\EDA.csv,CAEN,Réduction de la menace
63,0306MDR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1557145160_A012950306 MDR\EDA.csv,CAEN,Réduction de la menace
64,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1557735741_A01295 0307SMR\EDA.csv,CAEN,Réduction de la menace
65,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1561452848_A01295 0308RGR\EDA.csv,CAEN,Réduction de la menace
66,0309DBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1561634352_A01295 0309DBS\EDA.csv,CAEN,Standard
67,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1562140652_A01295 0310ACS\EDA.csv,CAEN,Standard
68,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1562153876_A01295 0311CJS\EDA.csv,CAEN,Standard
69,0312JMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1563782337_A01295 0312JMS\EDA.csv,CAEN,Standard
70,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1563884804_A01295 0313FPR\EDA.csv,CAEN,Réduction de la menace
71,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567064965_A01295 0315VCS\EDA.csv,CAEN,Standard
72,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567496846_A01295 0316TMS\EDA.csv,CAEN,Standard
73,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567669152_A01295 0317LGS\EDA.csv,CAEN,Standard
74,0318PMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1567758189_A01295 0318PMS\EDA.csv,CAEN,Standard
75,0320DGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1569917948_A01295 0320DGS\EDA.csv,CAEN,Standard
76,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1570523646_A01295 0321DRR\EDA.csv,CAEN,Réduction de la menace
77,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1570697421_A01295 0322RMS\EDA.csv,CAEN,Standard
78,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1572945137_A01295 0323RFS\EDA.csv,CAEN,Standard
79,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1573207008_A01295 0324LMR\EDA.csv,CAEN,Réduction de la menace
80,0325LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1573809796_A01295 0325LCR\EDA.csv,CAEN,Réduction de la menace
81,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1574413338_A01295 0326BJR\EDA.csv,CAEN,Réduction de la menace
82,0327IAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1574672184_A01295 0327IAR\EDA.csv,CAEN,Réduction de la menace
83,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1575535612_A01295 0328MPR\EDA.csv,CAEN,Réduction de la menace
84,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1580201554_A01295 0329NMR\EDA.csv,CAEN,Réduction de la menace
85,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1580460885_A01295 0330RTR\EDA.csv,CAEN,Réduction de la menace
86,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1581429283_A01295 0331GRS\EDA.csv,CAEN,Standard
87,0332MCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1583485073_A01295 0332MCR\EDA.csv,CAEN,Réduction de la menace
88,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1601019503_A01295 0333MMS\EDA.csv,CAEN,Standard
89,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1601538039_A01295 0334TVS\EDA.csv,CAEN,Standard
90,0336CBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1602834220_A01295 0336CBS\EDA.csv,CAEN,Standard
91,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1606206251_A01295 0337BFS\EDA.csv,CAEN,Standard
92,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1614242134_A01295 0339NPR\EDA.csv,CAEN,Réduction de la menace
93,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1621237386_A01295 0341LJS\EDA.csv,CAEN,Standard
94,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1622533024_A01295 0342VNS\EDA.csv,CAEN,Standard
95,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1623137842_A01295 0343PAS\EDA.csv,CAEN,Standard
96,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643287622_A01295 0345LAR\EDA.csv,CAEN,Réduction de la menace
97,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643358334_A01295 0346GLS\EDA.csv,CAEN,Standard
98,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643619887_A01295 0347DMR\EDA.csv,CAEN,Réduction de la menace
99,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1643707290_A01295 0348GCR\EDA.csv,CAEN,Réduction de la menace
100,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1645433839_A01295 0349LLS\EDA.csv,CAEN,Standard
101,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1647593250_A01295 0350MYR\EDA.csv,CAEN,Réduction de la menace
102,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1648198966_A01295 0351FIR\EDA.csv,CAEN,Réduction de la menace
103,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1650009653_A01295 0352RNR\EDA.csv,CAEN,Réduction de la menace
104,0354GKR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1656315057_A01295 0354GKR\EDA.csv,CAEN,Réduction de la menace
105,0355BAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1656575009_A01295 0355BAS\EDA.csv,CAEN,Standard
106,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1663832640_A012950356DMS\EDA.csv,CAEN,Standard
107,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V2\0401TSS- montre\EDA.csv,POITIERS,Standard
108,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS- V2\0402LLS- montre\EDA.csv,POITIERS,Standard
109,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V2\0403DCR- montre\EDA.csv,POITIERS,Réduction de la menace
110,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404CYS-V2\0404YC-montre\EDA.csv,POITIERS,Standard
111,0405FCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0405 FC\0405 FCR-V2\0405FCR- montre\EDA.csv,POITIERS,Réduction de la menace
112,0406MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0406 MC\0406 MCS-V2\0406MCS-montre\EDA.csv,POITIERS,Standard
113,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V2\0407LJ-montre\EDA.csv,POITIERS,Réduction de la menace
114,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC V2\0408BC-montre\EDA.csv,POITIERS,Standard
115,0410PGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0410 PG\0410 PGS - V2\montre\0410PGS\EDA.csv,POITIERS,Standard
116,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V2\0411VE montre\EDA.csv,POITIERS,Standard

In [28]:
# CONSERVATION DES FEUILLES ET DES CONDITIONS 

chemin_txt = r"C:\Users\judupont\Desktop\df_global_v2_EDA.txt"

df_global.to_csv(
    chemin_txt,
    sep="\t",
    index=False,
    encoding="utf-8-sig"
)

print(f"📄 df_global sauvegardé : {chemin_txt}")

📄 df_global sauvegardé : C:\Users\judupont\Desktop\df_global_v2_EDA.txt

# Verification que le temps d'experience et le temps du fichier EDA correspondent, offset et continuité

In [29]:
def convertir_heure_en_secondes(x):
    if pd.isna(x):
        return None

    if isinstance(x, (int, float)):
        seconds = float(x) * 24 * 3600
        return seconds % (24 * 3600)

    try:
        t = pd.to_datetime(str(x).strip()).time()
        return t.hour * 3600 + t.minute * 60 + t.second
    except Exception:
        return None

set_global = set(df_global["Numero_inclusion"])


dfs_excel = []

for feuille, data in resultats_bloc1.items():

    df_excel = data["df"].copy()

    # ===== NORMALISATION EXCEL =====
    df_excel["Numero_inclusion"] = (
        df_excel["Numero_inclusion"]
        .astype(str)
        .str.strip()
        .str.upper()
    )
    
    df_excel = df_excel[
        df_excel["Numero_inclusion"].isin(set_global)
    ]

    if df_excel.empty:
        continue

    # ===== Conversion heures =====
    df_excel["heure_debut_sec"] = df_excel["heure_montre_v2"].apply(convertir_heure_en_secondes)
    df_excel["heure_fin_sec"] = df_excel["heure_fin_tests_v2"].apply(convertir_heure_en_secondes)

    # ========= Durée de la visite ========== 
    df_excel["duree_experience_sec"] = (
        df_excel["heure_fin_sec"] - df_excel["heure_debut_sec"]
    )

    df_excel.loc[
        df_excel["duree_experience_sec"] < 0,
        "duree_experience_sec"
    ] += 24 * 3600

    df_excel["Feuille"] = feuille
    dfs_excel.append(df_excel)


if dfs_excel:
    df_excel_global = pd.concat(dfs_excel, ignore_index=True)
else:
    df_excel_global = pd.DataFrame()

print(f"Lignes Excel retenues : {len(df_excel_global)}")
display(df_excel_global[[
    "Numero_inclusion",
    "Feuille",
    "duree_experience_sec"
]])

Lignes Excel retenues : 156

    Numero_inclusion            Feuille  duree_experience_sec
0            0101CAR               APHM                  9420
1            0102PCR               APHM                  7560
2            0103SHS               APHM                  5520
3            0105PNR               APHM                  7260
4            0104FJS               APHM                  9600
5            0106JLS               APHM                  7440
6            0107DSS               APHM                  7320
7            0108BFS               APHM                  7920
8            0109GSS               APHM                  7500
9            0110LPR               APHM                  8160
10           0111MNR               APHM                  7860
11           0112BSR               APHM                  9240
12           0113BMR               APHM                  7620
13           0114LMS               APHM                  6360
14           0115CJR               APHM                  6120
15           0116VAR               APHM                  8700
16           0117POS               APHM                  6660
17           0118TNS               APHM                  6780
18           0119LJS               APHM                  6540
19           0120LCR               APHM                  7500
20           0121MJR               APHM                  7080
21           0123RMS               APHM                  6960
22           0124BAR               APHM                  7380
23           0125BMR               APHM                  7860
24           0301GNR               CAEN                  7560
25           0302ZMR               CAEN                  6540
26           0303PAR               CAEN                  5880
27           0304VMR               CAEN                  7740
28           0305LCR               CAEN                  6540
29           0307SMR               CAEN                  7440
30           0306MDR               CAEN                  6360
31           0308RGR               CAEN                  7140
32           0309DBS               CAEN                  7740
33           0311CJS               CAEN                  7200
34           0310ACS               CAEN                  7560
35           0315VCS               CAEN                  6240
36           0318PMS               CAEN                  5340
37           0313FPR               CAEN                  6660
38           0312JMS               CAEN                  6480
39           0316TMS               CAEN                  5580
40           0317LGS               CAEN                  5640
41           0320DGS               CAEN                  5340
42           0321DRR               CAEN                  5940
43           0323RFS               CAEN                  6060
44           0322RMS               CAEN                  4920
45           0324LMR               CAEN                  6240
46           0325LCR               CAEN                  6060
47           0327IAR               CAEN                  6300
48           0326BJR               CAEN                  6420
49           0328MPR               CAEN                  6600
50           0330RTR               CAEN                  6840
51           0329NMR               CAEN                  7020
52           0331GRS               CAEN                  5280
53           0332MCR               CAEN                  7260
54           0333MMS               CAEN                  5640
55           0334TVS               CAEN                  5460
56           0336CBS               CAEN                  7200
57           0337BFS               CAEN                  9000
58           0339NPR               CAEN                  6180
59           0341LJS               CAEN                  5820
60           0342VNS               CAEN                  6780
61           0343PAS               CAEN                  5100
62           0345LAR               CAEN                  5640
63           0349LLS               CAEN                  6720
64           0347DMR               CAEN                  6540
65           0346GLS               CAEN                  5460
66           0348GCR               CAEN                  7200
67           0350MYR               CAEN                  6420
68           0351FIR               CAEN                  6600
69           0352RNR               CAEN                  6000
70           0354GKR               CAEN                  6600
71           0355BAS               CAEN                  6240
72           0356DMS               CAEN                  6180
73           0401TSS           POITIERS                  8580
74           0402LLS           POITIERS                  7380
75           0403DCR           POITIERS                  7500
76           0405FCR           POITIERS                  8760
77           0404CYS           POITIERS                  9240
78           0406MCS           POITIERS                  7260
79           0407LJR           POITIERS                  8940
80           0408BCS           POITIERS                  8100
81           0410PGS           POITIERS                  8460
82           0413HFS           POITIERS                  7860
83           0411VES           POITIERS                  7620
84           0412ANS           POITIERS                  7080
85           0415VMR           POITIERS                  6480
86           0501MBS              ROUEN                  6300
87           0502LIR              ROUEN                  7260
88           0503LCR              ROUEN                  7080
89           0504BCS              ROUEN                  6900
90           0505PPR              ROUEN                  7200
91           0506VMS              ROUEN                  7140
92           0508SRR              ROUEN                  6540
93           0507BDS              ROUEN                  7740
94           0509LGS              ROUEN                  7620
95           0510DFS              ROUEN                  6540
96           0511LCS              ROUEN                  8100
97           0512RCR              ROUEN                  6600
98           0513EBS              ROUEN                  5820
99           0515FAR              ROUEN                  6720
100          0626MCS            LAVERAN                  6540
101          0628DMR            LAVERAN                  8040
102          0630RJR            LAVERAN                  5580
103          0629TCR            LAVERAN                  8040
104          0631LHR            LAVERAN                  5820
105          0101EMS                LPC                  6240
106          0103BPS                LPC                  5160
107          0104IBS                LPC                  5640
108          0106DJR                LPC                  6600
109          0109MJR                LPC                  6360
110          0110RMS                LPC                  5640
111          0113DGR                LPC                  6240
112          0114MLR                LPC                  6780
113          0115MHR                LPC                  6540
114          0116CNR                LPC                  7020
115          0117MSR                LPC                  6780
116          0118TMS                LPC                  6960
117          0119BIR                LPC                  6060
118          0120ANS                LPC                  5580
119          0121RPS                LPC                  5400
120          0122VCR                LPC                  7920
121          0123GVS                LPC                  4980
122          0124PAS                LPC                  5160
123          0126VLR                LPC                  5820
124          0127CMS                LPC                  5340
125          0128ALS                LPC                  5700
126          0129APR                LPC                  8580
127          0130FAR                LPC                  7560
128          0131CPS                LPC                  5340
129          0132GAR                LPC                  5580
130          0133BPS                LPC                  5760
131          0134IFR                LPC                  5520
132          0135KLS                LPC                  5700
133          0136CJR                LPC                  5880
134          0137BMS                LPC                  6060
135          0138NWR                LPC                  6780
136          0140LMR                LPC                  7260
137          0143EBR                LPC                  7140
138          0144ZGR                LPC                  9120
139          0801HDR  SAINTE-MARGUERITE                  7200
140          0802LAS  SAINTE-MARGUERITE                  6540
141          0804GOR  SAINTE-MARGUERITE                  6720
142          0805BMS  SAINTE-MARGUERITE                  5520
143          0807OMR  SAINTE-MARGUERITE                  6120
144          0808PJR  SAINTE-MARGUERITE                  6720
145          0902SIS                CGD                  4860
146          0906DNR                CGD                 10020
147          0904KJS                CGD                  6060
148          0905SLR                CGD                  6600
149          0413MMR              CERCA                  6840
150          0414PVR              CERCA                  6840
151          0415HJS              CERCA                  5940
152          0417FAS              CERCA                  6300
153          0418MPR              CERCA                  7320
154          0420MCR              CERCA                  7440
155          0421ACS              CERCA                  5580

In [30]:
# ==== Conversion Date dans Excel ====
df_excel_global["Date_v2_dt"] = pd.to_datetime(
    df_excel_global["Date_v2"], errors="coerce"
).dt.date

rows_eda = []

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin = row["Chemin"]

    # ---- récupérer ligne Excel ----
    ligne_excel = df_excel_global[df_excel_global["Numero_inclusion"] == pid]
    if ligne_excel.empty:
        continue

    date_v2 = ligne_excel.iloc[0]["Date_v2_dt"]
    duree_excel_sec = ligne_excel.iloc[0]["duree_experience_sec"]

    # ---- lecture CSV EDA (ZIP ou non) ----
    try:
        if ".ZIP|" in chemin.upper():
            zip_path, inner_csv = chemin.split("|", 1)
            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_eda_raw = pd.read_csv(f, header=None)
        else:
            df_eda_raw = pd.read_csv(chemin, header=None)

    except Exception as e:
        print(f"⚠️ Lecture impossible EDA pour {pid} : {e}")
        continue

    if len(df_eda_raw) < 3:
        continue

    # ---- récupération timestamp initial + fréquence ----
    try:
        t0_unix = float(df_eda_raw.iloc[0, 0])
        freq = float(df_eda_raw.iloc[1, 0])
    except:
        continue

    if freq <= 0:
        continue

    # ---- données EDA ----
    df_eda = df_eda_raw.iloc[2:].copy()
    df_eda.columns = ["EDA"]
    df_eda["EDA"] = pd.to_numeric(df_eda["EDA"], errors="coerce")
    df_eda = df_eda.dropna()

    if df_eda.empty:
        continue

    # ---- construction timestamps ----
    pas = 1 / freq
    n_points = len(df_eda)

    duree_eda_sec = (n_points - 2) * pas

    # timestamp début/fin
    t_debut = datetime.datetime.fromtimestamp(t0_unix)
    t_fin = t_debut + datetime.timedelta(seconds=duree_eda_sec)


    rows_eda.append({
        "Numero_inclusion": pid,
        "duree_eda_sec": round(duree_eda_sec, 0),
        "duree_excel_sec": duree_excel_sec,
        "nb_points": n_points,
        "frequence": freq
    })

df_eda_global = pd.DataFrame(rows_eda)

print(f"EDA calculés : {len(df_eda_global)}")
display(df_eda_global)

EDA calculés : 156

    Numero_inclusion  duree_eda_sec  duree_excel_sec  nb_points  frequence
0            0101CAR         9529.0             9420      38118        4.0
1            0101EMS         6298.0             6240      25194        4.0
2            0102PCR         7702.0             7560      30810        4.0
3            0103BPS         5198.0             5160      20796        4.0
4            0103SHS         5628.0             5520      22512        4.0
5            0104FJS         9864.0             9600      39456        4.0
6            0104IBS         5665.0             5640      22662        4.0
7            0105PNR         7476.0             7260      29904        4.0
8            0106DJR         6658.0             6600      26634        4.0
9            0106JLS         7638.0             7440      30552        4.0
10           0107DSS         7286.0             7320      29148        4.0
11           0108BFS         8052.0             7920      32208        4.0
12           0109GSS         7813.0             7500      31254        4.0
13           0109MJR         6325.0             6360      25302        4.0
14           0110LPR         8252.0             8160      33012        4.0
15           0110RMS         5698.0             5640      22794        4.0
16           0111MNR         7933.0             7860      31734        4.0
17           0112BSR         9372.0             9240      37488        4.0
18           0113BMR         7741.0             7620      30966        4.0
19           0113DGR         6266.0             6240      25068        4.0
20           0114LMS         6464.0             6360      25860        4.0
21           0114MLR         6832.0             6780      27330        4.0
22           0115CJR         6320.0             6120      25284        4.0
23           0115MHR         6559.0             6540      26238        4.0
24           0116CNR         7012.0             7020      28050        4.0
25           0116VAR         8755.0             8700      35022        4.0
26           0117MSR         6814.0             6780      27258        4.0
27           0117POS         6790.0             6660      27162        4.0
28           0118TMS         6985.0             6960      27942        4.0
29           0118TNS         6865.0             6780      27462        4.0
30           0119BIR         6066.0             6060      24264        4.0
31           0119LJS         6769.0             6540      27078        4.0
32           0120ANS         5628.0             5580      22512        4.0
33           0120LCR         7728.0             7500      30912        4.0
34           0121MJR         7312.0             7080      29250        4.0
35           0121RPS         5414.0             5400      21660        4.0
36           0122VCR         8148.0             7920      32592        4.0
37           0123GVS         4958.0             4980      19836        4.0
38           0123RMS         7148.0             6960      28596        4.0
39           0124BAR         7368.0             7380      29472        4.0
40           0124PAS         5161.0             5160      20646        4.0
41           0125BMR         7990.0             7860      31962        4.0
42           0126VLR         5714.0             5820      22860        4.0
43           0127CMS         5354.0             5340      21420        4.0
44           0128ALS         5758.0             5700      23034        4.0
45           0129APR         8644.0             8580      34578        4.0
46           0130FAR         7760.0             7560      31044        4.0
47           0131CPS         5322.0             5340      21288        4.0
48           0132GAR         5719.0             5580      22878        4.0
49           0133BPS         5774.0             5760      23100        4.0
50           0134IFR         5569.0             5520      22278        4.0
51           0135KLS         5552.0             5700      22212        4.0
52           0136CJR         5923.0             5880      23694        4.0
53           0137BMS         6080.0             6060      24324        4.0
54           0138NWR         6796.0             6780      27186        4.0
55           0140LMR         7262.0             7260      29052        4.0
56           0143EBR         7225.0             7140      28902        4.0
57           0144ZGR         9080.0             9120      36324        4.0
58           0301GNR         8920.0             7560      35682        4.0
59           0302ZMR         7072.0             6540      28290        4.0
60           0303PAR         6046.0             5880      24186        4.0
61           0304VMR         8839.0             7740      35358        4.0
62           0305LCR         6967.0             6540      27870        4.0
63           0306MDR         6559.0             6360      26238        4.0
64           0307SMR         7734.0             7440      30936        4.0
65           0308RGR         7324.0             7140      29298        4.0
66           0309DBS         8028.0             7740      32112        4.0
67           0310ACS         7580.0             7560      30324        4.0
68           0311CJS         7411.0             7200      29646        4.0
69           0312JMS         6686.0             6480      26748        4.0
70           0313FPR         6680.0             6660      26724        4.0
71           0315VCS         6684.0             6240      26736        4.0
72           0316TMS         5980.0             5580      23922        4.0
73           0317LGS         6535.0             5640      26142        4.0
74           0318PMS         5758.0             5340      23034        4.0
75           0320DGS         5488.0             5340      21954        4.0
76           0321DRR         6200.0             5940      24804        4.0
77           0322RMS         4963.0             4920      19854        4.0
78           0323RFS         7708.0             6060      30834        4.0
79           0324LMR         6598.0             6240      26394        4.0
80           0325LCR         6775.0             6060      27102        4.0
81           0326BJR         6534.0             6420      26136        4.0
82           0327IAR         6770.0             6300      27084        4.0
83           0328MPR         7150.0             6600      28602        4.0
84           0329NMR         7626.0             7020      30504        4.0
85           0330RTR         6946.0             6840      27786        4.0
86           0331GRS         5596.0             5280      22386        4.0
87           0332MCR         8578.0             7260      34314        4.0
88           0333MMS         6652.0             5640      26610        4.0
89           0334TVS         5773.0             5460      23094        4.0
90           0336CBS         7902.0             7200      31608        4.0
91           0337BFS         9649.0             9000      38598        4.0
92           0339NPR         6696.0             6180      26784        4.0
93           0341LJS         6596.0             5820      26388        4.0
94           0342VNS         7153.0             6780      28614        4.0
95           0343PAS         5916.0             5100      23664        4.0
96           0345LAR         5995.0             5640      23982        4.0
97           0346GLS         7946.0             5460      31788        4.0
98           0347DMR         7016.0             6540      28068        4.0
99           0348GCR         7396.0             7200      29586        4.0
100          0349LLS         7118.0             6720      28476        4.0
101          0350MYR         6972.0             6420      27888        4.0
102          0351FIR         8088.0             6600      32352        4.0
103          0352RNR         6458.0             6000      25836        4.0
104          0354GKR         7998.0             6600      31992        4.0
105          0355BAS         6902.0             6240      27612        4.0
106          0356DMS         3643.0             6180      14574        4.0
107          0401TSS         9079.0             8580      36318        4.0
108          0402LLS         8460.0             7380      33840        4.0
109          0403DCR         8606.0             7500      34428        4.0
110          0404CYS        11696.0             9240      46788        4.0
111          0405FCR        10165.0             8760      40662        4.0
112          0406MCS         8992.0             7260      35970        4.0
113          0407LJR          430.0             8940       1722        4.0
114          0408BCS         9956.0             8100      39828        4.0
115          0410PGS         9787.0             8460      39150        4.0
116          0411VES         8732.0             7620      34932        4.0
117          0412ANS         7609.0             7080      30438        4.0
118          0413HFS         8432.0             7860      33732        4.0
119          0413MMR         7058.0             6840      28236        4.0
120          0414PVR         6766.0             6840      27066        4.0
121          0415HJS         5912.0             5940      23652        4.0
122          0415VMR         7081.0             6480      28326        4.0
123          0417FAS         6256.0             6300      25026        4.0
124          0418MPR         7388.0             7320      29556        4.0
125          0420MCR         7292.0             7440      29172        4.0
126          0421ACS         5700.0             5580      22800        4.0
127          0501MBS         6902.0             6300      27612        4.0
128          0502LIR         7411.0             7260      29646        4.0
129          0503LCR         7020.0             7080      28080        4.0
130          0504BCS         7904.0             6900      31620        4.0
131          0505PPR         7358.0             7200      29436        4.0
132          0506VMS         7536.0             7140      30144        4.0
133          0507BDS         7990.0             7740      31962        4.0
134          0508SRR         6757.0             6540      27030        4.0
135          0509LGS        17808.0             7620      71232        4.0
136          0510DFS         6727.0             6540      26910        4.0
137          0511LCS         8461.0             8100      33846        4.0
138          0512RCR         6962.0             6600      27852        4.0
139          0513EBS         5815.0             5820      23262        4.0
140          0515FAR         8234.0             6720      32940        4.0
141          0626MCS         6988.0             6540      27954        4.0
142          0628DMR         8065.0             8040      32262        4.0
143          0629TCR         8124.0             8040      32496        4.0
144          0630RJR         5530.0             5580      22122        4.0
145          0631LHR         6246.0             5820      24984        4.0
146          0801HDR         7273.0             7200      29094        4.0
147          0802LAS         6505.0             6540      26022        4.0
148          0804GOR         6454.0             6720      25818        4.0
149          0805BMS         5528.0             5520      22116        4.0
150          0807OMR         6097.0             6120      24390        4.0
151          0808PJR         6876.0             6720      27504        4.0
152          0902SIS         4969.0             4860      19878        4.0
153          0904KJS         6115.0             6060      24462        4.0
154          0905SLR         6708.0             6600      26832        4.0
155          0906DNR         9764.0            10020      39060        4.0

In [31]:
global_ids = set(df_global["Numero_inclusion"])
excel_ids = set(df_excel_global["Numero_inclusion"])

manquants_dans_global = excel_ids - global_ids
manquants_dans_excel = global_ids - excel_ids

print("Présents dans Excel mais pas dans RR :", manquants_dans_global)
print("Présents dans RR mais pas dans Excel :", manquants_dans_excel)

Présents dans Excel mais pas dans RR : set()
Présents dans RR mais pas dans Excel : set()

# Verif temps unix

In [ ]:
# Exemple de timestamp Unix
timestamp_unix = 1530858300.000000

# Conversion en datetime
dt = datetime.datetime.fromtimestamp(timestamp_unix)

print(dt)

# D'ou vient l'écart ? L'offest doit etre appliqué en debut, en fin, au milieu?

In [32]:
def sec_to_datetime(sec, date_ref):
    return datetime.combine(
        date_ref.date(),
        datetime.min.time()
    ) + timedelta(seconds=int(sec))


resultats_offset_eda = []

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin_eda = row["Chemin"]

    # ===== Lecture EDA =====
    try:
        if ".ZIP|" in chemin_eda.upper():
            zip_path, inner_csv = chemin_eda.split("|", 1)
            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_raw = pd.read_csv(f, header=None)
        else:
            df_raw = pd.read_csv(chemin_eda, header=None)

    except Exception as e:
        print(f"⚠️ Lecture EDA impossible pour {pid} : {e}")
        continue

    if len(df_raw) < 3:
        continue

    # ===== Reconstruction Timestamp =====
    try:
        t0_unix = float(df_raw.iloc[0, 0])
        freq = float(df_raw.iloc[1, 0])
    except:
        continue

    if freq <= 0:
        continue

    df_eda = df_raw.iloc[2:].copy()
    df_eda.columns = ["EDA"]
    df_eda["EDA"] = pd.to_numeric(df_eda["EDA"], errors="coerce")
    df_eda = df_eda.dropna()

    if df_eda.empty:
        continue

    pas = 1 / 4
    n = len(df_eda)

    t_debut = datetime.fromtimestamp(t0_unix)
    df_eda["Timestamp"] = [
        t_debut + timedelta(seconds=i * pas)
        for i in range(n)
    ]

    t_min = df_eda["Timestamp"].min()
    t_max = df_eda["Timestamp"].max()

    ligne_excel = df_excel_global.loc[
        df_excel_global["Numero_inclusion"] == pid
    ]

    if ligne_excel.empty:
        continue

    h_debut_sec = ligne_excel["heure_debut_sec"].values[0]
    h_fin_sec   = ligne_excel["heure_fin_sec"].values[0]
    duree_excel_sec = ligne_excel["duree_experience_sec"].values[0]

    if pd.isna(h_debut_sec) or pd.isna(h_fin_sec) or pd.isna(duree_excel_sec):
        continue

    h_debut = sec_to_datetime(h_debut_sec, t_min)
    h_fin   = sec_to_datetime(h_fin_sec, t_min)

    # =====================================================
    # Calcul du retard si EDA commence après Excel
    # =====================================================
    if t_min > h_debut:
        delta_retard_sec = (t_min - h_debut).total_seconds()
    else:
        delta_retard_sec = 0

    # ===== Comptages =====
    nb_avant = (df_eda["Timestamp"] < h_debut).sum()
    nb_dans = (
        (df_eda["Timestamp"] >= h_debut) &
        (df_eda["Timestamp"] <= h_fin)
    ).sum()
    nb_apres = (df_eda["Timestamp"] > h_fin).sum()

    total = len(df_eda)

    if nb_apres > nb_avant:
        origine = "FIN"
    elif nb_avant > nb_apres:
        origine = "DEBUT"
    else:
        origine = "MIXTE"

    resultats_offset_eda.append({
        "Numero_inclusion": pid,
        "nb_total_points": total,
        "nb_avant_excel": nb_avant,
        "nb_dans_excel": nb_dans,
        "nb_apres_excel": nb_apres,
        "origine_offset": origine,
        "delta_retard_sec": delta_retard_sec
    })

df_offset_eda = pd.DataFrame(resultats_offset_eda)

print(f"Offsets EDA calculés : {len(df_offset_eda)}")
display(df_offset_eda)

Offsets EDA calculés : 156

,Numero_inclusion,nb_total_points,nb_avant_excel,nb_dans_excel,nb_apres_excel,origine_offset,delta_retard_sec
0,0101CAR,38118,0,37681,437,FIN,0.0
1,0101EMS,25194,0,24801,393,FIN,40.0
2,0102PCR,30810,0,30229,581,FIN,3.0
3,0103BPS,20796,0,20505,291,FIN,34.0
4,0103SHS,22512,0,21885,627,FIN,49.0
5,0104FJS,39456,0,38033,1423,FIN,92.0
6,0104IBS,22662,0,22365,297,FIN,49.0
7,0105PNR,29904,0,28909,995,FIN,33.0
8,0106DJR,26634,0,26093,541,FIN,77.0
9,0106JLS,30552,0,29733,819,FIN,7.0
10,0107DSS,29148,0,28873,275,FIN,102.0
11,0108BFS,32208,0,31493,715,FIN,47.0
12,0109GSS,31254,0,29841,1413,FIN,40.0
13,0109MJR,25302,0,25302,0,MIXTE,6.0
14,0110LPR,33012,0,31469,1543,FIN,293.0
15,0110RMS,22794,0,22561,233,FIN,0.0
16,0111MNR,31734,0,30225,1509,FIN,304.0
17,0112BSR,37488,0,35917,1571,FIN,261.0
18,0113BMR,30966,0,30269,697,FIN,53.0
19,0113DGR,25068,40,24961,67,FIN,0.0
20,0114LMS,25860,0,25349,511,FIN,23.0
21,0114MLR,27330,0,27089,241,FIN,8.0
22,0115CJR,25284,0,24245,1039,FIN,59.0
23,0115MHR,26238,0,26069,169,FIN,23.0
24,0116CNR,28050,0,28037,13,FIN,11.0
25,0116VAR,35022,0,33821,1201,FIN,245.0
26,0117MSR,27258,0,27077,181,FIN,11.0
27,0117POS,27162,0,25493,1669,FIN,287.0
28,0118TMS,27942,0,27753,189,FIN,22.0
29,0118TNS,27462,0,27041,421,FIN,20.0
30,0119BIR,24264,0,24181,83,FIN,15.0
31,0119LJS,27078,0,26005,1073,FIN,39.0
32,0120ANS,22512,0,22241,271,FIN,20.0
33,0120LCR,30912,0,29765,1147,FIN,59.0
34,0121MJR,29250,0,27629,1621,FIN,173.0
35,0121RPS,21660,0,21601,59,FIN,0.0
36,0122VCR,32592,44,31681,867,FIN,0.0
37,0123GVS,19836,0,19733,103,FIN,47.0
38,0123RMS,28596,0,27629,967,FIN,53.0
39,0124BAR,29472,0,29457,15,FIN,16.0
40,0124PAS,20646,0,20561,85,FIN,20.0
41,0125BMR,31962,0,31289,673,FIN,38.0
42,0126VLR,22860,0,22817,43,FIN,116.0
43,0127CMS,21420,0,21273,147,FIN,22.0
44,0128ALS,23034,0,22745,289,FIN,14.0
45,0129APR,34578,36,34321,221,FIN,0.0
46,0130FAR,31044,8,30241,795,FIN,0.0
47,0131CPS,21288,0,21237,51,FIN,31.0
48,0132GAR,22878,0,22285,593,FIN,9.0
49,0133BPS,23100,0,22845,255,FIN,49.0
50,0134IFR,22278,0,21905,373,FIN,44.0
51,0135KLS,22212,0,22212,0,MIXTE,120.0
52,0136CJR,23694,0,23245,449,FIN,69.0
53,0137BMS,24324,0,24221,103,FIN,5.0
54,0138NWR,27186,316,26870,0,DEBUT,0.0
55,0140LMR,29052,0,28861,191,FIN,45.0
56,0143EBR,28902,0,28217,685,FIN,86.0
57,0144ZGR,36324,0,35945,379,FIN,134.0
58,0301GNR,35682,0,29293,6389,FIN,237.0
59,0302ZMR,28290,0,25925,2365,FIN,59.0
60,0303PAR,24186,0,23313,873,FIN,52.0
61,0304VMR,35358,3084,30961,1313,DEBUT,0.0
62,0305LCR,27870,0,25545,2325,FIN,154.0
63,0306MDR,26238,0,24881,1357,FIN,140.0
64,0307SMR,30936,0,29197,1739,FIN,141.0
65,0308RGR,29298,0,27809,1489,FIN,188.0
66,0309DBS,32112,0,30193,1919,FIN,192.0
67,0310ACS,30324,0,29393,931,FIN,212.0
68,0311CJS,29646,0,28097,1549,FIN,176.0
69,0312JMS,26748,0,24973,1775,FIN,237.0
70,0313FPR,26724,0,25745,979,FIN,224.0
71,0315VCS,26736,0,24621,2115,FIN,85.0
72,0316TMS,23922,0,21737,2185,FIN,146.0
73,0317LGS,26142,0,22273,3869,FIN,72.0
74,0318PMS,23034,0,21085,1949,FIN,69.0
75,0320DGS,21954,0,20849,1105,FIN,128.0
76,0321DRR,24804,0,23497,1307,FIN,66.0
77,0322RMS,19854,0,19357,497,FIN,81.0
78,0323RFS,30834,0,23933,6901,FIN,77.0
79,0324LMR,26394,0,24529,1865,FIN,108.0
80,0325LCR,27102,0,23937,3165,FIN,76.0
81,0326BJR,26136,0,25129,1007,FIN,138.0
82,0327IAR,27084,0,24625,2459,FIN,144.0
83,0328MPR,28602,0,25953,2649,FIN,112.0
84,0329NMR,30504,0,27465,3039,FIN,154.0
85,0330RTR,27786,0,25021,2765,FIN,585.0
86,0331GRS,22386,0,20949,1437,FIN,43.0
87,0332MCR,34314,0,28829,5485,FIN,53.0
88,0333MMS,26610,0,22229,4381,FIN,83.0
89,0334TVS,23094,0,21205,1889,FIN,159.0
90,0336CBS,31608,0,28161,3447,FIN,160.0
91,0337BFS,38598,0,35237,3361,FIN,191.0
92,0339NPR,26784,0,23625,3159,FIN,274.0
93,0341LJS,26388,0,22777,3611,FIN,126.0
94,0342VNS,28614,0,26625,1989,FIN,124.0
95,0343PAS,23664,0,19833,3831,FIN,142.0
96,0345LAR,23982,0,22313,1669,FIN,62.0
97,0346GLS,31788,0,21465,10323,FIN,94.0
98,0347DMR,28068,0,25973,2095,FIN,47.0
99,0348GCR,29586,0,28441,1145,FIN,90.0
100,0349LLS,28476,0,26325,2151,FIN,139.0
101,0350MYR,27888,0,25321,2567,FIN,90.0
102,0351FIR,32352,0,26217,6135,FIN,46.0
103,0352RNR,25836,0,23789,2047,FIN,53.0
104,0354GKR,31992,0,25933,6059,FIN,117.0
105,0355BAS,27612,0,24605,3007,FIN,89.0
106,0356DMS,14574,0,14574,0,MIXTE,60.0
107,0401TSS,36318,124,34321,1873,FIN,0.0
108,0402LLS,33840,152,29521,4167,FIN,0.0
109,0403DCR,34428,348,30001,4079,FIN,0.0
110,0404CYS,46788,0,36589,10199,FIN,93.0
111,0405FCR,40662,116,35041,5505,FIN,0.0
112,0406MCS,35970,0,28653,7317,FIN,97.0
113,0407LJR,1722,1722,0,0,DEBUT,0.0
114,0408BCS,39828,224,32401,7203,FIN,0.0
115,0410PGS,39150,260,33841,5049,FIN,0.0
116,0411VES,34932,0,29257,5675,FIN,306.0
117,0412ANS,30438,0,28249,2189,FIN,18.0
118,0413HFS,33732,376,31441,1915,FIN,0.0
119,0413MMR,28236,48,27361,827,FIN,0.0
120,0414PVR,27066,0,27057,9,FIN,76.0
121,0415HJS,23652,0,23585,67,FIN,44.0
122,0415VMR,28326,0,25617,2709,FIN,76.0
123,0417FAS,25026,0,24765,261,FIN,109.0
124,0418MPR,29556,0,29093,463,FIN,47.0
125,0420MCR,29172,0,29029,143,FIN,183.0
126,0421ACS,22800,224,22321,255,FIN,0.0
127,0501MBS,27612,0,24905,2707,FIN,74.0
128,0502LIR,29646,0,28881,765,FIN,40.0
129,0503LCR,28080,0,28080,0,MIXTE,51.0
130,0504BCS,31620,16,27601,4003,FIN,0.0
131,0505PPR,29436,0,28537,899,FIN,66.0
132,0506VMS,30144,0,28497,1647,FIN,16.0
133,0507BDS,31962,0,30653,1309,FIN,77.0
134,0508SRR,27030,296,26161,573,FIN,0.0
135,0509LGS,71232,316,30481,40435,FIN,0.0
136,0510DFS,26910,56,26161,693,FIN,0.0
137,0511LCS,33846,0,32241,1605,FIN,40.0
138,0512RCR,27852,0,26233,1619,FIN,42.0
139,0513EBS,23262,0,22825,437,FIN,114.0
140,0515FAR,32940,436,26881,5623,FIN,0.0
141,0626MCS,27954,0,25957,1997,FIN,51.0
142,0628DMR,32262,0,32113,149,FIN,12.0
143,0629TCR,32496,0,31973,523,FIN,47.0
144,0630RJR,22122,0,21969,153,FIN,88.0
145,0631LHR,24984,0,23121,1863,FIN,40.0
146,0801HDR,29094,0,27369,1725,FIN,358.0
147,0802LAS,26022,0,25757,265,FIN,101.0
148,0804GOR,25818,0,25401,417,FIN,370.0
149,0805BMS,22116,0,21973,143,FIN,27.0
150,0807OMR,24390,0,24081,309,FIN,100.0
151,0808PJR,27504,96,26881,527,FIN,0.0
152,0902SIS,19878,0,19405,473,FIN,9.0
153,0904KJS,24462,0,24077,385,FIN,41.0
154,0905SLR,26832,0,26349,483,FIN,13.0
155,0906DNR,39060,0,38849,211,FIN,308.0

In [34]:
# ===== Dossier de sortie =====
desktop = Path.home() / "Desktop"
output_dir = desktop / "EDA_v2_tronqués"
output_dir.mkdir(exist_ok=True)

print(f"📁 Dossier de sortie : {output_dir}")

# ===== Boucle sur les fichiers tronqués =====
for _, row in df_offset_eda.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()

    # récupérer chemin EDA depuis df_global
    ligne_global = df_global[df_global["Numero_inclusion"] == pid]
    if ligne_global.empty:
        continue

    chemin_eda = ligne_global.iloc[0]["Chemin"]

    nb_avant = int(row["nb_avant_excel"])
    nb_apres = int(row["nb_apres_excel"])

    # ===== Lecture EDA (ZIP ou non) =====
    try:
        if ".ZIP|" in chemin_eda.upper():
            zip_path, inner_csv = chemin_eda.split("|", 1)

            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_eda = pd.read_csv(f)
        else:
            df_eda = pd.read_csv(chemin_eda)

    except Exception as e:
        print(f"❌ Lecture impossible {pid}: {e}")
        continue

    total = len(df_eda)

    # ===== Indices de coupe =====
    # On conserve les 2 premières lignes (temps UNIX et fréquence), troncage à partir de la 3ème
    start = 2 + nb_avant
    end = total - nb_apres

    if start >= end:
        print(f"⚠️ Troncature invalide pour {pid} (start={start}, end={end})")
        continue

    # On concatène les 2 premières lignes intactes + le reste tronqué
    df_eda_trunc = pd.concat([df_eda.iloc[:2], df_eda.iloc[start:end]]).reset_index(drop=True)

    if df_eda_trunc.empty:
        print(f"⚠️ {pid} → fichier vide après troncature")
        continue

    # ===== Nom fichier de sortie =====
    if ".ZIP|" in chemin_eda.upper():
        nom_base = Path(inner_csv).name
    else:
        nom_base = Path(chemin_eda).name

    nom_fichier = f"offset_{pid}_{nom_base}"
    path_sortie = output_dir / nom_fichier

    # ===== Sauvegarde =====
    df_eda_trunc.to_csv(path_sortie, index=False)

    print(
        f"✅ {pid} | "
        f"avant={nb_avant}, après={nb_apres} | "
        f"{len(df_eda_trunc)} lignes → {path_sortie.name}"
    )

print("🎯 Troncature terminée")

📁 Dossier de sortie : C:\Users\judupont\Desktop\EDA_v2_tronqués
✅ 0101CAR | avant=0, après=437 | 37682 lignes → offset_0101CAR_EDA.csv
✅ 0101EMS | avant=0, après=393 | 24802 lignes → offset_0101EMS_EDA.csv
✅ 0102PCR | avant=0, après=581 | 30230 lignes → offset_0102PCR_EDA.csv
✅ 0103BPS | avant=0, après=291 | 20506 lignes → offset_0103BPS_EDA.csv
✅ 0103SHS | avant=0, après=627 | 21886 lignes → offset_0103SHS_EDA.csv
✅ 0104FJS | avant=0, après=1423 | 38034 lignes → offset_0104FJS_EDA.csv
✅ 0104IBS | avant=0, après=297 | 22366 lignes → offset_0104IBS_EDA.csv
✅ 0105PNR | avant=0, après=995 | 28910 lignes → offset_0105PNR_EDA.csv
✅ 0106DJR | avant=0, après=541 | 26094 lignes → offset_0106DJR_EDA.csv
✅ 0106JLS | avant=0, après=819 | 29734 lignes → offset_0106JLS_EDA.csv
✅ 0107DSS | avant=0, après=275 | 28874 lignes → offset_0107DSS_EDA.csv
✅ 0108BFS | avant=0, après=715 | 31494 lignes → offset_0108BFS_EDA.csv
✅ 0109GSS | avant=0, après=1413 | 29842 lignes → offset_0109GSS_EDA.csv
✅ 0109MJR | avant=0, après=0 | 25303 lignes → offset_0109MJR_EDA.csv
✅ 0110LPR | avant=0, après=1543 | 31470 lignes → offset_0110LPR_EDA.csv
✅ 0110RMS | avant=0, après=233 | 22562 lignes → offset_0110RMS_EDA.csv
✅ 0111MNR | avant=0, après=1509 | 30226 lignes → offset_0111MNR_EDA.csv
✅ 0112BSR | avant=0, après=1571 | 35918 lignes → offset_0112BSR_EDA.csv
✅ 0113BMR | avant=0, après=697 | 30270 lignes → offset_0113BMR_EDA.csv
✅ 0113DGR | avant=40, après=67 | 24962 lignes → offset_0113DGR_EDA.csv
✅ 0114LMS | avant=0, après=511 | 25350 lignes → offset_0114LMS_EDA.csv
✅ 0114MLR | avant=0, après=241 | 27090 lignes → offset_0114MLR_EDA.csv
✅ 0115CJR | avant=0, après=1039 | 24246 lignes → offset_0115CJR_EDA.csv
✅ 0115MHR | avant=0, après=169 | 26070 lignes → offset_0115MHR_EDA.csv
✅ 0116CNR | avant=0, après=13 | 28038 lignes → offset_0116CNR_EDA.csv
✅ 0116VAR | avant=0, après=1201 | 33822 lignes → offset_0116VAR_EDA.csv
✅ 0117MSR | avant=0, après=181 | 27078 lignes → offset_0117MSR_EDA.csv
✅ 0117POS | avant=0, après=1669 | 25494 lignes → offset_0117POS_EDA.csv
✅ 0118TMS | avant=0, après=189 | 27754 lignes → offset_0118TMS_EDA.csv
✅ 0118TNS | avant=0, après=421 | 27042 lignes → offset_0118TNS_EDA.csv
✅ 0119BIR | avant=0, après=83 | 24182 lignes → offset_0119BIR_EDA.csv
✅ 0119LJS | avant=0, après=1073 | 26006 lignes → offset_0119LJS_EDA.csv
✅ 0120ANS | avant=0, après=271 | 22242 lignes → offset_0120ANS_EDA.csv
✅ 0120LCR | avant=0, après=1147 | 29766 lignes → offset_0120LCR_EDA.csv
✅ 0121MJR | avant=0, après=1621 | 27630 lignes → offset_0121MJR_EDA.csv
✅ 0121RPS | avant=0, après=59 | 21602 lignes → offset_0121RPS_EDA.csv
✅ 0122VCR | avant=44, après=867 | 31682 lignes → offset_0122VCR_EDA.csv
✅ 0123GVS | avant=0, après=103 | 19734 lignes → offset_0123GVS_EDA.csv
✅ 0123RMS | avant=0, après=967 | 27630 lignes → offset_0123RMS_EDA.csv
✅ 0124BAR | avant=0, après=15 | 29458 lignes → offset_0124BAR_EDA.csv
✅ 0124PAS | avant=0, après=85 | 20562 lignes → offset_0124PAS_EDA.csv
✅ 0125BMR | avant=0, après=673 | 31290 lignes → offset_0125BMR_EDA.csv
✅ 0126VLR | avant=0, après=43 | 22818 lignes → offset_0126VLR_EDA.csv
✅ 0127CMS | avant=0, après=147 | 21274 lignes → offset_0127CMS_EDA.csv
✅ 0128ALS | avant=0, après=289 | 22746 lignes → offset_0128ALS_EDA.csv
✅ 0129APR | avant=36, après=221 | 34322 lignes → offset_0129APR_EDA.csv
✅ 0130FAR | avant=8, après=795 | 30242 lignes → offset_0130FAR_EDA.csv
✅ 0131CPS | avant=0, après=51 | 21238 lignes → offset_0131CPS_EDA.csv
✅ 0132GAR | avant=0, après=593 | 22286 lignes → offset_0132GAR_EDA.csv
✅ 0133BPS | avant=0, après=255 | 22846 lignes → offset_0133BPS_EDA.csv
✅ 0134IFR | avant=0, après=373 | 21906 lignes → offset_0134IFR_EDA.csv
✅ 0135KLS | avant=0, après=0 | 22213 lignes → offset_0135KLS_EDA.csv
✅ 0136CJR | avant=0, après=449 | 23246 lignes → offset_0136CJR_EDA.csv
✅ 0137BMS | avant=0, après=103 | 24222 lignes → offset_0137BMS_EDA.csv
✅ 0138NWR | avant=316, après=0 | 26871 lignes → offset_0138NWR_EDA.csv
✅ 0140LMR | avant=0, après=191 | 28862 lignes → offset_0140LMR_EDA.csv
✅ 0143EBR | avant=0, après=685 | 28218 lignes → offset_0143EBR_EDA.csv
✅ 0144ZGR | avant=0, après=379 | 35946 lignes → offset_0144ZGR_EDA.csv
✅ 0301GNR | avant=0, après=6389 | 29294 lignes → offset_0301GNR_EDA.csv
✅ 0302ZMR | avant=0, après=2365 | 25926 lignes → offset_0302ZMR_EDA.csv
✅ 0303PAR | avant=0, après=873 | 23314 lignes → offset_0303PAR_EDA.csv
✅ 0304VMR | avant=3084, après=1313 | 30962 lignes → offset_0304VMR_EDA.csv
✅ 0305LCR | avant=0, après=2325 | 25546 lignes → offset_0305LCR_EDA.csv
✅ 0306MDR | avant=0, après=1357 | 24882 lignes → offset_0306MDR_EDA.csv
✅ 0307SMR | avant=0, après=1739 | 29198 lignes → offset_0307SMR_EDA.csv
✅ 0308RGR | avant=0, après=1489 | 27810 lignes → offset_0308RGR_EDA.csv
✅ 0309DBS | avant=0, après=1919 | 30194 lignes → offset_0309DBS_EDA.csv
✅ 0310ACS | avant=0, après=931 | 29394 lignes → offset_0310ACS_EDA.csv
✅ 0311CJS | avant=0, après=1549 | 28098 lignes → offset_0311CJS_EDA.csv
✅ 0312JMS | avant=0, après=1775 | 24974 lignes → offset_0312JMS_EDA.csv
✅ 0313FPR | avant=0, après=979 | 25746 lignes → offset_0313FPR_EDA.csv
✅ 0315VCS | avant=0, après=2115 | 24622 lignes → offset_0315VCS_EDA.csv
✅ 0316TMS | avant=0, après=2185 | 21738 lignes → offset_0316TMS_EDA.csv
✅ 0317LGS | avant=0, après=3869 | 22274 lignes → offset_0317LGS_EDA.csv
✅ 0318PMS | avant=0, après=1949 | 21086 lignes → offset_0318PMS_EDA.csv
✅ 0320DGS | avant=0, après=1105 | 20850 lignes → offset_0320DGS_EDA.csv
✅ 0321DRR | avant=0, après=1307 | 23498 lignes → offset_0321DRR_EDA.csv
✅ 0322RMS | avant=0, après=497 | 19358 lignes → offset_0322RMS_EDA.csv
✅ 0323RFS | avant=0, après=6901 | 23934 lignes → offset_0323RFS_EDA.csv
✅ 0324LMR | avant=0, après=1865 | 24530 lignes → offset_0324LMR_EDA.csv
✅ 0325LCR | avant=0, après=3165 | 23938 lignes → offset_0325LCR_EDA.csv
✅ 0326BJR | avant=0, après=1007 | 25130 lignes → offset_0326BJR_EDA.csv
✅ 0327IAR | avant=0, après=2459 | 24626 lignes → offset_0327IAR_EDA.csv
✅ 0328MPR | avant=0, après=2649 | 25954 lignes → offset_0328MPR_EDA.csv
✅ 0329NMR | avant=0, après=3039 | 27466 lignes → offset_0329NMR_EDA.csv
✅ 0330RTR | avant=0, après=2765 | 25022 lignes → offset_0330RTR_EDA.csv
✅ 0331GRS | avant=0, après=1437 | 20950 lignes → offset_0331GRS_EDA.csv
✅ 0332MCR | avant=0, après=5485 | 28830 lignes → offset_0332MCR_EDA.csv
✅ 0333MMS | avant=0, après=4381 | 22230 lignes → offset_0333MMS_EDA.csv
✅ 0334TVS | avant=0, après=1889 | 21206 lignes → offset_0334TVS_EDA.csv
✅ 0336CBS | avant=0, après=3447 | 28162 lignes → offset_0336CBS_EDA.csv
✅ 0337BFS | avant=0, après=3361 | 35238 lignes → offset_0337BFS_EDA.csv
✅ 0339NPR | avant=0, après=3159 | 23626 lignes → offset_0339NPR_EDA.csv
✅ 0341LJS | avant=0, après=3611 | 22778 lignes → offset_0341LJS_EDA.csv
✅ 0342VNS | avant=0, après=1989 | 26626 lignes → offset_0342VNS_EDA.csv
✅ 0343PAS | avant=0, après=3831 | 19834 lignes → offset_0343PAS_EDA.csv
✅ 0345LAR | avant=0, après=1669 | 22314 lignes → offset_0345LAR_EDA.csv
✅ 0346GLS | avant=0, après=10323 | 21466 lignes → offset_0346GLS_EDA.csv
✅ 0347DMR | avant=0, après=2095 | 25974 lignes → offset_0347DMR_EDA.csv
✅ 0348GCR | avant=0, après=1145 | 28442 lignes → offset_0348GCR_EDA.csv
✅ 0349LLS | avant=0, après=2151 | 26326 lignes → offset_0349LLS_EDA.csv
✅ 0350MYR | avant=0, après=2567 | 25322 lignes → offset_0350MYR_EDA.csv
✅ 0351FIR | avant=0, après=6135 | 26218 lignes → offset_0351FIR_EDA.csv
✅ 0352RNR | avant=0, après=2047 | 23790 lignes → offset_0352RNR_EDA.csv
✅ 0354GKR | avant=0, après=6059 | 25934 lignes → offset_0354GKR_EDA.csv
✅ 0355BAS | avant=0, après=3007 | 24606 lignes → offset_0355BAS_EDA.csv
✅ 0356DMS | avant=0, après=0 | 14575 lignes → offset_0356DMS_EDA.csv
✅ 0401TSS | avant=124, après=1873 | 34322 lignes → offset_0401TSS_EDA.csv
✅ 0402LLS | avant=152, après=4167 | 29522 lignes → offset_0402LLS_EDA.csv
✅ 0403DCR | avant=348, après=4079 | 30002 lignes → offset_0403DCR_EDA.csv
✅ 0404CYS | avant=0, après=10199 | 36590 lignes → offset_0404CYS_EDA.csv
✅ 0405FCR | avant=116, après=5505 | 35042 lignes → offset_0405FCR_EDA.csv
✅ 0406MCS | avant=0, après=7317 | 28654 lignes → offset_0406MCS_EDA.csv
⚠️ Troncature invalide pour 0407LJR (start=1724, end=1723)
✅ 0408BCS | avant=224, après=7203 | 32402 lignes → offset_0408BCS_EDA.csv
✅ 0410PGS | avant=260, après=5049 | 33842 lignes → offset_0410PGS_EDA.csv
✅ 0411VES | avant=0, après=5675 | 29258 lignes → offset_0411VES_EDA.csv
✅ 0412ANS | avant=0, après=2189 | 28250 lignes → offset_0412ANS_EDA.csv
✅ 0413HFS | avant=376, après=1915 | 31442 lignes → offset_0413HFS_EDA.csv
✅ 0413MMR | avant=48, après=827 | 27362 lignes → offset_0413MMR_EDA.csv
✅ 0414PVR | avant=0, après=9 | 27058 lignes → offset_0414PVR_EDA.csv
✅ 0415HJS | avant=0, après=67 | 23586 lignes → offset_0415HJS_EDA.csv
✅ 0415VMR | avant=0, après=2709 | 25618 lignes → offset_0415VMR_EDA.csv
✅ 0417FAS | avant=0, après=261 | 24766 lignes → offset_0417FAS_EDA.csv
✅ 0418MPR | avant=0, après=463 | 29094 lignes → offset_0418MPR_EDA.csv
✅ 0420MCR | avant=0, après=143 | 29030 lignes → offset_0420MCR_EDA.csv
✅ 0421ACS | avant=224, après=255 | 22322 lignes → offset_0421ACS_EDA.csv
✅ 0501MBS | avant=0, après=2707 | 24906 lignes → offset_0501MBS_EDA.csv
✅ 0502LIR | avant=0, après=765 | 28882 lignes → offset_0502LIR_EDA.csv
✅ 0503LCR | avant=0, après=0 | 28081 lignes → offset_0503LCR_EDA.csv
✅ 0504BCS | avant=16, après=4003 | 27602 lignes → offset_0504BCS_EDA.csv
✅ 0505PPR | avant=0, après=899 | 28538 lignes → offset_0505PPR_EDA.csv
✅ 0506VMS | avant=0, après=1647 | 28498 lignes → offset_0506VMS_EDA.csv
✅ 0507BDS | avant=0, après=1309 | 30654 lignes → offset_0507BDS_EDA - Copie.csv
✅ 0508SRR | avant=296, après=573 | 26162 lignes → offset_0508SRR_EDA.csv
✅ 0509LGS | avant=316, après=40435 | 30482 lignes → offset_0509LGS_EDA.csv
✅ 0510DFS | avant=56, après=693 | 26162 lignes → offset_0510DFS_EDA.csv
✅ 0511LCS | avant=0, après=1605 | 32242 lignes → offset_0511LCS_EDA[1].csv
✅ 0512RCR | avant=0, après=1619 | 26234 lignes → offset_0512RCR_EDA.csv
✅ 0513EBS | avant=0, après=437 | 22826 lignes → offset_0513EBS_EDA.csv
✅ 0515FAR | avant=436, après=5623 | 26882 lignes → offset_0515FAR_EDA.csv
✅ 0626MCS | avant=0, après=1997 | 25958 lignes → offset_0626MCS_EDA.csv
✅ 0628DMR | avant=0, après=149 | 32114 lignes → offset_0628DMR_EDA.csv
✅ 0629TCR | avant=0, après=523 | 31974 lignes → offset_0629TCR_EDA.csv
✅ 0630RJR | avant=0, après=153 | 21970 lignes → offset_0630RJR_EDA.csv
✅ 0631LHR | avant=0, après=1863 | 23122 lignes → offset_0631LHR_EDA.csv
✅ 0801HDR | avant=0, après=1725 | 27370 lignes → offset_0801HDR_EDA.csv
✅ 0802LAS | avant=0, après=265 | 25758 lignes → offset_0802LAS_EDA.csv
✅ 0804GOR | avant=0, après=417 | 25402 lignes → offset_0804GOR_EDA.csv
✅ 0805BMS | avant=0, après=143 | 21974 lignes → offset_0805BMS_EDA.csv
✅ 0807OMR | avant=0, après=309 | 24082 lignes → offset_0807OMR_EDA.csv
✅ 0808PJR | avant=96, après=527 | 26882 lignes → offset_0808PJR_EDA.csv
✅ 0902SIS | avant=0, après=473 | 19406 lignes → offset_0902SIS_EDA.csv
✅ 0904KJS | avant=0, après=385 | 24078 lignes → offset_0904KJS_EDA.csv
✅ 0905SLR | avant=0, après=483 | 26350 lignes → offset_0905SLR_EDA.csv
✅ 0906DNR | avant=0, après=211 | 38850 lignes → offset_0906DNR_EDA.csv
🎯 Troncature terminée

In [35]:
# ===== Paramètres =====
min_lignes = 10000
candidats_a_exclure = {"0356DMS","0130FAR"} # le fichier du 0130FAR est celui de la v4

dossier = Path.home() / "Desktop" / "EDA_v2_tronqués"

print(f"📂 Dossier analysé : {dossier}")

supprimes = []
conserves = []

for fichier in dossier.glob("*.csv"):

    nom = fichier.name

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", nom.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {nom}")
        continue

    pid = match.group()

    # ===== Exclusion candidat spécifique =====
    if pid in candidats_a_exclure:
        fichier.unlink()
        supprimes.append((nom, "candidat exclu"))
        print(f"🗑️ {nom} → candidat exclu ({pid})")
        continue

    # ===== Comptage rapide des lignes =====
    try:
        with open(fichier, "r", encoding="utf-8") as f:
            n_lignes = sum(1 for _ in f)
    except Exception as e:
        print(f"❌ Lecture impossible {nom}: {e}")
        continue

    # ===== Exclusion fichiers trop courts =====
    if n_lignes < min_lignes:
        fichier.unlink()
        supprimes.append((nom, f"{n_lignes} lignes"))
        print(f"❌ {nom} → trop petit ({n_lignes} lignes)")
    else:
        conserves.append((nom, n_lignes))
        print(f"✅ {nom} → conservé ({n_lignes} lignes)")

# ===== Résumé =====
print("\n====== RÉSUMÉ ======")
print(f"Fichiers supprimés : {len(supprimes)}")
print(f"Fichiers conservés : {len(conserves)}")

if supprimes:
    print("\nDétail suppressions :")
    for s in supprimes:
        print(" -", s)

📂 Dossier analysé : C:\Users\judupont\Desktop\EDA_v2_tronqués
✅ offset_0101CAR_EDA.csv → conservé (37683 lignes)
✅ offset_0101EMS_EDA.csv → conservé (24803 lignes)
✅ offset_0102PCR_EDA.csv → conservé (30231 lignes)
✅ offset_0103BPS_EDA.csv → conservé (20507 lignes)
✅ offset_0103SHS_EDA.csv → conservé (21887 lignes)
✅ offset_0104FJS_EDA.csv → conservé (38035 lignes)
✅ offset_0104IBS_EDA.csv → conservé (22367 lignes)
✅ offset_0105PNR_EDA.csv → conservé (28911 lignes)
✅ offset_0106DJR_EDA.csv → conservé (26095 lignes)
✅ offset_0106JLS_EDA.csv → conservé (29735 lignes)
✅ offset_0107DSS_EDA.csv → conservé (28875 lignes)
✅ offset_0108BFS_EDA.csv → conservé (31495 lignes)
✅ offset_0109GSS_EDA.csv → conservé (29843 lignes)
✅ offset_0109MJR_EDA.csv → conservé (25304 lignes)
✅ offset_0110LPR_EDA.csv → conservé (31471 lignes)
✅ offset_0110RMS_EDA.csv → conservé (22563 lignes)
✅ offset_0111MNR_EDA.csv → conservé (30227 lignes)
✅ offset_0112BSR_EDA.csv → conservé (35919 lignes)
✅ offset_0113BMR_EDA.csv → conservé (30271 lignes)
✅ offset_0113DGR_EDA.csv → conservé (24963 lignes)
✅ offset_0114LMS_EDA.csv → conservé (25351 lignes)
✅ offset_0114MLR_EDA.csv → conservé (27091 lignes)
✅ offset_0115CJR_EDA.csv → conservé (24247 lignes)
✅ offset_0115MHR_EDA.csv → conservé (26071 lignes)
✅ offset_0116CNR_EDA.csv → conservé (28039 lignes)
✅ offset_0116VAR_EDA.csv → conservé (33823 lignes)
✅ offset_0117MSR_EDA.csv → conservé (27079 lignes)
✅ offset_0117POS_EDA.csv → conservé (25495 lignes)
✅ offset_0118TMS_EDA.csv → conservé (27755 lignes)
✅ offset_0118TNS_EDA.csv → conservé (27043 lignes)
✅ offset_0119BIR_EDA.csv → conservé (24183 lignes)
✅ offset_0119LJS_EDA.csv → conservé (26007 lignes)
✅ offset_0120ANS_EDA.csv → conservé (22243 lignes)
✅ offset_0120LCR_EDA.csv → conservé (29767 lignes)
✅ offset_0121MJR_EDA.csv → conservé (27631 lignes)
✅ offset_0121RPS_EDA.csv → conservé (21603 lignes)
✅ offset_0122VCR_EDA.csv → conservé (31683 lignes)
✅ offset_0123GVS_EDA.csv → conservé (19735 lignes)
✅ offset_0123RMS_EDA.csv → conservé (27631 lignes)
✅ offset_0124BAR_EDA.csv → conservé (29459 lignes)
✅ offset_0124PAS_EDA.csv → conservé (20563 lignes)
✅ offset_0125BMR_EDA.csv → conservé (31291 lignes)
✅ offset_0126VLR_EDA.csv → conservé (22819 lignes)
✅ offset_0127CMS_EDA.csv → conservé (21275 lignes)
✅ offset_0128ALS_EDA.csv → conservé (22747 lignes)
✅ offset_0129APR_EDA.csv → conservé (34323 lignes)
🗑️ offset_0130FAR_EDA.csv → candidat exclu (0130FAR)
✅ offset_0131CPS_EDA.csv → conservé (21239 lignes)
✅ offset_0132GAR_EDA.csv → conservé (22287 lignes)
✅ offset_0133BPS_EDA.csv → conservé (22847 lignes)
✅ offset_0134IFR_EDA.csv → conservé (21907 lignes)
✅ offset_0135KLS_EDA.csv → conservé (22214 lignes)
✅ offset_0136CJR_EDA.csv → conservé (23247 lignes)
✅ offset_0137BMS_EDA.csv → conservé (24223 lignes)
✅ offset_0138NWR_EDA.csv → conservé (26872 lignes)
✅ offset_0140LMR_EDA.csv → conservé (28863 lignes)
✅ offset_0143EBR_EDA.csv → conservé (28219 lignes)
✅ offset_0144ZGR_EDA.csv → conservé (35947 lignes)
✅ offset_0301GNR_EDA.csv → conservé (29295 lignes)
✅ offset_0302ZMR_EDA.csv → conservé (25927 lignes)
✅ offset_0303PAR_EDA.csv → conservé (23315 lignes)
✅ offset_0304VMR_EDA.csv → conservé (30963 lignes)
✅ offset_0305LCR_EDA.csv → conservé (25547 lignes)
✅ offset_0306MDR_EDA.csv → conservé (24883 lignes)
✅ offset_0307SMR_EDA.csv → conservé (29199 lignes)
✅ offset_0308RGR_EDA.csv → conservé (27811 lignes)
✅ offset_0309DBS_EDA.csv → conservé (30195 lignes)
✅ offset_0310ACS_EDA.csv → conservé (29395 lignes)
✅ offset_0311CJS_EDA.csv → conservé (28099 lignes)
✅ offset_0312JMS_EDA.csv → conservé (24975 lignes)
✅ offset_0313FPR_EDA.csv → conservé (25747 lignes)
✅ offset_0315VCS_EDA.csv → conservé (24623 lignes)
✅ offset_0316TMS_EDA.csv → conservé (21739 lignes)
✅ offset_0317LGS_EDA.csv → conservé (22275 lignes)
✅ offset_0318PMS_EDA.csv → conservé (21087 lignes)
✅ offset_0320DGS_EDA.csv → conservé (20851 lignes)
✅ offset_0321DRR_EDA.csv → conservé (23499 lignes)
✅ offset_0322RMS_EDA.csv → conservé (19359 lignes)
✅ offset_0323RFS_EDA.csv → conservé (23935 lignes)
✅ offset_0324LMR_EDA.csv → conservé (24531 lignes)
✅ offset_0325LCR_EDA.csv → conservé (23939 lignes)
✅ offset_0326BJR_EDA.csv → conservé (25131 lignes)
✅ offset_0327IAR_EDA.csv → conservé (24627 lignes)
✅ offset_0328MPR_EDA.csv → conservé (25955 lignes)
✅ offset_0329NMR_EDA.csv → conservé (27467 lignes)
✅ offset_0330RTR_EDA.csv → conservé (25023 lignes)
✅ offset_0331GRS_EDA.csv → conservé (20951 lignes)
✅ offset_0332MCR_EDA.csv → conservé (28831 lignes)
✅ offset_0333MMS_EDA.csv → conservé (22231 lignes)
✅ offset_0334TVS_EDA.csv → conservé (21207 lignes)
✅ offset_0336CBS_EDA.csv → conservé (28163 lignes)
✅ offset_0337BFS_EDA.csv → conservé (35239 lignes)
✅ offset_0339NPR_EDA.csv → conservé (23627 lignes)
✅ offset_0341LJS_EDA.csv → conservé (22779 lignes)
✅ offset_0342VNS_EDA.csv → conservé (26627 lignes)
✅ offset_0343PAS_EDA.csv → conservé (19835 lignes)
✅ offset_0345LAR_EDA.csv → conservé (22315 lignes)
✅ offset_0346GLS_EDA.csv → conservé (21467 lignes)
✅ offset_0347DMR_EDA.csv → conservé (25975 lignes)
✅ offset_0348GCR_EDA.csv → conservé (28443 lignes)
✅ offset_0349LLS_EDA.csv → conservé (26327 lignes)
✅ offset_0350MYR_EDA.csv → conservé (25323 lignes)
✅ offset_0351FIR_EDA.csv → conservé (26219 lignes)
✅ offset_0352RNR_EDA.csv → conservé (23791 lignes)
✅ offset_0354GKR_EDA.csv → conservé (25935 lignes)
✅ offset_0355BAS_EDA.csv → conservé (24607 lignes)
🗑️ offset_0356DMS_EDA.csv → candidat exclu (0356DMS)
✅ offset_0401TSS_EDA.csv → conservé (34323 lignes)
✅ offset_0402LLS_EDA.csv → conservé (29523 lignes)
✅ offset_0403DCR_EDA.csv → conservé (30003 lignes)
✅ offset_0404CYS_EDA.csv → conservé (36591 lignes)
✅ offset_0405FCR_EDA.csv → conservé (35043 lignes)
✅ offset_0406MCS_EDA.csv → conservé (28655 lignes)
✅ offset_0408BCS_EDA.csv → conservé (32403 lignes)
✅ offset_0410PGS_EDA.csv → conservé (33843 lignes)
✅ offset_0411VES_EDA.csv → conservé (29259 lignes)
✅ offset_0412ANS_EDA.csv → conservé (28251 lignes)
✅ offset_0413HFS_EDA.csv → conservé (31443 lignes)
✅ offset_0413MMR_EDA.csv → conservé (27363 lignes)
✅ offset_0414PVR_EDA.csv → conservé (27059 lignes)
✅ offset_0415HJS_EDA.csv → conservé (23587 lignes)
✅ offset_0415VMR_EDA.csv → conservé (25619 lignes)
✅ offset_0417FAS_EDA.csv → conservé (24767 lignes)
✅ offset_0418MPR_EDA.csv → conservé (29095 lignes)
✅ offset_0420MCR_EDA.csv → conservé (29031 lignes)
✅ offset_0421ACS_EDA.csv → conservé (22323 lignes)
✅ offset_0501MBS_EDA.csv → conservé (24907 lignes)
✅ offset_0502LIR_EDA.csv → conservé (28883 lignes)
✅ offset_0503LCR_EDA.csv → conservé (28082 lignes)
✅ offset_0504BCS_EDA.csv → conservé (27603 lignes)
✅ offset_0505PPR_EDA.csv → conservé (28539 lignes)
✅ offset_0506VMS_EDA.csv → conservé (28499 lignes)
✅ offset_0507BDS_EDA - Copie.csv → conservé (30655 lignes)
✅ offset_0508SRR_EDA.csv → conservé (26163 lignes)
✅ offset_0509LGS_EDA.csv → conservé (30483 lignes)
✅ offset_0510DFS_EDA.csv → conservé (26163 lignes)
✅ offset_0511LCS_EDA[1].csv → conservé (32243 lignes)
✅ offset_0512RCR_EDA.csv → conservé (26235 lignes)
✅ offset_0513EBS_EDA.csv → conservé (22827 lignes)
✅ offset_0515FAR_EDA.csv → conservé (26883 lignes)
✅ offset_0626MCS_EDA.csv → conservé (25959 lignes)
✅ offset_0628DMR_EDA.csv → conservé (32115 lignes)
✅ offset_0629TCR_EDA.csv → conservé (31975 lignes)
✅ offset_0630RJR_EDA.csv → conservé (21971 lignes)
✅ offset_0631LHR_EDA.csv → conservé (23123 lignes)
✅ offset_0801HDR_EDA.csv → conservé (27371 lignes)
✅ offset_0802LAS_EDA.csv → conservé (25759 lignes)
✅ offset_0804GOR_EDA.csv → conservé (25403 lignes)
✅ offset_0805BMS_EDA.csv → conservé (21975 lignes)
✅ offset_0807OMR_EDA.csv → conservé (24083 lignes)
✅ offset_0808PJR_EDA.csv → conservé (26883 lignes)
✅ offset_0902SIS_EDA.csv → conservé (19407 lignes)
✅ offset_0904KJS_EDA.csv → conservé (24079 lignes)
✅ offset_0905SLR_EDA.csv → conservé (26351 lignes)
✅ offset_0906DNR_EDA.csv → conservé (38851 lignes)

====== RÉSUMÉ ======
Fichiers supprimés : 2
Fichiers conservés : 153

Détail suppressions :
 - ('offset_0130FAR_EDA.csv', 'candidat exclu')
 - ('offset_0356DMS_EDA.csv', 'candidat exclu')

# On peut passer au découpage!

In [47]:
def decouper_eda_par_bloc(df_eda, duree_bloc1, duree_video, duree_bloc2, duree_bloc3, delta):
    
    df_eda = df_eda.copy()
    
    if len(df_eda) < 3:
        print("⚠️ Fichier trop court pour découpages")
        return None

    # ===== Lire timestamp initial et fréquence =====
    ts_unix = df_eda.iloc[0, 0]  # première ligne, première colonne
    freq_hz = df_eda.iloc[1, 0]  # deuxième ligne, première colonne
    print(df_eda.iloc[0])
    print(df_eda.iloc[1])

    try:
        t0 = datetime.datetime.fromtimestamp(int(ts_unix))
        delta_sec = 1.0 / 4
    except Exception as e:
        print(f"⚠️ Impossible de lire timestamp/freq : {e}")
        return None

    # ===== Générer colonne Timestamp =====
    nb_lignes = len(df_eda) - 2  # exclure les 2 premières lignes
    timestamps = [t0 + datetime.timedelta(seconds=i * delta_sec) for i in range(nb_lignes)]
    df_eda_data = df_eda.iloc[2:].copy()
    df_eda_data["Timestamp"] = timestamps

    t_fin_rr = df_eda_data["Timestamp"].max()

    # ===== Bornes temporelles =====
    fin_bloc1 = t0 + pd.Timedelta(seconds=max(0, duree_bloc1 - delta))
    debut_bloc2 = fin_bloc1 + pd.Timedelta(seconds=duree_video)
    fin_bloc2 = debut_bloc2 + pd.Timedelta(seconds=duree_bloc2)
    fin_bloc3 = fin_bloc2 + pd.Timedelta(seconds=duree_bloc3)
    fin_bloc3 = min(fin_bloc3, t_fin_rr)  # sécurité

    # ===== Découpage =====
    blocs = {
        "bloc1": df_eda_data[(df_eda_data["Timestamp"] >= t0) & (df_eda_data["Timestamp"] < fin_bloc1)],
        "bloc2": df_eda_data[(df_eda_data["Timestamp"] >= debut_bloc2) & (df_eda_data["Timestamp"] < fin_bloc2)],
        "bloc3": df_eda_data[(df_eda_data["Timestamp"] >= fin_bloc2) & (df_eda_data["Timestamp"] <= fin_bloc3)],
        "bornes": {
            "t0": t0,
            "fin_bloc1": fin_bloc1,
            "debut_bloc2": debut_bloc2,
            "fin_bloc2": fin_bloc2,
            "fin_bloc3": fin_bloc3,
            "t_fin_rr": t_fin_rr
        }
    }

    return blocs

In [44]:
def convertir_et_normaliser_heure(x):
    """
    Convertit n'importe quel format d'heure Excel / texte / datetime en pd.Timestamp
    normalisé sur le 1900-01-01, ne gardant que l'heure, minute, seconde.
    """
    if pd.isna(x):
        return pd.NaT

    # Excel numérique → fraction de jour ou date complète
    if isinstance(x, (int, float)):
        seconds = (float(x) * 24 * 3600) % (24*3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # Timestamp ou datetime → on garde juste l'heure
    if isinstance(x, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=x.hour, minute=x.minute, second=x.second
        )

    # Texte
    try:
        t = pd.to_datetime(str(x).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

In [45]:
def get_durees_blocs(pid, feuille):
    """
    Récupère les durées pour les 3 blocs et la vidéo pour un PID donné et une feuille donnée.
    Applique un correctif spécifique pour 0101EMS.
    """
    pid = str(pid).upper()

    # ===== Bloc 1 =====
    df_b1 = pd.DataFrame(resultats_bloc1[feuille]["df"])
    ligne = df_b1.loc[df_b1["Numero_inclusion"].str.upper() == pid]

    if ligne.empty:
        raise ValueError(f"PID {pid} absent du bloc 1 dans la feuille {feuille}")

    d1 = ligne["duree_bloc1"].values[0]
    condition = ligne["Condition"].values[0]

    # ===== Durée vidéo =====
    t_fin_anamnese = convertir_et_normaliser_heure(
        ligne["heure_fin_anamnese_v2"].values[0]
    )
    t_debut_rlri = convertir_et_normaliser_heure(
        ligne["heure_rlri16imm_debut_V2"].values[0]
    )

    if pd.notna(t_fin_anamnese) and pd.notna(t_debut_rlri):
        delta = (t_debut_rlri - t_fin_anamnese) / pd.Timedelta(seconds=1)  # en secondes
        if delta < 0:
            delta += 24*3600
    else:
        delta = 0
    duree_video_sec = delta

    # ===== DEBUG =====
    print("\n=== DEBUG VIDEO ===")
    print("Feuille :", feuille)
    print("PID :", pid)
    print("heure_fin_anamnese brute :", ligne["heure_fin_anamnese_v2"].values[0])
    print("heure_rlri16imm_debut brute :", ligne["heure_rlri16imm_debut_V2"].values[0])
    print("t_fin_anamnese :", t_fin_anamnese)
    print("t_debut_rlri  :", t_debut_rlri)
    print("delta final (s) :", delta)
    print("===================")

    # ===== Bloc 2 =====
    if condition == "Standard":
        df_b2 = pd.DataFrame(resultats_bloc2_S[feuille]["df"])
        duree_col = "duree_bloc2S"
    else:
        df_b2 = pd.DataFrame(resultats_bloc2_R[feuille]["df"])
        duree_col = "duree_bloc2R"

    # ⚠️ Correction spécifique pour 0101EMS
    if pid == "0101EMS":
        for col in ["heure_rlri16imm_debut_V2", "heure_nback_v2 (consigne)"]:
            val = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, col].values[0]
            ts = convertir_et_normaliser_heure(val)
            df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, col] = ts

        # Recalculer la durée pour ce PID
        start = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, "heure_rlri16imm_debut_V2"].values[0]
        end   = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, "heure_nback_v2 (consigne)"].values[0]
        df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, duree_col] = (end - start) / pd.Timedelta(minutes=1)

    # ===== Récupérer d2 normalement =====
    d2 = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, duree_col].values[0]

    # ⚠️ Ajouter delta vidéo uniquement pour 0101EMS
    if pid == "0101EMS":
        d2 += duree_video_sec / 60  # secondes → minutes

    # ===== Bloc 3 =====
    df_b3 = pd.DataFrame(resultats_bloc3[feuille]["df"])
    d3 = df_b3.loc[df_b3["Numero_inclusion"].str.upper() == pid, "duree_bloc3"].values[0]

    return {
        "bloc1_sec": d1 * 60,
        "video_sec": duree_video_sec,
        "bloc2_sec": d2 * 60,
        "bloc3_sec": d3 * 60,
        "condition": condition
    }

In [51]:
# ===== Dossiers =====
input_dir = os.path.join(os.path.expanduser("~"), "Desktop", "EDA_v2_tronqués")
output_dir = os.path.join(os.path.expanduser("~"), "Desktop", "EDA_v2_tronque_blocs")
os.makedirs(output_dir, exist_ok=True)

resultats_decoupage = {}

# ===== Boucle UNIQUEMENT sur les fichiers tronqués =====
for fichier in os.listdir(input_dir):

    if not fichier.lower().endswith(".csv"):
        continue

    chemin_eda = os.path.join(input_dir, fichier)

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", fichier.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {fichier}")
        continue

    pid = match.group()

    # ===== Récupération de la feuille associée =====
    ligne = df_global.loc[df_global["Numero_inclusion"] == pid]
    if ligne.empty:
        print(f"⚠️ Feuille introuvable pour {pid}")
        continue

    feuille = ligne["Feuille"].values[0]

    print(f"\n--- Découpage {pid} ({feuille}) ---")

    # ===== Lecture EDA =====
    try:
        df_rr = pd.read_csv(chemin_eda,header=None)
    except Exception as e:
        print(f"❌ Lecture impossible {pid} : {e}")
        continue

    # ===== Récupération des durées =====
    try:
        durees = get_durees_blocs(pid, feuille)
    except Exception as e:
        print(f"⚠️ Impossible de récupérer les durées pour {pid} ({feuille}) : {e}")
        continue
        
    delta_row = df_offset_eda.loc[df_offset_eda["Numero_inclusion"].str.upper() == pid.upper()]
    if delta_row.empty:
        delta_val = 0
    else:
        delta_val = float(delta_row["delta_retard_sec"].values[0])
        
    # ===== Découpage =====
    decoupe = decouper_eda_par_bloc(
        df_eda=df_rr,
        delta = delta_val,
        duree_bloc1=durees["bloc1_sec"],
        duree_video=durees["video_sec"],
        duree_bloc2=durees["bloc2_sec"],
        duree_bloc3=durees["bloc3_sec"]
    )

    if decoupe is None:
        print(f"⚠️ Découpage vide pour {pid}")
        continue

    # ===== Sauvegarde par bloc =====
    for bloc in ["bloc1", "bloc2", "bloc3"]:
        df_bloc = decoupe[bloc]

        if df_bloc.empty:
            print(f"⚠️ {pid} {bloc} vide")
            continue

        nom_sortie = f"{pid}_{bloc}.csv"
        df_bloc.to_csv(
            os.path.join(output_dir, nom_sortie),
            index=False
        )

    # ===== Stockage mémoire =====
    resultats_decoupage[pid] = decoupe

    print(
        f"✔ {pid} | "
        f"B1={len(decoupe['bloc1'])} | "
        f"B2={len(decoupe['bloc2'])} | "
        f"B3={len(decoupe['bloc3'])}"
    )

print("\n✅ Découpage terminé")
print("📁 Résultats dans :", output_dir)

--- Découpage 0101CAR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0101CAR
heure_fin_anamnese brute : 08:50:00
heure_rlri16imm_debut brute : 08:57:00
t_fin_anamnese : 1900-01-01 08:50:00
t_debut_rlri  : 1900-01-01 08:57:00
delta final (s) : 420.0
===================
0    1.530858e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0101CAR | B1=6000 | B2=15360 | B3=14401

--- Découpage 0101EMS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0101EMS
heure_fin_anamnese brute : 10:33:00
heure_rlri16imm_debut brute :  10:35
t_fin_anamnese : 1900-01-01 10:33:00
t_debut_rlri  : 1900-01-01 10:35:00
delta final (s) : 120.0
===================
0    1.548148e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0101EMS | B1=5360 | B2=9360 | B3=9601

--- Découpage 0102PCR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0102PCR
heure_fin_anamnese brute : 09:24:00
heure_rlri16imm_debut brute : 09:30:00
t_fin_anamnese : 1900-01-01 09:24:00
t_debut_rlri  : 1900-01-01 09:30:00
delta final (s) : 360.0
===================
0    1.531119e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0102PCR | B1=6228 | B2=10080 | B3=12001

--- Découpage 0103BPS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0103BPS
heure_fin_anamnese brute : 10:20:00
heure_rlri16imm_debut brute : 10:21:00
t_fin_anamnese : 1900-01-01 10:20:00
t_debut_rlri  : 1900-01-01 10:21:00
delta final (s) : 60.0
===================
0    1.544519e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0103BPS | B1=2744 | B2=8160 | B3=9361

--- Découpage 0103SHS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0103SHS
heure_fin_anamnese brute : 09:14:00
heure_rlri16imm_debut brute : 09:15:00
t_fin_anamnese : 1900-01-01 09:14:00
t_debut_rlri  : 1900-01-01 09:15:00
delta final (s) : 60.0
===================
0    1.536563e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0103SHS | B1=2204 | B2=9120 | B3=10321

--- Découpage 0104FJS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0104FJS
heure_fin_anamnese brute : 08:56:00
heure_rlri16imm_debut brute : 08:58:00
t_fin_anamnese : 1900-01-01 08:56:00
t_debut_rlri  : 1900-01-01 08:58:00
delta final (s) : 120.0
===================
0    1.543477e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0104FJS | B1=6112 | B2=14880 | B3=16561

--- Découpage 0104IBS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0104IBS
heure_fin_anamnese brute : 10:14:00
heure_rlri16imm_debut brute : 10:18:00
t_fin_anamnese : 1900-01-01 10:14:00
t_debut_rlri  : 1900-01-01 10:18:00
delta final (s) : 240.0
===================
0    1.543396e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0104IBS | B1=3644 | B2=7680 | B3=10081

--- Découpage 0105PNR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0105PNR
heure_fin_anamnese brute : 08:48:00
heure_rlri16imm_debut brute : 08:55:00
t_fin_anamnese : 1900-01-01 08:48:00
t_debut_rlri  : 1900-01-01 08:55:00
delta final (s) : 420.0
===================
0    1.544427e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0105PNR | B1=5868 | B2=9840 | B3=11281

--- Découpage 0106DJR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0106DJR
heure_fin_anamnese brute : 10:22:00
heure_rlri16imm_debut brute : 10:28:00
t_fin_anamnese : 1900-01-01 10:22:00
t_debut_rlri  : 1900-01-01 10:28:00
delta final (s) : 360.0
===================
0    1.545210e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0106DJR | B1=4012 | B2=9120 | B3=11281

--- Découpage 0106JLS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0106JLS
heure_fin_anamnese brute : 08:42:00
heure_rlri16imm_debut brute : 08:43:00
t_fin_anamnese : 1900-01-01 08:42:00
t_debut_rlri  : 1900-01-01 08:43:00
delta final (s) : 60.0
===================
0    1.546500e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0106JLS | B1=3572 | B2=16320 | B3=9601

--- Découpage 0107DSS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0107DSS
heure_fin_anamnese brute : 08:44:00
heure_rlri16imm_debut brute : 08:45:00
t_fin_anamnese : 1900-01-01 08:44:00
t_debut_rlri  : 1900-01-01 08:45:00
delta final (s) : 60.0
===================
0    1.547451e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0107DSS | B1=4392 | B2=13680 | B3=10561

--- Découpage 0108BFS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0108BFS
heure_fin_anamnese brute : 09:00:00
heure_rlri16imm_debut brute : 09:01:00
t_fin_anamnese : 1900-01-01 09:00:00
t_debut_rlri  : 1900-01-01 09:01:00
delta final (s) : 60.0
===================
0    1.547711e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0108BFS | B1=3652 | B2=12000 | B3=15601

--- Découpage 0109GSS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0109GSS
heure_fin_anamnese brute : 09:21:00
heure_rlri16imm_debut brute : 09:23:00
t_fin_anamnese : 1900-01-01 09:21:00
t_debut_rlri  : 1900-01-01 09:23:00
delta final (s) : 120.0
===================
0    1.550477e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0109GSS | B1=5600 | B2=11520 | B3=12241

--- Découpage 0109MJR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0109MJR
heure_fin_anamnese brute : 09:50:00
heure_rlri16imm_debut brute : 09:58:00
t_fin_anamnese : 1900-01-01 09:50:00
t_debut_rlri  : 1900-01-01 09:58:00
delta final (s) : 480.0
===================
0    1.544690e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0109MJR | B1=2616 | B2=8880 | B3=11761

--- Découpage 0110LPR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0110LPR
heure_fin_anamnese brute : 09:11:00
heure_rlri16imm_debut brute : 09:17:00
t_fin_anamnese : 1900-01-01 09:11:00
t_debut_rlri  : 1900-01-01 09:17:00
delta final (s) : 360.0
===================
0    1.551167e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0110LPR | B1=5308 | B2=10800 | B3=13681

--- Découpage 0110RMS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0110RMS
heure_fin_anamnese brute : 09:48:00
heure_rlri16imm_debut brute : 09:49:00
t_fin_anamnese : 1900-01-01 09:48:00
t_debut_rlri  : 1900-01-01 09:49:00
delta final (s) : 60.0
===================
0    1.544777e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0110RMS | B1=2640 | B2=9600 | B3=10081

--- Découpage 0111MNR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0111MNR
heure_fin_anamnese brute : 09:27:00
heure_rlri16imm_debut brute : 09:35:00
t_fin_anamnese : 1900-01-01 09:27:00
t_debut_rlri  : 1900-01-01 09:35:00
delta final (s) : 480.0
===================
0    1.551341e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0111MNR | B1=5504 | B2=10800 | B3=12001

--- Découpage 0112BSR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0112BSR
heure_fin_anamnese brute : 09:27:00
heure_rlri16imm_debut brute : 09:33:00
t_fin_anamnese : 1900-01-01 09:27:00
t_debut_rlri  : 1900-01-01 09:33:00
delta final (s) : 360.0
===================
0    1.559803e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0112BSR | B1=13356 | B2=8160 | B3=12721

--- Découpage 0113BMR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0113BMR
heure_fin_anamnese brute : 08:42:00
heure_rlri16imm_debut brute : 08:49:00
t_fin_anamnese : 1900-01-01 08:42:00
t_debut_rlri  : 1900-01-01 08:49:00
delta final (s) : 420.0
===================
0    1.561012e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0113BMR | B1=5308 | B2=11280 | B3=11761

--- Découpage 0113DGR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0113DGR
heure_fin_anamnese brute : 09:57:00
heure_rlri16imm_debut brute : 10:07:00
t_fin_anamnese : 1900-01-01 09:57:00
t_debut_rlri  : 1900-01-01 10:07:00
delta final (s) : 600.0
===================
0    1.543308e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0113DGR | B1=3840 | B2=8880 | B3=9361

--- Découpage 0114LMS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0114LMS
heure_fin_anamnese brute : 08:57:00
heure_rlri16imm_debut brute : 08:59:00
t_fin_anamnese : 1900-01-01 08:57:00
t_debut_rlri  : 1900-01-01 08:59:00
delta final (s) : 120.0
===================
0    1.561617e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0114LMS | B1=4708 | B2=9120 | B3=11041

--- Découpage 0114MLR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0114MLR
heure_fin_anamnese brute : 10:17:00
heure_rlri16imm_debut brute : 10:22:00
t_fin_anamnese : 1900-01-01 10:17:00
t_debut_rlri  : 1900-01-01 10:22:00
delta final (s) : 300.0
===================
0    1.546852e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0114MLR | B1=3568 | B2=9600 | B3=12481

--- Découpage 0115CJR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0115CJR
heure_fin_anamnese brute : 08:36:00
heure_rlri16imm_debut brute : 08:44:00
t_fin_anamnese : 1900-01-01 08:36:00
t_debut_rlri  : 1900-01-01 08:44:00
delta final (s) : 480.0
===================
0    1.566887e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0115CJR | B1=2164 | B2=10560 | B3=9361

--- Découpage 0115MHR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0115MHR
heure_fin_anamnese brute : 09:58:00
heure_rlri16imm_debut brute : 10:05:00
t_fin_anamnese : 1900-01-01 09:58:00
t_debut_rlri  : 1900-01-01 10:05:00
delta final (s) : 420.0
===================
0    1.547196e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0115MHR | B1=3988 | B2=9360 | B3=10801

--- Découpage 0116CNR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0116CNR
heure_fin_anamnese brute : 09:56:00
heure_rlri16imm_debut brute : 10:03:00
t_fin_anamnese : 1900-01-01 09:56:00
t_debut_rlri  : 1900-01-01 10:03:00
delta final (s) : 420.0
===================
0    1.547110e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0116CNR | B1=2356 | B2=9840 | B3=13921

--- Découpage 0116VAR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0116VAR
heure_fin_anamnese brute : 09:13:00
heure_rlri16imm_debut brute : 09:21:00
t_fin_anamnese : 1900-01-01 09:13:00
t_debut_rlri  : 1900-01-01 09:21:00
delta final (s) : 480.0
===================
0    1.567061e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0116VAR | B1=7900 | B2=10080 | B3=13921

--- Découpage 0117MSR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0117MSR
heure_fin_anamnese brute : 10:04:00
heure_rlri16imm_debut brute : 10:09:00
t_fin_anamnese : 1900-01-01 10:04:00
t_debut_rlri  : 1900-01-01 10:09:00
delta final (s) : 300.0
===================
0    1.547456e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0117MSR | B1=4276 | B2=9120 | B3=12241

--- Découpage 0117POS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0117POS
heure_fin_anamnese brute : 08:43:00
heure_rlri16imm_debut brute : 08:44:00
t_fin_anamnese : 1900-01-01 08:43:00
t_debut_rlri  : 1900-01-01 08:44:00
delta final (s) : 60.0
===================
0    1.567665e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0117POS | B1=4132 | B2=10560 | B3=10561

--- Découpage 0118TMS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0118TMS
heure_fin_anamnese brute : 10:07:00
heure_rlri16imm_debut brute : 10:07:00
t_fin_anamnese : 1900-01-01 10:07:00
t_debut_rlri  : 1900-01-01 10:07:00
delta final (s) : 0.0
===================
0    1.547628e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0118TMS | B1=6392 | B2=8880 | B3=12481

--- Découpage 0118TNS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0118TNS
heure_fin_anamnese brute : 09:03:00
heure_rlri16imm_debut brute : 09:04:00
t_fin_anamnese : 1900-01-01 09:03:00
t_debut_rlri  : 1900-01-01 09:04:00
delta final (s) : 60.0
===================
0    1.569912e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0118TNS | B1=6160 | B2=8640 | B3=12001

--- Découpage 0119BIR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0119BIR
heure_fin_anamnese brute : 09:47:00
heure_rlri16imm_debut brute : 09:53:00
t_fin_anamnese : 1900-01-01 09:47:00
t_debut_rlri  : 1900-01-01 09:53:00
delta final (s) : 360.0
===================
0    1.548665e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0119BIR | B1=2820 | B2=9120 | B3=10561

--- Découpage 0119LJS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0119LJS
heure_fin_anamnese brute : 08:58:00
heure_rlri16imm_debut brute : 09:00:00
t_fin_anamnese : 1900-01-01 08:58:00
t_debut_rlri  : 1900-01-01 09:00:00
delta final (s) : 120.0
===================
0    1.573112e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0119LJS | B1=4644 | B2=9600 | B3=11281

--- Découpage 0120ANS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0120ANS
heure_fin_anamnese brute : 09:58:00
heure_rlri16imm_debut brute : 09:59:00
t_fin_anamnese : 1900-01-01 09:58:00
t_debut_rlri  : 1900-01-01 09:59:00
delta final (s) : 60.0
===================
0    1.549270e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0120ANS | B1=3280 | B2=7440 | B3=11281

--- Découpage 0120LCR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0120LCR
heure_fin_anamnese brute : 08:57:00
heure_rlri16imm_debut brute : 09:02:00
t_fin_anamnese : 1900-01-01 08:57:00
t_debut_rlri  : 1900-01-01 09:02:00
delta final (s) : 300.0
===================
0    1.575617e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0120LCR | B1=7444 | B2=9600 | B3=11521

--- Découpage 0121MJR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0121MJR
heure_fin_anamnese brute : 09:21:00
heure_rlri16imm_debut brute : 09:28:00
t_fin_anamnese : 1900-01-01 09:21:00
t_debut_rlri  : 1900-01-01 09:28:00
delta final (s) : 420.0
===================
0    1.576138e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0121MJR | B1=4108 | B2=9600 | B3=12241

--- Découpage 0121RPS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0121RPS
heure_fin_anamnese brute : 09:38:00
heure_rlri16imm_debut brute : 09:39:00
t_fin_anamnese : 1900-01-01 09:38:00
t_debut_rlri  : 1900-01-01 09:39:00
delta final (s) : 60.0
===================
0    1.548232e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0121RPS | B1=2400 | B2=8400 | B3=10561

--- Découpage 0122VCR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0122VCR
heure_fin_anamnese brute : 10:02:00
heure_rlri16imm_debut brute : 10:08:00
t_fin_anamnese : 1900-01-01 10:02:00
t_debut_rlri  : 1900-01-01 10:08:00
delta final (s) : 360.0
===================
0    1.549010e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0122VCR | B1=6000 | B2=10560 | B3=13441

--- Découpage 0123GVS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0123GVS
heure_fin_anamnese brute : 09:39:00
heure_rlri16imm_debut brute : 09:39:00
t_fin_anamnese : 1900-01-01 09:39:00
t_debut_rlri  : 1900-01-01 09:39:00
delta final (s) : 0.0
===================
0    1.549614e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0123GVS | B1=2692 | B2=7920 | B3=9121

--- Découpage 0123RMS (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0123RMS
heure_fin_anamnese brute : 08:56:00
heure_rlri16imm_debut brute : 08:57:00
t_fin_anamnese : 1900-01-01 08:56:00
t_debut_rlri  : 1900-01-01 08:57:00
delta final (s) : 60.0
===================
0    1.576827e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0123RMS | B1=4828 | B2=12720 | B3=9841

--- Découpage 0124BAR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0124BAR
heure_fin_anamnese brute : 09:59:00
heure_rlri16imm_debut brute : 10:08:00
t_fin_anamnese : 1900-01-01 09:59:00
t_debut_rlri  : 1900-01-01 10:08:00
delta final (s) : 540.0
===================
0    1.578387e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0124BAR | B1=4016 | B2=10800 | B3=12241

--- Découpage 0124PAS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0124PAS
heure_fin_anamnese brute : 10:38:00
heure_rlri16imm_debut brute : 10:38:00
t_fin_anamnese : 1900-01-01 10:38:00
t_debut_rlri  : 1900-01-01 10:38:00
delta final (s) : 0.0
===================
0    1.550223e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0124PAS | B1=2320 | B2=8400 | B3=9841

--- Découpage 0125BMR (APHM) ---

=== DEBUG VIDEO ===
Feuille : APHM
PID : 0125BMR
heure_fin_anamnese brute : 11:54:00
heure_rlri16imm_debut brute : 12:00:00
t_fin_anamnese : 1900-01-01 11:54:00
t_debut_rlri  : 1900-01-01 12:00:00
delta final (s) : 360.0
===================
0    1.578998e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0125BMR | B1=6328 | B2=13200 | B3=10081

--- Découpage 0126VLR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0126VLR
heure_fin_anamnese brute : 09:55:00
heure_rlri16imm_debut brute : 10:01:00
t_fin_anamnese : 1900-01-01 09:55:00
t_debut_rlri  : 1900-01-01 10:01:00
delta final (s) : 360.0
===================
0    1.552034e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0126VLR | B1=4096 | B2=7680 | B3=9361

--- Découpage 0127CMS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0127CMS
heure_fin_anamnese brute : 09:50:00
heure_rlri16imm_debut brute : 09:50:00
t_fin_anamnese : 1900-01-01 09:50:00
t_debut_rlri  : 1900-01-01 09:50:00
delta final (s) : 0.0
===================
0    1.550738e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0127CMS | B1=3272 | B2=8400 | B3=9601

--- Découpage 0128ALS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0128ALS
heure_fin_anamnese brute : 09:52:00
heure_rlri16imm_debut brute : 09:52:00
t_fin_anamnese : 1900-01-01 09:52:00
t_debut_rlri  : 1900-01-01 09:52:00
delta final (s) : 0.0
===================
0    1.552467e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0128ALS | B1=2344 | B2=8640 | B3=11761

--- Découpage 0129APR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0129APR
heure_fin_anamnese brute : 10:10:00
heure_rlri16imm_debut brute : 10:18:00
t_fin_anamnese : 1900-01-01 10:10:00
t_debut_rlri  : 1900-01-01 10:18:00
delta final (s) : 480.0
===================
0    1.552553e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0129APR | B1=5760 | B2=12720 | B3=13681

--- Découpage 0131CPS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0131CPS
heure_fin_anamnese brute : 10:15:00
heure_rlri16imm_debut brute : 10:16:00
t_fin_anamnese : 1900-01-01 10:15:00
t_debut_rlri  : 1900-01-01 10:16:00
delta final (s) : 60.0
===================
0    1.575882e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0131CPS | B1=2756 | B2=8880 | B3=9361

--- Découpage 0132GAR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0132GAR
heure_fin_anamnese brute : 10:09:00
heure_rlri16imm_debut brute : 10:15:00
t_fin_anamnese : 1900-01-01 10:09:00
t_debut_rlri  : 1900-01-01 10:15:00
delta final (s) : 360.0
===================
0    1.582103e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0132GAR | B1=2844 | B2=7920 | B3=9601

--- Découpage 0133BPS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0133BPS
heure_fin_anamnese brute : 10:19:00
heure_rlri16imm_debut brute : 10:20:00
t_fin_anamnese : 1900-01-01 10:19:00
t_debut_rlri  : 1900-01-01 10:20:00
delta final (s) : 60.0
===================
0    1.582708e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0133BPS | B1=3644 | B2=7920 | B3=11041

--- Découpage 0134IFR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0134IFR
heure_fin_anamnese brute : 09:47:00
heure_rlri16imm_debut brute : 09:52:00
t_fin_anamnese : 1900-01-01 09:47:00
t_debut_rlri  : 1900-01-01 09:52:00
delta final (s) : 300.0
===================
0    1.583225e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0134IFR | B1=2704 | B2=8160 | B3=9601

--- Découpage 0135KLS (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0135KLS
heure_fin_anamnese brute : 08:58:00
heure_rlri16imm_debut brute : 08:59:00
t_fin_anamnese : 1900-01-01 08:58:00
t_debut_rlri  : 1900-01-01 08:59:00
delta final (s) : 60.0
===================
0    1.614757e+09
Name: 0, dtype: float64
0    4.0
Name: 1, dtype: float64
✔ 0135KLS | B1=3840 | B2=8640 | B3=9492

--- Découpage 0136CJR (LPC) ---

=== DEBUG VIDEO ===
Feuille : LPC
PID : 0136CJR

# DATA FRAME DIRECT 
lignes_globales = []

for pid, decoupe in resultats_decoupage.items():

    # ===== Condition =====
    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    # ===== Offset =====
    offset_sec = abs(
        df_controle_durees.loc[
            df_controle_durees["Numero_inclusion"] == pid,
            "ecart_sec"
        ].values[0]
    )

    bornes = decoupe["bornes"]

    for nom_bloc in ["bloc1", "bloc2", "bloc3"]:

        df_bloc = decoupe[nom_bloc]

        if df_bloc.empty:
            continue

        # =====================================================
        # CAS 1 : RR fourni par l'appareil (RtoR)
        # =====================================================
        if "RtoR" in df_bloc.columns:

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row["Timestamp"],
                    "RtoR": row["RtoR"],      
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 2 : RR calculé (temps_ms / rr_ms)
        # =====================================================
        elif {"temps_ms", "rr_ms"}.issubset(df_bloc.columns):

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row.get("Timestamp", pd.NaT),
                    "RtoR": row["rr_ms"] / 1000,  # ms → sec
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 3 : Timestamp seul
        # =====================================================
        else:
            for ts in df_bloc["Timestamp"]:
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": ts,
                    "RtoR": None,
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

df_rr_global = pd.DataFrame(lignes_globales)

# DATA FRAME IMBRIQUE
lignes_patients = []

for pid, decoupe in resultats_decoupage.items():

    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    lignes_patients.append({
        "Numero_inclusion": pid,
        "Condition": condition,
        "baseline": decoupe["bloc1"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc2": decoupe["bloc2"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc3": decoupe["bloc3"][["Timestamp", "RtoR"]].reset_index(drop=True),
    })

df_patients = pd.DataFrame(lignes_patients)

In [ ]:
## Traitment pour passer le fichier dans kubios