# Bibliotheque + lecture Excel

In [1]:
import pandas as pd 
import numpy as np 
import os
import re
import datetime
from collections import defaultdict
import zipfile
from datetime import datetime, timedelta
from pathlib import Path

In [2]:
df = pd.read_excel('AGING_Ceinture_Montre (avec groupe).xlsx',sheet_name=None)

C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
df.keys()

dict_keys(['APHM', 'CAEN', 'POITIERS', 'ROUEN', 'LAVERAN', 'LPC', 'SAINTE-MARGUERITE', 'CGD', 'CERCA', 'Effectifs ceinture', 'Effectifs montre', 'CODEBOOK '])

# Vérification blocs

In [4]:
 # ===== Conversion heures =====
def convertir_heure_excel_ou_texte(x):
     if pd.isna(x):
        return pd.NaT
     if isinstance(x, (int, float)):
        return pd.to_datetime(x, unit="D", origin="1899-12-30")
     try:
        return pd.to_datetime(str(x).strip(), format="%H:%M")
     except Exception:
         try:
             return pd.to_datetime(str(x).strip())
         except Exception:
            return pd.NaT

In [5]:
def analyser_feuille_bloc(
    df,
    nom_feuille,
    col_debut,
    col_fin,
    nom_bloc
):
    print(f"\n--- Feuille : {nom_feuille} | {nom_bloc} ---")

    col_id = "Numero_inclusion"

    # ===== Dictionnaire des règles par centre / bloc / candidat =====
    REGLES_CANDIDATS = {
        ("CAEN", "bloc2", None): {"col_fin": "heure_rappel_cond_v4"},
        ("CAEN", "bloc3", None): {"col_debut": "heure_rappel_cond_v4"},
        ("CAEN", "bloc2", "0326BJR"): {"col_fin": "heure_fluence_sem_v4"},
        ("CAEN", "bloc3", "0326BJR"): {"col_debut": "heure_fluence_sem_v4"},

        ("POITIERS", 'bloc1', "0406MCS"): {"col_debut": "heure_montre_v4"},
        ("POITIERS", 'bloc2', "0408BCS"): {"col_fin": "heure_rappel_cond_v4"},
        ("POITIERS", 'bloc3', "0408BCS"): {"col_debut": "heure_rappel_cond_v4"},

        ("LPC", 'bloc2', "0112DRR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0112DRR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0115MHR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0115MHR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0141HJR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0141HJR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0144ZGR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0144ZGR"): {"col_debut": "heure_rappel_cond_v4"},

        ("CERCA", 'bloc2', "0406BBS"): {"col_fin": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc3', "0406BBS"): {"col_debut": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc2', "0408SJS"): {"col_fin": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc3', "0408SJS"): {"col_debut": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc2', "0409HCR"): {"col_fin": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc3', "0409HCR"): {"col_debut": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc2', "0410FMS"): {"col_fin": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc3', "0410FMS"): {"col_debut": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc2', "0418TJR"): {"col_fin": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc3', "0418TJR"): {"col_debut": "heure_rappel_cond_v4"},
        ("CERCA", 'bloc2', "0420MCR"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0420MCR"): {"col_debut": "heure_nback_v4"},
        ("CERCA", 'bloc2', "0420MCR"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0420MCR"): {"col_debut": "heure_nback_v4"},
        ("CERCA", 'bloc2', "0423SVS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0423SVS"): {"col_debut": "heure_nback_v4"},
        ("CERCA", 'bloc2', "0432CGS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0432CGS"): {"col_debut": "heure_nback_v4"},
        
    }

    # ===== Colonnes effectives par défaut =====
    col_debut_effective = col_debut
    col_fin_effective = col_fin

    # ===== Application des règles =====
    for (centre, bloc, candidat), regle in REGLES_CANDIDATS.items():
        if centre != nom_feuille:
            continue
        if bloc is not None and bloc != nom_bloc:
            continue
        if candidat is not None:
            mask_candidat = df[col_id] == candidat
            if not mask_candidat.any():
                continue

        # Colonnes à remplacer
        if "col_debut" in regle:
            col_debut_effective = regle["col_debut"]
        if "col_fin" in regle:
            col_fin_effective = regle["col_fin"]

        print(f"🔧 Règle appliquée → centre={centre}, bloc={bloc}, candidat={candidat}")

    # ===== Vérification colonnes =====
    for col in [col_debut_effective, col_fin_effective, col_id]:
        if col not in df.columns:
            print(f"❌ Colonne manquante : {col}")
            return None

    # ===== Copie du DataFrame =====
    df = df.copy()

    # Conversion UNIQUEMENT des colonnes utilisées
    df[col_debut_effective] = df[col_debut_effective].apply(convertir_heure_excel_ou_texte)
    df[col_fin_effective] = df[col_fin_effective].apply(convertir_heure_excel_ou_texte)

    # ===== Durée =====
    col_duree = f"duree_{nom_bloc}"
    col_rejet = f"rejeter_{nom_bloc}"

    df[col_duree] = (df[col_fin_effective] - df[col_debut_effective]).dt.total_seconds() / 60

    # Passage de minuit
    df.loc[df[col_duree] < 0, col_duree] += 24 * 60

    # ===== Masques =====
    mask_manquant = df[col_duree].isna()
    mask_valide = df[col_duree].notna() & (df[col_duree] > 0)

    # ===== Statistiques =====
    moyenne = df.loc[mask_valide, col_duree].mean()
    ecart_type = df.loc[mask_valide, col_duree].std()
    print(f"Moyenne = {moyenne:.2f} min")
    print(f"Écart-type = {ecart_type:.2f} min")

    borne_inf = moyenne - 2 * ecart_type

    # ===== Rejets =====
    df[col_rejet] = 0
    df.loc[mask_manquant, col_rejet] = 2

    mask_rejet = df[col_duree] < borne_inf

    # Règle spécifique bloc 1
    if nom_bloc == "bloc1":
        mask_rejet = mask_rejet | (df[col_duree] < 10)

    df.loc[mask_valide & mask_rejet, col_rejet] = 1

    # ===== Résumé =====
    print(f"\nRésumé {col_rejet} :")
    print(df[col_rejet].value_counts().sort_index())

    return {
        "df": df,
        "moyenne": moyenne,
        "ecart_type": ecart_type,
        "rejets": {
            "manquant": df.loc[df[col_rejet] == 2, col_id].tolist(),
            "rejetes": df.loc[df[col_rejet] == 1, col_id].tolist(),
        }
    }

## Bloc 1

In [6]:
feuilles = [
    'APHM', 'CAEN', 'POITIERS', 'ROUEN',
    'LAVERAN', 'LPC', 'SAINTE-MARGUERITE',
    'CGD', 'CERCA'
]

resultats_bloc1 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc1[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_montre_v4",   
        col_fin="heure_anamnese_fin_v4",        
        nom_bloc="bloc1"
    )

============================================================

--- Feuille : APHM | bloc1 ---
Moyenne = 19.61 min
Écart-type = 9.05 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
1     4
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc1 ---
Moyenne = 13.50 min
Écart-type = 4.36 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    39
1     9
2     8
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc1 ---
🔧 Règle appliquée → centre=POITIERS, bloc=bloc1, candidat=0406MCS
Moyenne = 20.08 min
Écart-type = 6.76 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    12
2     3
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc1 ---
Moyenne = 17.53 min
Écart-type = 6.74 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc1 ---
Moyenne = 21.75 min
Écart-type = 2.22 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc1 ---
Moyenne = 19.44 min
Écart-type = 8.31 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    41
1     2
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc1 ---
Moyenne = 16.38 min
Écart-type = 6.91 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    7
1    1
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc1 ---
Moyenne = 28.20 min
Écart-type = 3.56 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc1 ---
Moyenne = 11.48 min
Écart-type = 8.95 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    13
1    14
2    13
Name: count, dtype: int64

## Bloc 2

In [7]:
resultats_bloc2 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_v4",  
        col_fin= "heure_nback_v4 (consignes)" ,         
        nom_bloc="bloc2"
    )

============================================================

--- Feuille : APHM | bloc2 ---
Moyenne = 46.72 min
Écart-type = 9.14 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    18
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2 ---
🔧 Règle appliquée → centre=CAEN, bloc=bloc2, candidat=None
🔧 Règle appliquée → centre=CAEN, bloc=bloc2, candidat=0326BJR
Moyenne = 44.57 min
Écart-type = 6.41 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    48
1     1
2     7
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2 ---
🔧 Règle appliquée → centre=POITIERS, bloc=bloc2, candidat=0408BCS
Moyenne = 46.00 min
Écart-type = 10.40 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    12
2     3
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2 ---
Moyenne = 40.47 min
Écart-type = 5.58 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2 ---
Moyenne = 40.00 min
Écart-type = 13.14 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2 ---
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0112DRR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0115MHR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0141HJR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0144ZGR
Moyenne = 37.30 min
Écart-type = 7.50 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    43
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2 ---
Moyenne = 41.88 min
Écart-type = 5.64 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2 ---
Moyenne = 41.60 min
Écart-type = 4.10 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2 ---
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0406BBS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0408SJS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0409HCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0410FMS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0418TJR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0420MCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0423SVS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0432CGS
Moyenne = 44.31 min
Écart-type = 14.26 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    26
2    14
Name: count, dtype: int64

resultats_bloc2

## Bloc 3

In [8]:
resultats_bloc3 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc3[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_nback_v4 (consignes)",   # à adapter si besoin
        col_fin="heure_fin_tests_v4",         # à adapter si besoin
        nom_bloc="bloc3"
    )

============================================================

--- Feuille : APHM | bloc3 ---
Moyenne = 46.33 min
Écart-type = 13.57 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    18
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc3 ---
🔧 Règle appliquée → centre=CAEN, bloc=bloc3, candidat=None
🔧 Règle appliquée → centre=CAEN, bloc=bloc3, candidat=0326BJR
Moyenne = 61.45 min
Écart-type = 198.00 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    49
2     7
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc3 ---
🔧 Règle appliquée → centre=POITIERS, bloc=bloc3, candidat=0408BCS
Moyenne = 43.50 min
Écart-type = 13.26 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    12
2     3
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc3 ---
Moyenne = 44.67 min
Écart-type = 6.21 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc3 ---
Moyenne = 41.75 min
Écart-type = 9.03 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc3 ---
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0112DRR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0115MHR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0141HJR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0144ZGR
Moyenne = 45.00 min
Écart-type = 6.96 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    41
1     2
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc3 ---
Moyenne = 43.25 min
Écart-type = 4.53 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc3 ---
Moyenne = 41.80 min
Écart-type = 7.12 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc3 ---
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0406BBS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0408SJS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0409HCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0410FMS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0418TJR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0420MCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0423SVS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0432CGS
Moyenne = 46.14 min
Écart-type = 8.09 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    29
2    11
Name: count, dtype: int64

# Nombre de candidats qui passent toutes les conditions

In [9]:
def candidats_valides_tous_blocs_depuis_resultats(
    feuille,
    resultats_blocs,
    col_id="Numero_inclusion"
):
    """
    resultats_blocs = dict {
        "bloc1": resultats_bloc1,
        "bloc2": resultats_bloc2,
        "bloc3": resultats_bloc3
    }
    """

    # Récupération du df de référence (bloc1 par ex)
    df_ref = resultats_blocs["bloc1"][feuille]["df"].copy()

    colonnes_rejet = []

    # Ajouter chaque colonne de rejet depuis chaque bloc
    for nom_bloc, res_bloc in resultats_blocs.items():
        col_rejet = f"rejeter_{nom_bloc}"
        if col_rejet not in res_bloc[feuille]["df"].columns:
            print(f"Colonne manquante : {col_rejet} dans {feuille}")
            return None

        df_ref[col_rejet] = res_bloc[feuille]["df"][col_rejet]
        colonnes_rejet.append(col_rejet)

    # Condition : tout à 0
    mask_valide = (df_ref[colonnes_rejet] == 0).all(axis=1)

    candidats_ok = df_ref.loc[mask_valide, col_id].tolist()
    candidats_rejetes = df_ref.loc[~mask_valide, col_id].tolist()

    print(f"\n=== {feuille} ===")
    print(f"Candidats valides sur TOUS les blocs : {len(candidats_ok)}")

    print("Liste des candidats conservés :")
    for pid in candidats_ok:
        print(f" - {pid}")

    return {
        "nb_valides": len(candidats_ok),
        "valides": candidats_ok,
        "rejetes": candidats_rejetes,
    }

In [10]:
resultats_globaux = {}

colonnes_blocs = [
    "rejeter_bloc1",
    "rejeter_bloc2",
    "rejeter_bloc3"
]

for feuille in feuilles:
    print("\n" + "=" * 70)
    print(f"Analyse globale – Feuille : {feuille}")

    # ===== Base : bloc 1 =====
    df_global = resultats_bloc1[feuille]["df"][
        ["Numero_inclusion", "rejeter_bloc1"]
    ].copy()

    # ===== Fusion bloc 2 =====
    df_global = df_global.merge(
        resultats_bloc2[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 3 =====
    df_global = df_global.merge(
        resultats_bloc3[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc3"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Affichage debug AVANT filtre =====
    print("\n📊 df_global AVANT fillna et filtres :")
    display(df_global)

    # ===== Sécurité : NaN → rejet (2) =====
    df_global[colonnes_blocs] = df_global[colonnes_blocs].fillna(2)

    mask = (
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    # ===== Extraction =====
    candidats_valides = df_global.loc[
        mask, "Numero_inclusion"
    ].tolist()

    candidats_rejetes = df_global.loc[
        ~mask, "Numero_inclusion"
    ].tolist()

    # ===== Résumés =====
    print(f"\nNombre total de candidats : {len(df_global)}")
    print(f"Candidats VALIDES (selon Condition) : {len(candidats_valides)}")
    print(f"Candidats REJETÉS : {len(candidats_rejetes)}")

    print("\nListe des candidats valides :")
    for pid in candidats_valides:
        print(f" - {pid}")

    # ===== Stockage =====
    resultats_globaux[feuille] = {
        "df": df_global,
        "valides": candidats_valides,
        "rejetes": candidats_rejetes,
        "n_valides": len(candidats_valides),
        "n_rejetes": len(candidats_rejetes),
    }

======================================================================
Analyse globale – Feuille : APHM

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0101CAR              0              0              0
1           0102PCR              0              0              0
2           0103SHS              1              0              0
3           0105PNR              0              0              0
4           0104FJS              0              0              0
5           0106JLS              1              0              0
6           0107DSS              0              0              0
7           0108BFS              1              0              0
8           0109GSS              1              0              0
9           0110LPR              0              0              0
10          0111MNR              0              0              0
11          0112BSR              0              0              0
12          0113BMR              2              2              2
13          0114LMS              0              0              0
14          0115CJR              2              2              2
15          0116VAR              0              0              0
16          0117POS              2              2              2
17          0118TNS              2              2              2
18          0119LJS              0              0              0
19          0120LCR              2              2              2
20          0121MJR              0              0              0
21          0122BDS              0              0              0
22          0123RMS              0              0              0
23          0124BAR              2              2              2
24          0125BMR              2              2              2

Nombre total de candidats : 25
Candidats VALIDES (selon Condition) : 14
Candidats REJETÉS : 11

Liste des candidats valides :
 - 0101CAR
 - 0102PCR
 - 0105PNR
 - 0104FJS
 - 0107DSS
 - 0110LPR
 - 0111MNR
 - 0112BSR
 - 0114LMS
 - 0116VAR
 - 0119LJS
 - 0121MJR
 - 0122BDS
 - 0123RMS

======================================================================
Analyse globale – Feuille : CAEN

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0301GNR              2              2              2
1           0302ZMR              0              0              0
2           0303PAR              2              2              2
3           0304VMR              0              0              0
4           0305LCR              0              0              0
5           0307SMR              0              0              0
6           0306MDR              1              0              0
7           0308RGR              0              0              0
8           0309DBS              2              2              2
9           0311CJS              0              0              0
10          0310ACS              0              0              0
11          0315VCS              0              0              0
12          0318PMS              2              2              2
13          0313FPR              0              0              0
14          0312JMS              1              0              0
15          0316TMS              0              0              0
16          0314CDS              0              2              2
17          0317LGS              0              0              0
18          0319LJS              0              0              0
19          0320DGS              0              1              0
20          0321DRR              0              0              0
21          0323RFS              0              0              0
22          0322RMS              0              0              0
23          0324LMR              0              0              0
24          0325LCR              1              0              0
25          0327IAR              1              0              0
26          0326BJR              2              0              0
27          0328MPR              0              0              0
28          0330RTR              0              0              0
29          0329NMR              0              0              0
30          0331GRS              0              0              0
31          0332MCR              1              0              0
32          0333MMS              0              0              0
33          0334TVS              0              0              0
34          0335JMS              2              2              2
35          0336CBS              2              0              0
36          0337BFS              0              0              0
37          0338JBS              0              0              0
38          0339NPR              0              0              0
39          0340BAR              0              0              0
40          0341LJS              0              0              0
41          0342VNS              0              0              0
42          0343PAS              0              0              0
43          0344DBS              1              0              0
44          0345LAR              0              0              0
45          0349LLS              1              0              0
46          0347DMR              0              0              0
47          0346GLS              0              0              0
48          0348GCR              0              0              0
49          0350MYR              0              0              0
50          0351FIR              0              0              0
51          0353LNR              2              2              2
52          0352RNR              0              0              0
53          0354GKR              1              0              0
54          0355BAS              1              0              0
55          0356DMS              0              0              0

Nombre total de candidats : 56
Candidats VALIDES (selon Condition) : 37
Candidats REJETÉS : 19

Liste des candidats valides :
 - 0302ZMR
 - 0304VMR
 - 0305LCR
 - 0307SMR
 - 0308RGR
 - 0311CJS
 - 0310ACS
 - 0315VCS
 - 0313FPR
 - 0316TMS
 - 0317LGS
 - 0319LJS
 - 0321DRR
 - 0323RFS
 - 0322RMS
 - 0324LMR
 - 0328MPR
 - 0330RTR
 - 0329NMR
 - 0331GRS
 - 0333MMS
 - 0334TVS
 - 0337BFS
 - 0338JBS
 - 0339NPR
 - 0340BAR
 - 0341LJS
 - 0342VNS
 - 0343PAS
 - 0345LAR
 - 0347DMR
 - 0346GLS
 - 0348GCR
 - 0350MYR
 - 0351FIR
 - 0352RNR
 - 0356DMS

======================================================================
Analyse globale – Feuille : POITIERS

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0401TSS              0              0              0
1           0402LLS              0              0              0
2           0403DCR              0              0              0
3           0405FCR              2              2              2
4           0404CYS              0              0              0
5           0406MCS              0              0              0
6           0407LJR              0              0              0
7           0408BCS              0              0              0
8           0409PHR              2              2              2
9           0410PGS              2              2              2
10          0413HFS              0              0              0
11          0411VES              0              0              0
12          0412ANS              0              0              0
13          0414PJS              0              0              0
14          0415VMR              0              0              0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 12
Candidats REJETÉS : 3

Liste des candidats valides :
 - 0401TSS
 - 0402LLS
 - 0403DCR
 - 0404CYS
 - 0406MCS
 - 0407LJR
 - 0408BCS
 - 0413HFS
 - 0411VES
 - 0412ANS
 - 0414PJS
 - 0415VMR

======================================================================
Analyse globale – Feuille : ROUEN

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0501MBS              0              0              0
1           0502LIR              0              0              0
2           0503LCR              0              0              0
3           0504BCS              0              0              0
4           0505PPR              0              0              0
5           0506VMS              1              0              0
6           0508SRR              0              0              0
7           0507BDS              0              0              0
8           0509LGS              0              0              0
9           0510DFS              0              0              0
10          0511LCS              0              0              1
11          0512RCR              0              0              0
12          0513EBS              0              0              0
13          0514LPS              0              0              0
14          0515FAR              0              0              0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 13
Candidats REJETÉS : 2

Liste des candidats valides :
 - 0501MBS
 - 0502LIR
 - 0503LCR
 - 0504BCS
 - 0505PPR
 - 0508SRR
 - 0507BDS
 - 0509LGS
 - 0510DFS
 - 0512RCR
 - 0513EBS
 - 0514LPS
 - 0515FAR

======================================================================
Analyse globale – Feuille : LAVERAN

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0626MCS              0              0              0
1          0628DMR              2              2              2
2          0630RJR              0              0              0
3          0629TCR              0              0              0
4          0631LHR              0              0              0

Nombre total de candidats : 5
Candidats VALIDES (selon Condition) : 4
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0626MCS
 - 0630RJR
 - 0629TCR
 - 0631LHR

======================================================================
Analyse globale – Feuille : LPC

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0101EMS              0              0              0
1           0102EMS              0              0              0
2           0103BPS              0              0              0
3           0104IBS              0              0              0
4           0105HAR              1              0              0
5           0106DJR              0              0              0
6           0107LER              0              0              0
7           0108MMS              0              0              0
8           0109MJR              0              0              0
9           0110RMS              0              0              0
10          0111TAS              0              0              0
11          0112DRR              0              0              0
12          0113DGR              0              0              0
13          0114MLR              0              0              0
14          0115MHR              0              0              0
15          0116CNR              0              0              0
16          0117MSR              0              0              0
17          0118TMS              0              0              0
18          0119BIR              0              0              0
19          0120ANS              0              0              0
20          0121RPS              0              0              0
21          0122VCR              0              0              0
22          0123GVS              0              0              0
23          0124PAS              0              0              0
24          0125AMR              1              0              0
25          0126VLR              0              0              0
26          0127CMS              0              0              0
27          0128ALS              0              0              0
28          0129APR              0              0              0
29          0130FAR              0              0              0
30          0131CPS              0              0              1
31          0132GAR              0              0              0
32          0133BPS              0              0              0
33          0134IFR              0              0              1
34          0135KLS              2              2              2
35          0136CJR              0              0              0
36          0137BMS              0              0              0
37          0138NWR              0              0              0
38          0139BMR              0              0              0
39          0140LMR              0              0              0
40          0141HJR              0              0              0
41          0142LLS              0              0              0
42          0143EBR              0              0              0
43          0144ZGR              0              0              0

Nombre total de candidats : 44
Candidats VALIDES (selon Condition) : 39
Candidats REJETÉS : 5

Liste des candidats valides :
 - 0101EMS
 - 0102EMS
 - 0103BPS
 - 0104IBS
 - 0106DJR
 - 0107LER
 - 0108MMS
 - 0109MJR
 - 0110RMS
 - 0111TAS
 - 0112DRR
 - 0113DGR
 - 0114MLR
 - 0115MHR
 - 0116CNR
 - 0117MSR
 - 0118TMS
 - 0119BIR
 - 0120ANS
 - 0121RPS
 - 0122VCR
 - 0123GVS
 - 0124PAS
 - 0126VLR
 - 0127CMS
 - 0128ALS
 - 0129APR
 - 0130FAR
 - 0132GAR
 - 0133BPS
 - 0136CJR
 - 0137BMS
 - 0138NWR
 - 0139BMR
 - 0140LMR
 - 0141HJR
 - 0142LLS
 - 0143EBR
 - 0144ZGR

======================================================================
Analyse globale – Feuille : SAINTE-MARGUERITE

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0801HDR              0              0              0
1          0802LAS              0              0              0
2          0804GOR              0              0              0
3          0803DPS              0              0              0
4          0805BMS              0              0              0
5          0806KHS              0              0              0
6          0807OMR              0              0              0
7          0808PJR              1              0              0

Nombre total de candidats : 8
Candidats VALIDES (selon Condition) : 7
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0801HDR
 - 0802LAS
 - 0804GOR
 - 0803DPS
 - 0805BMS
 - 0806KHS
 - 0807OMR

======================================================================
Analyse globale – Feuille : CGD

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0901SMR              0              0              0
1          0903DJS              0              0              0
2          0902SIS              0              0              0
3          0906DNR              2              2              2
4          0904KJS              0              0              0
5          0905SLR              0              0              0

Nombre total de candidats : 6
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0901SMR
 - 0903DJS
 - 0902SIS
 - 0904KJS
 - 0905SLR

======================================================================
Analyse globale – Feuille : CERCA

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0401BDS              0              0              0
1           0402TFR              2              2              2
2           0404DER              0              0              0
3           0405RCR              0              0              0
4           0406BBS              0              0              0
5           0407HMS              2              2              2
6           0408SJS              0              0              0
7           0409HCR              0              0              0
8           0410FMS              0              0              0
9           0411NPR              2              2              2
10          0412CMS              1              0              0
11          0413MMR              0              0              0
12          0414PVR              0              0              0
13          0415HJS              1              0              0
14          0416CPR              2              2              2
15          0417FAS              1              0              0
16          0417KMS              1              0              0
17          0418MPR              0              0              0
18          0418TJR              1              2              2
19          0419CHR              1              0              0
20          0419SRR              1              2              2
21          0420MCR              0              0              0
22          0420LMR              1              2              2
23          0421ACS              1              0              0
24          0422LVR              1              0              0
25          0422WCS              1              2              0
26          0423SVS              0              0              0
27          0423RMR              2              2              2
28          0424GMS              1              2              0
29          0424BLR              1              0              0
30          0425CDS              2              0              0
31          0426DGS              2              2              2
32          0432CGS              0              2              2
33          0433RMR              2              0              0
34          0434GPS              2              0              0
35          0809VJR              1              2              0
36          0810LCR              2              2              2
37          0812DMS              2              0              0
38          0813PJS              2              0              0
39          0811MCS              2              0              0

Nombre total de candidats : 40
Candidats VALIDES (selon Condition) : 12
Candidats REJETÉS : 28

Liste des candidats valides :
 - 0401BDS
 - 0404DER
 - 0405RCR
 - 0406BBS
 - 0408SJS
 - 0409HCR
 - 0410FMS
 - 0413MMR
 - 0414PVR
 - 0418MPR
 - 0420MCR
 - 0423SVS

In [11]:
total_valides = sum(
    res["n_valides"] for res in resultats_globaux.values()
)

print("=" * 70)
print(f"✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : {total_valides}")

======================================================================
✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : 143

# 143 candidats retenus

# Recherche des candidats et téléchargement de leur fichier EDA V4

In [12]:
import pandas as pd

# Afficher toutes les lignes
pd.set_option('display.max_rows', None)

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

# Afficher toute la largeur de chaque colonne
pd.set_option('display.max_colwidth', None)

## APHM

In [13]:
# ===== Racine des patients =====
racine_aphm = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"

# ===== Candidats valides =====
candidats_aphm = [c.upper() for c in resultats_globaux["APHM"]["valides"]]

rows = []

for root, dirs, files in os.walk(racine_aphm):

    if not any("V4" in d.upper() for d in root.split(os.sep)):
        continue

    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper(): 
            continue

        chemin = os.path.join(root, f)

        # ===== Numero_inclusion = dossier juste après la racine =====
        rel_path = os.path.relpath(chemin, racine_aphm)
        parts = rel_path.split(os.sep)
        pid_trouve = parts[0].upper()

        if pid_trouve not in candidats_aphm:
            continue

        # ===== Timestamp Unix (dossier juste avant EDA.csv) =====
        folder = os.path.basename(os.path.dirname(chemin))
        timestamp_match = re.match(r"(\d+)_", folder)
        timestamp_unix = int(timestamp_match.group(1)) if timestamp_match else None

        # ===== Conversion Unix → date locale =====
        date_eda = datetime.datetime.fromtimestamp(timestamp_unix) if timestamp_unix else None

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille": "APHM",
            "Timestamp_unix": timestamp_unix,
            "Date_eda": date_eda
        })

# ===== DataFrame =====
df_aphm = pd.DataFrame(rows, columns=["Numero_inclusion", "Chemin", "Feuille", "Timestamp_unix", "Date_eda"])

# ===== Suppression des doublons =====
if not df_aphm.empty:
    df_aphm_final = (
        df_aphm
        .assign(priorite_montre=df_aphm["Chemin"].str.contains("MONTRE", case=False))
        .sort_values(["Numero_inclusion", "priorite_montre"], ascending=[True, False])
        .drop_duplicates(subset="Numero_inclusion", keep="first")
        .drop(columns="priorite_montre")
        .reset_index(drop=True)
    )
else:
    df_aphm_final = df_aphm.copy()

print(f"Candidats attendus APHM : {len(candidats_aphm)}")
print(f"Fichiers EDA APHM V2 retenus : {len(df_aphm_final)}")

display(df_aphm_final)

Candidats attendus APHM : 14
Fichiers EDA APHM V2 retenus : 14

,Numero_inclusion,Chemin,Feuille,Timestamp_unix,Date_eda
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 04-04-2019 V4\Montre 0101CAR\1554360113_A01093\EDA.csv,APHM,1.554360e+09,2019-04-04 08:41:53
1,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 12-04-2019 V4\Montre 0102PCR\1555052819_A01093\EDA.csv,APHM,1.555053e+09,2019-04-12 09:06:59
2,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 08-11-2019 V4\Montre 0104FJS\1573198120_A01093\EDA.csv,APHM,1.573198e+09,2019-11-08 08:28:40
3,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 09-09-2019 V4\Montre 0105PNR\1568012045_A01093\EDA.csv,APHM,1.568012e+09,2019-09-09 08:54:05
4,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 17-10-2019 V4\Montre 0107DSS\1571296181_A01093\EDA.csv,APHM,1.571296e+09,2019-10-17 09:09:41
5,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 21-11-2019 V4\Montre 0110LPR\1574323503_A01093\EDA.csv,APHM,1.574324e+09,2019-11-21 09:05:03
6,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 22-11-2019 V4\Montre 0111MNR\1574410699_A01093\EDA.csv,APHM,1.574411e+09,2019-11-22 09:18:19
7,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR - V4\V4\montre\1583397568_A01093\EDA.csv,APHM,1.583398e+09,2020-03-05 09:39:28
8,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS_V4\montre\EDA.csv,APHM,NaN,NaT
9,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR_v4\montre\1591255686_A01093\EDA.csv,APHM,1.591256e+09,2020-06-04 09:28:06
10,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS_v4\MONTRE\MONTRE_0119LJS\EDA.csv,APHM,NaN,NaT
11,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR_v4_e\MONTRE\montre_0121MJR_v4\EDA.csv,APHM,NaN,NaT
12,0122BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0122BDS\0122BDS_V4\MONTRE\0122BDS_V4\EDA.csv,APHM,NaN,NaT
13,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS_V4\MONTRE\0123RMS_V4\EDA.csv,APHM,NaN,NaT

## CAEN

In [14]:
# ===== Racine CAEN =====
racine_caen = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN"

# ===== Liste candidats valides =====
candidats_caen = [
    c.upper().replace(" ", "")
    for c in resultats_globaux["CAEN"]["valides"]
]

# =========================================================
# PATHS FORCÉS pour 3 candidats 
# =========================================================

paths_forces = {
    "0346GLS":r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1666942984_A012950346GLS\EDA.csv",
    "0345LAR" : r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1667550736_A012950345LAR\EDA.csv",
    "0322RMS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1595319263_A012950322RMS\EDA.csv",
    # 0308RGR mal nommé 0308GRR dans l'arborescence
    "0308RGR": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1599030387_A01295 0308GRR\EDA.csv",

    # Inversion dossiers 0342 / 0343
    "0342VNS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1646730228_A01295 0343PAS\EDA.csv",
    "0343PAS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1648798691_A01295 0342VNS\EDA.csv",
}

# ===== DataFrame Excel V4 =====
df_excel_caen = df["CAEN"][["Numero_inclusion", "Date_v4"]].copy()
df_excel_caen["Numero_inclusion"] = (
    df_excel_caen["Numero_inclusion"]
    .str.upper()
    .str.strip()
)

df_excel_caen["Date_v4"] = pd.to_datetime(
    df_excel_caen["Date_v4"],
    dayfirst=True,
    errors="coerce"
).dt.date

# ===== Dictionnaire Numero_inclusion -> date =====
dict_date_v4 = dict(zip(
    df_excel_caen["Numero_inclusion"],
    df_excel_caen["Date_v4"]
))

rows = []

for pid, chemin in paths_forces.items():

    if not os.path.exists(chemin):
        print(f"⚠️ Path forcé introuvable : {chemin}")
        continue

    folder = os.path.basename(os.path.dirname(chemin))
    match = re.match(r"(\d+)_A\d+", folder)

    timestamp_unix = int(match.group(1)) if match else None

    date_eda = (
        datetime.datetime.fromtimestamp(timestamp_unix).date()
        if timestamp_unix else None
    )

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin,
        "Feuille" : "CAEN",
        "Timestamp_unix": timestamp_unix,
        "Date_eda": date_eda,
        "Date_v4_excel": dict_date_v4.get(pid)
    })

print("✔ Fichiers forcés ajoutés")

# =========================================================
# Regex Numero_inclusion
# =========================================================

patterns_candidats = {
    pid: re.compile(rf"\b{pid}\b", re.IGNORECASE)
    for pid in candidats_caen
    if pid not in paths_forces
}


for root, dirs, files in os.walk(racine_caen):

    for f in files:

        if not f.lower().endswith(".csv"):
            continue

        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)

        pid_trouve = None
        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        folder = os.path.basename(os.path.dirname(chemin))
        match = re.match(r"(\d+)_A\d+", folder)

        timestamp_unix = int(match.group(1)) if match else None

        date_eda = (
            datetime.datetime.fromtimestamp(timestamp_unix).date()
            if timestamp_unix else None
        )

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille" : "CAEN",
            "Timestamp_unix": timestamp_unix,
            "Date_eda": date_eda,
            "Date_v4_excel": dict_date_v4.get(pid_trouve)
        })

# =========================================================
# DATAFRAME
# =========================================================

df_caen = pd.DataFrame(rows)

# =========================================================
# SUPPRESSION DES DOUBLONS
# =========================================================

if not df_caen.empty:

    def choisir_meilleur_fichier(groupe):

        date_excel = groupe["Date_v4_excel"].iloc[0]

        if pd.isna(date_excel):
            return groupe.iloc[0]

        groupe = groupe.copy()

        groupe["ecart_jours"] = (
            pd.to_datetime(groupe["Date_eda"]) -
            pd.to_datetime(date_excel)
        ).abs().dt.days

        exact = groupe[groupe["Date_eda"] == date_excel]
        if not exact.empty:
            return exact.iloc[0]

        return groupe.sort_values("ecart_jours").iloc[0]

    df_caen_final = (
        df_caen
        .groupby("Numero_inclusion", as_index=False)
        .apply(choisir_meilleur_fichier)
        .reset_index(drop=True)
    )

else:
    df_caen_final = df_caen.copy()

# =========================================================
# FILTRE SUR LA DATE
# =========================================================

# convertion en datetime.date
df_caen_final["Date_eda"] = pd.to_datetime(df_caen_final["Date_eda"]).dt.date
df_caen_final["Date_v4_excel"] = pd.to_datetime(df_caen_final["Date_v4_excel"]).dt.date

df_caen_final = df_caen_final[
    df_caen_final["Date_eda"] == df_caen_final["Date_v4_excel"]
].copy()

# =========================================================
# AFFICHAGE
# =========================================================

print(f"\nCandidats attendus CAEN : {len(candidats_caen)}")
print(f"Fichiers EDA CAEN V4 retenus après filtrage exact : {len(df_caen_final)}")

display(df_caen_final)

candidats_trouves = set(df_caen_final["Numero_inclusion"])
candidats_manquants = sorted(set(candidats_caen) - candidats_trouves)

if candidats_manquants:
    print("\n⚠️ Candidats manquants après filtrage :")
    for c in candidats_manquants:
        print(" -", c)
else:
    print("\n✅ Tous les candidats ont été trouvés après filtrage")

✔ Fichiers forcés ajoutés

Candidats attendus CAEN : 37
Fichiers EDA CAEN V4 retenus après filtrage exact : 36

C:\Users\judupont\AppData\Local\Temp\ipykernel_22300\525280060.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_excel_caen["Date_v4"] = pd.to_datetime(
C:\Users\judupont\AppData\Local\Temp\ipykernel_22300\525280060.py:174: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(choisir_meilleur_fichier)

,Numero_inclusion,Chemin,Feuille,Timestamp_unix,Date_eda,Date_v4_excel,ecart_jours
0,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1571731715_A01295 0302ZMR\EDA.csv,CAEN,1571731715,2019-10-22,2019-10-22,0
1,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1579856234_A01295 0304VMR\EDA.csv,CAEN,1579856234,2020-01-24,2020-01-24,0
2,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1579769470_A01295 0305LCR\EDA.csv,CAEN,1579769470,2020-01-23,2020-01-23,0
3,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1590395693_A01295 0307SMR\EDA.csv,CAEN,1590395693,2020-05-25,2020-05-25,0
4,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1599030387_A01295 0308GRR\EDA.csv,CAEN,1599030387,2020-09-02,2020-09-02,0
5,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1589787562_A01295 0310ACS\EDA.csv,CAEN,1589787562,2020-05-18,2020-05-18,0
6,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1592377927_A01295 0311CJS\EDA.csv,CAEN,1592377927,2020-06-17,2020-06-17,0
7,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591603371_A01295 0313FPR\EDA.csv,CAEN,1591603371,2020-06-08,2020-06-08,0
8,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591861453_A01295 0315VCS\EDA.csv,CAEN,1591861453,2020-06-11,2020-06-11,0
9,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591084669_A01295 0316TMS\EDA.csv,CAEN,1591084669,2020-06-02,2020-06-02,0
10,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591258701_A01295 0317LGS\EDA.csv,CAEN,1591258701,2020-06-04,2020-06-04,0
11,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1593071627_A01295 0319LJS\EDA.csv,CAEN,1593071627,2020-06-25,2020-06-25,0
12,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1594108662_A01295 0321DRR\EDA.csv,CAEN,1594108662,2020-07-07,2020-07-07,0
13,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1595319263_A012950322RMS\EDA.csv,CAEN,1595319263,2020-07-21,2020-07-21,0
14,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1598513134_A01295 0323RFS\EDA.csv,CAEN,1598513134,2020-08-27,2020-08-27,0
15,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1598345471_A01295 0324LMR\EDA.csv,CAEN,1598345471,2020-08-25,2020-08-25,0
17,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1604393467_A01295 0329NMR\EDA.csv,CAEN,1604393467,2020-11-03,2020-11-03,0
18,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1610959444_A01295 0330RTR\EDA.csv,CAEN,1610959444,2021-01-18,2021-01-18,0
19,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1606467065_A01295 0331GRS\EDA.csv,CAEN,1606467065,2020-11-27,2020-11-27,0
20,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1624606133_A01295 0333MMS\EDA.csv,CAEN,1624606133,2021-06-25,2021-06-25,0
21,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1624955329_A01295 0334TVS\EDA.csv,CAEN,1624955329,2021-06-29,2021-06-29,0
22,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1630655430_A01295 0337BFS\EDA.csv,CAEN,1630655430,2021-09-03,2021-09-03,0
23,0338JBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1634887870_A01295 0338JBS\EDA.csv,CAEN,1634887870,2021-10-22,2021-10-22,0
24,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1638449112_A01295 0339NPR\EDA.csv,CAEN,1638449112,2021-12-02,2021-12-02,0
25,0340BAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1639485951_A01295 0340BAR\EDA.csv,CAEN,1639485951,2021-12-14,2021-12-14,0
26,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1644915087_A01295 0341LJS\EDA.csv,CAEN,1644915087,2022-02-15,2022-02-15,0
27,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1646730228_A01295 0343PAS\EDA.csv,CAEN,1646730228,2022-03-08,2022-03-08,0
28,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1648798691_A01295 0342VNS\EDA.csv,CAEN,1648798691,2022-04-01,2022-04-01,0
29,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1667550736_A012950345LAR\EDA.csv,CAEN,1667550736,2022-11-04,2022-11-04,0
30,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1666942984_A012950346GLS\EDA.csv,CAEN,1666942984,2022-10-28,2022-10-28,0
31,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1668760658_A01295 0347DMR\EDA.csv,CAEN,1668760658,2022-11-18,2022-11-18,0
32,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1668501119_A01295 0348GCR\EDA.csv,CAEN,1668501119,2022-11-15,2022-11-15,0
33,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1670920566_A01295 0350MYR\EDA.csv,CAEN,1670920566,2022-12-13,2022-12-13,0
34,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1672909097_A01295 0351FIR\EDA.csv,CAEN,1672909097,2023-01-05,2023-01-05,0
35,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1673513100_A01295 0352RNR\EDA.csv,CAEN,1673513100,2023-01-12,2023-01-12,0
36,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1687245889_A01295 0356DMS\EDA.csv,CAEN,1687245889,2023-06-20,2023-06-20,0

⚠️ Candidats manquants après filtrage :
 - 0328MPR

## POITIERS

In [16]:
# ===== Racine POITIERS =====
racine_poitiers = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY"

# ===== Candidats valides =====
candidats_poitiers = [
    c.upper().replace(" ", "")
    for c in resultats_globaux["POITIERS"]["valides"]
]

# ===== Regex POITIERS =====
# ex : 0401TSS → match "0401 TS"
patterns_candidats = {
    pid: re.compile(
        rf"{pid[:4]}\s*-?\s*{pid[4:6]}",
        re.IGNORECASE
    )
    for pid in candidats_poitiers
}

fichiers_par_candidat = defaultdict(list)

for root, dirs, files in os.walk(racine_poitiers):

    if "V4" not in root.upper():
        continue

    for f in files:
        if f.upper() != "EDA.CSV":
            continue

        chemin = os.path.join(root, f)

        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                fichiers_par_candidat[pid].append(chemin)
                break

rows = []

for pid, fichiers in fichiers_par_candidat.items():

    fichiers = sorted(set(fichiers))  # sécurité doublons exacts

    # priorité MONTRE (logique équivalente à CEINTURE)
    montre = [f for f in fichiers if "montre" in f.lower()]
    chemin_final = montre[0] if montre else fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Feuille": "POITIERS"
    })

df_poitiers_final = pd.DataFrame(rows)

# ===== Affichage =====
print(f"Candidats attendus POITIERS : {len(candidats_poitiers)}")
print(f"Fichiers EDA POITIERS V2 retenus : {len(df_poitiers_final)}")

manquants = sorted(
    set(candidats_poitiers) - set(df_poitiers_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats POITIERS sont présents")

display(df_poitiers_final)

Candidats attendus POITIERS : 12
Fichiers EDA POITIERS V2 retenus : 10
⚠️ Candidats manquants : ['0414PJS', '0415VMR']

,Numero_inclusion,Chemin,Feuille
0,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V4\0401TSS - montre V4\1578646774_A012C6\EDA.csv,POITIERS
1,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS-V4\0402LLS -montre V4\EDA.csv,POITIERS
2,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V4\0403DCR - montre V4\EDA.csv,POITIERS
3,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404YCS-V4\0404YC-montre V4\EDA.csv,POITIERS
4,0406MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0406 MC\0406MCS-V4\0406MC -montre V4\EDA.csv,POITIERS
5,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V4\0407LJ-montre V4\EDA.csv,POITIERS
6,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC-V4\0408BC-montre V4\1596702371_A012C6\EDA.csv,POITIERS
7,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V4\0411VE-montre V4\EDA.csv,POITIERS
8,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V4\0412ANS-V4\EDA.csv,POITIERS
9,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS V4\0413HFS montre V4\EDA.csv,POITIERS

## ROUEN

In [18]:
# ===== Racine ROUEN =====
racine_rouen = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER"

# ===== Candidats valides =====
candidats_rouen = [c.upper() for c in resultats_globaux["ROUEN"]["valides"]]


# ===== Patterns candidats : 05-09, 05-11, etc =====
patterns_candidats = {
    pid: re.compile(rf"\b{pid[:2]}-{pid[2:4]}\b", re.IGNORECASE)
    for pid in candidats_rouen
}

rows = []

# ===== Parcours fichiers =====
for root, dirs, files in os.walk(racine_rouen):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue

        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        pid_trouve = None
        for pid, pat in patterns_candidats.items():
            if pat.search(chemin_upper):
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille": "ROUEN"
        })

# ===== DataFrame =====
df_rouen_final = pd.DataFrame(rows)

# ===== Suppression des doublons =====
df_rouen_final = (
    df_rouen_final
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# ===== Affichage =====
print(f"Candidats attendus ROUEN : {len(candidats_rouen)}")
print(f"Fichiers EDA ROUEN V2 retenus : {len(df_rouen_final)}")

manquants = sorted(set(candidats_rouen) - set(df_rouen_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats ROUEN manquants :", manquants)
else:
    print("✅ Tous les candidats ROUEN sont présents")

display(df_rouen_final)

Candidats attendus ROUEN : 13
Fichiers EDA ROUEN V2 retenus : 12
⚠️ Candidats ROUEN manquants : ['0509LGS']

,Numero_inclusion,Chemin,Feuille
0,0501MBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-01-MB-S\V4\MONTRE\1574064476_A012E9\EDA.csv,ROUEN
1,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V4\MONTRE\EDA.csv,ROUEN
2,0503LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-03-LC-R\V4\MONTRE\1579767764_A012E9\EDA.csv,ROUEN
3,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V4\MONTRE V4\EDA.csv,ROUEN
4,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V4\MONTRE\EDA.csv,ROUEN
5,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V4\MONTRE\EDA.csv,ROUEN
6,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V4\MONTRE\1589267765_A012E9 (2)\EDA.csv,ROUEN
7,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V4\MONTRE\EDA.csv,ROUEN
8,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V4\MONTRE\EDA.csv,ROUEN
9,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V4\MONTRE\1647332236_A012E9\EDA.csv,ROUEN
10,0514LPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-14-LP-S\V4\MONTRE\EDA.csv,ROUEN
11,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V4\MONTRE\EDA.csv,ROUEN

## LAVERAN

In [20]:
# ===== Racine LAVERAN =====
racine_laveran = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"
)

# ===== Candidats attendus =====
candidats_laveran = [c.upper() for c in resultats_globaux["LAVERAN"]["valides"]]

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_laveran):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)

        # ===== Numero_inclusion = 1er dossier après la racine =====
        rel_path = os.path.relpath(chemin, racine_laveran)
        pid = rel_path.split(os.sep)[0].upper()

        if pid not in candidats_laveran:
            continue

        rows.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "LAVERAN"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_laveran = pd.DataFrame(rows)

df_laveran_final = (
    df_laveran
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LAVERAN : {len(candidats_laveran)}")
print(f"Fichiers EDA LAVERAN retenus : {len(df_laveran_final)}")

manquants = sorted(
    set(candidats_laveran) - set(df_laveran_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LAVERAN manquants :", manquants)
else:
    print("✅ Tous les candidats LAVERAN sont présents")

display(df_laveran_final)

OK [0626MCS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V4\0626MCS_v4\MONTRE\1603959501_A01093\EDA.csv
OK [0629TCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\0629TCR_V4\MONTRE\1605603058_A01093\EDA.csv
OK [0630RJR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V4\MONTRE\1605517689_A01093\EDA.csv
OK [0631LHR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\0631LHR_V4\MONTRE\1605688444_A01093\EDA.csv

====================================
Candidats attendus LAVERAN : 4
Fichiers EDA LAVERAN retenus : 4
✅ Tous les candidats LAVERAN sont présents

,Numero_inclusion,Chemin,Feuille
0,0626MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V4\0626MCS_v4\MONTRE\1603959501_A01093\EDA.csv,LAVERAN
1,0629TCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\0629TCR_V4\MONTRE\1605603058_A01093\EDA.csv,LAVERAN
2,0630RJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V4\MONTRE\1605517689_A01093\EDA.csv,LAVERAN
3,0631LHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\0631LHR_V4\MONTRE\1605688444_A01093\EDA.csv,LAVERAN

## LPC

In [21]:
# ===== Racine LPC =====
racine_lpc = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LNSC\DESHAYES\DESHAYES\DATA_Aging"
)

# ===== Candidats attendus =====
candidats_lpc = [c.upper() for c in resultats_globaux["LPC"]["valides"]]

# ===== CORRECTIONS MANUELLES ARBORESCENCE → EXCEL =====
CORRESPONDANCE_IDS = {
    "0117MSR": "0117MMR"  
}
CORRESPONDANCE_INVERSE = {v: k for k, v in CORRESPONDANCE_IDS.items()}

# ===== PATHS FORCÉS =====
paths_forces = {
    "0130FAR": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\Marseille_LABO_08decembre2020\DATA_Aging_08decembre2020\0154FAR\V4\0130FAR\montre\1581410797_A01115.zip"
}

rows = []

# =========================================================
# AJOUT DES FICHIERS FORCÉS 
# =========================================================
for pid, chemin in paths_forces.items():

    if not os.path.exists(chemin):
        print(f"⚠️ Path forcé introuvable : {chemin}")
        continue

    chemin_final = chemin  # par défaut

    # 🔥 Si c'est un ZIP → on extrait le premier EDA.csv
    if chemin.lower().endswith(".zip"):
        try:
            with zipfile.ZipFile(chemin, 'r') as zf:

                eda_files = [
                    name for name in zf.namelist()
                    if "EDA" in name.upper() and name.lower().endswith(".csv")
                ]

                if not eda_files:
                    print(f"❌ Aucun EDA trouvé dans {chemin}")
                    continue

                eda_name = eda_files[0]

                dossier_extraction = os.path.dirname(chemin)
                zf.extract(eda_name, dossier_extraction)

                chemin_final = os.path.join(dossier_extraction, eda_name)

                print(f"✅ ZIP extrait pour {pid} → {chemin_final}")

        except zipfile.BadZipFile:
            print(f"❌ ZIP corrompu : {chemin}")
            continue

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Feuille": "LPC"
    })

print("✔ Fichiers forcés ajoutés")

# =========================================================
# BOUCLE PRINCIPALE 
# =========================================================
for root, dirs, files in os.walk(racine_lpc):

    if "V4" not in root.upper():
        continue

    for f in files:

        # ===== EDA uniquement =====
        if not f.lower().endswith(".csv") and not f.lower().endswith(".zip"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)

        rel_path = os.path.relpath(chemin, racine_lpc)
        pid_arbo = rel_path.split(os.sep)[0].upper()
        pid_excel = CORRESPONDANCE_INVERSE.get(pid_arbo, pid_arbo)

        if pid_excel not in candidats_lpc:
            continue

        if pid_excel in paths_forces:
            continue

        rows.append({
            "Numero_inclusion": pid_excel,
            "Chemin": chemin,
            "Feuille": "LPC"
        })

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_lpc_final = (
    pd.DataFrame(rows)
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LPC : {len(candidats_lpc)}")
print(f"Fichiers EDA LPC retenus : {len(df_lpc_final)}")

manquants = sorted(set(candidats_lpc) - set(df_lpc_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC sont présents")

display(df_lpc_final)

✅ ZIP extrait pour 0130FAR → C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\Marseille_LABO_08decembre2020\DATA_Aging_08decembre2020\0154FAR\V4\0130FAR\montre\EDA.csv
✔ Fichiers forcés ajoutés

====================================
Candidats attendus LPC : 39
Fichiers EDA LPC retenus : 27
⚠️ Candidats LPC manquants : ['0106DJR', '0132GAR', '0133BPS', '0136CJR', '0137BMS', '0138NWR', '0139BMR', '0140LMR', '0141HJR', '0142LLS', '0143EBR', '0144ZGR']

,Numero_inclusion,Chemin,Feuille
0,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\0101EMS V4\Montre\1571730172_A01115\EDA.csv,LPC
1,0102EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0102EMS\V4 0102EMS\Montre\1567668999_A01115\EDA.csv,LPC
2,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V4 0103BPS\Montre\1568706200_A01115\EDA.csv,LPC
3,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V4 0104IBS\Montre\EDA.csv,LPC
4,0107LER,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0107LER\V4 0107LER\Montre\1567584597_A01115\EDA.csv,LPC
5,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V4\Montre\1571900786_A01115\EDA.csv,LPC
6,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V4\Montre\1568360086_A01115\EDA.csv,LPC
7,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V4\Montre\1568619102_A01115\EDA.csv,LPC
8,0111TAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0111TAS\V4\Montre\1570087686_A01115\EDA.csv,LPC
9,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V4\Montre\1573029333_A01115\EDA.csv,LPC
10,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V4\montre\1566891799_A01115\EDA.csv,LPC
11,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\0114MLR V4\Montre\1571128491_A01115\EDA.csv,LPC
12,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V4\Montre\1570605904_A01115\EDA.csv,LPC
13,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V4\Montre\1570173945_A01115\EDA.csv,LPC
14,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V4\Montre\1570778826_A01115\EDA.csv,LPC
15,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V4\Montre\1571205473_A01115\EDA.csv,LPC
16,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V4\Montre\1572252531_A01115\EDA.csv,LPC
17,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V4\Montre\1574153203_A01115\EDA.csv,LPC
18,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V4\Montre\1571816051_A01115\EDA.csv,LPC
19,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V4\Montre\1572941907_A01115\EDA.csv,LPC
20,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V4\Montre\1573201375_A01115\EDA.csv,LPC
21,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V4\Montre\1573806435_A01115\EDA.csv,LPC
22,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V4\Montre\1575273925_A01115\EDA.csv,LPC
23,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V4\Montre\1574325279_A01115\EDA.csv,LPC
24,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V4\Montre\1576053205_A01115\EDA.csv,LPC
25,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V4\Montre\1576658477_A01115\EDA.csv,LPC
26,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\Marseille_LABO_08decembre2020\DATA_Aging_08decembre2020\0154FAR\V4\0130FAR\montre\EDA.csv,LPC

In [22]:
# ===== Racines =====
racines = [
    r"C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire",
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo"
]

# ===== Candidats LPC partie 2 =====
candidats_lpc2 = [
    c.upper() for c in resultats_globaux["LPC"]["valides"][28:]
]

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for racine in racines:

    print(f"\n--- Scan de : {racine}")

    for root, dirs, files in os.walk(racine):

        root_upper = root.upper()

        if not re.search(r'(^|[^A-Z0-9])V4([^A-Z0-9]|$)', root_upper):
            continue

        if "MONTRE" not in root_upper:
            continue

        for f in files:

            if f.upper() != "EDA.CSV":
                continue
            chemin = os.path.join(root, f)
            chemin_upper = chemin.upper()
            pid_trouve = None
            for c in candidats_lpc2:
                if c in chemin_upper:
                    pid_trouve = c
                    break

            if not pid_trouve:
                print("❌ PID NON TROUVÉ :", chemin)
                continue

            # =================================================
            # DEBUG TEMPS : UNIX (dossier) vs DATE fichier
            # =================================================
            dossier_parent = os.path.basename(os.path.dirname(chemin))
            ts_unix = None
            date_unix_str = "None"

            if "_" in dossier_parent:
                try:
                    ts_unix = int(dossier_parent.split("_")[0])
                    date_unix_str = datetime.datetime.fromtimestamp(
                        ts_unix
                    ).strftime("%Y-%m-%d %H:%M:%S")
                except Exception:
                    pass

            date_fichier_str = datetime.datetime.fromtimestamp(
                os.path.getmtime(chemin)
            ).strftime("%Y-%m-%d %H:%M:%S")

            rows.append({
                "Numero_inclusion": pid_trouve,
                "Chemin": chemin,
                "Feuille": "LPC",
                "Timestamp_unix": ts_unix,
                "Date_unix_path": date_unix_str,
                "Date_modif_csv": date_fichier_str
            })

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
print("\nDEBUG rows length :", len(rows))

if rows:
    df_lpc2_final = (
        pd.DataFrame(rows)
        .sort_values("Chemin")
        .drop_duplicates(subset="Numero_inclusion", keep="first")
        .reset_index(drop=True)
    )
else:
    df_lpc2_final = pd.DataFrame(
        columns=["Numero_inclusion", "Chemin", "Feuille", "Timestamp_unix", "Date_unix_path", "Date_modif_csv"]
    )

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus LPC (partie 2) : {len(candidats_lpc2)}")
print(f"Fichiers EDA retenus              : {len(df_lpc2_final)}")

manquants = sorted(
    set(candidats_lpc2) - set(df_lpc2_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC partie 2 sont présents")

display(df_lpc2_final)

--- Scan de : C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire

--- Scan de : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0101EMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0101EMS\V4\Montre\1571730172_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0102BJS\V4 0102BJS\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0103EMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0103EMS\V4\Montre\1567668999_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0105AER\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0105AER\V4\Montre\1567496349_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0107GLS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0107GLS\V4\Montre\1571038588_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0108BPS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0108BPS\V4\Montre\1568706200_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0109IBS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0109IBS\V4\Montre\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0110HAR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0110HAR\V4\Montre\1567149936_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0112LER\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0112LER\V4\Montre\1567584597_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0113MMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0113MMS\V4\Montre\1571900786_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0114MJR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0114MJR\V4\Montre\1568360086_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0115RMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0115RMS\V4\Montre\1568619102_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0116TAS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0116TAS\V4\Montre\1570087686_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0117DRR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0117DRR\V4\Montre\1573029333_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0118DGR\V4\montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0118DGR\V4\montre\1566891799_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0119MLR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0119MLR\V4\Montre\1571128491_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0120MHR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0120MHR\V4\Montre\1570605904_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0121CNR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0121CNR\V4\Montre\1570173945_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0122MMR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0122MMR\V4\Montre\1570778826_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0123TMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0123TMS\V4\Montre\1571205473_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0124BIR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0124BIR\V4\Montre\1572252531_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0125BMR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0125BMR\V4\Montre\1571383836_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0126ANS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0126ANS\V4\Montre\1574153203_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0127RPS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0127RPS\V4\Montre\1571816051_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0128VCR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0128VCR\V4\Montre\1572941907_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0129GVS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0129GVS\V4\Montre\1573201375_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V4\0130FAR\montre\1581410797_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131CPS0156CPS\0131CPS_v4\MONTRE\1603095182_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131PAS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0131PAS\V4\Montre\1573806435_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132AMR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132AMR\V4\Montre\1573115568_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133VLR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133VLR\V4\Montre\1575273925_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\0162IFR_V4\montre\1612947443_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134TMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134TMS\V4\Montre\1576225980_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135FCS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135FCS\V4\Montre\1574064706_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136SAS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136SAS\V4\Montre\1573548151_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137CMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137CMS\V4\Montre\1574325279_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138RMR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138RMR\V4\Montre\1574239023_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0139LCR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0139LCR\V4\Montre\1573634552_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0140MMS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0140MMS\V4\Montre\1574756891_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0141ACR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0141ACR\V4\Montre\1574671088_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0142NFR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0142NFR\V4\Montre\1574929883_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0143BCR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0143BCR\V4\Montre\1575362239_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144SNS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144SNS\V4\Montre\1578557790_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0145GPR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0145GPR\V4\Montre\1576832811_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0146CAR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0146CAR\V4\Montre\1576743263_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0147ALS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0147ALS\V4\Montre\1576053205_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0148APR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0148APR\V4\Montre\1576658477_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0149CAS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0149CAS\V4\Montre\1575015791_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0151SSS\V4\montre\1580718759_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0151SSS\V4\montre\1580718759_A01115 (1)\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0152RER\V4\montre\1580822144_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0152RER\V4\montre\1580822144_A01115 (1)\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0153RDS\V4\montre\1581948895_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0154FAR\V4\0130FAR\montre\1581410797_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0155CPR\0155CPR_v4\MONTRE\1603356247_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0155CPR\V4\MONTRE\1603356247_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0156CPS\V4\MONTRE\1603095182_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0161MAS\0161MAS_V4\montre\1613034351_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0165BMS\V4\Montre\1637312131_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0169HJR\0169HJR V4\montre\1676279708_A01115\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0170LLS\0170LLS V4\montre\1681459588_A01115\EDA.csv

DEBUG rows length : 7

====================================
Candidats attendus LPC (partie 2) : 11
Fichiers EDA retenus              : 7
⚠️ Candidats LPC manquants : ['0137BMS', '0139BMR', '0141HJR', '0142LLS']

,Numero_inclusion,Chemin,Feuille,Timestamp_unix,Date_unix_path,Date_modif_csv
0,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\0132GAR_V4\montre\1612774878_A01093\EDA.csv,LPC,1612774878,2021-02-08 10:01:18,2026-02-19 10:52:52
1,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\0157BPS_V4\montre\1612860803_A01115\EDA.csv,LPC,1612860803,2021-02-09 09:53:23,2026-02-19 10:52:52
2,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR_V4\Montre\1639127858_A01115\EDA.csv,LPC,1639127858,2021-12-10 10:17:38,2026-02-19 10:52:53
3,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V4\montre\1649059272_A01115\EDA.csv,LPC,1649059272,2022-04-04 10:01:12,2026-02-19 10:52:53
4,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V4\montre\1681200504_A01115\EDA.csv,LPC,1681200504,2023-04-11 10:08:24,2026-02-19 10:52:54
5,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V4 0140LMR\montre\1676451829_A01115\EDA.csv,LPC,1676451829,2023-02-15 10:03:49,2026-02-19 10:52:56
6,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR_V4\montre\1682409900_A01115\EDA.csv,LPC,1682409900,2023-04-25 10:05:00,2026-02-19 10:52:57

## SAINTE-MARGUERITE

In [24]:
# ===== Racine Sainte-Marguerite =====
racine_sm = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite"

# ===== Candidats attendus =====
candidats_sm = [c.upper() for c in resultats_globaux["SAINTE-MARGUERITE"]["valides"]]

# ===== Liste pour stocker les fichiers EDA =====
rows = []

# =========================================================
# BOUCLE SUR LES ZIP
# =========================================================
for root, dirs, files in os.walk(racine_sm):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".zip"):
            continue

        chemin_zip = os.path.join(root, f)

        try:
            pid_trouve = root.split(os.sep)[-3].upper()
        except IndexError:
            print(f"❌ Structure inattendue : {chemin_zip}")
            continue

        if pid_trouve not in candidats_sm:
            print(f"❌ PID NON ATTENDU : {pid_trouve}")
            continue

        # =====================================================
        # Dézipper dans le dossier du ZIP lui-même
        # =====================================================
        try:
            with zipfile.ZipFile(chemin_zip, 'r') as zf:

                eda_files = [
                    name for name in zf.namelist()
                    if "EDA" in name.upper() and name.lower().endswith(".csv")
                ]

                if not eda_files:
                    print(f"❌ Pas de fichier EDA dans : {chemin_zip}")
                    continue

                for eda_name in eda_files:

                    zf.extract(eda_name, root)
                    eda_path = os.path.join(root, eda_name)

                    rows.append({
                        "Numero_inclusion": pid_trouve,
                        "Chemin": eda_path,
                        "Feuille": "SAINTE-MARGUERITE"
                    })

                    print(f"✅ EDA extrait [{pid_trouve}] :", eda_path)

        except zipfile.BadZipFile:
            print(f"❌ ZIP corrompu : {chemin_zip}")

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_sm = pd.DataFrame(rows)

df_sm = (
    df_sm
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

print(f"\nNombre de fichiers EDA extraits Sainte-Marguerite : {len(df_sm)}")
display(df_sm)

✅ EDA extrait [0801HDR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V4\Montre\EDA.csv
✅ EDA extrait [0802LAS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V4\Montre\EDA.csv
✅ EDA extrait [0803DPS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS-V4\Montre\EDA.csv
✅ EDA extrait [0804GOR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR_V4\Montre\EDA.csv
✅ EDA extrait [0805BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V4\Montre\EDA.csv
✅ EDA extrait [0806KHS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\0806KHS-V4\montre\EDA.csv
✅ EDA extrait [0807OMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V4\montre\EDA.csv
❌ PID NON ATTENDU : 0808PJR

Nombre de fichiers EDA extraits Sainte-Marguerite : 7

,Numero_inclusion,Chemin,Feuille
0,0801HDR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V4\Montre\EDA.csv,SAINTE-MARGUERITE
1,0802LAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V4\Montre\EDA.csv,SAINTE-MARGUERITE
2,0803DPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS-V4\Montre\EDA.csv,SAINTE-MARGUERITE
3,0804GOR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR_V4\Montre\EDA.csv,SAINTE-MARGUERITE
4,0805BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V4\Montre\EDA.csv,SAINTE-MARGUERITE
5,0806KHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\0806KHS-V4\montre\EDA.csv,SAINTE-MARGUERITE
6,0807OMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V4\montre\EDA.csv,SAINTE-MARGUERITE

## CGD

In [26]:
# ===== Racine CGD =====
racine_cgd = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD"
)

# ===== Candidats attendus =====
candidats_cgd = [
    c.upper() for c in resultats_globaux["CGD"]["valides"]
]

rows_cgd = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_cgd):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification =====
        pid = None
        for c in candidats_cgd:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_cgd.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "CGD"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_cgd = pd.DataFrame(rows_cgd)

df_cgd = (
    df_cgd
    .sort_values("Chemin")
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CGD : {len(candidats_cgd)}")
print(f"Fichiers EDA retenus   : {len(df_cgd)}")

manquants = sorted(
    set(candidats_cgd) - set(df_cgd["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CGD sont présents")

display(df_cgd)

OK [0901SMR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0901SMR\0901SMR - V4\Montre\1671008068_A01115\EDA.csv
OK [0902SIS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS-V4\montre\1675242525_A01115\EDA.csv
OK [0903DJS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0903DJS\V4\montre\1678265782_A01115\EDA.csv
OK [0904KJS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS-V4\montre\1679472202_A01115\EDA.csv
OK [0905SLR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V4\montre\1680680968_A01115\EDA.csv

====================================
Candidats attendus CGD : 5
Fichiers EDA retenus   : 5
✅ Tous les candidats CGD sont présents

,Numero_inclusion,Chemin,Feuille
0,0901SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0901SMR\0901SMR - V4\Montre\1671008068_A01115\EDA.csv,CGD
1,0902SIS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS-V4\montre\1675242525_A01115\EDA.csv,CGD
2,0903DJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0903DJS\V4\montre\1678265782_A01115\EDA.csv,CGD
3,0904KJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS-V4\montre\1679472202_A01115\EDA.csv,CGD
4,0905SLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V4\montre\1680680968_A01115\EDA.csv,CGD

## CERCA

In [28]:
# ===== Racine CERCA =====
racine_cerca = r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA"

# ===== Candidats CERCA =====
candidats_cerca = [c.upper() for c in resultats_globaux['CERCA']['valides']]

# ===== Liste pour stocker les fichiers EDA =====
rows = []

# =========================================================
# BOUCLE PRINCIPALE 
# =========================================================
for root, dirs, files in os.walk(racine_cerca):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if "EDA" not in f.upper():
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== Identification =====
        pid_trouve = None
        for c in candidats_cerca:
            if c in chemin_upper:
                pid_trouve = c
                break

        if not pid_trouve:
            print(f"❌ PID NON TROUVÉ : {chemin}")
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille": "CERCA"
        })

        print(f"✅ EDA trouvé [{pid_trouve}] :", chemin)

# =========================================================
# DATAFRAME
# =========================================================
df_cerca_final = pd.DataFrame(rows)
df_cerca_final = df_cerca_final.drop_duplicates(subset="Numero_inclusion", keep="first").reset_index(drop=True)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CERCA : {len(candidats_cerca)}")
print(f"Fichiers EDA retenus CERCA : {len(df_cerca_final)}")

manquants = sorted(set(candidats_cerca) - set(df_cerca_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CERCA sont présents")

display(df_cerca_final)

✅ EDA trouvé [0401BDS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Montre\1573634231_A0117F\EDA.csv
✅ EDA trouvé [0405RCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Montre\EDA.csv
✅ EDA trouvé [0406BBS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0407HMS\V4\Montre\EDA.csv
✅ EDA trouvé [0408SJS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Montre\1574847506_A0117F\EDA.csv
✅ EDA trouvé [0404DER] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Montre\1573202858_A0117F\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0407HMS\V4\Montre\EDA.csv
✅ EDA trouvé [0409HCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Montre\EDA.csv
✅ EDA trouvé [0410FMS] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Montre\EDA.csv
✅ EDA trouvé [0413MMR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0413MMR\V4\Montre\EDA.csv
✅ EDA trouvé [0414PVR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0415HJS\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0419CHR\V4\Montre\EDA.csv
✅ EDA trouvé [0420MCR] : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Montre\EDA.csv
❌ PID NON TROUVÉ : C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0421ACS\V4\Montre\EDA.csv

====================================
Candidats attendus CERCA : 12
Fichiers EDA retenus CERCA : 10
⚠️ Candidats manquants : ['0418MPR', '0423SVS']

,Numero_inclusion,Chemin,Feuille
0,0401BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Montre\1573634231_A0117F\EDA.csv,CERCA
1,0405RCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Montre\EDA.csv,CERCA
2,0406BBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Montre\EDA.csv,CERCA
3,0408SJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Montre\1574847506_A0117F\EDA.csv,CERCA
4,0404DER,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Montre\1573202858_A0117F\EDA.csv,CERCA
5,0409HCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Montre\EDA.csv,CERCA
6,0410FMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Montre\EDA.csv,CERCA
7,0413MMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0413MMR\V4\Montre\EDA.csv,CERCA
8,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Montre\EDA.csv,CERCA
9,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Montre\EDA.csv,CERCA

## CONCATENATION

In [29]:
# ===== Liste des DataFrames par feuille =====
dfs = [
    df_aphm_final,  
    df_caen_final,
    df_poitiers_final,     
    df_rouen_final,
    df_laveran_final,
    df_lpc_final,         
    df_lpc2_final,
    df_sm,          
    df_cgd,         
    df_cerca_final      
]

# ===== Normalisation des colonnes =====
for i, df in enumerate(dfs):
    if "PID" in df.columns:
        df.rename(columns={"PID": "Numero_inclusion"}, inplace=True)
    # Assurer que la colonne Condition existe
    if "Condition" not in df.columns:
        df["Condition"] = None
    # On garde uniquement les colonnes essentielles
    df = df[["Numero_inclusion", "Chemin", "Feuille"]]
    dfs[i] = df

# ===== Concatenation =====
df_global = pd.concat(dfs, ignore_index=True)

# ===== Suppression des doublons par Numero_inclusion =====
df_global = df_global.drop_duplicates(subset=["Numero_inclusion"], keep="first")

# ===== Tri par Numero_inclusion =====
df_global = df_global.sort_values("Numero_inclusion").reset_index(drop=True)

# ===== Résumé =====
print(f"Total candidats uniques : {df_global['Numero_inclusion'].nunique()}")
print(f"Total fichiers conservés : {len(df_global)}")
display(df_global)

Total candidats uniques : 132
Total fichiers conservés : 132

,Numero_inclusion,Chemin,Feuille
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 04-04-2019 V4\Montre 0101CAR\1554360113_A01093\EDA.csv,APHM
1,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\0101EMS V4\Montre\1571730172_A01115\EDA.csv,LPC
2,0102EMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0102EMS\V4 0102EMS\Montre\1567668999_A01115\EDA.csv,LPC
3,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 12-04-2019 V4\Montre 0102PCR\1555052819_A01093\EDA.csv,APHM
4,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V4 0103BPS\Montre\1568706200_A01115\EDA.csv,LPC
5,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 08-11-2019 V4\Montre 0104FJS\1573198120_A01093\EDA.csv,APHM
6,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V4 0104IBS\Montre\EDA.csv,LPC
7,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 09-09-2019 V4\Montre 0105PNR\1568012045_A01093\EDA.csv,APHM
8,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 17-10-2019 V4\Montre 0107DSS\1571296181_A01093\EDA.csv,APHM
9,0107LER,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0107LER\V4 0107LER\Montre\1567584597_A01115\EDA.csv,LPC
10,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V4\Montre\1571900786_A01115\EDA.csv,LPC
11,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V4\Montre\1568360086_A01115\EDA.csv,LPC
12,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 21-11-2019 V4\Montre 0110LPR\1574323503_A01093\EDA.csv,APHM
13,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V4\Montre\1568619102_A01115\EDA.csv,LPC
14,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 22-11-2019 V4\Montre 0111MNR\1574410699_A01093\EDA.csv,APHM
15,0111TAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0111TAS\V4\Montre\1570087686_A01115\EDA.csv,LPC
16,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR - V4\V4\montre\1583397568_A01093\EDA.csv,APHM
17,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V4\Montre\1573029333_A01115\EDA.csv,LPC
18,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V4\montre\1566891799_A01115\EDA.csv,LPC
19,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS_V4\montre\EDA.csv,APHM
20,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\0114MLR V4\Montre\1571128491_A01115\EDA.csv,LPC
21,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V4\Montre\1570605904_A01115\EDA.csv,LPC
22,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V4\Montre\1570173945_A01115\EDA.csv,LPC
23,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR_v4\montre\1591255686_A01093\EDA.csv,APHM
24,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V4\Montre\1570778826_A01115\EDA.csv,LPC
25,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V4\Montre\1571205473_A01115\EDA.csv,LPC
26,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V4\Montre\1572252531_A01115\EDA.csv,LPC
27,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS_v4\MONTRE\MONTRE_0119LJS\EDA.csv,APHM
28,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V4\Montre\1574153203_A01115\EDA.csv,LPC
29,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR_v4_e\MONTRE\montre_0121MJR_v4\EDA.csv,APHM
30,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V4\Montre\1571816051_A01115\EDA.csv,LPC
31,0122BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0122BDS\0122BDS_V4\MONTRE\0122BDS_V4\EDA.csv,APHM
32,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V4\Montre\1572941907_A01115\EDA.csv,LPC
33,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V4\Montre\1573201375_A01115\EDA.csv,LPC
34,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS_V4\MONTRE\0123RMS_V4\EDA.csv,APHM
35,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V4\Montre\1573806435_A01115\EDA.csv,LPC
36,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V4\Montre\1575273925_A01115\EDA.csv,LPC
37,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V4\Montre\1574325279_A01115\EDA.csv,LPC
38,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V4\Montre\1576053205_A01115\EDA.csv,LPC
39,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V4\Montre\1576658477_A01115\EDA.csv,LPC
40,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\Marseille_LABO_08decembre2020\DATA_Aging_08decembre2020\0154FAR\V4\0130FAR\montre\EDA.csv,LPC
41,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\0132GAR_V4\montre\1612774878_A01093\EDA.csv,LPC
42,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\0157BPS_V4\montre\1612860803_A01115\EDA.csv,LPC
43,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR_V4\Montre\1639127858_A01115\EDA.csv,LPC
44,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V4\montre\1649059272_A01115\EDA.csv,LPC
45,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V4 0140LMR\montre\1676451829_A01115\EDA.csv,LPC
46,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR_V4\montre\1682409900_A01115\EDA.csv,LPC
47,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V4\montre\1681200504_A01115\EDA.csv,LPC
48,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1571731715_A01295 0302ZMR\EDA.csv,CAEN
49,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1579856234_A01295 0304VMR\EDA.csv,CAEN
50,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1579769470_A01295 0305LCR\EDA.csv,CAEN
51,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1590395693_A01295 0307SMR\EDA.csv,CAEN
52,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1599030387_A01295 0308GRR\EDA.csv,CAEN
53,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1589787562_A01295 0310ACS\EDA.csv,CAEN
54,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1592377927_A01295 0311CJS\EDA.csv,CAEN
55,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591603371_A01295 0313FPR\EDA.csv,CAEN
56,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591861453_A01295 0315VCS\EDA.csv,CAEN
57,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591084669_A01295 0316TMS\EDA.csv,CAEN
58,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1591258701_A01295 0317LGS\EDA.csv,CAEN
59,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1593071627_A01295 0319LJS\EDA.csv,CAEN
60,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1594108662_A01295 0321DRR\EDA.csv,CAEN
61,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1595319263_A012950322RMS\EDA.csv,CAEN
62,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1598513134_A01295 0323RFS\EDA.csv,CAEN
63,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1598345471_A01295 0324LMR\EDA.csv,CAEN
64,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1604393467_A01295 0329NMR\EDA.csv,CAEN
65,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1610959444_A01295 0330RTR\EDA.csv,CAEN
66,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1606467065_A01295 0331GRS\EDA.csv,CAEN
67,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1624606133_A01295 0333MMS\EDA.csv,CAEN
68,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1624955329_A01295 0334TVS\EDA.csv,CAEN
69,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1630655430_A01295 0337BFS\EDA.csv,CAEN
70,0338JBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1634887870_A01295 0338JBS\EDA.csv,CAEN
71,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1638449112_A01295 0339NPR\EDA.csv,CAEN
72,0340BAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1639485951_A01295 0340BAR\EDA.csv,CAEN
73,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1644915087_A01295 0341LJS\EDA.csv,CAEN
74,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1646730228_A01295 0343PAS\EDA.csv,CAEN
75,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1648798691_A01295 0342VNS\EDA.csv,CAEN
76,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1667550736_A012950345LAR\EDA.csv,CAEN
77,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1666942984_A012950346GLS\EDA.csv,CAEN
78,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1668760658_A01295 0347DMR\EDA.csv,CAEN
79,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1668501119_A01295 0348GCR\EDA.csv,CAEN
80,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1670920566_A01295 0350MYR\EDA.csv,CAEN
81,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1672909097_A01295 0351FIR\EDA.csv,CAEN
82,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1673513100_A01295 0352RNR\EDA.csv,CAEN
83,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\MONTRE\1687245889_A01295 0356DMS\EDA.csv,CAEN
84,0401BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Montre\1573634231_A0117F\EDA.csv,CERCA
85,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V4\0401TSS - montre V4\1578646774_A012C6\EDA.csv,POITIERS
86,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS-V4\0402LLS -montre V4\EDA.csv,POITIERS
87,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V4\0403DCR - montre V4\EDA.csv,POITIERS
88,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404YCS-V4\0404YC-montre V4\EDA.csv,POITIERS
89,0404DER,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Montre\1573202858_A0117F\EDA.csv,CERCA
90,0405RCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Montre\EDA.csv,CERCA
91,0406BBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Montre\EDA.csv,CERCA
92,0406MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0406 MC\0406MCS-V4\0406MC -montre V4\EDA.csv,POITIERS
93,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V4\0407LJ-montre V4\EDA.csv,POITIERS
94,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC-V4\0408BC-montre V4\1596702371_A012C6\EDA.csv,POITIERS
95,0408SJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Montre\1574847506_A0117F\EDA.csv,CERCA
96,0409HCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Montre\EDA.csv,CERCA
97,0410FMS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Montre\EDA.csv,CERCA
98,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V4\0411VE-montre V4\EDA.csv,POITIERS
99,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V4\0412ANS-V4\EDA.csv,POITIERS
100,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS V4\0413HFS montre V4\EDA.csv,POITIERS
101,0413MMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0413MMR\V4\Montre\EDA.csv,CERCA
102,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Montre\EDA.csv,CERCA
103,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Montre\EDA.csv,CERCA
104,0501MBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-01-MB-S\V4\MONTRE\1574064476_A012E9\EDA.csv,ROUEN
105,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V4\MONTRE\EDA.csv,ROUEN
106,0503LCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-03-LC-R\V4\MONTRE\1579767764_A012E9\EDA.csv,ROUEN
107,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V4\MONTRE V4\EDA.csv,ROUEN
108,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V4\MONTRE\EDA.csv,ROUEN
109,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V4\MONTRE\EDA.csv,ROUEN
110,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V4\MONTRE\1589267765_A012E9 (2)\EDA.csv,ROUEN
111,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V4\MONTRE\EDA.csv,ROUEN
112,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V4\MONTRE\EDA.csv,ROUEN
113,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V4\MONTRE\1647332236_A012E9\EDA.csv,ROUEN
114,0514LPS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-14-LP-S\V4\MONTRE\EDA.csv,ROUEN
115,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V4\MONTRE\EDA.csv,ROUEN
116,0626MCS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V4\0626MCS_v4\MONTRE\1603959501_A01093\EDA.csv,LAVERAN
117,0629TCR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\0629TCR_V4\MONTRE\1605603058_A01093\EDA.csv,LAVERAN
118,0630RJR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V4\MONTRE\1605517689_A01093\EDA.csv,LAVERAN
119,0631LHR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\0631LHR_V4\MONTRE\1605688444_A01093\EDA.csv,LAVERAN
120,0801HDR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V4\Montre\EDA.csv,SAINTE-MARGUERITE
121,0802LAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V4\Montre\EDA.csv,SAINTE-MARGUERITE
122,0803DPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS-V4\Montre\EDA.csv,SAINTE-MARGUERITE
123,0804GOR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR_V4\Montre\EDA.csv,SAINTE-MARGUERITE
124,0805BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V4\Montre\EDA.csv,SAINTE-MARGUERITE
125,0806KHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\0806KHS-V4\montre\EDA.csv,SAINTE-MARGUERITE
126,0807OMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V4\montre\EDA.csv,SAINTE-MARGUERITE
127,0901SMR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0901SMR\0901SMR - V4\Montre\1671008068_A01115\EDA.csv,CGD
128,0902SIS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS-V4\montre\1675242525_A01115\EDA.csv,CGD
129,0903DJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0903DJS\V4\montre\1678265782_A01115\EDA.csv,CGD
130,0904KJS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS-V4\montre\1679472202_A01115\EDA.csv,CGD
131,0905SLR,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V4\montre\1680680968_A01115\EDA.csv,CGD

In [30]:
# CONSERVATION DES FEUILLES DANS UN FICHEIR TXT
chemin_txt = r"C:\Users\judupont\Desktop\df_global_v4_EDA.txt"

df_global.to_csv(
    chemin_txt,
    sep="\t",
    index=False,
    encoding="utf-8-sig"
)

print(f"📄 df_global sauvegardé : {chemin_txt}")

📄 df_global sauvegardé : C:\Users\judupont\Desktop\df_global_v4_EDA.txt

# Verif temps unix

In [ ]:
# Exemple de timestamp Unix
timestamp_unix = 1554360113

# Conversion en datetime
dt = datetime.datetime.fromtimestamp(timestamp_unix)

print(dt)

# Verification que le temps d'experience et le temps du fichier EDA correspondent, offset et continuité

In [31]:
def convertir_heure_en_secondes(x):
    if pd.isna(x):
        return None

    # Excel → heure uniquement
    if isinstance(x, (int, float)):
        seconds = float(x) * 24 * 3600
        return seconds % (24 * 3600)

    try:
        t = pd.to_datetime(str(x).strip()).time()
        return t.hour * 3600 + t.minute * 60 + t.second
    except Exception:
        return None



dfs_excel = []

for feuille, data in resultats_bloc1.items():

    df_excel = data["df"].copy()

    # filtrage candidats retenus
    df_excel["Numero_inclusion"] = df_excel["Numero_inclusion"].astype(str)
    df_excel = df_excel[
        df_excel["Numero_inclusion"].isin(df_global['Numero_inclusion'])
    ]

    if df_excel.empty:
        continue

    # Conversion heures → secondes
    df_excel["heure_debut_sec"] = df_excel["heure_montre_v4"].apply(convertir_heure_en_secondes)
    df_excel["heure_fin_sec"] = df_excel["heure_fin_tests_v4"].apply(convertir_heure_en_secondes)

    # Durée visite Excel
    df_excel["duree_experience_sec"] = (
        df_excel["heure_fin_sec"] - df_excel["heure_debut_sec"]
    )

    # Sécurité passage minuit
    df_excel.loc[
        df_excel["duree_experience_sec"] < 0,
        "duree_experience_sec"
    ] += 24 * 3600

    df_excel["Feuille"] = feuille
    dfs_excel.append(df_excel)

df_excel_global = pd.concat(dfs_excel, ignore_index=True)


print(f"Lignes Excel retenues : {len(df_excel_global)}")
display(df_excel_global[[
    "Numero_inclusion",
    "Feuille",
    "duree_experience_sec"
]])

Lignes Excel retenues : 132

    Numero_inclusion            Feuille  duree_experience_sec
0            0101CAR               APHM                  9660
1            0102PCR               APHM                  7440
2            0105PNR               APHM                  7080
3            0104FJS               APHM                  6120
4            0107DSS               APHM                  6060
5            0110LPR               APHM                  8700
6            0111MNR               APHM                  7560
7            0112BSR               APHM                  8220
8            0114LMS               APHM                  6960
9            0116VAR               APHM                 10020
10           0119LJS               APHM                  8160
11           0121MJR               APHM                  9300
12           0122BDS               APHM                  5580
13           0123RMS               APHM                  7440
14           0302ZMR               CAEN                  5760
15           0304VMR               CAEN                  6780
16           0305LCR               CAEN                  6240
17           0307SMR               CAEN                  7620
18           0308RGR               CAEN                  5160
19           0311CJS               CAEN                  8160
20           0310ACS               CAEN                  7800
21           0315VCS               CAEN                  5640
22           0313FPR               CAEN                  5460
23           0316TMS               CAEN                  6960
24           0317LGS               CAEN                  6360
25           0319LJS               CAEN                  5040
26           0321DRR               CAEN                  5460
27           0323RFS               CAEN                  5460
28           0322RMS               CAEN                  4860
29           0324LMR               CAEN                  5160
30           0330RTR               CAEN                  7500
31           0329NMR               CAEN                  6660
32           0331GRS               CAEN                  6660
33           0333MMS               CAEN                  5520
34           0334TVS               CAEN                  4740
35           0337BFS               CAEN                  7020
36           0338JBS               CAEN                  6300
37           0339NPR               CAEN                  5520
38           0340BAR               CAEN                  4680
39           0341LJS               CAEN                  6000
40           0342VNS               CAEN                  4740
41           0343PAS               CAEN                  5820
42           0345LAR               CAEN                  6120
43           0347DMR               CAEN                  6420
44           0346GLS               CAEN                  6180
45           0348GCR               CAEN                  7320
46           0350MYR               CAEN                  6360
47           0351FIR               CAEN                  5820
48           0352RNR               CAEN                  5820
49           0356DMS               CAEN                  7020
50           0401TSS           POITIERS                  9600
51           0402LLS           POITIERS                  7860
52           0403DCR           POITIERS                  6840
53           0404CYS           POITIERS                  6840
54           0406MCS           POITIERS                  8880
55           0407LJR           POITIERS                  7500
56           0408BCS           POITIERS                  5400
57           0413HFS           POITIERS                  8820
58           0411VES           POITIERS                  6300
59           0412ANS           POITIERS                  7200
60           0501MBS              ROUEN                  7500
61           0502LIR              ROUEN                  6900
62           0503LCR              ROUEN                  5940
63           0504BCS              ROUEN                  6420
64           0505PPR              ROUEN                  6840
65           0508SRR              ROUEN                  6600
66           0507BDS              ROUEN                  6900
67           0510DFS              ROUEN                  7020
68           0512RCR              ROUEN                  6300
69           0513EBS              ROUEN                  6360
70           0514LPS              ROUEN                  6360
71           0515FAR              ROUEN                  7800
72           0626MCS            LAVERAN                  7800
73           0630RJR            LAVERAN                  6060
74           0629TCR            LAVERAN                  8220
75           0631LHR            LAVERAN                  5640
76           0101EMS                LPC                  7860
77           0102EMS                LPC                  4980
78           0103BPS                LPC                  7020
79           0104IBS                LPC                  6900
80           0107LER                LPC                  6780
81           0108MMS                LPC                  5880
82           0109MJR                LPC                  6420
83           0110RMS                LPC                  5820
84           0111TAS                LPC                  5700
85           0112DRR                LPC                  6180
86           0113DGR                LPC                  6000
87           0114MLR                LPC                  7440
88           0115MHR                LPC                  7320
89           0116CNR                LPC                  7740
90           0117MSR                LPC                  6720
91           0118TMS                LPC                  7080
92           0119BIR                LPC                  6180
93           0120ANS                LPC                  5880
94           0121RPS                LPC                  7620
95           0122VCR                LPC                  7020
96           0123GVS                LPC                  5460
97           0124PAS                LPC                  6000
98           0126VLR                LPC                  6120
99           0127CMS                LPC                  6360
100          0128ALS                LPC                  5940
101          0129APR                LPC                  9540
102          0130FAR                LPC                  8340
103          0132GAR                LPC                  6480
104          0133BPS                LPC                  6960
105          0136CJR                LPC                  6300
106          0138NWR                LPC                  6960
107          0140LMR                LPC                  9120
108          0143EBR                LPC                  8100
109          0144ZGR                LPC                 11340
110          0801HDR  SAINTE-MARGUERITE                  6180
111          0802LAS  SAINTE-MARGUERITE                  6780
112          0804GOR  SAINTE-MARGUERITE                  6960
113          0803DPS  SAINTE-MARGUERITE                  7680
114          0805BMS  SAINTE-MARGUERITE                  6840
115          0806KHS  SAINTE-MARGUERITE                  6480
116          0807OMR  SAINTE-MARGUERITE                  5520
117          0901SMR                CGD                  7740
118          0903DJS                CGD                  7980
119          0902SIS                CGD                  6540
120          0904KJS                CGD                  7500
121          0905SLR                CGD                  7200
122          0401BDS              CERCA                  7860
123          0404DER              CERCA                  6840
124          0405RCR              CERCA                  6780
125          0406BBS              CERCA                  7860
126          0408SJS              CERCA                 10380
127          0409HCR              CERCA                  6420
128          0410FMS              CERCA                  7860
129          0413MMR              CERCA                  7140
130          0414PVR              CERCA                  7800
131          0420MCR              CERCA                  8400

# D'ou vient l'écart ? L'offest doit etre appliqué en debut, en fin, au milieu?

In [32]:
def sec_to_datetime(sec, date_ref):
    return datetime.combine(
        date_ref.date(),
        datetime.min.time()
    ) + timedelta(seconds=int(sec))


resultats_offset_eda = []

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin_eda = row["Chemin"]

    # ===== Lecture EDA =====
    try:
        if ".ZIP|" in chemin_eda.upper():
            zip_path, inner_csv = chemin_eda.split("|", 1)
            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_raw = pd.read_csv(f, header=None)
        else:
            df_raw = pd.read_csv(chemin_eda, header=None)

    except Exception as e:
        print(f"⚠️ Lecture EDA impossible pour {pid} : {e}")
        continue

    if len(df_raw) < 3:
        continue

    # ===== Reconstruction Timestamp =====
    try:
        t0_unix = float(df_raw.iloc[0, 0])
        freq = float(df_raw.iloc[1, 0])
    except:
        continue

    if freq <= 0:
        continue

    df_eda = df_raw.iloc[2:].copy()
    df_eda.columns = ["EDA"]
    df_eda["EDA"] = pd.to_numeric(df_eda["EDA"], errors="coerce")
    df_eda = df_eda.dropna()

    if df_eda.empty:
        continue

    pas = 1 / 4
    n = len(df_eda)

    t_debut = datetime.fromtimestamp(t0_unix)
    df_eda["Timestamp"] = [
        t_debut + timedelta(seconds=i * pas)
        for i in range(n)
    ]

    t_min = df_eda["Timestamp"].min()
    t_max = df_eda["Timestamp"].max()

    # ===== Excel =====
    ligne_excel = df_excel_global.loc[
        df_excel_global["Numero_inclusion"] == pid
    ]

    if ligne_excel.empty:
        continue

    h_debut_sec = ligne_excel["heure_debut_sec"].values[0]
    h_fin_sec   = ligne_excel["heure_fin_sec"].values[0]
    duree_excel_sec = ligne_excel["duree_experience_sec"].values[0]

    if pd.isna(h_debut_sec) or pd.isna(h_fin_sec) or pd.isna(duree_excel_sec):
        continue

    h_debut = sec_to_datetime(h_debut_sec, t_min)
    h_fin   = sec_to_datetime(h_fin_sec, t_min)

    # =====================================================
    # Calcul du retard si EDA commence après Excel
    # =====================================================
    if t_min > h_debut:
        delta_retard_sec = (t_min - h_debut).total_seconds()
    else:
        delta_retard_sec = 0

    # ===== Comptages =====
    nb_avant = (df_eda["Timestamp"] < h_debut).sum()
    nb_dans = (
        (df_eda["Timestamp"] >= h_debut) &
        (df_eda["Timestamp"] <= h_fin)
    ).sum()
    nb_apres = (df_eda["Timestamp"] > h_fin).sum()

    total = len(df_eda)

    if nb_apres > nb_avant:
        origine = "FIN"
    elif nb_avant > nb_apres:
        origine = "DEBUT"
    else:
        origine = "MIXTE"

    resultats_offset_eda.append({
        "Numero_inclusion": pid,
        "nb_total_points": total,
        "nb_avant_excel": nb_avant,
        "nb_dans_excel": nb_dans,
        "nb_apres_excel": nb_apres,
        "origine_offset": origine,
        "delta_retard_sec": delta_retard_sec
    })

df_offset_eda = pd.DataFrame(resultats_offset_eda)

print(f"Offsets EDA calculés : {len(df_offset_eda)}")
display(df_offset_eda)

Offsets EDA calculés : 132

,Numero_inclusion,nb_total_points,nb_avant_excel,nb_dans_excel,nb_apres_excel,origine_offset,delta_retard_sec
0,0101CAR,39066,0,36749,2317,FIN,473.0
1,0101EMS,32076,32,31441,603,FIN,0.0
2,0102EMS,19662,0,19662,0,MIXTE,39.0
3,0102PCR,30570,0,29525,1045,FIN,59.0
4,0103BPS,28356,0,28001,355,FIN,20.0
5,0104FJS,25314,0,24321,993,FIN,40.0
6,0104IBS,27918,8,27601,309,FIN,0.0
7,0105PNR,28668,0,28301,367,FIN,5.0
8,0107DSS,24696,0,24077,619,FIN,41.0
9,0107LER,27414,12,27121,281,FIN,0.0
10,0108MMS,23664,0,23417,247,FIN,26.0
11,0109MJR,25680,0,25497,183,FIN,46.0
12,0110LPR,33348,0,33348,0,MIXTE,3.0
13,0110RMS,23280,0,23113,167,FIN,42.0
14,0111MNR,29946,0,29946,0,MIXTE,19.0
15,0111TAS,22848,0,22777,71,FIN,6.0
16,0112BSR,33060,0,32769,291,FIN,28.0
17,0112DRR,24666,0,24589,77,FIN,33.0
18,0113DGR,23460,0,23460,0,MIXTE,19.0
19,0114LMS,28008,0,27525,483,FIN,79.0
20,0114MLR,29904,0,29557,347,FIN,51.0
21,0115MHR,29340,0,29265,75,FIN,4.0
22,0116CNR,30546,0,30546,0,MIXTE,45.0
23,0116VAR,40314,0,39817,497,FIN,66.0
24,0117MSR,26952,0,26857,95,FIN,6.0
25,0118TMS,28434,28,28321,85,FIN,0.0
26,0119BIR,25170,36,24721,413,FIN,0.0
27,0119LJS,33540,0,32417,1123,FIN,56.0
28,0120ANS,23640,0,23349,291,FIN,43.0
29,0121MJR,38658,0,36901,1757,FIN,75.0
30,0121RPS,30564,0,30437,127,FIN,11.0
31,0122BDS,22188,0,21945,243,FIN,94.0
32,0122VCR,28050,0,27973,77,FIN,27.0
33,0123GVS,22176,20,21841,315,FIN,0.0
34,0123RMS,30150,0,29573,577,FIN,47.0
35,0124PAS,24378,0,23941,437,FIN,15.0
36,0126VLR,24660,0,24381,279,FIN,25.0
37,0127CMS,25338,84,25254,0,DEBUT,0.0
38,0128ALS,23922,0,23661,261,FIN,25.0
39,0129APR,37938,0,37938,0,MIXTE,17.0
40,0130FAR,31338,0,31053,285,FIN,577.0
41,0132GAR,26220,168,25921,131,DEBUT,0.0
42,0133BPS,27648,0,27509,139,FIN,83.0
43,0136CJR,24960,0,24809,151,FIN,98.0
44,0138NWR,28434,0,27793,641,FIN,12.0
45,0140LMR,36402,44,36358,0,DEBUT,0.0
46,0143EBR,34200,0,32401,1799,FIN,0.0
47,0144ZGR,45486,0,45265,221,FIN,24.0
48,0302ZMR,24150,0,22661,1489,FIN,95.0
49,0304VMR,29424,0,26585,2839,FIN,134.0
50,0305LCR,26604,0,24201,2403,FIN,190.0
51,0307SMR,32442,0,30269,2173,FIN,53.0
52,0308RGR,23694,0,20053,3641,FIN,147.0
53,0310ACS,35898,0,30633,5265,FIN,142.0
54,0311CJS,33732,0,31893,1839,FIN,187.0
55,0313FPR,22524,0,21157,1367,FIN,171.0
56,0315VCS,24078,0,22029,2049,FIN,133.0
57,0316TMS,30138,0,27165,2973,FIN,169.0
58,0317LGS,25698,0,24877,821,FIN,141.0
59,0319LJS,24216,0,19493,4723,FIN,167.0
60,0321DRR,42150,0,21673,20477,FIN,42.0
61,0322RMS,19914,0,18869,1045,FIN,143.0
62,0323RFS,23034,0,21465,1569,FIN,94.0
63,0324LMR,21840,0,20117,1723,FIN,131.0
64,0329NMR,27732,0,26133,1599,FIN,127.0
65,0330RTR,26238,0,26238,0,MIXTE,184.0
66,0331GRS,29250,0,25901,3349,FIN,185.0
67,0333MMS,21822,0,20669,1153,FIN,353.0
68,0334TVS,18966,0,17565,1401,FIN,349.0
69,0337BFS,31050,0,27001,4049,FIN,270.0
70,0338JBS,27966,0,24921,3045,FIN,70.0
71,0339NPR,23388,0,22033,1355,FIN,12.0
72,0340BAR,20466,0,18277,2189,FIN,111.0
73,0341LJS,25374,0,23653,1721,FIN,87.0
74,0342VNS,22296,0,18289,4007,FIN,168.0
75,0343PAS,29430,0,22997,6433,FIN,71.0
76,0345LAR,27492,0,24417,3075,FIN,16.0
77,0346GLS,25368,0,24465,903,FIN,64.0
78,0347DMR,29238,0,25289,3949,FIN,98.0
79,0348GCR,32106,244,29281,2581,FIN,0.0
80,0350MYR,28146,0,25177,2969,FIN,66.0
81,0351FIR,29868,0,23213,6655,FIN,17.0
82,0352RNR,31194,0,22801,8393,FIN,120.0
83,0356DMS,29226,0,27405,1821,FIN,169.0
84,0401BDS,31452,0,31157,295,FIN,71.0
85,0401TSS,43242,344,38401,4497,FIN,0.0
86,0402LLS,35244,284,31441,3519,FIN,0.0
87,0403DCR,29226,420,27361,1445,FIN,0.0
88,0404CYS,27852,0,27153,699,FIN,52.0
89,0404DER,27726,0,27209,517,FIN,38.0
90,0405RCR,26904,0,26701,203,FIN,105.0
91,0406BBS,32292,748,31441,103,DEBUT,0.0
92,0406MCS,36162,0,35469,693,FIN,13.0
93,0407LJR,31908,0,29933,1975,FIN,17.0
94,0408BCS,27912,0,21317,6595,FIN,71.0
95,0408SJS,41694,0,41177,517,FIN,86.0
96,0409HCR,24888,0,24657,231,FIN,256.0
97,0410FMS,31392,0,31345,47,FIN,24.0
98,0411VES,27138,0,24257,2881,FIN,236.0
99,0412ANS,31482,0,28585,2897,FIN,54.0
100,0413HFS,38388,0,35173,3215,FIN,27.0
101,0413MMR,28506,0,28257,249,FIN,76.0
102,0414PVR,31170,0,30901,269,FIN,75.0
103,0420MCR,24342,24342,0,0,DEBUT,0.0
104,0501MBS,31452,0,28097,3355,FIN,476.0
105,0502LIR,28170,32,27601,537,FIN,0.0
106,0503LCR,24750,64,23761,925,FIN,0.0
107,0504BCS,27624,0,25605,2019,FIN,19.0
108,0505PPR,28872,820,27361,691,DEBUT,0.0
109,0507BDS,28380,28,27601,751,FIN,0.0
110,0508SRR,28080,0,26141,1939,FIN,65.0
111,0510DFS,28722,0,27629,1093,FIN,113.0
112,0512RCR,26760,0,25105,1655,FIN,24.0
113,0513EBS,26046,0,25377,669,FIN,16.0
114,0514LPS,26376,0,24589,1787,FIN,213.0
115,0515FAR,30648,0,30613,35,FIN,147.0
116,0626MCS,28860,0,28860,0,MIXTE,81.0
117,0629TCR,33372,0,32649,723,FIN,58.0
118,0630RJR,24528,0,23965,563,FIN,69.0
119,0631LHR,22788,0,22305,483,FIN,64.0
120,0801HDR,24840,0,24525,315,FIN,49.0
121,0802LAS,27168,0,26997,171,FIN,31.0
122,0803DPS,30756,0,30713,43,FIN,2.0
123,0804GOR,27540,0,27409,131,FIN,108.0
124,0805BMS,27414,0,27101,313,FIN,65.0
125,0806KHS,25710,0,25313,397,FIN,152.0
126,0807OMR,22026,0,21997,29,FIN,21.0
127,0901SMR,31068,0,30849,219,FIN,28.0
128,0902SIS,26268,0,25981,287,FIN,45.0
129,0903DJS,32172,152,31921,99,DEBUT,0.0
130,0904KJS,30486,0,29913,573,FIN,22.0
131,0905SLR,28536,0,28449,87,FIN,88.0

In [34]:
# ===== Dossier de sortie =====
desktop = Path.home() / "Desktop"
output_dir = desktop / "EDA_v4_tronqués"
output_dir.mkdir(exist_ok=True)

print(f"📁 Dossier de sortie : {output_dir}")

# ===== Boucle troncature =====
for _, row in df_offset_eda.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()

    # récupérer chemin EDA depuis df_global
    ligne_global = df_global[df_global["Numero_inclusion"] == pid]
    if ligne_global.empty:
        continue

    chemin_eda = ligne_global.iloc[0]["Chemin"]

    nb_avant = int(row["nb_avant_excel"])
    nb_apres = int(row["nb_apres_excel"])

    # ===== Lecture EDA (ZIP ou non) =====
    try:
        if ".ZIP|" in chemin_eda.upper():
            zip_path, inner_csv = chemin_eda.split("|", 1)

            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_eda = pd.read_csv(f)
        else:
            df_eda = pd.read_csv(chemin_eda)

    except Exception as e:
        print(f"❌ Lecture impossible {pid}: {e}")
        continue

    total = len(df_eda)

    # ===== Indices de coupe =====
    # On conserve les 2 premières lignes, troncage à partir de la 3ème
    start = 2 + nb_avant
    end = total - nb_apres

    if start >= end:
        print(f"⚠️ Troncature invalide pour {pid} (start={start}, end={end})")
        continue

    # On concatène les 2 premières lignes intactes + le reste tronqué
    df_eda_trunc = pd.concat([df_eda.iloc[:2], df_eda.iloc[start:end]]).reset_index(drop=True)

    if df_eda_trunc.empty:
        print(f"⚠️ {pid} → fichier vide après troncature")
        continue

    # ===== Nom fichier de sortie =====
    if ".ZIP|" in chemin_eda.upper():
        nom_base = Path(inner_csv).name
    else:
        nom_base = Path(chemin_eda).name

    nom_fichier = f"offset_{pid}_{nom_base}"
    path_sortie = output_dir / nom_fichier

    # ===== Sauvegarde =====
    df_eda_trunc.to_csv(path_sortie, index=False)

    print(
        f"✅ {pid} | "
        f"avant={nb_avant}, après={nb_apres} | "
        f"{len(df_eda_trunc)} lignes → {path_sortie.name}"
    )

print("🎯 Troncature terminée")

📁 Dossier de sortie : C:\Users\judupont\Desktop\EDA_v4_tronqués
✅ 0101CAR | avant=0, après=2317 | 36750 lignes → offset_0101CAR_EDA.csv
✅ 0101EMS | avant=32, après=603 | 31442 lignes → offset_0101EMS_EDA.csv
✅ 0102EMS | avant=0, après=0 | 19663 lignes → offset_0102EMS_EDA.csv
✅ 0102PCR | avant=0, après=1045 | 29526 lignes → offset_0102PCR_EDA.csv
✅ 0103BPS | avant=0, après=355 | 28002 lignes → offset_0103BPS_EDA.csv
✅ 0104FJS | avant=0, après=993 | 24322 lignes → offset_0104FJS_EDA.csv
✅ 0104IBS | avant=8, après=309 | 27602 lignes → offset_0104IBS_EDA.csv
✅ 0105PNR | avant=0, après=367 | 28302 lignes → offset_0105PNR_EDA.csv
✅ 0107DSS | avant=0, après=619 | 24078 lignes → offset_0107DSS_EDA.csv
✅ 0107LER | avant=12, après=281 | 27122 lignes → offset_0107LER_EDA.csv
✅ 0108MMS | avant=0, après=247 | 23418 lignes → offset_0108MMS_EDA.csv
✅ 0109MJR | avant=0, après=183 | 25498 lignes → offset_0109MJR_EDA.csv
✅ 0110LPR | avant=0, après=0 | 33349 lignes → offset_0110LPR_EDA.csv
✅ 0110RMS | avant=0, après=167 | 23114 lignes → offset_0110RMS_EDA.csv
✅ 0111MNR | avant=0, après=0 | 29947 lignes → offset_0111MNR_EDA.csv
✅ 0111TAS | avant=0, après=71 | 22778 lignes → offset_0111TAS_EDA.csv
✅ 0112BSR | avant=0, après=291 | 32770 lignes → offset_0112BSR_EDA.csv
✅ 0112DRR | avant=0, après=77 | 24590 lignes → offset_0112DRR_EDA.csv
✅ 0113DGR | avant=0, après=0 | 23461 lignes → offset_0113DGR_EDA.csv
✅ 0114LMS | avant=0, après=483 | 27526 lignes → offset_0114LMS_EDA.csv
✅ 0114MLR | avant=0, après=347 | 29558 lignes → offset_0114MLR_EDA.csv
✅ 0115MHR | avant=0, après=75 | 29266 lignes → offset_0115MHR_EDA.csv
✅ 0116CNR | avant=0, après=0 | 30547 lignes → offset_0116CNR_EDA.csv
✅ 0116VAR | avant=0, après=497 | 39818 lignes → offset_0116VAR_EDA.csv
✅ 0117MSR | avant=0, après=95 | 26858 lignes → offset_0117MSR_EDA.csv
✅ 0118TMS | avant=28, après=85 | 28322 lignes → offset_0118TMS_EDA.csv
✅ 0119BIR | avant=36, après=413 | 24722 lignes → offset_0119BIR_EDA.csv
✅ 0119LJS | avant=0, après=1123 | 32418 lignes → offset_0119LJS_EDA.csv
✅ 0120ANS | avant=0, après=291 | 23350 lignes → offset_0120ANS_EDA.csv
✅ 0121MJR | avant=0, après=1757 | 36902 lignes → offset_0121MJR_EDA.csv
✅ 0121RPS | avant=0, après=127 | 30438 lignes → offset_0121RPS_EDA.csv
✅ 0122BDS | avant=0, après=243 | 21946 lignes → offset_0122BDS_EDA.csv
✅ 0122VCR | avant=0, après=77 | 27974 lignes → offset_0122VCR_EDA.csv
✅ 0123GVS | avant=20, après=315 | 21842 lignes → offset_0123GVS_EDA.csv
✅ 0123RMS | avant=0, après=577 | 29574 lignes → offset_0123RMS_EDA.csv
✅ 0124PAS | avant=0, après=437 | 23942 lignes → offset_0124PAS_EDA.csv
✅ 0126VLR | avant=0, après=279 | 24382 lignes → offset_0126VLR_EDA.csv
✅ 0127CMS | avant=84, après=0 | 25255 lignes → offset_0127CMS_EDA.csv
✅ 0128ALS | avant=0, après=261 | 23662 lignes → offset_0128ALS_EDA.csv
✅ 0129APR | avant=0, après=0 | 37939 lignes → offset_0129APR_EDA.csv
✅ 0130FAR | avant=0, après=285 | 31054 lignes → offset_0130FAR_EDA.csv
✅ 0132GAR | avant=168, après=131 | 25922 lignes → offset_0132GAR_EDA.csv
✅ 0133BPS | avant=0, après=139 | 27510 lignes → offset_0133BPS_EDA.csv
✅ 0136CJR | avant=0, après=151 | 24810 lignes → offset_0136CJR_EDA.csv
✅ 0138NWR | avant=0, après=641 | 27794 lignes → offset_0138NWR_EDA.csv
✅ 0140LMR | avant=44, après=0 | 36359 lignes → offset_0140LMR_EDA.csv
✅ 0143EBR | avant=0, après=1799 | 32402 lignes → offset_0143EBR_EDA.csv
✅ 0144ZGR | avant=0, après=221 | 45266 lignes → offset_0144ZGR_EDA.csv
✅ 0302ZMR | avant=0, après=1489 | 22662 lignes → offset_0302ZMR_EDA.csv
✅ 0304VMR | avant=0, après=2839 | 26586 lignes → offset_0304VMR_EDA.csv
✅ 0305LCR | avant=0, après=2403 | 24202 lignes → offset_0305LCR_EDA.csv
✅ 0307SMR | avant=0, après=2173 | 30270 lignes → offset_0307SMR_EDA.csv
✅ 0308RGR | avant=0, après=3641 | 20054 lignes → offset_0308RGR_EDA.csv
✅ 0310ACS | avant=0, après=5265 | 30634 lignes → offset_0310ACS_EDA.csv
✅ 0311CJS | avant=0, après=1839 | 31894 lignes → offset_0311CJS_EDA.csv
✅ 0313FPR | avant=0, après=1367 | 21158 lignes → offset_0313FPR_EDA.csv
✅ 0315VCS | avant=0, après=2049 | 22030 lignes → offset_0315VCS_EDA.csv
✅ 0316TMS | avant=0, après=2973 | 27166 lignes → offset_0316TMS_EDA.csv
✅ 0317LGS | avant=0, après=821 | 24878 lignes → offset_0317LGS_EDA.csv
✅ 0319LJS | avant=0, après=4723 | 19494 lignes → offset_0319LJS_EDA.csv
✅ 0321DRR | avant=0, après=20477 | 21674 lignes → offset_0321DRR_EDA.csv
✅ 0322RMS | avant=0, après=1045 | 18870 lignes → offset_0322RMS_EDA.csv
✅ 0323RFS | avant=0, après=1569 | 21466 lignes → offset_0323RFS_EDA.csv
✅ 0324LMR | avant=0, après=1723 | 20118 lignes → offset_0324LMR_EDA.csv
✅ 0329NMR | avant=0, après=1599 | 26134 lignes → offset_0329NMR_EDA.csv
✅ 0330RTR | avant=0, après=0 | 26239 lignes → offset_0330RTR_EDA.csv
✅ 0331GRS | avant=0, après=3349 | 25902 lignes → offset_0331GRS_EDA.csv
✅ 0333MMS | avant=0, après=1153 | 20670 lignes → offset_0333MMS_EDA.csv
✅ 0334TVS | avant=0, après=1401 | 17566 lignes → offset_0334TVS_EDA.csv
✅ 0337BFS | avant=0, après=4049 | 27002 lignes → offset_0337BFS_EDA.csv
✅ 0338JBS | avant=0, après=3045 | 24922 lignes → offset_0338JBS_EDA.csv
✅ 0339NPR | avant=0, après=1355 | 22034 lignes → offset_0339NPR_EDA.csv
✅ 0340BAR | avant=0, après=2189 | 18278 lignes → offset_0340BAR_EDA.csv
✅ 0341LJS | avant=0, après=1721 | 23654 lignes → offset_0341LJS_EDA.csv
✅ 0342VNS | avant=0, après=4007 | 18290 lignes → offset_0342VNS_EDA.csv
✅ 0343PAS | avant=0, après=6433 | 22998 lignes → offset_0343PAS_EDA.csv
✅ 0345LAR | avant=0, après=3075 | 24418 lignes → offset_0345LAR_EDA.csv
✅ 0346GLS | avant=0, après=903 | 24466 lignes → offset_0346GLS_EDA.csv
✅ 0347DMR | avant=0, après=3949 | 25290 lignes → offset_0347DMR_EDA.csv
✅ 0348GCR | avant=244, après=2581 | 29282 lignes → offset_0348GCR_EDA.csv
✅ 0350MYR | avant=0, après=2969 | 25178 lignes → offset_0350MYR_EDA.csv
✅ 0351FIR | avant=0, après=6655 | 23214 lignes → offset_0351FIR_EDA.csv
✅ 0352RNR | avant=0, après=8393 | 22802 lignes → offset_0352RNR_EDA.csv
✅ 0356DMS | avant=0, après=1821 | 27406 lignes → offset_0356DMS_EDA.csv
✅ 0401BDS | avant=0, après=295 | 31158 lignes → offset_0401BDS_EDA.csv
✅ 0401TSS | avant=344, après=4497 | 38402 lignes → offset_0401TSS_EDA.csv
✅ 0402LLS | avant=284, après=3519 | 31442 lignes → offset_0402LLS_EDA.csv
✅ 0403DCR | avant=420, après=1445 | 27362 lignes → offset_0403DCR_EDA.csv
✅ 0404CYS | avant=0, après=699 | 27154 lignes → offset_0404CYS_EDA.csv
✅ 0404DER | avant=0, après=517 | 27210 lignes → offset_0404DER_EDA.csv
✅ 0405RCR | avant=0, après=203 | 26702 lignes → offset_0405RCR_EDA.csv
✅ 0406BBS | avant=748, après=103 | 31442 lignes → offset_0406BBS_EDA.csv
✅ 0406MCS | avant=0, après=693 | 35470 lignes → offset_0406MCS_EDA.csv
✅ 0407LJR | avant=0, après=1975 | 29934 lignes → offset_0407LJR_EDA.csv
✅ 0408BCS | avant=0, après=6595 | 21318 lignes → offset_0408BCS_EDA.csv
✅ 0408SJS | avant=0, après=517 | 41178 lignes → offset_0408SJS_EDA.csv
✅ 0409HCR | avant=0, après=231 | 24658 lignes → offset_0409HCR_EDA.csv
✅ 0410FMS | avant=0, après=47 | 31346 lignes → offset_0410FMS_EDA.csv
✅ 0411VES | avant=0, après=2881 | 24258 lignes → offset_0411VES_EDA.csv
✅ 0412ANS | avant=0, après=2897 | 28586 lignes → offset_0412ANS_EDA.csv
✅ 0413HFS | avant=0, après=3215 | 35174 lignes → offset_0413HFS_EDA.csv
✅ 0413MMR | avant=0, après=249 | 28258 lignes → offset_0413MMR_EDA.csv
✅ 0414PVR | avant=0, après=269 | 30902 lignes → offset_0414PVR_EDA.csv
⚠️ Troncature invalide pour 0420MCR (start=24344, end=24343)
✅ 0501MBS | avant=0, après=3355 | 28098 lignes → offset_0501MBS_EDA.csv
✅ 0502LIR | avant=32, après=537 | 27602 lignes → offset_0502LIR_EDA.csv
✅ 0503LCR | avant=64, après=925 | 23762 lignes → offset_0503LCR_EDA.csv
✅ 0504BCS | avant=0, après=2019 | 25606 lignes → offset_0504BCS_EDA.csv
✅ 0505PPR | avant=820, après=691 | 27362 lignes → offset_0505PPR_EDA.csv
✅ 0507BDS | avant=28, après=751 | 27602 lignes → offset_0507BDS_EDA.csv
✅ 0508SRR | avant=0, après=1939 | 26142 lignes → offset_0508SRR_EDA.csv
✅ 0510DFS | avant=0, après=1093 | 27630 lignes → offset_0510DFS_EDA.csv
✅ 0512RCR | avant=0, après=1655 | 25106 lignes → offset_0512RCR_EDA.csv
✅ 0513EBS | avant=0, après=669 | 25378 lignes → offset_0513EBS_EDA.csv
✅ 0514LPS | avant=0, après=1787 | 24590 lignes → offset_0514LPS_EDA.csv
✅ 0515FAR | avant=0, après=35 | 30614 lignes → offset_0515FAR_EDA.csv
✅ 0626MCS | avant=0, après=0 | 28861 lignes → offset_0626MCS_EDA.csv
✅ 0629TCR | avant=0, après=723 | 32650 lignes → offset_0629TCR_EDA.csv
✅ 0630RJR | avant=0, après=563 | 23966 lignes → offset_0630RJR_EDA.csv
✅ 0631LHR | avant=0, après=483 | 22306 lignes → offset_0631LHR_EDA.csv
✅ 0801HDR | avant=0, après=315 | 24526 lignes → offset_0801HDR_EDA.csv
✅ 0802LAS | avant=0, après=171 | 26998 lignes → offset_0802LAS_EDA.csv
✅ 0803DPS | avant=0, après=43 | 30714 lignes → offset_0803DPS_EDA.csv
✅ 0804GOR | avant=0, après=131 | 27410 lignes → offset_0804GOR_EDA.csv
✅ 0805BMS | avant=0, après=313 | 27102 lignes → offset_0805BMS_EDA.csv
✅ 0806KHS | avant=0, après=397 | 25314 lignes → offset_0806KHS_EDA.csv
✅ 0807OMR | avant=0, après=29 | 21998 lignes → offset_0807OMR_EDA.csv
✅ 0901SMR | avant=0, après=219 | 30850 lignes → offset_0901SMR_EDA.csv
✅ 0902SIS | avant=0, après=287 | 25982 lignes → offset_0902SIS_EDA.csv
✅ 0903DJS | avant=152, après=99 | 31922 lignes → offset_0903DJS_EDA.csv
✅ 0904KJS | avant=0, après=573 | 29914 lignes → offset_0904KJS_EDA.csv
✅ 0905SLR | avant=0, après=87 | 28450 lignes → offset_0905SLR_EDA.csv
🎯 Troncature terminée

In [35]:
# ===== Paramètres =====
min_lignes = 10000
candidats_a_exclure = {"0330RTR", "0626MCS"} # trop court par rapport au temps d'experience 

dossier = Path.home() / "Desktop" / "EDA_v4_tronqués"

print(f"📂 Dossier analysé : {dossier}")

supprimes = []
conserves = []

for fichier in dossier.glob("*.csv"):

    nom = fichier.name

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", nom.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {nom}")
        continue

    pid = match.group()

    # ===== Exclusion candidat spécifique =====
    if pid in candidats_a_exclure:
        fichier.unlink()
        supprimes.append((nom, "candidat exclu"))
        print(f"🗑️ {nom} → candidat exclu ({pid})")
        continue

    # ===== Comptage rapide des lignes =====
    try:
        with open(fichier, "r", encoding="utf-8") as f:
            n_lignes = sum(1 for _ in f)
    except Exception as e:
        print(f"❌ Lecture impossible {nom}: {e}")
        continue

    # ===== Exclusion fichiers trop courts =====
    if n_lignes < min_lignes:
        fichier.unlink()
        supprimes.append((nom, f"{n_lignes} lignes"))
        print(f"❌ {nom} → trop petit ({n_lignes} lignes)")
    else:
        conserves.append((nom, n_lignes))
        print(f"✅ {nom} → conservé ({n_lignes} lignes)")

# ===== Résumé =====
print("\n====== RÉSUMÉ ======")
print(f"Fichiers supprimés : {len(supprimes)}")
print(f"Fichiers conservés : {len(conserves)}")

if supprimes:
    print("\nDétail suppressions :")
    for s in supprimes:
        print(" -", s)

📂 Dossier analysé : C:\Users\judupont\Desktop\EDA_v4_tronqués
✅ offset_0101CAR_EDA.csv → conservé (36751 lignes)
✅ offset_0101EMS_EDA.csv → conservé (31443 lignes)
✅ offset_0102EMS_EDA.csv → conservé (19664 lignes)
✅ offset_0102PCR_EDA.csv → conservé (29527 lignes)
✅ offset_0103BPS_EDA.csv → conservé (28003 lignes)
✅ offset_0104FJS_EDA.csv → conservé (24323 lignes)
✅ offset_0104IBS_EDA.csv → conservé (27603 lignes)
✅ offset_0105PNR_EDA.csv → conservé (28303 lignes)
✅ offset_0107DSS_EDA.csv → conservé (24079 lignes)
✅ offset_0107LER_EDA.csv → conservé (27123 lignes)
✅ offset_0108MMS_EDA.csv → conservé (23419 lignes)
✅ offset_0109MJR_EDA.csv → conservé (25499 lignes)
✅ offset_0110LPR_EDA.csv → conservé (33350 lignes)
✅ offset_0110RMS_EDA.csv → conservé (23115 lignes)
✅ offset_0111MNR_EDA.csv → conservé (29948 lignes)
✅ offset_0111TAS_EDA.csv → conservé (22779 lignes)
✅ offset_0112BSR_EDA.csv → conservé (32771 lignes)
✅ offset_0112DRR_EDA.csv → conservé (24591 lignes)
✅ offset_0113DGR_EDA.csv → conservé (23462 lignes)
✅ offset_0114LMS_EDA.csv → conservé (27527 lignes)
✅ offset_0114MLR_EDA.csv → conservé (29559 lignes)
✅ offset_0115MHR_EDA.csv → conservé (29267 lignes)
✅ offset_0116CNR_EDA.csv → conservé (30548 lignes)
✅ offset_0116VAR_EDA.csv → conservé (39819 lignes)
✅ offset_0117MSR_EDA.csv → conservé (26859 lignes)
✅ offset_0118TMS_EDA.csv → conservé (28323 lignes)
✅ offset_0119BIR_EDA.csv → conservé (24723 lignes)
✅ offset_0119LJS_EDA.csv → conservé (32419 lignes)
✅ offset_0120ANS_EDA.csv → conservé (23351 lignes)
✅ offset_0121MJR_EDA.csv → conservé (36903 lignes)
✅ offset_0121RPS_EDA.csv → conservé (30439 lignes)
✅ offset_0122BDS_EDA.csv → conservé (21947 lignes)
✅ offset_0122VCR_EDA.csv → conservé (27975 lignes)
✅ offset_0123GVS_EDA.csv → conservé (21843 lignes)
✅ offset_0123RMS_EDA.csv → conservé (29575 lignes)
✅ offset_0124PAS_EDA.csv → conservé (23943 lignes)
✅ offset_0126VLR_EDA.csv → conservé (24383 lignes)
✅ offset_0127CMS_EDA.csv → conservé (25256 lignes)
✅ offset_0128ALS_EDA.csv → conservé (23663 lignes)
✅ offset_0129APR_EDA.csv → conservé (37940 lignes)
✅ offset_0130FAR_EDA.csv → conservé (31055 lignes)
✅ offset_0132GAR_EDA.csv → conservé (25923 lignes)
✅ offset_0133BPS_EDA.csv → conservé (27511 lignes)
✅ offset_0136CJR_EDA.csv → conservé (24811 lignes)
✅ offset_0138NWR_EDA.csv → conservé (27795 lignes)
✅ offset_0140LMR_EDA.csv → conservé (36360 lignes)
✅ offset_0143EBR_EDA.csv → conservé (32403 lignes)
✅ offset_0144ZGR_EDA.csv → conservé (45267 lignes)
✅ offset_0302ZMR_EDA.csv → conservé (22663 lignes)
✅ offset_0304VMR_EDA.csv → conservé (26587 lignes)
✅ offset_0305LCR_EDA.csv → conservé (24203 lignes)
✅ offset_0307SMR_EDA.csv → conservé (30271 lignes)
✅ offset_0308RGR_EDA.csv → conservé (20055 lignes)
✅ offset_0310ACS_EDA.csv → conservé (30635 lignes)
✅ offset_0311CJS_EDA.csv → conservé (31895 lignes)
✅ offset_0313FPR_EDA.csv → conservé (21159 lignes)
✅ offset_0315VCS_EDA.csv → conservé (22031 lignes)
✅ offset_0316TMS_EDA.csv → conservé (27167 lignes)
✅ offset_0317LGS_EDA.csv → conservé (24879 lignes)
✅ offset_0319LJS_EDA.csv → conservé (19495 lignes)
✅ offset_0321DRR_EDA.csv → conservé (21675 lignes)
✅ offset_0322RMS_EDA.csv → conservé (18871 lignes)
✅ offset_0323RFS_EDA.csv → conservé (21467 lignes)
✅ offset_0324LMR_EDA.csv → conservé (20119 lignes)
✅ offset_0329NMR_EDA.csv → conservé (26135 lignes)
🗑️ offset_0330RTR_EDA.csv → candidat exclu (0330RTR)
✅ offset_0331GRS_EDA.csv → conservé (25903 lignes)
✅ offset_0333MMS_EDA.csv → conservé (20671 lignes)
✅ offset_0334TVS_EDA.csv → conservé (17567 lignes)
✅ offset_0337BFS_EDA.csv → conservé (27003 lignes)
✅ offset_0338JBS_EDA.csv → conservé (24923 lignes)
✅ offset_0339NPR_EDA.csv → conservé (22035 lignes)
✅ offset_0340BAR_EDA.csv → conservé (18279 lignes)
✅ offset_0341LJS_EDA.csv → conservé (23655 lignes)
✅ offset_0342VNS_EDA.csv → conservé (18291 lignes)
✅ offset_0343PAS_EDA.csv → conservé (22999 lignes)
✅ offset_0345LAR_EDA.csv → conservé (24419 lignes)
✅ offset_0346GLS_EDA.csv → conservé (24467 lignes)
✅ offset_0347DMR_EDA.csv → conservé (25291 lignes)
✅ offset_0348GCR_EDA.csv → conservé (29283 lignes)
✅ offset_0350MYR_EDA.csv → conservé (25179 lignes)
✅ offset_0351FIR_EDA.csv → conservé (23215 lignes)
✅ offset_0352RNR_EDA.csv → conservé (22803 lignes)
✅ offset_0356DMS_EDA.csv → conservé (27407 lignes)
✅ offset_0401BDS_EDA.csv → conservé (31159 lignes)
✅ offset_0401TSS_EDA.csv → conservé (38403 lignes)
✅ offset_0402LLS_EDA.csv → conservé (31443 lignes)
✅ offset_0403DCR_EDA.csv → conservé (27363 lignes)
✅ offset_0404CYS_EDA.csv → conservé (27155 lignes)
✅ offset_0404DER_EDA.csv → conservé (27211 lignes)
✅ offset_0405RCR_EDA.csv → conservé (26703 lignes)
✅ offset_0406BBS_EDA.csv → conservé (31443 lignes)
✅ offset_0406MCS_EDA.csv → conservé (35471 lignes)
✅ offset_0407LJR_EDA.csv → conservé (29935 lignes)
✅ offset_0408BCS_EDA.csv → conservé (21319 lignes)
✅ offset_0408SJS_EDA.csv → conservé (41179 lignes)
✅ offset_0409HCR_EDA.csv → conservé (24659 lignes)
✅ offset_0410FMS_EDA.csv → conservé (31347 lignes)
✅ offset_0411VES_EDA.csv → conservé (24259 lignes)
✅ offset_0412ANS_EDA.csv → conservé (28587 lignes)
✅ offset_0413HFS_EDA.csv → conservé (35175 lignes)
✅ offset_0413MMR_EDA.csv → conservé (28259 lignes)
✅ offset_0414PVR_EDA.csv → conservé (30903 lignes)
✅ offset_0501MBS_EDA.csv → conservé (28099 lignes)
✅ offset_0502LIR_EDA.csv → conservé (27603 lignes)
✅ offset_0503LCR_EDA.csv → conservé (23763 lignes)
✅ offset_0504BCS_EDA.csv → conservé (25607 lignes)
✅ offset_0505PPR_EDA.csv → conservé (27363 lignes)
✅ offset_0507BDS_EDA.csv → conservé (27603 lignes)
✅ offset_0508SRR_EDA.csv → conservé (26143 lignes)
✅ offset_0510DFS_EDA.csv → conservé (27631 lignes)
✅ offset_0512RCR_EDA.csv → conservé (25107 lignes)
✅ offset_0513EBS_EDA.csv → conservé (25379 lignes)
✅ offset_0514LPS_EDA.csv → conservé (24591 lignes)
✅ offset_0515FAR_EDA.csv → conservé (30615 lignes)
🗑️ offset_0626MCS_EDA.csv → candidat exclu (0626MCS)
✅ offset_0629TCR_EDA.csv → conservé (32651 lignes)
✅ offset_0630RJR_EDA.csv → conservé (23967 lignes)
✅ offset_0631LHR_EDA.csv → conservé (22307 lignes)
✅ offset_0801HDR_EDA.csv → conservé (24527 lignes)
✅ offset_0802LAS_EDA.csv → conservé (26999 lignes)
✅ offset_0803DPS_EDA.csv → conservé (30715 lignes)
✅ offset_0804GOR_EDA.csv → conservé (27411 lignes)
✅ offset_0805BMS_EDA.csv → conservé (27103 lignes)
✅ offset_0806KHS_EDA.csv → conservé (25315 lignes)
✅ offset_0807OMR_EDA.csv → conservé (21999 lignes)
✅ offset_0901SMR_EDA.csv → conservé (30851 lignes)
✅ offset_0902SIS_EDA.csv → conservé (25983 lignes)
✅ offset_0903DJS_EDA.csv → conservé (31923 lignes)
✅ offset_0904KJS_EDA.csv → conservé (29915 lignes)
✅ offset_0905SLR_EDA.csv → conservé (28451 lignes)

====== RÉSUMÉ ======
Fichiers supprimés : 2
Fichiers conservés : 129

Détail suppressions :
 - ('offset_0330RTR_EDA.csv', 'candidat exclu')
 - ('offset_0626MCS_EDA.csv', 'candidat exclu')

# On peut passer au découpage!

In [36]:
# Calcul de la durée de l'écriture pour shift le debut du bloc 2, 7 minutes pour les candidats ayant un Nr dans l'une des deux colonnes de calcul 

# ===== PARAMÈTRE =====
DUREE_MOYENNE_ECRITURE_SEC = 7 * 60  # 7 minutes

col_debut = "heure_anamnese_fin_v4"
col_fin   = "heure_rlri16imm_debut_v4"

df = df_excel_global.copy()

# ===== Détection valeur non horaire =====
def est_non_horaire(val):
    if pd.isna(val):
        return True
    if isinstance(val, str):
        v = val.strip().upper()
        return v in {"NR", "N/R", "NON RENSEIGNE", ""}
    return False

# ===== Conversion vers Timestamp =====
def convertir_heure(val):
    if est_non_horaire(val):
        return pd.NaT

    # Excel numérique (fraction de jour)
    if isinstance(val, (int, float)):
        seconds = (float(val) * 24 * 3600) % (24 * 3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # datetime / Timestamp
    if isinstance(val, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=val.hour, minute=val.minute, second=val.second
        )

    try:
        t = pd.to_datetime(str(val).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

# ===== Conversion des colonnes =====
df["_ecriture_debut_ts"] = df[col_debut].apply(convertir_heure)
df["_ecriture_fin_ts"]   = df[col_fin].apply(convertir_heure)

# ===== Calcul durée =====
def calcul_duree(row):
    debut = row["_ecriture_debut_ts"]
    fin   = row["_ecriture_fin_ts"]

    if pd.notna(debut) and pd.notna(fin):
        delta = (fin - debut).total_seconds()

        # sécurité : durée négative ou absurde
        if 0 <= delta < 3600:
            return int(delta)

    return DUREE_MOYENNE_ECRITURE_SEC

df["duree_ecriture_sec"] = df.apply(calcul_duree, axis=1)

# ===== Diagnostic =====
nb_moyenne = (df["duree_ecriture_sec"] == DUREE_MOYENNE_ECRITURE_SEC).sum()

print("===== DURÉE ÉCRITURE CALCULÉE =====")
print(f"Total candidats : {len(df)}")
print("Le seul caniddat avec une assigantion de temps par défaut est le 0410FMS")

# ===== Nettoyage colonnes temporaires =====
df = df.drop(columns=["_ecriture_debut_ts", "_ecriture_fin_ts"])

# ===== Mise à jour dataframe principal =====
df_excel_global["duree_ecriture_sec"] = df["duree_ecriture_sec"]

display(
    df_excel_global[[
        "Numero_inclusion",
        col_debut,
        col_fin,
        "duree_ecriture_sec"
    ]]
)

===== DURÉE ÉCRITURE CALCULÉE =====
Total candidats : 132
Durées réelles calculées : 121
Durées remplacées par la moyenne (7 min) : 11

,Numero_inclusion,heure_anamnese_fin_v4,heure_rlri16imm_debut_v4,duree_ecriture_sec
0,0101CAR,2026-03-10 08:54:00,09:07:00,780
1,0102PCR,2026-03-10 09:20:00,09:30:00,600
2,0105PNR,2026-03-10 09:08:00,09:22:00,840
3,0104FJS,2026-03-10 08:44:00,08:50:00,360
4,0107DSS,2026-03-10 09:33:00,09:45:00,720
5,0110LPR,2026-03-10 09:19:00,09:36:00,1020
6,0111MNR,2026-03-10 09:37:00,09:47:00,600
7,0112BSR,2026-03-10 10:10:00,10:25:00,900
8,0114LMS,2026-03-10 10:12:00,10:21:00,540
9,0116VAR,2026-03-10 10:00:00,10:18:00,1080
10,0119LJS,2026-03-10 09:51:00,10:06:00,900
11,0121MJR,2026-03-10 09:44:00,10:00:00,960
12,0122BDS,2026-03-10 09:47:00,09:55:00,480
13,0123RMS,2026-03-10 09:45:00,09:55:00,600
14,0302ZMR,2026-03-10 10:20:00,10:30:00,600
15,0304VMR,2026-03-10 10:15:00,10:25:00,600
16,0305LCR,2026-03-10 10:01:00,10:10:00,540
17,0307SMR,2026-03-10 10:56:00,11:06:00,600
18,0308RGR,2026-03-10 09:17:00,09:25:00,480
19,0311CJS,2026-03-10 09:35:00,09:50:00,900
20,0310ACS,2026-03-10 09:55:00,10:05:00,600
21,0315VCS,2026-03-10 10:00:00,10:10:00,600
22,0313FPR,2026-03-10 10:10:00,10:16:00,360
23,0316TMS,2026-03-10 10:05:00,10:18:00,780
24,0317LGS,2026-03-10 10:37:00,10:43:00,360
25,0319LJS,2026-03-10 10:02:00,10:10:00,480
26,0321DRR,2026-03-10 10:12:00,10:14:00,120
27,0323RFS,2026-03-10 09:35:00,09:40:00,300
28,0322RMS,2026-03-10 10:22:00,10:30:00,480
29,0324LMR,2026-03-10 11:00:00,11:05:00,300
30,0330RTR,2026-03-10 09:58:00,10:05:00,420
31,0329NMR,2026-03-10 10:05:00,10:16:00,660
32,0331GRS,2026-03-10 10:01:00,10:07:00,360
33,0333MMS,2026-03-10 09:36:00,09:45:00,540
34,0334TVS,2026-03-10 10:35:00,10:43:00,480
35,0337BFS,2026-03-10 10:04:00,10:12:00,480
36,0338JBS,2026-03-10 09:41:00,09:50:00,540
37,0339NPR,2026-03-10 13:58:00,14:05:00,420
38,0340BAR,2026-03-10 14:00:00,14:06:00,360
39,0341LJS,2026-03-10 10:00:00,10:17:00,1020
40,0342VNS,2026-03-10 10:15:00,10:21:00,360
41,0343PAS,2026-03-10 09:55:00,10:05:00,600
42,0345LAR,2026-03-10 09:47:00,09:53:00,360
43,0347DMR,2026-03-10 09:53:00,10:00:00,420
44,0346GLS,2026-03-10 09:53:00,10:02:00,540
45,0348GCR,2026-03-10 09:52:00,10:02:00,600
46,0350MYR,2026-03-10 09:45:00,09:50:00,300
47,0351FIR,2026-03-10 10:10:00,10:20:00,600
48,0352RNR,2026-03-10 09:56:00,10:05:00,540
49,0356DMS,2026-03-10 09:42:00,09:47:00,300
50,0401TSS,2026-03-10 10:21:00,10:42:00,1260
51,0402LLS,2026-03-10 10:04:00,10:11:00,420
52,0403DCR,2026-03-10 10:26:00,10:37:00,660
53,0404CYS,2026-03-10 10:37:00,10:47:00,600
54,0406MCS,2026-03-10 13:43:00,13:50:00,420
55,0407LJR,2026-03-10 10:11:00,10:25:00,840
56,0408BCS,2026-03-10 10:39:00,10:57:00,1080
57,0413HFS,2026-03-10 10:09:00,10:28:00,1140
58,0411VES,2026-03-10 10:33:00,10:42:00,540
59,0412ANS,2026-03-10 10:28:00,10:38:00,600
60,0501MBS,2026-03-10 09:20:00,09:40:00,1200
61,0502LIR,2026-03-10 09:10:00,09:24:00,840
62,0503LCR,2026-03-10 09:36:00,09:45:00,540
63,0504BCS,2026-03-10 09:24:00,09:37:00,780
64,0505PPR,2026-03-10 09:30:00,09:30:00,0
65,0508SRR,2026-03-10 09:31:00,09:43:00,720
66,0507BDS,2026-03-10 09:40:00,09:44:00,240
67,0510DFS,2026-03-10 09:25:00,09:36:00,660
68,0512RCR,2026-03-10 14:25:00,14:31:00,360
69,0513EBS,2026-03-10 09:35:00,09:45:00,600
70,0514LPS,2026-03-10 09:35:00,09:44:00,540
71,0515FAR,2026-03-10 09:30:00,09:54:00,1440
72,0626MCS,2026-03-10 09:38:00,09:52:00,840
73,0630RJR,2026-03-10 10:30:00,10:37:00,420
74,0629TCR,2026-03-10 10:14:00,10:29:00,900
75,0631LHR,2026-03-10 09:52:00,10:04:00,720
76,0101EMS,2026-03-10 10:19:00,10:31:00,720
77,0102EMS,2026-03-10 09:46:00,09:56:00,600
78,0103BPS,2026-03-10 10:13:00,10:26:00,780
79,0104IBS,2026-03-10 10:50:00,11:04:00,840
80,0107LER,2026-03-10 10:30:00,10:40:00,600
81,0108MMS,2026-03-10 09:16:00,09:28:00,720
82,0109MJR,2026-03-10 09:49:00,10:00:00,660
83,0110RMS,2026-03-10 09:41:00,09:54:00,780
84,0111TAS,2026-03-10 09:40:00,09:47:00,420
85,0112DRR,2026-03-10 09:45:00,09:58:00,780
86,0113DGR,2026-03-10 09:56:00,10:03:00,420
87,0114MLR,2026-03-10 11:03:00,11:12:00,540
88,0115MHR,2026-03-10 09:54:00,10:08:00,840
89,0116CNR,2026-03-10 09:42:00,09:55:00,780
90,0117MSR,2026-03-10 09:42:00,09:56:00,840
91,0118TMS,2026-03-10 08:21:00,08:34:00,780
92,0119BIR,2026-03-10 10:02:00,10:15:00,780
93,0120ANS,2026-03-10 09:57:00,10:11:00,840
94,0121RPS,2026-03-10 10:02:00,10:14:00,720
95,0122VCR,2026-03-10 09:34:00,09:49:00,900
96,0123GVS,2026-03-10 09:35:00,09:46:00,660
97,0124PAS,2026-03-10 09:43:00,09:56:00,780
98,0126VLR,2026-03-10 09:23:00,09:37:00,840
99,0127CMS,2026-03-10 09:48:00,10:01:00,780
100,0128ALS,2026-03-10 09:44:00,09:56:00,720
101,0129APR,2026-03-10 10:16:00,10:30:00,840
102,0130FAR,2026-03-10 10:15:00,10:29:00,840
103,0132GAR,2026-03-10 10:20:00,10:32:00,720
104,0133BPS,2026-03-10 10:18:00,10:31:00,780
105,0136CJR,2026-03-10 10:33:00,10:40:00,420
106,0138NWR,2026-03-10 10:15:00,10:27:00,720
107,0140LMR,2026-03-10 10:28:00,10:42:00,840
108,0143EBR,2026-03-10 10:32:00,10:37:00,300
109,0144ZGR,2026-03-10 10:41:00,11:08:00,1620
110,0801HDR,2026-03-10 10:30:00,10:36:00,360
111,0802LAS,2026-03-10 10:25:00,10:33:00,480
112,0804GOR,2026-03-10 10:16:00,10:23:00,420
113,0803DPS,2026-03-10 10:35:00,10:47:00,720
114,0805BMS,2026-03-10 09:29:00,09:41:00,720
115,0806KHS,2026-03-10 09:46:00,09:52:00,360
116,0807OMR,2026-03-10 09:48:00,09:53:00,300
117,0901SMR,2026-03-10 10:19:00,10:31:00,720
118,0903DJS,2026-03-10 10:26:00,10:39:00,780
119,0902SIS,2026-03-10 10:40:00,10:52:00,720
120,0904KJS,2026-03-10 09:34:00,09:45:00,660
121,0905SLR,2026-03-10 10:12:00,10:22:00,600
122,0401BDS,2026-03-10 09:58:00,10:12:00,840
123,0404DER,2026-03-10 09:57:00,10:12:00,900
124,0405RCR,2026-03-10 10:20:00,10:36:00,960
125,0406BBS,2026-03-10 11:22:00,11:43:00,1260
126,0408SJS,2026-03-10 11:23:00,11:42:00,1140
127,0409HCR,2026-03-10 10:31:00,10:42:00,660
128,0410FMS,2026-03-10 10:47:00,10:03:00,420
129,0413MMR,2026-03-10 09:14:00,09:29:00,900
130,0414PVR,2026-03-10 09:52:00,10:04:00,720
131,0420MCR,2026-03-10 14:31:00,14:45:00,840

In [38]:
def decouper_eda_par_bloc(df_eda, duree_bloc1, duree_bloc2, duree_bloc3, delta, duree_ecriture):
    """
    Découpe un EDA en 3 blocs en prenant en compte le retard (delta)
    pour ajuster la durée du bloc 1.
    """

    df_eda = df_eda.copy()
    
    if len(df_eda) < 3:
        print(f"⚠️ {pid} : Fichier trop court pour découpages")
        return None

    # ===== Lire timestamp initial et fréquence =====
    ts_unix = df_eda.iloc[0, 0]  # première ligne, première colonne
    freq_hz = df_eda.iloc[1, 0]  # deuxième ligne, première colonne

    try:
        t0 = datetime.datetime.fromtimestamp(float(ts_unix))
        delta_sec = 1.0 / 4  # fréquence EDA fixe 4 Hz
    except Exception as e:
        print(f"⚠️ {pid} : Impossible de lire timestamp/freq : {e}")
        return None

    # ===== Générer colonne Timestamp =====
    nb_lignes = len(df_eda) - 2
    timestamps = [t0 + datetime.timedelta(seconds=i * delta_sec) for i in range(nb_lignes)]
    df_eda_data = df_eda.iloc[2:].copy()
    df_eda_data["Timestamp"] = timestamps
    t_fin_rr = df_eda_data["Timestamp"].max()

    # ===== Récupérer durées des blocs =====
    durees = get_durees_blocs(pid, feuille)
    duree_bloc1 = durees["bloc1_sec"]
    duree_ecriture = durees["duree_ecriture_sec"]
    duree_bloc2 = durees["bloc2_sec"]
    duree_bloc3 = durees["bloc3_sec"]

    # ===== Récupérer delta pour ce PID =====
    delta_row = df_offset_eda.loc[df_offset_eda["Numero_inclusion"].str.upper() == pid.upper()]
    if delta_row.empty:
        delta = 0
    else:
        delta = float(delta_row["delta_retard_sec"].values[0])

    # ===== Bornes temporelles avec delta =====
    fin_bloc1 = t0 + pd.Timedelta(seconds=max(0, duree_bloc1 - delta))
    debut_bloc2 = fin_bloc1 + pd.Timedelta(seconds=duree_ecriture)
    fin_bloc2 = debut_bloc2 + pd.Timedelta(seconds=duree_bloc2)
    fin_bloc3 = fin_bloc2 + pd.Timedelta(seconds=duree_bloc3)
    fin_bloc3 = min(fin_bloc3, t_fin_rr)  # sécurité

    # ===== Découpage =====
    blocs = {
        "bloc1": df_eda_data[(df_eda_data["Timestamp"] >= t0) & (df_eda_data["Timestamp"] < fin_bloc1)],
        "bloc2": df_eda_data[(df_eda_data["Timestamp"] >= debut_bloc2) & (df_eda_data["Timestamp"] < fin_bloc2)],
        "bloc3": df_eda_data[(df_eda_data["Timestamp"] >= fin_bloc2) & (df_eda_data["Timestamp"] <= fin_bloc3)],
        "bornes": {
            "t0": t0,
            "fin_bloc1": fin_bloc1,
            "debut_bloc2": debut_bloc2,
            "fin_bloc2": fin_bloc2,
            "fin_bloc3": fin_bloc3,
            "t_fin_rr": t_fin_rr,
            "delta_sec": delta
        }
    }

    return blocs

In [39]:
def convertir_et_normaliser_heure(x):
    """
    Convertit n'importe quel format d'heure Excel / texte / datetime en pd.Timestamp
    normalisé sur le 1900-01-01, ne gardant que l'heure, minute, seconde.
    """
    if pd.isna(x):
        return pd.NaT

    # Excel numérique → fraction de jour ou date complète
    if isinstance(x, (int, float)):
        seconds = (float(x) * 24 * 3600) % (24*3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # Timestamp ou datetime → on garde juste l'heure
    if isinstance(x, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=x.hour, minute=x.minute, second=x.second
        )

    # Texte
    try:
        t = pd.to_datetime(str(x).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

In [40]:
def get_durees_blocs(pid, feuille):
    """
    Récupère les durées pour les 3 blocs et la durée d'écriture à partir de df_excel_global
    pour un PID donné et une feuille donnée.
    
    La durée d'écriture sert à décaler le début du bloc 2.
    Si la durée n'est pas renseignée ou NR, on met 7 minutes (420 s) par défaut.
    """
    pid = str(pid).upper()
    
    # ===== Bloc 1 =====
    df_b1 = pd.DataFrame(resultats_bloc1[feuille]["df"])
    ligne = df_b1.loc[df_b1["Numero_inclusion"].str.upper() == pid]
    if ligne.empty:
        raise ValueError(f"PID {pid} absent du bloc 1 dans la feuille {feuille}")
    d1 = ligne["duree_bloc1"].values[0]

    # ===== Durée écriture =====
    # On part de df_excel_global
    ligne_excel = df_excel_global.loc[df_excel_global["Numero_inclusion"].str.upper() == pid]
    if ligne_excel.empty:
        val_ecriture = 420  # défaut si absent
    else:
        val_ecriture = ligne_excel["duree_ecriture_sec"].values[0]
        if pd.isna(val_ecriture) or val_ecriture < 0:
            val_ecriture = 420  # défaut pour NR ou vide

    # ===== Bloc 2 =====
    df_b2 = pd.DataFrame(resultats_bloc2[feuille]["df"])
    d2 = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, "duree_bloc2"].values[0]

    # ===== Bloc 3 =====
    df_b3 = pd.DataFrame(resultats_bloc3[feuille]["df"])
    d3 = df_b3.loc[df_b3["Numero_inclusion"].str.upper() == pid, "duree_bloc3"].values[0]

    return {
        "bloc1_sec": d1 * 60,
        "duree_ecriture_sec": val_ecriture,  # durée spécifique du candidat
        "bloc2_sec": d2 * 60,
        "bloc3_sec": d3 * 60,
    }

In [41]:
# ===== Dossiers =====
input_dir = os.path.join(os.path.expanduser("~"), "Desktop", "EDA_v4_tronqués")
output_dir = os.path.join(os.path.expanduser("~"), "Desktop", "EDA_v4_tronque_blocs")
os.makedirs(output_dir, exist_ok=True)

resultats_decoupage = {}

# ===== Boucle UNIQUEMENT sur les fichiers tronqués =====
for fichier in os.listdir(input_dir):

    if not fichier.lower().endswith(".csv"):
        continue

    chemin_eda = os.path.join(input_dir, fichier)

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", fichier.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {fichier}")
        continue

    pid = match.group()

    # ===== Récupération de la feuille associée =====
    ligne = df_global.loc[df_global["Numero_inclusion"] == pid]
    if ligne.empty:
        print(f"⚠️ Feuille introuvable pour {pid}")
        continue

    feuille = ligne["Feuille"].values[0]

    print(f"\n--- Découpage {pid} ({feuille}) ---")

    # ===== Lecture EDA =====
    try:
        df_rr = pd.read_csv(chemin_eda, header = None)
    except Exception as e:
        print(f"❌ Lecture impossible {pid} : {e}")
        continue

    # ===== Récupération des durées =====
    try:
        durees = get_durees_blocs(pid, feuille)
    except Exception as e:
        print(f"⚠️ Impossible de récupérer les durées pour {pid} ({feuille}) : {e}")
        continue
        
    delta_row = df_offset_eda.loc[df_offset_eda["Numero_inclusion"].str.upper() == pid.upper()]
    if delta_row.empty:
        delta_val = 0
    else:
        delta_val = float(delta_row["delta_retard_sec"].values[0])
        
    # ===== Découpage =====
    decoupe = decouper_eda_par_bloc(
        df_eda=df_rr,
        duree_ecriture=durees["duree_ecriture_sec"],
        duree_bloc1=durees["bloc1_sec"],
        duree_bloc2=durees["bloc2_sec"],
        duree_bloc3=durees["bloc3_sec"],
        delta = delta_val
    )

    if decoupe is None:
        print(f"⚠️ Découpage vide pour {pid}")
        continue

    # ===== Sauvegarde par bloc =====
    for bloc in ["bloc1", "bloc2", "bloc3"]:
        df_bloc = decoupe[bloc]

        if df_bloc.empty:
            print(f"⚠️ {pid} {bloc} vide")
            continue

        nom_sortie = f"{pid}_{bloc}.csv"
        df_bloc.to_csv(
            os.path.join(output_dir, nom_sortie),
            index=False
        )

    # ===== Stockage mémoire =====
    resultats_decoupage[pid] = decoupe

    print(
        f"✔ {pid} | "
        f"B1={len(decoupe['bloc1'])} | "
        f"B2={len(decoupe['bloc2'])} | "
        f"B3={len(decoupe['bloc3'])}"
    )

print("\n✅ Découpage terminé")
print("📁 Résultats dans :", output_dir)

--- Découpage 0101CAR (APHM) ---
✔ 0101CAR | B1=2908 | B2=17040 | B3=13680

--- Découpage 0101EMS (LPC) ---
✔ 0101EMS | B1=8640 | B2=9120 | B3=10800

--- Découpage 0102EMS (LPC) ---
✔ 0102EMS | B1=2244 | B2=6000 | B3=9017

--- Découpage 0102PCR (APHM) ---
✔ 0102PCR | B1=3124 | B2=14160 | B3=9840

--- Découpage 0103BPS (LPC) ---
✔ 0103BPS | B1=7120 | B2=8400 | B3=9360

--- Découpage 0104FJS (APHM) ---
✔ 0104FJS | B1=3680 | B2=9600 | B3=9600

--- Découpage 0104IBS (LPC) ---
✔ 0104IBS | B1=6960 | B2=7680 | B3=9600

--- Découpage 0105PNR (APHM) ---
✔ 0105PNR | B1=3340 | B2=10320 | B3=11280

--- Découpage 0107DSS (APHM) ---
✔ 0107DSS | B1=5596 | B2=9120 | B3=6480

--- Découpage 0107LER (LPC) ---
✔ 0107LER | B1=4800 | B2=9600 | B3=10320

--- Découpage 0108MMS (LPC) ---
✔ 0108MMS | B1=2296 | B2=7680 | B3=10560

--- Découpage 0109MJR (LPC) ---
✔ 0109MJR | B1=3416 | B2=8880 | B3=10560

--- Découpage 0110LPR (APHM) ---
✔ 0110LPR | B1=3348 | B2=12240 | B3=13679

--- Découpage 0110RMS (LPC) ---
✔ 0110RMS | B1=2232 | B2=7680 | B3=10080

--- Découpage 0111MNR (APHM) ---
✔ 0111MNR | B1=4484 | B2=10080 | B3=12981

--- Découpage 0111TAS (LPC) ---
✔ 0111TAS | B1=2856 | B2=8160 | B3=10080

--- Découpage 0112BSR (APHM) ---
✔ 0112BSR | B1=7328 | B2=8400 | B3=13440

--- Découpage 0112DRR (LPC) ---
✔ 0112DRR | B1=2268 | B2=7920 | B3=11280

--- Découpage 0113DGR (LPC) ---
✔ 0113DGR | B1=3044 | B2=9120 | B3=9615

--- Découpage 0114LMS (APHM) ---
✔ 0114LMS | B1=6404 | B2=12000 | B3=6960

--- Découpage 0114MLR (LPC) ---
✔ 0114MLR | B1=6756 | B2=8880 | B3=11760

--- Découpage 0115MHR (LPC) ---
✔ 0115MHR | B1=6944 | B2=7200 | B3=11760

--- Découpage 0116CNR (LPC) ---
✔ 0116CNR | B1=3900 | B2=10080 | B3=13445

--- Découpage 0116VAR (APHM) ---
✔ 0116VAR | B1=7656 | B2=12480 | B3=15360

--- Découpage 0117MSR (LPC) ---
✔ 0117MSR | B1=3576 | B2=8640 | B3=11280

--- Découpage 0118TMS (LPC) ---
✔ 0118TMS | B1=5520 | B2=8640 | B3=11040

--- Découpage 0119BIR (LPC) ---
✔ 0119BIR | B1=3120 | B2=7920 | B3=10560

--- Découpage 0119LJS (APHM) ---
✔ 0119LJS | B1=7696 | B2=9840 | B3=11280

--- Découpage 0120ANS (LPC) ---
✔ 0120ANS | B1=2468 | B2=6960 | B3=10560

--- Découpage 0121MJR (APHM) ---
✔ 0121MJR | B1=5460 | B2=11520 | B3=16080

--- Découpage 0121RPS (LPC) ---
✔ 0121RPS | B1=6676 | B2=9360 | B3=11520

--- Découpage 0122BDS (APHM) ---
✔ 0122BDS | B1=6104 | B2=8880 | B3=5040

--- Découpage 0122VCR (LPC) ---
✔ 0122VCR | B1=3732 | B2=9120 | B3=11520

--- Découpage 0123GVS (LPC) ---
✔ 0123GVS | B1=2880 | B2=6720 | B3=9600

--- Découpage 0123RMS (APHM) ---
✔ 0123RMS | B1=6052 | B2=12960 | B3=8160

--- Découpage 0124PAS (LPC) ---
✔ 0124PAS | B1=3780 | B2=8160 | B3=8880

--- Découpage 0126VLR (LPC) ---
✔ 0126VLR | B1=4220 | B2=7200 | B3=9600

--- Découpage 0127CMS (LPC) ---
✔ 0127CMS | B1=3120 | B2=8880 | B3=10133

--- Découpage 0128ALS (LPC) ---
✔ 0128ALS | B1=2540 | B2=7440 | B3=10800

--- Découpage 0129APR (LPC) ---
✔ 0129APR | B1=8332 | B2=11280 | B3=14965

--- Découpage 0130FAR (LPC) ---
✔ 0130FAR | B1=6812 | B2=10320 | B3=10560

--- Découpage 0132GAR (LPC) ---
✔ 0132GAR | B1=4320 | B2=8400 | B3=10320

--- Découpage 0133BPS (LPC) ---
✔ 0133BPS | B1=5908 | B2=8160 | B3=10320

--- Découpage 0136CJR (LPC) ---
✔ 0136CJR | B1=3688 | B2=9360 | B3=10080

--- Découpage 0138NWR (LPC) ---
✔ 0138NWR | B1=3312 | B2=10560 | B3=11040

--- Découpage 0140LMR (LPC) ---
✔ 0140LMR | B1=5760 | B2=12240 | B3=14997

--- Découpage 0143EBR (LPC) ---
✔ 0143EBR | B1=6480 | B2=11520 | B3=13200

--- Découpage 0144ZGR (LPC) ---
✔ 0144ZGR | B1=7824 | B2=16560 | B3=14400

--- Découpage 0302ZMR (CAEN) ---
✔ 0302ZMR | B1=2740 | B2=8880 | B3=8640

--- Découpage 0304VMR (CAEN) ---
✔ 0304VMR | B1=4264 | B2=11040 | B3=8880

--- Découpage 0305LCR (CAEN) ---
✔ 0305LCR | B1=2360 | B2=10800 | B3=8880

--- Découpage 0307SMR (CAEN) ---
✔ 0307SMR | B1=5068 | B2=13200 | B3=9600

--- Découpage 0308RGR (CAEN) ---
✔ 0308RGR | B1=2532 | B2=9600 | B3=6000

--- Découpage 0310ACS (CAEN) ---
✔ 0310ACS | B1=3752 | B2=13920 | B3=10560

--- Découpage 0311CJS (CAEN) ---
✔ 0311CJS | B1=5492 | B2=11280 | B3=11520

--- Découpage 0313FPR (CAEN) ---
✔ 0313FPR | B1=1716 | B2=9840 | B3=8160

--- Découpage 0315VCS (CAEN) ---
✔ 0315VCS | B1=3788 | B2=10080 | B3=5760

--- Découpage 0316TMS (CAEN) ---
✔ 0316TMS | B1=1724 | B2=12000 | B3=10320

--- Découpage 0317LGS (CAEN) ---
✔ 0317LGS | B1=4476 | B2=10560 | B3=8400

--- Découpage 0319LJS (CAEN) ---
✔ 0319LJS | B1=1972 | B2=10080 | B3=5520

--- Découpage 0321DRR (CAEN) ---
✔ 0321DRR | B1=3432 | B2=9600 | B3=8160

--- Découpage 0322RMS (CAEN) ---
✔ 0322RMS | B1=1828 | B2=7680 | B3=7440

--- Découpage 0323RFS (CAEN) ---
✔ 0323RFS | B1=2264 | B2=11520 | B3=6480

--- Découpage 0324LMR (CAEN) ---
✔ 0324LMR | B1=2116 | B2=10800 | B3=6000

--- Découpage 0329NMR (CAEN) ---
✔ 0329NMR | B1=3332 | B2=11280 | B3=8880

--- Découpage 0331GRS (CAEN) ---
✔ 0331GRS | B1=2380 | B2=12720 | B3=9360

--- Découpage 0333MMS (CAEN) ---
✔ 0333MMS | B1=1708 | B2=12720 | B3=4080

--- Découpage 0334TVS (CAEN) ---
✔ 0334TVS | B1=1484 | B2=9600 | B3=4560

--- Découpage 0337BFS (CAEN) ---
✔ 0337BFS | B1=3240 | B2=12240 | B3=9600

--- Découpage 0338JBS (CAEN) ---
✔ 0338JBS | B1=2360 | B2=11280 | B3=9120

--- Découpage 0339NPR (CAEN) ---
✔ 0339NPR | B1=3072 | B2=9120 | B3=8160

--- Découpage 0340BAR (CAEN) ---
✔ 0340BAR | B1=3396 | B2=9120 | B3=4320

--- Découpage 0341LJS (CAEN) ---
✔ 0341LJS | B1=2052 | B2=8880 | B3=8640

--- Découpage 0342VNS (CAEN) ---
✔ 0342VNS | B1=2688 | B2=9120 | B3=5040

--- Découpage 0343PAS (CAEN) ---
✔ 0343PAS | B1=4036 | B2=8160 | B3=8400

--- Découpage 0345LAR (CAEN) ---
✔ 0345LAR | B1=3536 | B2=13680 | B3=5760

--- Découpage 0346GLS (CAEN) ---
✔ 0346GLS | B1=2384 | B2=11040 | B3=8880

--- Découpage 0347DMR (CAEN) ---
✔ 0347DMR | B1=3688 | B2=9600 | B3=10320

--- Découpage 0348GCR (CAEN) ---
✔ 0348GCR | B1=4560 | B2=13920 | B3=8400

--- Découpage 0350MYR (CAEN) ---
✔ 0350MYR | B1=2136 | B2=11520 | B3=10320

--- Découpage 0351FIR (CAEN) ---
✔ 0351FIR | B1=2812 | B2=8880 | B3=9120

--- Découpage 0352RNR (CAEN) ---
✔ 0352RNR | B1=2640 | B2=9600 | B3=8400

--- Découpage 0356DMS (CAEN) ---
✔ 0356DMS | B1=4124 | B2=11280 | B3=10800

--- Découpage 0401BDS (CERCA) ---
✔ 0401BDS | B1=4996 | B2=11760 | B3=11040

--- Découpage 0401TSS (POITIERS) ---
✔ 0401TSS | B1=4800 | B2=12720 | B3=15840

--- Découpage 0402LLS (POITIERS) ---
✔ 0402LLS | B1=7200 | B2=11040 | B3=11520

--- Découpage 0403DCR (POITIERS) ---
✔ 0403DCR | B1=2640 | B2=9840 | B3=12240

--- Découpage 0404CYS (POITIERS) ---
✔ 0404CYS | B1=5072 | B2=13200 | B3=6480

--- Découpage 0404DER (CERCA) ---
✔ 0404DER | B1=2248 | B2=12000 | B3=9360

--- Découpage 0405RCR (CERCA) ---
✔ 0405RCR | B1=3180 | B2=10560 | B3=9120

--- Découpage 0406BBS (CERCA) ---
✔ 0406BBS | B1=4800 | B2=10080 | B3=11520

--- Découpage 0406MCS (POITIERS) ---
✔ 0406MCS | B1=5228 | B2=16320 | B3=12240

--- Découpage 0407LJR (POITIERS) ---
✔ 0407LJR | B1=4252 | B2=10560 | B3=11760

--- Découpage 0408BCS (POITIERS) ---
✔ 0408BCS | B1=3076 | B2=9840 | B3=4080

--- Découpage 0408SJS (CERCA) ---
✔ 0408SJS | B1=10696 | B2=12960 | B3=12960

--- Découpage 0409HCR (CERCA) ---
✔ 0409HCR | B1=1616 | B2=9120 | B3=11280

--- Découpage 0410FMS (CERCA) ---
✔ 0410FMS | B1=3984 | B2=25440 | B3=240

--- Découpage 0411VES (POITIERS) ---
✔ 0411VES | B1=3376 | B2=6960 | B3=11760

--- Découpage 0412ANS (POITIERS) ---
✔ 0412ANS | B1=6024 | B2=9600 | B3=10560

--- Découpage 0413HFS (POITIERS) ---
✔ 0413HFS | B1=7572 | B2=11520 | B3=11520

--- Découpage 0413MMR (CERCA) ---
✔ 0413MMR | B1=2336 | B2=11040 | B3=11280

--- Découpage 0414PVR (CERCA) ---
✔ 0414PVR | B1=3540 | B2=12240 | B3=12240

--- Découpage 0501MBS (ROUEN) ---
✔ 0501MBS | B1=2896 | B2=10800 | B3=9600

--- Découpage 0502LIR (ROUEN) ---
✔ 0502LIR | B1=3600 | B2=9600 | B3=11040

--- Découpage 0503LCR (ROUEN) ---
✔ 0503LCR | B1=3120 | B2=8880 | B3=9600

--- Découpage 0504BCS (ROUEN) ---
✔ 0504BCS | B1=3284 | B2=8400 | B3=10800

--- Découpage 0505PPR (ROUEN) ---
✔ 0505PPR | B1=3360 | B2=12720 | B3=11280

--- Découpage 0507BDS (ROUEN) ---
✔ 0507BDS | B1=6000 | B2=9120 | B3=11520

--- Découpage 0508SRR (ROUEN) ---
✔ 0508SRR | B1=3580 | B2=9360 | B3=10320

--- Découpage 0510DFS (ROUEN) ---
✔ 0510DFS | B1=3148 | B2=10800 | B3=11040

--- Découpage 0512RCR (ROUEN) ---
✔ 0512RCR | B1=3504 | B2=9600 | B3=10560

--- Découpage 0513EBS (ROUEN) ---
✔ 0513EBS | B1=4256 | B2=9360 | B3=9360

--- Découpage 0514LPS (ROUEN) ---
✔ 0514LPS | B1=3948 | B2=7920 | B3=10560

--- Découpage 0515FAR (ROUEN) ---
✔ 0515FAR | B1=1812 | B2=9840 | B3=13200

--- Découpage 0629TCR (LAVERAN) ---
✔ 0629TCR | B1=5528 | B2=13920 | B3=9600

--- Découpage 0630RJR (LAVERAN) ---
✔ 0630RJR | B1=5244 | B2=8400 | B3=8640

--- Découpage 0631LHR (LAVERAN) ---
✔ 0631LHR | B1=4304 | B2=6480 | B3=8640

--- Découpage 0801HDR (SAINTE-MARGUERITE) ---
✔ 0801HDR | B1=3404 | B2=10560 | B3=9120

--- Découpage 0802LAS (SAINTE-MARGUERITE) ---
✔ 0802LAS | B1=4916 | B2=11040 | B3=9120

--- Découpage 0803DPS (SAINTE-MARGUERITE) ---
✔ 0803DPS | B1=3832 | B2=12720 | B3=11280

--- Découpage 0804GOR (SAINTE-MARGUERITE) ---
✔ 0804GOR | B1=5568 | B2=9120 | B3=11040

--- Découpage 0805BMS (SAINTE-MARGUERITE) ---
✔ 0805BMS | B1=4300 | B2=9600 | B3=10320

--- Découpage 0806KHS (SAINTE-MARGUERITE) ---
✔ 0806KHS | B1=4432 | B2=8640 | B3=10800

--- Découpage 0807OMR (SAINTE-MARGUERITE) ---
✔ 0807OMR | B1=2556 | B2=8880 | B3=9360

--- Découpage 0901SMR (CGD) ---
✔ 0901SMR | B1=5888 | B2=10320 | B3=11760

--- Découpage 0902SIS (CGD) ---
✔ 0902SIS | B1=7500 | B2=8400 | B3=7200

--- Découpage 0903DJS (CGD) ---
✔ 0903DJS | B1=6960 | B2=11040 | B3=10800

--- Découpage 0904KJS (CGD) ---
✔ 0904KJS | B1=7352 | B2=9840 | B3=10080

--- Découpage 0905SLR (CGD) ---
✔ 0905SLR | B1=5408 | B2=10320 | B3=10320

✅ Découpage terminé
📁 Résultats dans : C:\Users\judupont\Desktop\EDA_v4_tronque_blocs

# DATA FRAME DIRECT 
lignes_globales = []

for pid, decoupe in resultats_decoupage.items():

    # ===== Condition =====
    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    # ===== Offset =====
    offset_sec = abs(
        df_controle_durees.loc[
            df_controle_durees["Numero_inclusion"] == pid,
            "ecart_sec"
        ].values[0]
    )

    bornes = decoupe["bornes"]

    for nom_bloc in ["bloc1", "bloc2", "bloc3"]:

        df_bloc = decoupe[nom_bloc]

        if df_bloc.empty:
            continue

        # =====================================================
        # CAS 1 : RR fourni par l'appareil (RtoR)
        # =====================================================
        if "RtoR" in df_bloc.columns:

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row["Timestamp"],
                    "RtoR": row["RtoR"],      
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 2 : RR calculé (temps_ms / rr_ms)
        # =====================================================
        elif {"temps_ms", "rr_ms"}.issubset(df_bloc.columns):

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row.get("Timestamp", pd.NaT),
                    "RtoR": row["rr_ms"] / 1000,  # ms → sec
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 3 : Timestamp seul
        # =====================================================
        else:
            for ts in df_bloc["Timestamp"]:
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": ts,
                    "RtoR": None,
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

df_rr_global = pd.DataFrame(lignes_globales)

# DATA FRAME IMBRIQUE
lignes_patients = []

for pid, decoupe in resultats_decoupage.items():

    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    lignes_patients.append({
        "Numero_inclusion": pid,
        "Condition": condition,
        "baseline": decoupe["bloc1"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc2": decoupe["bloc2"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc3": decoupe["bloc3"][["Timestamp", "RtoR"]].reset_index(drop=True),
    })

df_patients = pd.DataFrame(lignes_patients)

In [ ]:
## Traitment pour passer le fichier dans kubios