# Bibliotheque + lecture Excel

In [1]:
import pandas as pd 
import numpy as np 
import os
import re
from collections import defaultdict
from datetime import datetime, timedelta
import datetime

In [2]:
df = pd.read_excel('AGING_Ceinture_Montre (avec groupe).xlsx',sheet_name=None)

C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
df.keys()

dict_keys(['APHM', 'CAEN', 'POITIERS', 'ROUEN', 'LAVERAN', 'LPC', 'SAINTE-MARGUERITE', 'CGD', 'CERCA', 'Effectifs ceinture', 'Effectifs montre', 'CODEBOOK '])

# Vérification blocs

In [4]:
 # ===== Conversion heures du Excel =====
def convertir_heure_excel_ou_texte(x):
     if pd.isna(x):
        return pd.NaT
     if isinstance(x, (int, float)):
        return pd.to_datetime(x, unit="D", origin="1899-12-30")
     try:
        return pd.to_datetime(str(x).strip(), format="%H:%M")
     except Exception:
         try:
             return pd.to_datetime(str(x).strip())
         except Exception:
            return pd.NaT

In [5]:
def analyser_feuille_bloc(
    df,
    nom_feuille,
    col_debut,
    col_fin,
    nom_bloc
):
    print(f"\n--- Feuille : {nom_feuille} | {nom_bloc} ---")

    col_id = "Numero_inclusion"

    # ===== Dictionnaire des colonnes atitrées manuellement =====
    REGLES_CANDIDATS = {
        ("CAEN", "bloc2", None): {"col_fin": "heure_rappel_cond_v4"},
        ("CAEN", "bloc3", None): {"col_debut": "heure_rappel_cond_v4"},
        ("CAEN", "bloc2", "0326BJR"): {"col_fin": "heure_fluence_sem_v4"},
        ("CAEN", "bloc3", "0326BJR"): {"col_debut": "heure_fluence_sem_v4"},

        ("POITIERS", 'bloc2', "0408BCS"): {"col_fin": "heure_rappel_cond_v4"},
        ("POITIERS", 'bloc3', "0408BCS"): {"col_debut": "heure_rappel_cond_v4"},

        ("LPC", 'bloc2', "0112DRR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0112DRR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0115MHR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0115MHR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0141HJR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0141HJR"): {"col_debut": "heure_rappel_cond_v4"},
        ("LPC", 'bloc2', "0144ZGR"): {"col_fin": "heure_rappel_cond_v4"},
        ("LPC", 'bloc3', "0144ZGR"): {"col_debut": "heure_rappel_cond_v4"},

        ("CERCA", 'bloc2', "0406BBS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0406BBS"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0408SJS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0408SJS"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0409HCR"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0409HCR"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0410FMS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0410FMS"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0418TJR"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0418TJR"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0420MCR"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0420MCR"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0423SVS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0423SVS"): {"col_debut": "heure_nback_v4"},
        
        ("CERCA", 'bloc2', "0432CGS"): {"col_fin": "heure_nback_v4"},
        ("CERCA", 'bloc3', "0432CGS"): {"col_debut": "heure_nback_v4"},
        
    }

    # ===== Colonnes effectives par défaut =====
    col_debut_effective = col_debut
    col_fin_effective = col_fin

    # ===== Application des règles =====
    for (centre, bloc, candidat), regle in REGLES_CANDIDATS.items():
        if centre != nom_feuille:
            continue
        if bloc is not None and bloc != nom_bloc:
            continue
        if candidat is not None:
            mask_candidat = df[col_id] == candidat
            if not mask_candidat.any():
                continue

        # Colonnes à remplacer
        if "col_debut" in regle:
            col_debut_effective = regle["col_debut"]
        if "col_fin" in regle:
            col_fin_effective = regle["col_fin"]

        print(f"🔧 Règle appliquée → centre={centre}, bloc={bloc}, candidat={candidat}")

    # ===== Vérification colonnes =====
    for col in [col_debut_effective, col_fin_effective, col_id]:
        if col not in df.columns:
            print(f"❌ Colonne manquante : {col}")
            return None

    # ===== Copie du DataFrame =====
    df = df.copy()

    # Conversion des colonnes utilisées
    df[col_debut_effective] = df[col_debut_effective].apply(convertir_heure_excel_ou_texte)
    df[col_fin_effective] = df[col_fin_effective].apply(convertir_heure_excel_ou_texte)

    # ===== Durée =====
    col_duree = f"duree_{nom_bloc}"
    col_rejet = f"rejeter_{nom_bloc}"

    df[col_duree] = (df[col_fin_effective] - df[col_debut_effective]).dt.total_seconds() / 60

    # Passage de minuit
    df.loc[df[col_duree] < 0, col_duree] += 24 * 60

    # ===== Masques =====
    mask_manquant = df[col_duree].isna()
    mask_valide = df[col_duree].notna() & (df[col_duree] > 0)

    # ===== Statistiques sur la durée =====
    moyenne = df.loc[mask_valide, col_duree].mean()
    ecart_type = df.loc[mask_valide, col_duree].std()
    print(f"Moyenne = {moyenne:.2f} min")
    print(f"Écart-type = {ecart_type:.2f} min")

    borne_inf = moyenne - 2 * ecart_type

    # ===== Filtre =====
    df[col_rejet] = 0
    df.loc[mask_manquant, col_rejet] = 2

    mask_rejet = df[col_duree] < borne_inf

    # Règle spécifique bloc 1
    if nom_bloc == "bloc1":
        mask_rejet = mask_rejet | (df[col_duree] < 10)

    df.loc[mask_valide & mask_rejet, col_rejet] = 1

    # ===== Résumé =====
    print(f"\nRésumé {col_rejet} :")
    print(df[col_rejet].value_counts().sort_index())

    return {
        "df": df,
        "moyenne": moyenne,
        "ecart_type": ecart_type,
        "rejets": {
            "manquant": df.loc[df[col_rejet] == 2, col_id].tolist(),
            "rejetes": df.loc[df[col_rejet] == 1, col_id].tolist(),
        }
    }

## Bloc 1

In [6]:
feuilles = [
    'APHM', 'CAEN', 'POITIERS', 'ROUEN',
    'LAVERAN', 'LPC', 'SAINTE-MARGUERITE',
    'CGD', 'CERCA'
]

resultats_bloc1 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc1[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_ceinture_v4",   
        col_fin="heure_anamnese_fin_v4",        
        nom_bloc="bloc1"
    )

============================================================

--- Feuille : APHM | bloc1 ---
Moyenne = 20.00 min
Écart-type = 8.72 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    15
1     3
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc1 ---
Moyenne = 13.33 min
Écart-type = 5.03 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    40
1     9
2     7
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc1 ---
Moyenne = 20.27 min
Écart-type = 7.04 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    11
2     4
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc1 ---
Moyenne = 17.13 min
Écart-type = 7.02 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc1 ---
Moyenne = 21.75 min
Écart-type = 2.22 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc1 ---
Moyenne = 19.16 min
Écart-type = 7.90 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    41
1     2
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc1 ---
Moyenne = 14.88 min
Écart-type = 6.60 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    7
1    1
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc1 ---
Moyenne = 26.40 min
Écart-type = 4.93 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc1 ---
Moyenne = 11.04 min
Écart-type = 9.12 min

Résumé rejeter_bloc1 :
rejeter_bloc1
0    12
1    15
2    13
Name: count, dtype: int64

## Bloc 2

In [7]:
resultats_bloc2 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_v4",  
        col_fin= "heure_nback_v4 (consignes)" ,         
        nom_bloc="bloc2"
    )

============================================================

--- Feuille : APHM | bloc2 ---
Moyenne = 46.72 min
Écart-type = 9.14 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    18
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2 ---
🔧 Règle appliquée → centre=CAEN, bloc=bloc2, candidat=None
🔧 Règle appliquée → centre=CAEN, bloc=bloc2, candidat=0326BJR
Moyenne = 44.57 min
Écart-type = 6.41 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    48
1     1
2     7
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2 ---
🔧 Règle appliquée → centre=POITIERS, bloc=bloc2, candidat=0408BCS
Moyenne = 46.00 min
Écart-type = 10.40 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    12
2     3
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2 ---
Moyenne = 40.47 min
Écart-type = 5.58 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2 ---
Moyenne = 40.00 min
Écart-type = 13.14 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2 ---
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0112DRR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0115MHR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0141HJR
🔧 Règle appliquée → centre=LPC, bloc=bloc2, candidat=0144ZGR
Moyenne = 37.30 min
Écart-type = 7.50 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    43
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2 ---
Moyenne = 41.88 min
Écart-type = 5.64 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2 ---
Moyenne = 41.60 min
Écart-type = 4.10 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2 ---
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0406BBS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0408SJS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0409HCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0410FMS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0418TJR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0420MCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0423SVS
🔧 Règle appliquée → centre=CERCA, bloc=bloc2, candidat=0432CGS
Moyenne = 44.31 min
Écart-type = 14.26 min

Résumé rejeter_bloc2 :
rejeter_bloc2
0    26
2    14
Name: count, dtype: int64

## Bloc 3

In [8]:
resultats_bloc3 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc3[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_nback_v4 (consignes)",   # à adapter si besoin
        col_fin="heure_fin_tests_v4",         # à adapter si besoin
        nom_bloc="bloc3"
    )

============================================================

--- Feuille : APHM | bloc3 ---
Moyenne = 46.33 min
Écart-type = 13.57 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    18
2     7
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc3 ---
🔧 Règle appliquée → centre=CAEN, bloc=bloc3, candidat=None
🔧 Règle appliquée → centre=CAEN, bloc=bloc3, candidat=0326BJR
Moyenne = 61.45 min
Écart-type = 198.00 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    49
2     7
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc3 ---
🔧 Règle appliquée → centre=POITIERS, bloc=bloc3, candidat=0408BCS
Moyenne = 43.50 min
Écart-type = 13.26 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    12
2     3
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc3 ---
Moyenne = 44.67 min
Écart-type = 6.21 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc3 ---
Moyenne = 41.75 min
Écart-type = 9.03 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc3 ---
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0112DRR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0115MHR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0141HJR
🔧 Règle appliquée → centre=LPC, bloc=bloc3, candidat=0144ZGR
Moyenne = 45.00 min
Écart-type = 6.96 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    41
1     2
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc3 ---
Moyenne = 43.25 min
Écart-type = 4.53 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc3 ---
Moyenne = 41.80 min
Écart-type = 7.12 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc3 ---
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0406BBS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0408SJS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0409HCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0410FMS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0418TJR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0420MCR
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0423SVS
🔧 Règle appliquée → centre=CERCA, bloc=bloc3, candidat=0432CGS
Moyenne = 46.14 min
Écart-type = 8.09 min

Résumé rejeter_bloc3 :
rejeter_bloc3
0    29
2    11
Name: count, dtype: int64

# Nombre de candidats qui passent toutes les conditions

In [9]:
def candidats_valides_tous_blocs_depuis_resultats(
    feuille,
    resultats_blocs,
    col_id="Numero_inclusion"
):
    """
     Un candidat est conservé si nous pouvons calculer la durée de tous ses blocs et si celles-ci respectent les conditions suivantes :
    - bloc 1 > 10 min
    - bloc2R/S et bloc 3 > mean - 2σ min
    
    resultats_blocs = dict {
        "bloc1": resultats_bloc1,
        "bloc2": resultats_bloc2,
        "bloc3": resultats_bloc3
    }
    """

    # Récupération du df de référence dans lequel sont renseignés les durées des blocs
    df_ref = resultats_blocs["bloc1"][feuille]["df"].copy()

    colonnes_rejet = []

    # Ajouter chaque colonne de rejet depuis chaque bloc
    for nom_bloc, res_bloc in resultats_blocs.items():
        col_rejet = f"rejeter_{nom_bloc}"
        if col_rejet not in res_bloc[feuille]["df"].columns:
            print(f"Colonne manquante : {col_rejet} dans {feuille}")
            return None

        df_ref[col_rejet] = res_bloc[feuille]["df"][col_rejet]
        colonnes_rejet.append(col_rejet)

    # Condition : tout à 0
    mask_valide = (df_ref[colonnes_rejet] == 0).all(axis=1)

    candidats_ok = df_ref.loc[mask_valide, col_id].tolist()
    candidats_rejetes = df_ref.loc[~mask_valide, col_id].tolist()

    print(f"\n=== {feuille} ===")
    print(f"Candidats valides sur TOUS les blocs : {len(candidats_ok)}")

    print("Liste des candidats conservés :")
    for pid in candidats_ok:
        print(f" - {pid}")

    return {
        "nb_valides": len(candidats_ok),
        "valides": candidats_ok,
        "rejetes": candidats_rejetes,
    }

In [10]:
resultats_globaux = {}

colonnes_blocs = [
    "rejeter_bloc1",
    "rejeter_bloc2",
    "rejeter_bloc3"
]

for feuille in feuilles:
    print("\n" + "=" * 70)
    print(f"Analyse globale – Feuille : {feuille}")

    # ===== Base : bloc 1 =====
    df_global = resultats_bloc1[feuille]["df"][
        ["Numero_inclusion", "rejeter_bloc1"]
    ].copy()

    # ===== Fusion bloc 2 =====
    df_global = df_global.merge(
        resultats_bloc2[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 3 =====
    df_global = df_global.merge(
        resultats_bloc3[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc3"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Affichage debug AVANT filtre =====
    print("\n📊 df_global AVANT fillna et filtres :")
    display(df_global)

    # ===== Sécurité : NaN → rejet (2) =====
    df_global[colonnes_blocs] = df_global[colonnes_blocs].fillna(2)

    mask = (
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    # ===== Extraction =====
    candidats_valides = df_global.loc[
        mask, "Numero_inclusion"
    ].tolist()

    candidats_rejetes = df_global.loc[
        ~mask, "Numero_inclusion"
    ].tolist()

    # ===== Résumés =====
    print(f"\nNombre total de candidats : {len(df_global)}")
    print(f"Candidats VALIDES (selon Condition) : {len(candidats_valides)}")
    print(f"Candidats REJETÉS : {len(candidats_rejetes)}")

    print("\nListe des candidats valides :")
    for pid in candidats_valides:
        print(f" - {pid}")

    # ===== Stockage =====
    resultats_globaux[feuille] = {
        "df": df_global,
        "valides": candidats_valides,
        "rejetes": candidats_rejetes,
        "n_valides": len(candidats_valides),
        "n_rejetes": len(candidats_rejetes),
    }

======================================================================
Analyse globale – Feuille : APHM

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0101CAR              0              0              0
1           0102PCR              0              0              0
2           0103SHS              1              0              0
3           0105PNR              0              0              0
4           0104FJS              0              0              0
5           0106JLS              1              0              0
6           0107DSS              0              0              0
7           0108BFS              1              0              0
8           0109GSS              0              0              0
9           0110LPR              0              0              0
10          0111MNR              0              0              0
11          0112BSR              0              0              0
12          0113BMR              2              2              2
13          0114LMS              0              0              0
14          0115CJR              2              2              2
15          0116VAR              0              0              0
16          0117POS              2              2              2
17          0118TNS              2              2              2
18          0119LJS              0              0              0
19          0120LCR              2              2              2
20          0121MJR              0              0              0
21          0122BDS              0              0              0
22          0123RMS              0              0              0
23          0124BAR              2              2              2
24          0125BMR              2              2              2

Nombre total de candidats : 25
Candidats VALIDES (selon Condition) : 15
Candidats REJETÉS : 10

Liste des candidats valides :
 - 0101CAR
 - 0102PCR
 - 0105PNR
 - 0104FJS
 - 0107DSS
 - 0109GSS
 - 0110LPR
 - 0111MNR
 - 0112BSR
 - 0114LMS
 - 0116VAR
 - 0119LJS
 - 0121MJR
 - 0122BDS
 - 0123RMS

======================================================================
Analyse globale – Feuille : CAEN

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0301GNR              2              2              2
1           0302ZMR              0              0              0
2           0303PAR              2              2              2
3           0304VMR              0              0              0
4           0305LCR              0              0              0
5           0307SMR              0              0              0
6           0306MDR              1              0              0
7           0308RGR              0              0              0
8           0309DBS              2              2              2
9           0311CJS              0              0              0
10          0310ACS              0              0              0
11          0315VCS              0              0              0
12          0318PMS              2              2              2
13          0313FPR              0              0              0
14          0312JMS              1              0              0
15          0316TMS              0              0              0
16          0314CDS              0              2              2
17          0317LGS              0              0              0
18          0319LJS              0              0              0
19          0320DGS              0              1              0
20          0321DRR              0              0              0
21          0323RFS              0              0              0
22          0322RMS              0              0              0
23          0324LMR              0              0              0
24          0325LCR              1              0              0
25          0327IAR              1              0              0
26          0326BJR              0              0              0
27          0328MPR              0              0              0
28          0330RTR              0              0              0
29          0329NMR              0              0              0
30          0331GRS              0              0              0
31          0332MCR              1              0              0
32          0333MMS              0              0              0
33          0334TVS              1              0              0
34          0335JMS              2              2              2
35          0336CBS              2              0              0
36          0337BFS              0              0              0
37          0338JBS              0              0              0
38          0339NPR              0              0              0
39          0340BAR              0              0              0
40          0341LJS              0              0              0
41          0342VNS              0              0              0
42          0343PAS              0              0              0
43          0344DBS              1              0              0
44          0345LAR              0              0              0
45          0349LLS              0              0              0
46          0347DMR              0              0              0
47          0346GLS              0              0              0
48          0348GCR              0              0              0
49          0350MYR              0              0              0
50          0351FIR              0              0              0
51          0353LNR              2              2              2
52          0352RNR              0              0              0
53          0354GKR              1              0              0
54          0355BAS              1              0              0
55          0356DMS              0              0              0

Nombre total de candidats : 56
Candidats VALIDES (selon Condition) : 38
Candidats REJETÉS : 18

Liste des candidats valides :
 - 0302ZMR
 - 0304VMR
 - 0305LCR
 - 0307SMR
 - 0308RGR
 - 0311CJS
 - 0310ACS
 - 0315VCS
 - 0313FPR
 - 0316TMS
 - 0317LGS
 - 0319LJS
 - 0321DRR
 - 0323RFS
 - 0322RMS
 - 0324LMR
 - 0326BJR
 - 0328MPR
 - 0330RTR
 - 0329NMR
 - 0331GRS
 - 0333MMS
 - 0337BFS
 - 0338JBS
 - 0339NPR
 - 0340BAR
 - 0341LJS
 - 0342VNS
 - 0343PAS
 - 0345LAR
 - 0349LLS
 - 0347DMR
 - 0346GLS
 - 0348GCR
 - 0350MYR
 - 0351FIR
 - 0352RNR
 - 0356DMS

======================================================================
Analyse globale – Feuille : POITIERS

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0401TSS              0              0              0
1           0402LLS              0              0              0
2           0403DCR              0              0              0
3           0405FCR              2              2              2
4           0404CYS              0              0              0
5           0406MCS              2              0              0
6           0407LJR              0              0              0
7           0408BCS              0              0              0
8           0409PHR              2              2              2
9           0410PGS              2              2              2
10          0413HFS              0              0              0
11          0411VES              0              0              0
12          0412ANS              0              0              0
13          0414PJS              0              0              0
14          0415VMR              0              0              0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 11
Candidats REJETÉS : 4

Liste des candidats valides :
 - 0401TSS
 - 0402LLS
 - 0403DCR
 - 0404CYS
 - 0407LJR
 - 0408BCS
 - 0413HFS
 - 0411VES
 - 0412ANS
 - 0414PJS
 - 0415VMR

======================================================================
Analyse globale – Feuille : ROUEN

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0501MBS              0              0              0
1           0502LIR              0              0              0
2           0503LCR              0              0              0
3           0504BCS              0              0              0
4           0505PPR              0              0              0
5           0506VMS              1              0              0
6           0508SRR              0              0              0
7           0507BDS              0              0              0
8           0509LGS              0              0              0
9           0510DFS              0              0              0
10          0511LCS              0              0              1
11          0512RCR              0              0              0
12          0513EBS              0              0              0
13          0514LPS              0              0              0
14          0515FAR              0              0              0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 13
Candidats REJETÉS : 2

Liste des candidats valides :
 - 0501MBS
 - 0502LIR
 - 0503LCR
 - 0504BCS
 - 0505PPR
 - 0508SRR
 - 0507BDS
 - 0509LGS
 - 0510DFS
 - 0512RCR
 - 0513EBS
 - 0514LPS
 - 0515FAR

======================================================================
Analyse globale – Feuille : LAVERAN

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0626MCS              0              0              0
1          0628DMR              2              2              2
2          0630RJR              0              0              0
3          0629TCR              0              0              0
4          0631LHR              0              0              0

Nombre total de candidats : 5
Candidats VALIDES (selon Condition) : 4
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0626MCS
 - 0630RJR
 - 0629TCR
 - 0631LHR

======================================================================
Analyse globale – Feuille : LPC

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0101EMS              0              0              0
1           0102EMS              0              0              0
2           0103BPS              0              0              0
3           0104IBS              0              0              0
4           0105HAR              1              0              0
5           0106DJR              0              0              0
6           0107LER              0              0              0
7           0108MMS              0              0              0
8           0109MJR              0              0              0
9           0110RMS              0              0              0
10          0111TAS              0              0              0
11          0112DRR              0              0              0
12          0113DGR              0              0              0
13          0114MLR              0              0              0
14          0115MHR              0              0              0
15          0116CNR              0              0              0
16          0117MSR              0              0              0
17          0118TMS              0              0              0
18          0119BIR              0              0              0
19          0120ANS              0              0              0
20          0121RPS              0              0              0
21          0122VCR              0              0              0
22          0123GVS              0              0              0
23          0124PAS              0              0              0
24          0125AMR              1              0              0
25          0126VLR              0              0              0
26          0127CMS              0              0              0
27          0128ALS              0              0              0
28          0129APR              0              0              0
29          0130FAR              0              0              0
30          0131CPS              0              0              1
31          0132GAR              0              0              0
32          0133BPS              0              0              0
33          0134IFR              0              0              1
34          0135KLS              2              2              2
35          0136CJR              0              0              0
36          0137BMS              0              0              0
37          0138NWR              0              0              0
38          0139BMR              0              0              0
39          0140LMR              0              0              0
40          0141HJR              0              0              0
41          0142LLS              0              0              0
42          0143EBR              0              0              0
43          0144ZGR              0              0              0

Nombre total de candidats : 44
Candidats VALIDES (selon Condition) : 39
Candidats REJETÉS : 5

Liste des candidats valides :
 - 0101EMS
 - 0102EMS
 - 0103BPS
 - 0104IBS
 - 0106DJR
 - 0107LER
 - 0108MMS
 - 0109MJR
 - 0110RMS
 - 0111TAS
 - 0112DRR
 - 0113DGR
 - 0114MLR
 - 0115MHR
 - 0116CNR
 - 0117MSR
 - 0118TMS
 - 0119BIR
 - 0120ANS
 - 0121RPS
 - 0122VCR
 - 0123GVS
 - 0124PAS
 - 0126VLR
 - 0127CMS
 - 0128ALS
 - 0129APR
 - 0130FAR
 - 0132GAR
 - 0133BPS
 - 0136CJR
 - 0137BMS
 - 0138NWR
 - 0139BMR
 - 0140LMR
 - 0141HJR
 - 0142LLS
 - 0143EBR
 - 0144ZGR

======================================================================
Analyse globale – Feuille : SAINTE-MARGUERITE

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0801HDR              0              0              0
1          0802LAS              0              0              0
2          0804GOR              0              0              0
3          0803DPS              0              0              0
4          0805BMS              0              0              0
5          0806KHS              0              0              0
6          0807OMR              0              0              0
7          0808PJR              1              0              0

Nombre total de candidats : 8
Candidats VALIDES (selon Condition) : 7
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0801HDR
 - 0802LAS
 - 0804GOR
 - 0803DPS
 - 0805BMS
 - 0806KHS
 - 0807OMR

======================================================================
Analyse globale – Feuille : CGD

📊 df_global AVANT fillna et filtres :

  Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0          0901SMR              0              0              0
1          0903DJS              0              0              0
2          0902SIS              0              0              0
3          0906DNR              2              2              2
4          0904KJS              0              0              0
5          0905SLR              0              0              0

Nombre total de candidats : 6
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 1

Liste des candidats valides :
 - 0901SMR
 - 0903DJS
 - 0902SIS
 - 0904KJS
 - 0905SLR

======================================================================
Analyse globale – Feuille : CERCA

📊 df_global AVANT fillna et filtres :

   Numero_inclusion  rejeter_bloc1  rejeter_bloc2  rejeter_bloc3
0           0401BDS              0              0              0
1           0402TFR              2              2              2
2           0404DER              0              0              0
3           0405RCR              0              0              0
4           0406BBS              0              0              0
5           0407HMS              2              2              2
6           0408SJS              0              0              0
7           0409HCR              0              0              0
8           0410FMS              0              0              0
9           0411NPR              2              2              2
10          0412CMS              1              0              0
11          0413MMR              1              0              0
12          0414PVR              0              0              0
13          0415HJS              1              0              0
14          0416CPR              2              2              2
15          0417FAS              1              0              0
16          0417KMS              1              0              0
17          0418MPR              0              0              0
18          0418TJR              1              2              2
19          0419CHR              1              0              0
20          0419SRR              1              2              2
21          0420MCR              0              0              0
22          0420LMR              1              2              2
23          0421ACS              1              0              0
24          0422LVR              1              0              0
25          0422WCS              1              2              0
26          0423SVS              0              0              0
27          0423RMR              2              2              2
28          0424GMS              1              2              0
29          0424BLR              1              0              0
30          0425CDS              2              0              0
31          0426DGS              2              2              2
32          0432CGS              0              2              2
33          0433RMR              2              0              0
34          0434GPS              2              0              0
35          0809VJR              1              2              0
36          0810LCR              2              2              2
37          0812DMS              2              0              0
38          0813PJS              2              0              0
39          0811MCS              2              0              0

Nombre total de candidats : 40
Candidats VALIDES (selon Condition) : 11
Candidats REJETÉS : 29

Liste des candidats valides :
 - 0401BDS
 - 0404DER
 - 0405RCR
 - 0406BBS
 - 0408SJS
 - 0409HCR
 - 0410FMS
 - 0414PVR
 - 0418MPR
 - 0420MCR
 - 0423SVS

In [11]:
total_valides = sum(
    res["n_valides"] for res in resultats_globaux.values()
)

print("=" * 70)
print(f"✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : {total_valides}")

======================================================================
✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : 143

# 144 candidats retenus

# Recherche des candidats et téléchargement de leur fichier V4 BB RR

In [12]:
import pandas as pd

# Afficher toutes les lignes
pd.set_option('display.max_rows', None)

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

# Afficher toute la largeur de chaque colonne
pd.set_option('display.max_colwidth', None)

## APHM

In [13]:
# ===== Racine aphm =====
racine_aphm = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS"

# ===== Exemple pour un centre (à dupliquer pour chaque centre) =====
centre = "APHM"
candidats_aphm = [c.upper() for c in resultats_globaux[centre]["valides"]]

rows = []

for root, dirs, files in os.walk(racine_aphm):

    if "V4" not in root.upper():
        continue

    for f in files:

        # Seulement CSV
        if not f.lower().endswith(".csv"):
            continue
        # Seulement BB_RR ou BR_RR
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== Détection du Numero_inclusion dans le chemin =====
        pid_trouve = None
        for pid in candidats_aphm:
            if pid in chemin_upper:
                pid_trouve = pid
                break
        if not pid_trouve:
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille": centre
        })

# ===== DataFrame =====
df_aphm = pd.DataFrame(rows)

# ===== Suppression doublons =====
df_aphm_final = (
    df_aphm
    .assign(priorite_ceinture=df_aphm["Chemin"].str.contains("CEINTURE", case=False))
    .sort_values(["Numero_inclusion", "priorite_ceinture"], ascending=[True, False])
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .drop(columns="priorite_ceinture")
    .reset_index(drop=True)
)

print(f"Candidats attendus {centre} : {len(candidats_aphm)}")
print(f"Fichiers BB/BR_RR {centre} V4 retenus : {len(df_aphm_final)}")

display(df_aphm_final)

Candidats attendus APHM : 15
Fichiers BB/BR_RR APHM V4 retenus : 15

,Numero_inclusion,Chemin,Feuille
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 04-04-2019 V4\Ceinture 0101CAR\2019_04_04-08_34_38_BB_RR.csv,APHM
1,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 12-04-2019 V4\Ceinture 0102PCR\2019_04_12-09_06_05_BB_RR.csv,APHM
2,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 08-11-2019 V4\Ceinture 0104FJS\2019_11_08-08_26_41_BB_RR.csv,APHM
3,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 09-09-2019 V4\Ceinture 0105PNR\2019_09_09-08_53_04_BB_RR.csv,APHM
4,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 17-10-2019 V4\Ceinture 0107DSS\2019_10_17-09_08_45_BB_RR.csv,APHM
5,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 14-11-2019 V4\Ceinture 0109GSS\2019_11_14-09_36_14_BB_RR.csv,APHM
6,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 21-11-2019 V4\Ceinture 0110LPR\2019_11_21-09_04_12_BB_RR.csv,APHM
7,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 22-11-2019 V4\Ceinture 0111MNR\2019_11_22-09_17_01_BB_RR.csv,APHM
8,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR - V4\V4\ceinture\2020_03_05-09_38_29\2020_03_05-09_38_29_BB_RR.csv,APHM
9,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS_V4\ceinture\2020_09_04-09_43_24\2020_09_04-09_43_24_BB_RR.csv,APHM
10,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR_v4\ceinture\2020_06_04-08_27_42\2020_06_04-08_27_42_BB_RR.csv,APHM
11,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS_v4\CEINTURE\2020_10_08-09_18_00\2020_10_08-09_18_00_BB_RR.csv,APHM
12,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR_v4_e\CEINTURE\2020_09_10-09_21_07\2020_09_10-09_21_07_BB_RR.csv,APHM
13,0122BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0122BDS\0122BDS_V4\CEINTURE\2020_09_25-09_20_42\2020_09_25-09_20_42_BB_RR.csv,APHM
14,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS_V4\CEINTURE\2020_09_24-09_19_20\2020_09_24-09_19_20_BB_RR.csv,APHM

## CAEN

In [15]:
# ======================================================
# RACINE CEINTURE CAEN
# ======================================================
racine_caen = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE"

# ======================================================
# EXTRACTION DATE_V4 ET FILTRE CANDIDATS VALIDES
# ======================================================
df_caen_excel = df["CAEN"].copy()  # contient la colonne Date_v4

# Normalisation des colonnes
df_caen_excel.columns = (
    df_caen_excel.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

COL_PID = "numero_inclusion"
COL_DATE = "date_v4"

# Filtrer seulement les candidats valides
candidats_valide = [c.upper() for c in resultats_globaux["CAEN"]["valides"]]
df_caen_excel = df_caen_excel[[COL_PID, COL_DATE]].dropna()
df_caen_excel[COL_PID] = df_caen_excel[COL_PID].str.upper()
df_caen_excel = df_caen_excel[df_caen_excel[COL_PID].isin(candidats_valide)]

# Conversion date Excel → datetime
df_caen_excel[COL_DATE] = pd.to_datetime(df_caen_excel[COL_DATE], errors="coerce", dayfirst=True)
df_caen_excel = df_caen_excel.dropna(subset=[COL_DATE])

# Création string YYYY_MM_DD pour matcher avec le nom du fichier
df_caen_excel["date_str"] = df_caen_excel[COL_DATE].dt.strftime("%Y_%m_%d")
dict_date_v4 = dict(zip(df_caen_excel[COL_PID], df_caen_excel["date_str"]))

# ======================================================
# PARCOURS DES FICHIERS CEINTURE CAEN
# ======================================================
rows = []

for root, dirs, files in os.walk(racine_caen):
    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"BB_RR|BR_RR", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== PID =====
        pid_trouve = None
        for pid in dict_date_v4:
            if pid in chemin_upper:
                pid_trouve = pid
                break
        if not pid_trouve:
            continue

        # ===== DATE fichier =====
        match_date = re.search(r"\d{4}[_-]\d{2}[_-]\d{2}", f)
        if not match_date:
            continue
        date_fichier = match_date.group().replace("-", "_")

        # ===== Comparaison avec la date V4 Excel =====
        if date_fichier != dict_date_v4[pid_trouve]:
            # Ignorer normalement si date différente
            # Mais pour certains cas on forcera plus bas
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Feuille": "CAEN"
        })

# ======================================================
# FORCER LES PATHS POUR LES CAS SPÉCIAUX
# ======================================================
#  Ces candidats sont échangés dans la base de donnée, donc on force les chemins des fichiers BB_RR
forced_paths = {
    "0342VNS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_08_10_03_11 0343PAS\2022_03_08__10_03_11_BR_RR.csv",
    "0343PAS": r"C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_04_01_09_38_38 0342VNS\2022_04_01__09_38_38_BR_RR.csv"
}

for pid, path_forced in forced_paths.items():
    rows.append({
        "Numero_inclusion": pid,
        "Chemin": path_forced,
        "Feuille": "CAEN"
    })

# ======================================================
# DATAFRAME FINAL CAEN V4
# ======================================================
df_caen_final = pd.DataFrame(rows).sort_values("Numero_inclusion").reset_index(drop=True)

# ======================================================
# SUPPRESSION DES DOUBLONS (on garde la première occurrence du Numero_inclusion)
# ======================================================
df_caen_final = df_caen_final.drop_duplicates(subset="Numero_inclusion", keep="first").reset_index(drop=True)

print(f"Candidats CAEN V4 attendus : {len(candidats_valide)}")
print(f"Candidats CAEN V4 retenus après suppression des doublons : {len(df_caen_final)}")

display(df_caen_final)

Candidats CAEN V4 attendus : 38
Candidats CAEN V4 retenus après suppression des doublons : 38

,Numero_inclusion,Chemin,Feuille
0,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_22-10_08_57 0302ZMR\2019_10_22-10_08_57_BB_RR.csv,CAEN
1,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_24-09_55_49 0304VMR\2020_01_24-09_55_49_BB_RR.csv,CAEN
2,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_23-09_51_21 0305LCR\2020_01_23-09_51_21_BB_RR (1).csv,CAEN
3,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_05_25-10_35_35 0307SMR\2020_05_25-10_35_35_BB_RR.csv,CAEN
4,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_02_09_04_56 0308RGR\2020_09_02__09_04_56_BR_RR (1).csv,CAEN
5,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_05_18-08_40_01 0310ACS\2020_05_18-08_40_01_BB_RR (1).csv,CAEN
6,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_17-09_10_51 0311CJS\2020_06_17__09_10_51_BR_RR.csv,CAEN
7,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_08-10_01_39 0313FPR\2020_06_08-10_01_39_BB_RR.csv,CAEN
8,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_11-09_44_57 0315VCS\2020_06_11-09_44_57_BB_RR.csv,CAEN
9,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_02-09_58_49 0316TMS\2020_06_02-09_58_49_BB_RR.csv,CAEN
10,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_04-10_17_18 0317LGS\2020_06_04-10_17_18_BB_RR.csv,CAEN
11,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_25-09_53_39 0319LJS\2020_06_25__09_53_39_BR_RR.csv,CAEN
12,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_07_07_10_00_01 0321DRR\2020_07_07__10_00_01_BR_RR.csv,CAEN
13,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_07_21_10_14_15_0322RMS\2020_07_21__10_14_15_BR_RR.csv,CAEN
14,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_27_09_25_18 0323RFS\2020_08_27__09_25_18_BR_RR.csv,CAEN
15,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_25_10_50_46_0324LMR\2020_08_25__10_50_46_BR_RR.csv,CAEN
16,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_06_09_29_07 0326BJR\2020_10_06__09_29_07_BR_RR.csv,CAEN
17,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_24_09_47_04_0328MPR\2020_09_24__09_47_04_BR_RR.csv,CAEN
18,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_03_09_51_23 0329NMR\2020_11_03__10_51_23_BR_RR.csv,CAEN
19,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_01_18_09_43_27 0330RTR\2021_01_18__09_43_27_BR_RR.csv,CAEN
20,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_27_09_49_41 0331GRS\2020_11_27__09_49_41_BR_RR.csv,CAEN
21,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_25_09_23_00 0333MMS\2021_06_25__09_23_00_BR_RR.csv,CAEN
22,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_09_03_09_48_21 0337BFS\2021_09_03__09_48_21_BR_RR.csv,CAEN
23,0338JBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_10_22_09_30_26 0338JBS\2021_10_22__09_30_26_BR_RR (1).csv,CAEN
24,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_12_02_13_45_00 0339NPR\2021_12_02__14_45_00_BR_RR.csv,CAEN
25,0340BAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_12_14_13_46_23 0340BAR\2021_12_14__13_46_23_BR_RR.csv,CAEN
26,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_15_09_52_03 0341LJS\2022_02_15__09_52_03_BR_RR.csv,CAEN
27,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_08_10_03_11 0343PAS\2022_03_08__10_03_11_BR_RR.csv,CAEN
28,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_04_01_09_38_38 0342VNS\2022_04_01__09_38_38_BR_RR.csv,CAEN
29,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_04_09_32_11 0345LAR\2022_11_04__09_32_11_BR_RR.csv,CAEN
30,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_10_28_09_40_15 0346GLS\2022_10_28__09_40_15_BR_RR.csv,CAEN
31,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_18_09_36_29 0347DMR\2022_11_18__09_36_29_BR_RR.csv,CAEN
32,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_15_09_30_10 0348GCR\2022_11_15__09_30_10_BR_RR.csv,CAEN
33,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_21_09_29_39 0349LLS\2022_11_21__09_29_39_BR_RR.csv,CAEN
34,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_12_13_09_34_08 0350MYR\2022_12_13__09_34_08_BR_RR.csv,CAEN
35,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_01_05_09_57_02 0351FIR\2023_01_05__09_57_02_BR_RR.csv,CAEN
36,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_01_12_09_42_36 0352RNR\2023_01_12__09_42_36_BR_RR.csv,CAEN
37,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_06_20_09_25_35 0356DMS\2023_06_20__09_25_35_BR_RR.csv,CAEN

## POITIERS

In [17]:
# ===== Racine POITIERS =====
racine_poitiers = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY"

# ===== Candidats valides =====
candidats_poitiers = [c.upper() for c in resultats_globaux["POITIERS"]["valides"]]

# ===== Regex POITIERS (tronquée → clé pour 0408 etc) =====
patterns_candidats = {
    pid: re.compile(rf"{pid[:4]}\s*-?\s*{pid[4:6]}", re.IGNORECASE)
    for pid in candidats_poitiers
}

# ===== Collecte brute des fichiers =====
fichiers_par_candidat = defaultdict(list)

for root, dirs, files in os.walk(racine_poitiers):
    if "V4" not in root.upper():
        continue

    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)

        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                fichiers_par_candidat[pid].append(chemin)
                break

# ===== Sélection finale + DataFrame =====
rows = []

for pid, fichiers in fichiers_par_candidat.items():
    fichiers = sorted(set(fichiers))  # enlever doublons exacts

    # priorité CEINTURE
    ceinture = [f for f in fichiers if "ceinture" in f.lower()]
    chemin_final = ceinture[0] if ceinture else fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Feuille": "POITIERS"
    })

df_poitiers_final = pd.DataFrame(rows)

# ===== Vérifications =====
print(f"Candidats attendus POITIERS : {len(candidats_poitiers)}")
print(f"Fichiers BB/BR_RR POITIERS V4 retenus : {len(df_poitiers_final)}")

manquants = sorted(set(candidats_poitiers) - set(df_poitiers_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats POITIERS V4 sont présents")

display(df_poitiers_final)

Candidats attendus POITIERS : 11
Fichiers BB/BR_RR POITIERS V4 retenus : 10
⚠️ Candidats manquants : ['0415VMR']

,Numero_inclusion,Chemin,Feuille
0,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V4\ceinture\No Team Assigned\2020_01_10-09_57_29\2020_01_10-09_57_29_BB_RR.csv,POITIERS
1,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS-V4\0402LLS ceinture V4\No Team Assigned\2020_02_07-09_30_21\2020_02_07-09_30_21_BB_RR.csv,POITIERS
2,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V4\0403DCR - ceinture V4\No Team Assigned\2020_02_28-10_11_17\2020_02_28-10_11_17_BB_RR.csv,POITIERS
3,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404YCS-V4\0404YC ceinture V4\2020_06_19-10_14_18_BB_RR.csv,POITIERS
4,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V4\0407LJ ceinture V4\No Team Assigned\2020_07_02-09_52_07\2020_07_02-09_52_07_BB_RR.csv,POITIERS
5,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC-V4\0408BC-ceinture V4\No Team Assigned\2020_08_06-10_25_47\2020_08_06-10_25_47_BB_RR.csv,POITIERS
6,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V4\0411VE-ceinture V4\0411VES - V4\2020_11_12-10_17_49\2020_11_12-10_17_49_BB_RR.csv,POITIERS
7,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V4\0412ANS ceinture V4\No Team Assigned\2020_11_19-10_02_29\2020_11_19-10_02_29_BB_RR.csv,POITIERS
8,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS V4\0413HFS-ceinture V4\No Team Assigned\2020_11_26-09_37_17\2020_11_26-09_37_17_BB_RR.csv,POITIERS
9,0414PJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0414 PJ\0414 PJ V4\0414PJ-ceinture V4\2021_06_10-09_47_37\2021_06_10-09_47_37_BB_RR.csv,POITIERS

## ROUEN

In [19]:
# ===== Racine ROUEN =====
racine_rouen = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER"

# ===== Candidats valides =====
candidats_rouen = [c.upper() for c in resultats_globaux["ROUEN"]["valides"]]

# ===== paramètres poids =====
POIDS_MIN = 3000 * 1024
POIDS_MAX = 8000 * 1024

# ===== pattern numéro (ex : 05-12) =====
patterns_candidats = [
    (pid, re.compile(rf"{pid[:2]}-{pid[2:4]}", re.IGNORECASE))
    for pid in candidats_rouen
]

# ===== pattern date dans le fichier =====
date_pattern = re.compile(r"(\d{4}_\d{2}_\d{2}[-_]\d{2}_\d{2}_\d{2})")

fichiers_dict = defaultdict(list)

for root, dirs, files in os.walk(racine_rouen):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue

        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)

        # ---- filtre poids ----
        try:
            taille = os.path.getsize(chemin)
        except OSError:
            continue

        if not (POIDS_MIN <= taille <= POIDS_MAX):
            continue

        # ---- identification candidat ----
        pid_trouve = None
        for pid, pat in patterns_candidats:
            if pat.search(chemin):
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        # ---- date ----
        m = date_pattern.search(chemin)
        date_str = m.group(1) if m else "inconnue"

        fichiers_dict[(pid_trouve, date_str)].append(chemin)

# ===== Sélection finale + DataFrame =====
rows = []

for (pid, date_str), fichiers in fichiers_dict.items():

    fichiers = sorted(set(fichiers)) 

    ceinture = [f for f in fichiers if "ceinture" in f.lower()]
    chemin_final = ceinture[0] if ceinture else fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Feuille": "ROUEN"
    })

df_rouen_final = pd.DataFrame(rows)

# ===== Résumé & contrôle =====
print(f"Candidats attendus ROUEN : {len(candidats_rouen)}")
print(f"Fichiers BB/BR_RR ROUEN V4 retenus : {len(df_rouen_final)}")

manquants = sorted(set(candidats_rouen) - set(df_rouen_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats ROUEN manquants :", manquants)
else:
    print("✅ Tous les candidats ROUEN V4 sont présents")

display(df_rouen_final)

# On perd le 0509LGS car pas de V4 dans l'arbo

Candidats attendus ROUEN : 13
Fichiers BB/BR_RR ROUEN V4 retenus : 12
⚠️ Candidats ROUEN manquants : ['0509LGS']

,Numero_inclusion,Chemin,Feuille
0,0501MBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-01-MB-S\V4\CEINTURE\2019_11_18-09_10_13_BB_RR - Copie.csv,ROUEN
1,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V4\CEINTURE\2019_11_13-08_56_31_BB_RR.csv,ROUEN
2,0503LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-03-LC-R\V4\CEINTURE\2020_01_23-09_24_20_BB_RR.csv,ROUEN
3,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V4\CEINTURE V4\2020_03_05-09_10_25_BB_RR.csv,ROUEN
4,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V4\CEINTURE\2020_02_14-09_12_56_BB_RR.csv,ROUEN
5,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V4\CEINTURE\2020_09_24-09_15_56_BB_RR.csv,ROUEN
6,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V4\CEINTURE\2020_05_12-09_15_51_BB_RR.csv,ROUEN
7,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V4\CEINTURE\2020_11_17-09_13_35_BB_RR.csv,ROUEN
8,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V4\CEINTURE\Record 1_2022_02_15-14_05_19_BB_RR.csv,ROUEN
9,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V4\CEINTURE\Record 1_2022_03_15-09_12_51_BB_RR - Copie.csv,ROUEN
10,0514LPS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-14-LP-S\V4\CEINTURE\No Team Assigned\2023_02_07-09_15_05\Record 1_2023_02_07-09_15_05_BB_RR.csv,ROUEN
11,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V4\CEINTURE\2023_08_11-09_24_47\Record 1_2023_08_11-09_24_47_BB_RR.csv,ROUEN

## LAVERAN

In [21]:
# ===== Racine LAVERAN =====
racine_laveran = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"
)

# ===== Candidats attendus =====
candidats_laveran = [c.upper() for c in resultats_globaux["LAVERAN"]["valides"]]

rows = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_laveran):

    if "V4" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification du candidat =====
        pid = None
        for c in candidats_laveran:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "LAVERAN"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_laveran_final = pd.DataFrame(rows)

# 1 fichier max par candidat
df_laveran_final = (
    df_laveran_final
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# RÉSUMÉ & CONTRÔLES
# =========================================================
print("\n====================================")
print(f"Candidats attendus LAVERAN : {len(candidats_laveran)}")
print(f"Fichiers retenus LAVERAN    : {len(df_laveran_final)}")

manquants = sorted(
    set(candidats_laveran) - set(df_laveran_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LAVERAN manquants :", manquants)
else:
    print("✅ Tous les candidats LAVERAN sont présents")

display(df_laveran_final)

OK [0626MCS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V4\0626MCS_v4\CEINTURE\No Team Assigned\2020_10_29-10_17_45\2020_10_29-10_17_45_BB_RR.csv
OK [0629TCR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\0629TCR_V4\CEINTURE\No Team Assigned\2020_11_17-09_49_55\2020_11_17-09_49_55_BB_RR.csv
OK [0630RJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V4\CEINTURE\2020_11_16-10_07_29\2020_11_16-10_07_29_BB_RR.csv
OK [0631LHR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\0631LHR_V4\CEINTURE\2020_11_18-09_33_29\2020_11_18-09_33_29_BB_RR.csv

====================================
Candidats attendus LAVERAN : 4
Fichiers retenus LAVERAN    : 4
✅ Tous les candidats LAVERAN sont présents

,Numero_inclusion,Chemin,Feuille
0,0626MCS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V4\0626MCS_v4\CEINTURE\No Team Assigned\2020_10_29-10_17_45\2020_10_29-10_17_45_BB_RR.csv,LAVERAN
1,0629TCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\0629TCR_V4\CEINTURE\No Team Assigned\2020_11_17-09_49_55\2020_11_17-09_49_55_BB_RR.csv,LAVERAN
2,0630RJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V4\CEINTURE\2020_11_16-10_07_29\2020_11_16-10_07_29_BB_RR.csv,LAVERAN
3,0631LHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\0631LHR_V4\CEINTURE\2020_11_18-09_33_29\2020_11_18-09_33_29_BB_RR.csv,LAVERAN

## LPC

In [22]:
# ===== Racine LPC =====
racine_lpc = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging"

# ===== Candidats attendus =====
candidats_lpc = [c.upper() for c in resultats_globaux["LPC"]["valides"]]

# ===== paramètres poids =====
POIDS_MIN = 2000 * 1024   # 2 Mo
POIDS_MAX = 8000 * 1024   # 8 Mo

# ===== pattern date dans le nom de fichier =====
date_pattern = re.compile(r"(\d{4}_\d{2}_\d{2}-\d{2}_\d{2}_\d{2})")

rows = []

for root, dirs, files in os.walk(racine_lpc):

    if "V4" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ---- filtre poids ----
        try:
            taille = os.path.getsize(chemin)
        except OSError:
            continue
        if not (POIDS_MIN <= taille <= POIDS_MAX):
            continue

        # ---- identification candidat ----
        pid = None
        for c in candidats_lpc:
            if c == "0117MSR" and "0117MMR" in chemin_upper:
                pid = c  # correction manuelle
                break
            if c in chemin_upper:
                pid = c
                break
        if not pid:
            continue

        # ---- date dans le fichier ----
        m = date_pattern.search(f)
        date_str = m.group(1) if m else "inconnue"

        rows.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "LPC"
        })

# ===== SUPPRESSION DES DOUBLONS =====
df_lpc_final = pd.DataFrame(rows)
df_lpc_final = (
    df_lpc_final
    .sort_values(["Numero_inclusion"])
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# ===== AFFICHAGE =====
print(f"Candidats attendus LPC : {len(candidats_lpc)}")
print(f"Fichiers BB/BR_RR V4 retenus : {len(df_lpc_final)}")

manquants = sorted(set(candidats_lpc) - set(df_lpc_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC sont présents")

display(df_lpc_final)

Candidats attendus LPC : 39
Fichiers BB/BR_RR V4 retenus : 26
⚠️ Candidats LPC manquants : ['0106DJR', '0130FAR', '0132GAR', '0133BPS', '0136CJR', '0137BMS', '0138NWR', '0139BMR', '0140LMR', '0141HJR', '0142LLS', '0143EBR', '0144ZGR']

,Numero_inclusion,Chemin,Feuille
0,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\0101EMS V4\Ceinture\2019_10_22-09_42_52\2019_10_22-09_42_52_BB_RR.csv,LPC
1,0102EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0102EMS\V4 0102EMS\Ceinture\2019_09_05-09_36_48\2019_09_05-09_36_48_BB_RR.csv,LPC
2,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V4 0103BPS\Ceinture\2019_09_17-09_43_26\2019_09_17-09_43_26_BB_RR.csv,LPC
3,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V4 0104IBS\Ceinture\2019_09_02-10_21_03\2019_09_02-10_21_03_BB_RR.csv,LPC
4,0107LER,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0107LER\V4 0107LER\Ceinture\No Team Assigned\2019_09_04-10_10_04\2019_09_04-10_10_04_BB_RR.csv,LPC
5,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V4\Ceinture\2019_10_24-09_06_30_BB_RR.csv,LPC
6,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V4\Ceinture\2019_09_13-09_33_09_BB_RR.csv,LPC
7,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V4\Ceinture\2019_09_16-09_30_11_BB_RR.csv,LPC
8,0111TAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0111TAS\V4\Ceinture\2019_10_03-09_26_21_BB_RR.csv,LPC
9,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V4\Ceinture\2019_11_06-09_35_42_BB_RR.csv,LPC
10,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V4\Ceinture\2019_08_27-09_41_17_BB_RR.csv,LPC
11,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\0114MLR V4\Ceinture\2019_10_15-10_35_01\2019_10_15-10_35_01_BB_RR.csv,LPC
12,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V4\Ceinture\2019_10_09-09_23_28_BB_RR.csv,LPC
13,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V4\Ceinture\2019_10_04-09_24_16_BB_RR.csv,LPC
14,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V4\Ceinture\2019_10_11-09_25_30_BB_RR.csv,LPC
15,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V4\Ceinture\2019_10_16-07_56_19_BB_RR.csv,LPC
16,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V4\Ceinture\2019_10_28-09_48_54_BB_RR.csv,LPC
17,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V4\Ceinture\2019_11_19-09_44_13_BB_RR.csv,LPC
18,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V4\Ceinture\2019_10_23-09_34_13_BB_RR.csv,LPC
19,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V4\Ceinture\2019_11_05-09_18_30_BB_RR.csv,LPC
20,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V4\Ceinture\2019_11_08-09_23_05_BB_RR.csv,LPC
21,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V4\Ceinture\2019_11_15-09_27_24_BB_RR.csv,LPC
22,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V4\Ceinture\2019_12_02-09_03_50_BB_RR.csv,LPC
23,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V4\Ceinture\2019_11_21-09_34_50_BB_RR.csv,LPC
24,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V4\Ceinture\2019_12_11-09_33_30_BB_RR.csv,LPC
25,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V4\Ceinture\2019_12_18-09_38_27_BB_RR.csv,LPC

In [23]:
# ===== Racines à scanner =====
racines = [
    r"C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire",
    r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo"
]

# ===== Numero_inclusion manquants =====
candidats_a_garder = [c.upper() for c in manquants]

# ===== Paramètres poids =====
POIDS_MIN = 2000 * 1024   # 2 Mo
POIDS_MAX = 8000 * 1024   # 8 Mo

# ===== Collecte fichiers =====
rows = []

for racine in racines:
    print(f"\n--- Scan de : {racine} ---")
    
    for root, dirs, files in os.walk(racine):

        if "V4" not in root.upper():
            continue

        for f in files:

            if not f.lower().endswith(".csv"):
                continue
            if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
                continue

            chemin = os.path.join(root, f)
            chemin_upper = chemin.upper()

            # ---- filtre poids ----
            try:
                taille = os.path.getsize(chemin)
            except OSError:
                continue
            if not (POIDS_MIN <= taille <= POIDS_MAX):
                continue

            # ---- identification ----
            pid_trouve = None
            for pid in candidats_a_garder:
                # Cas spécial si nécessaire, ex : 0117MSR -> 0117MMR
                if pid == "0117MSR" and "0117MMR" in chemin_upper:
                    pid_trouve = pid
                    break
                if pid in chemin_upper:
                    pid_trouve = pid
                    break

            if not pid_trouve:
                continue

            # ---- ajout à la liste ----
            rows.append({
                "Numero_inclusion": pid_trouve,
                "Chemin": chemin,
                "Feuille": "LPC"
            })
            print(f"OK [{pid_trouve}] :", chemin)

# ===== Création DataFrame =====
df_lpc_manquants = pd.DataFrame(rows)

# ===== Suppression doublons =====
df_lpc_manquants = df_lpc_manquants.drop_duplicates(
    subset="Numero_inclusion",
    keep="first"
).reset_index(drop=True)

# ===== Résumé & contrôle =====
print("\n====================================")
print(f"PIDs recherchés : {len(candidats_a_garder)}")
print(f"Fichiers retrouvés : {len(df_lpc_manquants)}")

manquants_restant = sorted(
    set(candidats_a_garder) - set(df_lpc_manquants["Numero_inclusion"])
)
if manquants_restant:
    print("⚠️ PIDs encore manquants :", manquants_restant)
else:
    print("✅ Tous les PIDs manquants ont été retrouvés")

display(df_lpc_manquants)

# ⚠️ PIDs encore manquants : ['0106DJR', '0137BMS', '0141HJR', '0142LLS'] pas dans l'arbo

--- Scan de : C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire ---

--- Scan de : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo ---
OK [0130FAR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V4\0130FAR\ceinture\2020_02_11-09_47_09\2020_02_11-09_47_09_BB_RR.csv
OK [0132GAR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\0132GAR_V4\ceinture\ceinture\2021_02_08-10_03_14_BB_RR.csv
OK [0133BPS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\0157BPS_V4\ceinture\No Team Assigned\2021_02_09-09_54_43\2021_02_09-09_54_43_BB_RR.csv
OK [0136CJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR_V4\Ceinture\No Team Assigned\2021_12_10-10_17_58\2021_12_10-10_17_58_BB_RR.csv
OK [0138NWR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V4\ceinture\No Team Assigned\2022_04_04-09_02_10\2022_04_04-09_02_10_BB_RR.csv
OK [0144ZGR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V4\ceinture\No Team Assigned\2023_04_11-09_08_49\2023_04_11-09_08_49_BB_RR.csv
OK [0130FAR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0154FAR\V4\0130FAR\ceinture\2020_02_11-09_47_09\2020_02_11-09_47_09_BB_RR.csv
OK [0139BMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0167BMR\0167BMR_V4 0139BMR_V4\ceinture\No Team Assigned\2023_02_17-10_05_43\2023_02_17-10_05_43_BB_RR.csv
OK [0140LMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V4 0140LMR\ceinture\No Team Assigned\2010_01_02-23_56_56\2010_01_02-23_56_56_BB_RR.csv
OK [0143EBR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR_V4\ceinture\No Team Assigned\2023_04_25-09_05_36\2023_04_25-09_05_36_BB_RR.csv

====================================
PIDs recherchés : 13
Fichiers retrouvés : 9
⚠️ PIDs encore manquants : ['0106DJR', '0137BMS', '0141HJR', '0142LLS']

,Numero_inclusion,Chemin,Feuille
0,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V4\0130FAR\ceinture\2020_02_11-09_47_09\2020_02_11-09_47_09_BB_RR.csv,LPC
1,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\0132GAR_V4\ceinture\ceinture\2021_02_08-10_03_14_BB_RR.csv,LPC
2,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\0157BPS_V4\ceinture\No Team Assigned\2021_02_09-09_54_43\2021_02_09-09_54_43_BB_RR.csv,LPC
3,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR_V4\Ceinture\No Team Assigned\2021_12_10-10_17_58\2021_12_10-10_17_58_BB_RR.csv,LPC
4,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V4\ceinture\No Team Assigned\2022_04_04-09_02_10\2022_04_04-09_02_10_BB_RR.csv,LPC
5,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V4\ceinture\No Team Assigned\2023_04_11-09_08_49\2023_04_11-09_08_49_BB_RR.csv,LPC
6,0139BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0167BMR\0167BMR_V4 0139BMR_V4\ceinture\No Team Assigned\2023_02_17-10_05_43\2023_02_17-10_05_43_BB_RR.csv,LPC
7,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V4 0140LMR\ceinture\No Team Assigned\2010_01_02-23_56_56\2010_01_02-23_56_56_BB_RR.csv,LPC
8,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR_V4\ceinture\No Team Assigned\2023_04_25-09_05_36\2023_04_25-09_05_36_BB_RR.csv,LPC

## SAINTE-MARGUERITE

In [24]:
# ===== Racine SAINTE-MARGUERITE =====
racine_st_marguerite = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite"
)

# ===== Candidats attendus =====
candidats_sm = [
    c.upper() for c in resultats_globaux["SAINTE-MARGUERITE"]["valides"]
]

rows_sm = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_st_marguerite):

    if "V4" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification =====
        pid = None
        for c in candidats_sm:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_sm.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "SAINTE-MARGUERITE"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_sm = pd.DataFrame(rows_sm)

df_sm = (
    df_sm
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus SAINTE-MARGUERITE : {len(candidats_sm)}")
print(f"Fichiers retenus                     : {len(df_sm)}")

manquants = sorted(
    set(candidats_sm) - set(df_sm["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats SAINTE-MARGUERITE sont présents")

display(df_sm)

OK [0801HDR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V4\Ceinture\2022_12_07-11_15_45_BB_RR.csv
OK [0802LAS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V4\Ceinture\2022_12_12-11_03_54_BB_RR.csv
OK [0803DPS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS-V4\ceinture\No Team Assigned\2023_03_01-10_20_00\2023_03_01-10_20_00_BB_RR.csv
OK [0804GOR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR_V4\Ceinture\No Team Assigned\2023_01_11-09_53_11\2023_01_11-09_53_11_BB_RR.csv
OK [0805BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V4\Ceinture\No Team Assigned\2023_01_18-09_11_15\2023_01_18-09_11_15_BB_RR.csv
OK [0806KHS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\0806KHS-V4\Ceinture\No Team Assigned\2023_03_27-08_28_46\2023_03_27-08_28_46_BB_RR.csv
OK [0807OMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V4\ceinture\No Team Assigned\2023_05_15-09_39_03\2023_05_15-09_39_03_BB_RR.csv

====================================
Candidats attendus SAINTE-MARGUERITE : 7
Fichiers retenus                     : 7
✅ Tous les candidats SAINTE-MARGUERITE sont présents

,Numero_inclusion,Chemin,Feuille
0,0801HDR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V4\Ceinture\2022_12_07-11_15_45_BB_RR.csv,SAINTE-MARGUERITE
1,0802LAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V4\Ceinture\2022_12_12-11_03_54_BB_RR.csv,SAINTE-MARGUERITE
2,0803DPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS-V4\ceinture\No Team Assigned\2023_03_01-10_20_00\2023_03_01-10_20_00_BB_RR.csv,SAINTE-MARGUERITE
3,0804GOR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR_V4\Ceinture\No Team Assigned\2023_01_11-09_53_11\2023_01_11-09_53_11_BB_RR.csv,SAINTE-MARGUERITE
4,0805BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V4\Ceinture\No Team Assigned\2023_01_18-09_11_15\2023_01_18-09_11_15_BB_RR.csv,SAINTE-MARGUERITE
5,0806KHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\0806KHS-V4\Ceinture\No Team Assigned\2023_03_27-08_28_46\2023_03_27-08_28_46_BB_RR.csv,SAINTE-MARGUERITE
6,0807OMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V4\ceinture\No Team Assigned\2023_05_15-09_39_03\2023_05_15-09_39_03_BB_RR.csv,SAINTE-MARGUERITE

## CGD

In [26]:
# ===== Racine CGD =====
racine_cgd = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD"
)

# ===== Candidats attendus =====
candidats_cgd = [
    c.upper() for c in resultats_globaux["CGD"]["valides"]
]

rows_cgd = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_cgd):

    if "V4" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification =====
        pid = None
        for c in candidats_cgd:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_cgd.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Feuille": "CGD"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_cgd = pd.DataFrame(rows_cgd)

df_cgd = (
    df_cgd
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CGD : {len(candidats_cgd)}")
print(f"Fichiers retenus CGD   : {len(df_cgd)}")

manquants = sorted(
    set(candidats_cgd) - set(df_cgd["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CGD sont présents")

display(df_cgd)

OK [0901SMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0901SMR\0901SMR - V4\Ceinture\2022_12_14-10_53_43_BB_RR.csv
OK [0903DJS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0903DJS\V4\ceinture\No Team Assigned\2023_03_08-10_03_10\2023_03_08-10_03_10_BB_RR.csv
OK [0904KJS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS-V4\ceinture\No Team Assigned\2023_03_22-09_03_56\2023_03_22-09_03_56_BB_RR.csv
OK [0905SLR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V4\ceinture\No Team Assigned\2023_04_05-09_51_00\2023_04_05-09_51_00_BB_RR.csv

====================================
Candidats attendus CGD : 5
Fichiers retenus CGD   : 4
⚠️ Candidats manquants : ['0902SIS']

,Numero_inclusion,Chemin,Feuille
0,0901SMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0901SMR\0901SMR - V4\Ceinture\2022_12_14-10_53_43_BB_RR.csv,CGD
1,0903DJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0903DJS\V4\ceinture\No Team Assigned\2023_03_08-10_03_10\2023_03_08-10_03_10_BB_RR.csv,CGD
2,0904KJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS-V4\ceinture\No Team Assigned\2023_03_22-09_03_56\2023_03_22-09_03_56_BB_RR.csv,CGD
3,0905SLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V4\ceinture\No Team Assigned\2023_04_05-09_51_00\2023_04_05-09_51_00_BB_RR.csv,CGD

## CERCA

In [28]:
import os
import re
import pandas as pd

# ===== Racines CERCA =====
racines_cerca = [
    r"C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS",
    r"C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU"
]

# ===== Candidats CERCA =====
candidats_cerca = [c.upper() for c in resultats_globaux["CERCA"]["valides"]]

fichiers_cerca = []

for racine in racines_cerca:
    print(f"\n--- Scan CERCA : {racine} ---")

    for root, dirs, files in os.walk(racine):

        if "V4" not in root.upper():
            continue

        for f in files:
            if not f.lower().endswith(".csv"):
                continue
            if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
                continue

            chemin = os.path.join(root, f)
            chemin_upper = chemin.upper()

            for pid in candidats_cerca:
                if pid in chemin_upper:
                    fichiers_cerca.append((pid, chemin))
                    print(f"OK [{pid}] :", chemin)
                    break

rows = []

for pid in candidats_cerca:
    fichiers_pid = [c for p, c in fichiers_cerca if p == pid]

    if not fichiers_pid:
        continue

    ceinture = [f for f in fichiers_pid if "CEINTURE" in f.upper()]
    chemin_final = ceinture[0] if ceinture else fichiers_pid[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Feuille": "CERCA"
    })

df_cerca = pd.DataFrame(rows)

# ===== Affichage =====
print("\n====================================")
print(f"Candidats attendus CERCA : {len(candidats_cerca)}")
print(f"Fichiers BB/BR_RR V4 retenus : {len(df_cerca)}")

manquants = sorted(set(candidats_cerca) - set(df_cerca["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats CERCA manquants :", manquants)
else:
    print("✅ Tous les candidats CERCA sont présents")

display(df_cerca)

--- Scan CERCA : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS ---
OK [0401BDS] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Ceinture\2019_11_13__09_37_08_BR_RR.csv
OK [0405RCR] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Ceinture\2020_02_14__10_06_12_BR_RR.csv
OK [0406BBS] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Ceinture\2019_12_18__11_01_15_BR_RR.csv
OK [0408SJS] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Ceinture\2019_11_27__10_38_19_BR_RR.csv
OK [0404DER] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Ceinture\2019_11_08__09_47_26_BR_RR.csv
OK [0409HCR] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Ceinture\2020_01_06__10_24_59_BR_RR.csv
OK [0410FMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Ceinture\2019_11_18__10_30_15_BR_RR.csv

--- Scan CERCA : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU ---
OK [0414PVR] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Ceinture\2021_07_09__09_38_01_BR_RR.csv
OK [0420MCR] : C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Ceinture\2021_07_05__14_07_01_BR_RR.csv

====================================
Candidats attendus CERCA : 11
Fichiers BB/BR_RR V4 retenus : 9
⚠️ Candidats CERCA manquants : ['0418MPR', '0423SVS']

,Numero_inclusion,Chemin,Feuille
0,0401BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Ceinture\2019_11_13__09_37_08_BR_RR.csv,CERCA
1,0404DER,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Ceinture\2019_11_08__09_47_26_BR_RR.csv,CERCA
2,0405RCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Ceinture\2020_02_14__10_06_12_BR_RR.csv,CERCA
3,0406BBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Ceinture\2019_12_18__11_01_15_BR_RR.csv,CERCA
4,0408SJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Ceinture\2019_11_27__10_38_19_BR_RR.csv,CERCA
5,0409HCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Ceinture\2020_01_06__10_24_59_BR_RR.csv,CERCA
6,0410FMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Ceinture\2019_11_18__10_30_15_BR_RR.csv,CERCA
7,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Ceinture\2021_07_09__09_38_01_BR_RR.csv,CERCA
8,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Ceinture\2021_07_05__14_07_01_BR_RR.csv,CERCA

## CONCATENATION

In [29]:
# ===== Liste des DataFrames par feuille =====
dfs = [
    df_aphm_final,  
    df_caen_final,
    df_poitiers_final,     
    df_rouen_final,
    df_laveran_final,
    df_lpc_final,         
    df_lpc_manquants,
    df_sm,          
    df_cgd,         
    df_cerca      
]

# ===== Normalisation des colonnes =====
for i, df in enumerate(dfs):
    if "PID" in df.columns:
        df.rename(columns={"PID": "Numero_inclusion"}, inplace=True)
    # Assurer que la colonne Condition existe
    if "Condition" not in df.columns:
        df["Condition"] = None
    # On garde uniquement les colonnes essentielles
    df = df[["Numero_inclusion", "Chemin", "Feuille"]]
    dfs[i] = df

# ===== Concatenation =====
df_global = pd.concat(dfs, ignore_index=True)

# ===== Suppression des doublons par Numero_inclusion =====
# On garde le premier fichier détecté par candidat
df_global = df_global.drop_duplicates(subset=["Numero_inclusion"], keep="first")

# ===== Tri par Numero_inclusion =====
df_global = df_global.sort_values("Numero_inclusion").reset_index(drop=True)

# ===== Résumé =====
print(f"Total candidats uniques : {df_global['Numero_inclusion'].nunique()}")
print(f"Total fichiers conservés : {len(df_global)}")
display(df_global)

Total candidats uniques : 134
Total fichiers conservés : 134

,Numero_inclusion,Chemin,Feuille
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 04-04-2019 V4\Ceinture 0101CAR\2019_04_04-08_34_38_BB_RR.csv,APHM
1,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\0101EMS V4\Ceinture\2019_10_22-09_42_52\2019_10_22-09_42_52_BB_RR.csv,LPC
2,0102EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0102EMS\V4 0102EMS\Ceinture\2019_09_05-09_36_48\2019_09_05-09_36_48_BB_RR.csv,LPC
3,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 12-04-2019 V4\Ceinture 0102PCR\2019_04_12-09_06_05_BB_RR.csv,APHM
4,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V4 0103BPS\Ceinture\2019_09_17-09_43_26\2019_09_17-09_43_26_BB_RR.csv,LPC
5,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 08-11-2019 V4\Ceinture 0104FJS\2019_11_08-08_26_41_BB_RR.csv,APHM
6,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V4 0104IBS\Ceinture\2019_09_02-10_21_03\2019_09_02-10_21_03_BB_RR.csv,LPC
7,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 09-09-2019 V4\Ceinture 0105PNR\2019_09_09-08_53_04_BB_RR.csv,APHM
8,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 17-10-2019 V4\Ceinture 0107DSS\2019_10_17-09_08_45_BB_RR.csv,APHM
9,0107LER,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0107LER\V4 0107LER\Ceinture\No Team Assigned\2019_09_04-10_10_04\2019_09_04-10_10_04_BB_RR.csv,LPC
10,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V4\Ceinture\2019_10_24-09_06_30_BB_RR.csv,LPC
11,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 14-11-2019 V4\Ceinture 0109GSS\2019_11_14-09_36_14_BB_RR.csv,APHM
12,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V4\Ceinture\2019_09_13-09_33_09_BB_RR.csv,LPC
13,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 21-11-2019 V4\Ceinture 0110LPR\2019_11_21-09_04_12_BB_RR.csv,APHM
14,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V4\Ceinture\2019_09_16-09_30_11_BB_RR.csv,LPC
15,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 22-11-2019 V4\Ceinture 0111MNR\2019_11_22-09_17_01_BB_RR.csv,APHM
16,0111TAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0111TAS\V4\Ceinture\2019_10_03-09_26_21_BB_RR.csv,LPC
17,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR - V4\V4\ceinture\2020_03_05-09_38_29\2020_03_05-09_38_29_BB_RR.csv,APHM
18,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V4\Ceinture\2019_11_06-09_35_42_BB_RR.csv,LPC
19,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V4\Ceinture\2019_08_27-09_41_17_BB_RR.csv,LPC
20,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS_V4\ceinture\2020_09_04-09_43_24\2020_09_04-09_43_24_BB_RR.csv,APHM
21,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\0114MLR V4\Ceinture\2019_10_15-10_35_01\2019_10_15-10_35_01_BB_RR.csv,LPC
22,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V4\Ceinture\2019_10_09-09_23_28_BB_RR.csv,LPC
23,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V4\Ceinture\2019_10_04-09_24_16_BB_RR.csv,LPC
24,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR_v4\ceinture\2020_06_04-08_27_42\2020_06_04-08_27_42_BB_RR.csv,APHM
25,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V4\Ceinture\2019_10_11-09_25_30_BB_RR.csv,LPC
26,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V4\Ceinture\2019_10_16-07_56_19_BB_RR.csv,LPC
27,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V4\Ceinture\2019_10_28-09_48_54_BB_RR.csv,LPC
28,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS_v4\CEINTURE\2020_10_08-09_18_00\2020_10_08-09_18_00_BB_RR.csv,APHM
29,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V4\Ceinture\2019_11_19-09_44_13_BB_RR.csv,LPC
30,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR_v4_e\CEINTURE\2020_09_10-09_21_07\2020_09_10-09_21_07_BB_RR.csv,APHM
31,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V4\Ceinture\2019_10_23-09_34_13_BB_RR.csv,LPC
32,0122BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0122BDS\0122BDS_V4\CEINTURE\2020_09_25-09_20_42\2020_09_25-09_20_42_BB_RR.csv,APHM
33,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V4\Ceinture\2019_11_05-09_18_30_BB_RR.csv,LPC
34,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V4\Ceinture\2019_11_08-09_23_05_BB_RR.csv,LPC
35,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS_V4\CEINTURE\2020_09_24-09_19_20\2020_09_24-09_19_20_BB_RR.csv,APHM
36,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V4\Ceinture\2019_11_15-09_27_24_BB_RR.csv,LPC
37,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V4\Ceinture\2019_12_02-09_03_50_BB_RR.csv,LPC
38,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V4\Ceinture\2019_11_21-09_34_50_BB_RR.csv,LPC
39,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V4\Ceinture\2019_12_11-09_33_30_BB_RR.csv,LPC
40,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V4\Ceinture\2019_12_18-09_38_27_BB_RR.csv,LPC
41,0130FAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0130FAR-0154FAR\V4\0130FAR\ceinture\2020_02_11-09_47_09\2020_02_11-09_47_09_BB_RR.csv,LPC
42,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\0132GAR_V4\ceinture\ceinture\2021_02_08-10_03_14_BB_RR.csv,LPC
43,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\0157BPS_V4\ceinture\No Team Assigned\2021_02_09-09_54_43\2021_02_09-09_54_43_BB_RR.csv,LPC
44,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR_V4\Ceinture\No Team Assigned\2021_12_10-10_17_58\2021_12_10-10_17_58_BB_RR.csv,LPC
45,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V4\ceinture\No Team Assigned\2022_04_04-09_02_10\2022_04_04-09_02_10_BB_RR.csv,LPC
46,0139BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0167BMR\0167BMR_V4 0139BMR_V4\ceinture\No Team Assigned\2023_02_17-10_05_43\2023_02_17-10_05_43_BB_RR.csv,LPC
47,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V4 0140LMR\ceinture\No Team Assigned\2010_01_02-23_56_56\2010_01_02-23_56_56_BB_RR.csv,LPC
48,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR_V4\ceinture\No Team Assigned\2023_04_25-09_05_36\2023_04_25-09_05_36_BB_RR.csv,LPC
49,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V4\ceinture\No Team Assigned\2023_04_11-09_08_49\2023_04_11-09_08_49_BB_RR.csv,LPC
50,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_22-10_08_57 0302ZMR\2019_10_22-10_08_57_BB_RR.csv,CAEN
51,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_24-09_55_49 0304VMR\2020_01_24-09_55_49_BB_RR.csv,CAEN
52,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_23-09_51_21 0305LCR\2020_01_23-09_51_21_BB_RR (1).csv,CAEN
53,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_05_25-10_35_35 0307SMR\2020_05_25-10_35_35_BB_RR.csv,CAEN
54,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_02_09_04_56 0308RGR\2020_09_02__09_04_56_BR_RR (1).csv,CAEN
55,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_05_18-08_40_01 0310ACS\2020_05_18-08_40_01_BB_RR (1).csv,CAEN
56,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_17-09_10_51 0311CJS\2020_06_17__09_10_51_BR_RR.csv,CAEN
57,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_08-10_01_39 0313FPR\2020_06_08-10_01_39_BB_RR.csv,CAEN
58,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_11-09_44_57 0315VCS\2020_06_11-09_44_57_BB_RR.csv,CAEN
59,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_02-09_58_49 0316TMS\2020_06_02-09_58_49_BB_RR.csv,CAEN
60,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_04-10_17_18 0317LGS\2020_06_04-10_17_18_BB_RR.csv,CAEN
61,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_06_25-09_53_39 0319LJS\2020_06_25__09_53_39_BR_RR.csv,CAEN
62,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_07_07_10_00_01 0321DRR\2020_07_07__10_00_01_BR_RR.csv,CAEN
63,0322RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_07_21_10_14_15_0322RMS\2020_07_21__10_14_15_BR_RR.csv,CAEN
64,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_27_09_25_18 0323RFS\2020_08_27__09_25_18_BR_RR.csv,CAEN
65,0324LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_25_10_50_46_0324LMR\2020_08_25__10_50_46_BR_RR.csv,CAEN
66,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_06_09_29_07 0326BJR\2020_10_06__09_29_07_BR_RR.csv,CAEN
67,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_24_09_47_04_0328MPR\2020_09_24__09_47_04_BR_RR.csv,CAEN
68,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_03_09_51_23 0329NMR\2020_11_03__10_51_23_BR_RR.csv,CAEN
69,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_01_18_09_43_27 0330RTR\2021_01_18__09_43_27_BR_RR.csv,CAEN
70,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_27_09_49_41 0331GRS\2020_11_27__09_49_41_BR_RR.csv,CAEN
71,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_25_09_23_00 0333MMS\2021_06_25__09_23_00_BR_RR.csv,CAEN
72,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_09_03_09_48_21 0337BFS\2021_09_03__09_48_21_BR_RR.csv,CAEN
73,0338JBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_10_22_09_30_26 0338JBS\2021_10_22__09_30_26_BR_RR (1).csv,CAEN
74,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_12_02_13_45_00 0339NPR\2021_12_02__14_45_00_BR_RR.csv,CAEN
75,0340BAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_12_14_13_46_23 0340BAR\2021_12_14__13_46_23_BR_RR.csv,CAEN
76,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_15_09_52_03 0341LJS\2022_02_15__09_52_03_BR_RR.csv,CAEN
77,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_08_10_03_11 0343PAS\2022_03_08__10_03_11_BR_RR.csv,CAEN
78,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026_copie\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_04_01_09_38_38 0342VNS\2022_04_01__09_38_38_BR_RR.csv,CAEN
79,0345LAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_04_09_32_11 0345LAR\2022_11_04__09_32_11_BR_RR.csv,CAEN
80,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_10_28_09_40_15 0346GLS\2022_10_28__09_40_15_BR_RR.csv,CAEN
81,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_18_09_36_29 0347DMR\2022_11_18__09_36_29_BR_RR.csv,CAEN
82,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_15_09_30_10 0348GCR\2022_11_15__09_30_10_BR_RR.csv,CAEN
83,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_11_21_09_29_39 0349LLS\2022_11_21__09_29_39_BR_RR.csv,CAEN
84,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_12_13_09_34_08 0350MYR\2022_12_13__09_34_08_BR_RR.csv,CAEN
85,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_01_05_09_57_02 0351FIR\2023_01_05__09_57_02_BR_RR.csv,CAEN
86,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_01_12_09_42_36 0352RNR\2023_01_12__09_42_36_BR_RR.csv,CAEN
87,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2023_06_20_09_25_35 0356DMS\2023_06_20__09_25_35_BR_RR.csv,CAEN
88,0401BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0401BDS\V4\Ceinture\2019_11_13__09_37_08_BR_RR.csv,CERCA
89,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V4\ceinture\No Team Assigned\2020_01_10-09_57_29\2020_01_10-09_57_29_BB_RR.csv,POITIERS
90,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS-V4\0402LLS ceinture V4\No Team Assigned\2020_02_07-09_30_21\2020_02_07-09_30_21_BB_RR.csv,POITIERS
91,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V4\0403DCR - ceinture V4\No Team Assigned\2020_02_28-10_11_17\2020_02_28-10_11_17_BB_RR.csv,POITIERS
92,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404YCS-V4\0404YC ceinture V4\2020_06_19-10_14_18_BB_RR.csv,POITIERS
93,0404DER,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0404DER\V4\Ceinture\2019_11_08__09_47_26_BR_RR.csv,CERCA
94,0405RCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0405RCR\V4\Ceinture\2020_02_14__10_06_12_BR_RR.csv,CERCA
95,0406BBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0406BBS\V4\Ceinture\2019_12_18__11_01_15_BR_RR.csv,CERCA
96,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V4\0407LJ ceinture V4\No Team Assigned\2020_07_02-09_52_07\2020_07_02-09_52_07_BB_RR.csv,POITIERS
97,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC-V4\0408BC-ceinture V4\No Team Assigned\2020_08_06-10_25_47\2020_08_06-10_25_47_BB_RR.csv,POITIERS
98,0408SJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0408SJS\V4\Ceinture\2019_11_27__10_38_19_BR_RR.csv,CERCA
99,0409HCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0409HCR\V4\Ceinture\2020_01_06__10_24_59_BR_RR.csv,CERCA
100,0410FMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0410FMS\V4\Ceinture\2019_11_18__10_30_15_BR_RR.csv,CERCA
101,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V4\0411VE-ceinture V4\0411VES - V4\2020_11_12-10_17_49\2020_11_12-10_17_49_BB_RR.csv,POITIERS
102,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V4\0412ANS ceinture V4\No Team Assigned\2020_11_19-10_02_29\2020_11_19-10_02_29_BB_RR.csv,POITIERS
103,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS V4\0413HFS-ceinture V4\No Team Assigned\2020_11_26-09_37_17\2020_11_26-09_37_17_BB_RR.csv,POITIERS
104,0414PJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0414 PJ\0414 PJ V4\0414PJ-ceinture V4\2021_06_10-09_47_37\2021_06_10-09_47_37_BB_RR.csv,POITIERS
105,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0414PVR\V4\Ceinture\2021_07_09__09_38_01_BR_RR.csv,CERCA
106,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\RIGALLEAU\RIGALLEAU\participant Sarah\0420MCR\V4\Ceinture\2021_07_05__14_07_01_BR_RR.csv,CERCA
107,0501MBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-01-MB-S\V4\CEINTURE\2019_11_18-09_10_13_BB_RR - Copie.csv,ROUEN
108,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V4\CEINTURE\2019_11_13-08_56_31_BB_RR.csv,ROUEN
109,0503LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-03-LC-R\V4\CEINTURE\2020_01_23-09_24_20_BB_RR.csv,ROUEN
110,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V4\CEINTURE V4\2020_03_05-09_10_25_BB_RR.csv,ROUEN
111,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V4\CEINTURE\2020_02_14-09_12_56_BB_RR.csv,ROUEN
112,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V4\CEINTURE\2020_09_24-09_15_56_BB_RR.csv,ROUEN
113,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V4\CEINTURE\2020_05_12-09_15_51_BB_RR.csv,ROUEN
114,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V4\CEINTURE\2020_11_17-09_13_35_BB_RR.csv,ROUEN
115,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V4\CEINTURE\Record 1_2022_02_15-14_05_19_BB_RR.csv,ROUEN
116,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V4\CEINTURE\Record 1_2022_03_15-09_12_51_BB_RR - Copie.csv,ROUEN
117,0514LPS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-14-LP-S\V4\CEINTURE\No Team Assigned\2023_02_07-09_15_05\Record 1_2023_02_07-09_15_05_BB_RR.csv,ROUEN
118,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V4\CEINTURE\2023_08_11-09_24_47\Record 1_2023_08_11-09_24_47_BB_RR.csv,ROUEN

In [30]:
# CONSERVATION DES FEUILLES ET CONDITIONS DANS UN FICHIER TXT 

chemin_txt = r"C:\Users\judupont\Desktop\df_global_v4.txt"

df_global.to_csv(
    chemin_txt,
    sep="\t",
    index=False,
    encoding="utf-8-sig"
)

print(f"📄 df_global sauvegardé : {chemin_txt}")

📄 df_global sauvegardé : C:\Users\judupont\Desktop\df_global_v4.txt

# Verification que le temps d'experience et le temps du fichier BB_RR correspondent, offset et continuité

In [31]:
def convertir_heure_en_secondes(x):
    if pd.isna(x):
        return None

    # Excel → heure uniquement
    if isinstance(x, (int, float)):
        seconds = float(x) * 24 * 3600
        return seconds % (24 * 3600)

    try:
        t = pd.to_datetime(str(x).strip()).time()
        return t.hour * 3600 + t.minute * 60 + t.second
    except Exception:
        return None



dfs_excel = []

for feuille, data in resultats_bloc1.items():

    df_excel = data["df"].copy()

    # filtrage candidats retenus
    df_excel["Numero_inclusion"] = df_excel["Numero_inclusion"].astype(str)
    df_excel = df_excel[
        df_excel["Numero_inclusion"].isin(df_global['Numero_inclusion'])
    ]

    if df_excel.empty:
        continue

    # Conversion heures → secondes
    df_excel["heure_debut_sec"] = df_excel["heure_ceinture_v4"].apply(convertir_heure_en_secondes)
    df_excel["heure_fin_sec"] = df_excel["heure_fin_tests_v4"].apply(convertir_heure_en_secondes)

    # Durée visite Excel
    df_excel["duree_experience_sec"] = (
        df_excel["heure_fin_sec"] - df_excel["heure_debut_sec"]
    )

    # Sécurité passage minuit
    df_excel.loc[
        df_excel["duree_experience_sec"] < 0,
        "duree_experience_sec"
    ] += 24 * 3600

    df_excel["Feuille"] = feuille
    dfs_excel.append(df_excel)

df_excel_global = pd.concat(dfs_excel, ignore_index=True)


print(f"Lignes Excel retenues : {len(df_excel_global)}")
display(df_excel_global[[
    "Numero_inclusion",
    "Feuille",
    "duree_experience_sec"
]])

Lignes Excel retenues : 134

    Numero_inclusion            Feuille  duree_experience_sec
0            0101CAR               APHM                  9660
1            0102PCR               APHM                  7440
2            0105PNR               APHM                  7140
3            0104FJS               APHM                  6180
4            0107DSS               APHM                  6060
5            0109GSS               APHM                  7140
6            0110LPR               APHM                  8760
7            0111MNR               APHM                  7620
8            0112BSR               APHM                  8220
9            0114LMS               APHM                  6960
10           0116VAR               APHM                 10020
11           0119LJS               APHM                  8160
12           0121MJR               APHM                  9300
13           0122BDS               APHM                  5580
14           0123RMS               APHM                  7440
15           0302ZMR               CAEN                  5640
16           0304VMR               CAEN                  6840
17           0305LCR               CAEN                  6120
18           0307SMR               CAEN                  7560
19           0308RGR               CAEN                  5160
20           0311CJS               CAEN                  8160
21           0310ACS               CAEN                  7740
22           0315VCS               CAEN                  5520
23           0313FPR               CAEN                  5460
24           0316TMS               CAEN                  6960
25           0317LGS               CAEN                  6360
26           0319LJS               CAEN                  4980
27           0321DRR               CAEN                  5400
28           0323RFS               CAEN                  5400
29           0322RMS               CAEN                  4860
30           0324LMR               CAEN                  5100
31           0326BJR               CAEN                  6780
32           0328MPR               CAEN                  6180
33           0330RTR               CAEN                  7500
34           0329NMR               CAEN                  6600
35           0331GRS               CAEN                  6720
36           0333MMS               CAEN                  5460
37           0337BFS               CAEN                  6900
38           0338JBS               CAEN                  6300
39           0339NPR               CAEN                  5520
40           0340BAR               CAEN                  4560
41           0341LJS               CAEN                  6000
42           0342VNS               CAEN                  4620
43           0343PAS               CAEN                  5760
44           0345LAR               CAEN                  6060
45           0349LLS               CAEN                  4800
46           0347DMR               CAEN                  6300
47           0346GLS               CAEN                  6180
48           0348GCR               CAEN                  7440
49           0350MYR               CAEN                  6420
50           0351FIR               CAEN                  5820
51           0352RNR               CAEN                  5820
52           0356DMS               CAEN                  6840
53           0401TSS           POITIERS                  9660
54           0402LLS           POITIERS                  7920
55           0403DCR           POITIERS                  6900
56           0404CYS           POITIERS                  6900
57           0407LJR           POITIERS                  7500
58           0408BCS           POITIERS                  5400
59           0413HFS           POITIERS                  8760
60           0411VES           POITIERS                  6360
61           0412ANS           POITIERS                  7200
62           0414PJS           POITIERS                  7380
63           0501MBS              ROUEN                  7380
64           0502LIR              ROUEN                  6840
65           0503LCR              ROUEN                  5880
66           0504BCS              ROUEN                  6420
67           0505PPR              ROUEN                  6840
68           0508SRR              ROUEN                  6600
69           0507BDS              ROUEN                  6900
70           0510DFS              ROUEN                  7020
71           0512RCR              ROUEN                  6240
72           0513EBS              ROUEN                  6420
73           0514LPS              ROUEN                  6360
74           0515FAR              ROUEN                  7800
75           0626MCS            LAVERAN                  7800
76           0630RJR            LAVERAN                  6060
77           0629TCR            LAVERAN                  8220
78           0631LHR            LAVERAN                  5640
79           0101EMS                LPC                  7860
80           0102EMS                LPC                  4980
81           0103BPS                LPC                  7020
82           0104IBS                LPC                  6900
83           0107LER                LPC                  6780
84           0108MMS                LPC                  5880
85           0109MJR                LPC                  6480
86           0110RMS                LPC                  5880
87           0111TAS                LPC                  5820
88           0112DRR                LPC                  6180
89           0113DGR                LPC                  6120
90           0114MLR                LPC                  7440
91           0115MHR                LPC                  7440
92           0116CNR                LPC                  7800
93           0117MSR                LPC                  6780
94           0118TMS                LPC                  7200
95           0119BIR                LPC                  6180
96           0120ANS                LPC                  6000
97           0121RPS                LPC                  7620
98           0122VCR                LPC                  7020
99           0123GVS                LPC                  5460
100          0124PAS                LPC                  6000
101          0126VLR                LPC                  6240
102          0127CMS                LPC                  6360
103          0128ALS                LPC                  5940
104          0129APR                LPC                  9720
105          0130FAR                LPC                  7740
106          0132GAR                LPC                  6420
107          0133BPS                LPC                  6840
108          0136CJR                LPC                  6180
109          0138NWR                LPC                  6900
110          0139BMR                LPC                  6480
111          0140LMR                LPC                  9060
112          0143EBR                LPC                  7980
113          0144ZGR                LPC                 11220
114          0801HDR  SAINTE-MARGUERITE                  6060
115          0802LAS  SAINTE-MARGUERITE                  6720
116          0804GOR  SAINTE-MARGUERITE                  6840
117          0803DPS  SAINTE-MARGUERITE                  7620
118          0805BMS  SAINTE-MARGUERITE                  6780
119          0806KHS  SAINTE-MARGUERITE                  6300
120          0807OMR  SAINTE-MARGUERITE                  5460
121          0901SMR                CGD                  7680
122          0903DJS                CGD                  7680
123          0904KJS                CGD                  7440
124          0905SLR                CGD                  7020
125          0401BDS              CERCA                  7860
126          0404DER              CERCA                  6840
127          0405RCR              CERCA                  6780
128          0406BBS              CERCA                  7860
129          0408SJS              CERCA                 10380
130          0409HCR              CERCA                  6420
131          0410FMS              CERCA                  7860
132          0414PVR              CERCA                  7680
133          0420MCR              CERCA                  8400

In [32]:
# ==== Conversion Date dans Excel ====
df_excel_global["Date_v4_dt"] = pd.to_datetime(
    df_excel_global["Date_v4"], errors="coerce"
).dt.date

# ==== Liste des candidats pour lesquels on ignore la vérification de la date car verifier à la main ==== # 0140LMR trop abberant
ignore_date_check = ["0114MLR","0503LCR","0512RCR","0513EBS"]

rows_rr = []

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"])
    chemin = row["Chemin"]

    # ---- récupérer la ligne Excel correspondant au PID ----
    ligne_excel = df_excel_global[df_excel_global["Numero_inclusion"] == pid]
    if ligne_excel.empty:
        continue

    date_v4 = ligne_excel.iloc[0]["Date_v4_dt"]
    duree_excel_sec = ligne_excel.iloc[0]["duree_experience_sec"]

    # ---- lecture CSV BB_RR ----
    try:
        df_rr = pd.read_csv(chemin)
    except Exception:
        continue

    if "Timestamp" not in df_rr.columns:
        continue

    # ---- conversion timestamp CSV (ignorer les millisecondes) ----
    df_rr["Timestamp_dt"] = pd.to_datetime(
        df_rr["Timestamp"].str.split(".").str[0],
        dayfirst=True,
        errors="coerce"
    )
    df_rr = df_rr.dropna(subset=["Timestamp_dt"])

    # ---- filtrage par date si pas dans ignore_date_check ----
    if pid not in ignore_date_check and pd.notna(date_v4):
        df_rr = df_rr[df_rr["Timestamp_dt"].dt.date == date_v4]

    if df_rr.empty:
        continue

    # ---- durée RR (sans ms) ----
    t_min = df_rr["Timestamp_dt"].dt.floor("s").min()
    t_max = df_rr["Timestamp_dt"].dt.floor("s").max()
    duree_rr_sec = (t_max - t_min).total_seconds()

    rows_rr.append({
        "Numero_inclusion": pid,
        "duree_rr_sec": duree_rr_sec,
        "duree_excel_sec": duree_excel_sec,
        "nb_points": len(df_rr),
    })

df_rr_global = pd.DataFrame(rows_rr)
print(f"RR calculés : {len(df_rr_global)}")
display(df_rr_global)

RR calculés : 133

    Numero_inclusion  duree_rr_sec  duree_excel_sec  nb_points
0            0101CAR        9809.0             9660     175160
1            0101EMS        8011.0             7860     143053
2            0102EMS        4897.0             4980      87446
3            0102PCR        7699.0             7440     137482
4            0103BPS        7069.0             7020     126232
5            0104FJS        6386.0             6180     114035
6            0104IBS        6995.0             6900     124910
7            0105PNR        7210.0             7140     128750
8            0107DSS        6228.0             6060     111214
9            0107LER        6890.0             6780     123035
10           0108MMS        5932.0             5880     105928
11           0109GSS        6774.0             7140     120964
12           0109MJR        6537.0             6480     116732
13           0110LPR        8389.0             8760     149803
14           0110RMS        5945.0             5880     106160
15           0111MNR        7542.0             7620     134678
16           0111TAS        5845.0             5820     104375
17           0112BSR        8350.0             8220     149107
18           0112DRR        6181.0             6180     110375
19           0113DGR        6024.0             6120     107571
20           0114LMS        7044.0             6960     125785
21           0114MLR        7482.0             7440     133607
22           0115MHR        7454.0             7440     133107
23           0116CNR        7757.0             7800     138517
24           0116VAR       10114.0            10020     180607
25           0117MSR        6859.0             6780     122482
26           0118TMS        7274.0             7200     129892
27           0119BIR        6307.0             6180     112625
28           0119LJS        8469.0             8160     151232
29           0120ANS        6086.0             6000     108678
30           0121MJR        9672.0             9300     172714
31           0121RPS        7669.0             7620     136946
32           0122BDS        5617.0             5580     100303
33           0122VCR        7037.0             7020     125660
34           0123GVS        5558.0             5460      99250
35           0123RMS        7575.0             7440     135267
36           0124PAS        6121.0             6000     109303
37           0126VLR        6287.0             6240     112267
38           0127CMS        6355.0             6360     113482
39           0128ALS        6010.0             5940     107321
40           0129APR        9697.0             9720     173160
41           0130FAR        7961.0             7740     142160
42           0132GAR        6478.0             6420     115678
43           0133BPS        6849.0             6840     122303
44           0136CJR        6233.0             6180     111303
45           0138NWR        7016.0             6900     125285
46           0139BMR        6611.0             6480     118053
47           0143EBR        8535.0             7980     152410
48           0144ZGR       11353.0            11220     202732
49           0302ZMR        6029.0             5640     107660
50           0304VMR        7420.0             6840     132500
51           0305LCR        6640.0             6120     118571
52           0307SMR        8112.0             7560     144857
53           0308RGR        6007.0             5160     107267
54           0310ACS        8972.0             7740     160214
55           0311CJS        8522.0             8160     152178
56           0313FPR        5729.0             5460     102303
57           0315VCS        6006.0             5520     107250
58           0316TMS        7498.0             6960     133892
59           0317LGS        6512.0             6360     116285
60           0319LJS        6083.0             4980     108625
61           0321DRR       11208.0             5400     200142
62           0322RMS        4995.0             4860      89196
63           0323RFS        5772.0             5400     103071
64           0324LMR        5542.0             5100      98964
65           0326BJR        7088.0             6780     126571
66           0328MPR        6771.0             6180     120910
67           0329NMR        6931.0             6600     123767
68           0330RTR        9308.0             7500     166214
69           0331GRS        7443.0             6720     132910
70           0333MMS        5809.0             5460     103732
71           0337BFS        7869.0             6900     140517
72           0338JBS        7044.0             6300     125785
73           0339NPR        5861.0             5520     104660
74           0340BAR        5098.0             4560      91035
75           0341LJS        6288.0             6000     112285
76           0342VNS        5608.0             4620     100142
77           0343PAS        7360.0             5760     131428
78           0345LAR        6886.0             6060     122964
79           0346GLS        6515.0             6180     116339
80           0347DMR        7361.0             6300     131446
81           0348GCR        8153.0             7440     145589
82           0349LLS        6070.0             4800     108392
83           0350MYR        6884.0             6420     122928
84           0351FIR        7504.0             5820     134000
85           0352RNR        7891.0             5820     140910
86           0356DMS        7260.0             6840     129642
87           0401BDS        7918.0             7860     141392
88           0401TSS       50550.0             9660     902689
89           0402LLS        8975.0             7920     160267
90           0403DCR        7480.0             6900     133571
91           0404CYS        7107.0             6900     126910
92           0404DER        6962.0             6840     124321
93           0405RCR        6810.0             6780     121607
94           0406BBS        7960.0             7860     142142
95           0407LJR        8067.0             7500     144053
96           0408BCS        7030.0             5400     125535
97           0408SJS       10415.0            10380     185982
98           0409HCR        6200.0             6420     110714
99           0410FMS        7881.0             7860     140732
100          0411VES        6830.0             6360     121964
101          0412ANS        7973.0             7200     142375
102          0413HFS        9683.0             8760     172910
103          0414PJS        8362.0             7380     149321
104          0414PVR        7782.0             7680     138964
105          0420MCR        8751.0             8400     156267
106          0501MBS        7748.0             7380     138357
107          0502LIR        6970.0             6840     124464
108          0503LCR        6082.0             5880     108607
109          0504BCS        6917.0             6420     123517
110          0505PPR        7189.0             6840     128375
111          0507BDS        7146.0             6900     127607
112          0508SRR        7079.0             6600     126410
113          0510DFS        7033.0             7020     125589
114          0512RCR        6977.0             6240     124589
115          0513EBS        9222.0             6420     164678
116          0514LPS        6759.0             6360     120696
117          0515FAR        7530.0             7800     134464
118          0626MCS        7260.0             7800     129642
119          0629TCR        8569.0             8220     153017
120          0630RJR        6189.0             6060     110517
121          0631LHR        5747.0             5640     102625
122          0801HDR        6144.0             6060     109714
123          0802LAS        6832.0             6720     122000
124          0803DPS        7686.0             7620     137250
125          0804GOR        6864.0             6840     122571
126          0805BMS        6836.0             6780     122071
127          0806KHS        6347.0             6300     113339
128          0807OMR        5436.0             5460      97071
129          0901SMR        7738.0             7680     138178
130          0903DJS        7660.0             7680     136785
131          0904KJS        7664.0             7440     136857
132          0905SLR        7083.0             7020     126482

# D'ou vient l'écart ? L'offest doit etre appliqué en debut, en fin, au milieu?

In [33]:
def sec_to_datetime(sec, date_ref):
    return datetime.combine(
        date_ref.date(),
        datetime.min.time()
    ) + timedelta(seconds=int(sec))


resultats_offset = []

# apres verification à la main ces candidats ont leur heure de debut decaler de plus ou moins 1h donc on decale pour appliquer le découpage quand meme

candidats_rebase_excel = {
    "0116VAR", "0138NWR", "0140LMR", "0143EBR", "0144ZGR", "0626MCS",
    "0310ACS", "0329NMR", "0806KHS", "0339NPR","0801HDR", "0802LAS", "0901SMR"
}


for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin_bb_rr = row["Chemin"]

    # ===== Lecture BB_RR (ZIP ou non) =====
    try:
        if ".ZIP|" in chemin_bb_rr.upper():
            zip_path, inner_csv = chemin_bb_rr.split("|", 1)
            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_rr = pd.read_csv(f)
        else:
            df_rr = pd.read_csv(chemin_bb_rr)
    except Exception as e:
        print(f"⚠️ Lecture BB_RR impossible pour {pid} : {e}")
        continue

    if "Timestamp" not in df_rr.columns:
        continue

    # ===== Parsing timestamp =====
    df_rr["Timestamp"] = pd.to_datetime(
        df_rr["Timestamp"].astype(str).str.split(".").str[0],
        dayfirst=True,
        errors="coerce"
    )
    df_rr = df_rr.dropna(subset=["Timestamp"])
    if df_rr.empty:
        continue

    t_min = df_rr["Timestamp"].min()
    t_max = df_rr["Timestamp"].max()

    # ===== Excel =====
    ligne_excel = df_excel_global.loc[
        df_excel_global["Numero_inclusion"] == pid
    ]
    if ligne_excel.empty:
        continue

    duree_excel_sec = ligne_excel["duree_experience_sec"].values[0]
    if pd.isna(duree_excel_sec):
        continue

    # ===== Cas spécial : rebase Excel sur RR =====
    if pid in candidats_rebase_excel:
        h_debut = t_min
        h_fin = h_debut + pd.to_timedelta(duree_excel_sec, unit="s")
        mode = "REBASE_RR"
        # 🔹 delta_retard_sec pour info, même si rebase
        delta_retard_sec = 0
    else:
        h_debut_sec = ligne_excel["heure_debut_sec"].values[0]
        h_fin_sec = ligne_excel["heure_fin_sec"].values[0]
        if pd.isna(h_debut_sec) or pd.isna(h_fin_sec):
            continue

        h_debut = sec_to_datetime(h_debut_sec, t_min)
        h_fin   = sec_to_datetime(h_fin_sec, t_min)
        mode = "STANDARD"

        # Calcul du delta retard sec
        delta_retard_sec = max((t_min - h_debut).total_seconds(), 0)

    # ===== Comptages =====
    nb_avant = (df_rr["Timestamp"] < h_debut).sum()
    nb_dans = ((df_rr["Timestamp"] >= h_debut) & (df_rr["Timestamp"] <= h_fin)).sum()
    nb_apres = (df_rr["Timestamp"] > h_fin).sum()
    total = len(df_rr)

    # ===== Diagnostic =====
    if nb_apres > nb_avant:
        origine = "FIN"
    elif nb_avant > nb_apres:
        origine = "DEBUT"
    else:
        origine = "MIXTE"

    resultats_offset.append({
        "Numero_inclusion": pid,
        "mode_calcul": mode,
        "nb_total_points": total,
        "nb_avant_excel": nb_avant,
        "nb_dans_excel": nb_dans,
        "nb_apres_excel": nb_apres,
        "origine_offset": origine,
        "delta_retard_sec": delta_retard_sec  
    })

df_offset_bb_rr = pd.DataFrame(resultats_offset)

print(f"Offsets BB_RR calculés : {len(df_offset_bb_rr)}")
display(df_offset_bb_rr)

Offsets BB_RR calculés : 134

,Numero_inclusion,mode_calcul,nb_total_points,nb_avant_excel,nb_dans_excel,nb_apres_excel,origine_offset,delta_retard_sec
0,0101CAR,STANDARD,175160,0,171833,3327,FIN,38.0
1,0101EMS,STANDARD,143053,136,140375,2542,FIN,0.0
2,0102EMS,STANDARD,87446,0,87446,0,MIXTE,48.0
3,0102PCR,STANDARD,137482,0,132779,4703,FIN,5.0
4,0103BPS,STANDARD,126232,0,124904,1328,FIN,26.0
5,0104FJS,STANDARD,114035,332,110375,3328,FIN,0.0
6,0104IBS,STANDARD,124910,0,123171,1739,FIN,3.0
7,0105PNR,STANDARD,128750,0,127439,1311,FIN,4.0
8,0107DSS,STANDARD,111214,261,108232,2721,FIN,0.0
9,0107LER,STANDARD,123035,0,121010,2025,FIN,4.0
10,0108MMS,STANDARD,105928,0,104475,1453,FIN,30.0
11,0109GSS,STANDARD,120964,0,120964,0,MIXTE,14.0
12,0109MJR,STANDARD,116732,0,115565,1167,FIN,9.0
13,0110LPR,STANDARD,149803,0,149803,0,MIXTE,12.0
14,0110RMS,STANDARD,106160,0,104815,1345,FIN,11.0
15,0111MNR,STANDARD,134678,0,134678,0,MIXTE,1.0
16,0111TAS,STANDARD,104375,0,103564,811,FIN,21.0
17,0112BSR,STANDARD,149107,546,146804,1757,FIN,0.0
18,0112DRR,STANDARD,110375,0,109618,757,FIN,42.0
19,0113DGR,STANDARD,107571,0,107571,0,MIXTE,17.0
20,0114LMS,STANDARD,125785,636,124303,846,FIN,0.0
21,0114MLR,STANDARD,133607,0,131779,1828,FIN,61.0
22,0115MHR,STANDARD,133107,0,132368,739,FIN,28.0
23,0116CNR,STANDARD,138517,0,138517,0,MIXTE,16.0
24,0116VAR,REBASE_RR,180607,0,178939,1668,FIN,0.0
25,0117MSR,STANDARD,122482,528,121090,864,FIN,0.0
26,0118TMS,STANDARD,129892,0,128243,1649,FIN,19.0
27,0119BIR,STANDARD,112625,100,110375,2150,FIN,0.0
28,0119LJS,STANDARD,151232,0,145725,5507,FIN,0.0
29,0120ANS,STANDARD,108678,0,106922,1756,FIN,13.0
30,0121MJR,STANDARD,172714,0,164886,7828,FIN,67.0
31,0121RPS,STANDARD,136946,0,135850,1096,FIN,13.0
32,0122BDS,STANDARD,100303,0,98904,1399,FIN,42.0
33,0122VCR,STANDARD,125660,0,124832,828,FIN,30.0
34,0123GVS,STANDARD,99250,0,97421,1829,FIN,5.0
35,0123RMS,STANDARD,135267,0,132511,2756,FIN,20.0
36,0124PAS,STANDARD,109303,0,106725,2578,FIN,24.0
37,0126VLR,STANDARD,112267,0,110546,1721,FIN,50.0
38,0127CMS,STANDARD,113482,171,113311,0,DEBUT,0.0
39,0128ALS,STANDARD,107321,0,105547,1774,FIN,30.0
40,0129APR,STANDARD,173160,0,173100,60,FIN,27.0
41,0130FAR,STANDARD,142160,0,138064,4096,FIN,9.0
42,0132GAR,STANDARD,115678,0,114404,1274,FIN,14.0
43,0133BPS,STANDARD,122303,0,121386,917,FIN,43.0
44,0136CJR,STANDARD,111303,29,110375,899,FIN,0.0
45,0138NWR,REBASE_RR,125285,0,123225,2060,FIN,0.0
46,0139BMR,STANDARD,118053,296,115732,2025,FIN,0.0
47,0140LMR,REBASE_RR,162750,0,161796,954,FIN,0.0
48,0143EBR,REBASE_RR,152410,0,142510,9900,FIN,0.0
49,0144ZGR,REBASE_RR,202732,0,200368,2364,FIN,0.0
50,0302ZMR,STANDARD,107660,47,100732,6881,FIN,0.0
51,0304VMR,STANDARD,132500,0,120207,12293,FIN,109.0
52,0305LCR,STANDARD,118571,0,107850,10721,FIN,81.0
53,0307SMR,STANDARD,144857,0,134386,10471,FIN,35.0
54,0308RGR,STANDARD,107267,0,91153,16114,FIN,56.0
55,0310ACS,REBASE_RR,160214,0,138225,21989,FIN,0.0
56,0311CJS,STANDARD,152178,0,143743,8435,FIN,111.0
57,0313FPR,STANDARD,102303,0,95743,6560,FIN,99.0
58,0315VCS,STANDARD,107250,0,97564,9686,FIN,57.0
59,0316TMS,STANDARD,133892,0,120207,13685,FIN,229.0
60,0317LGS,STANDARD,116285,0,112189,4096,FIN,78.0
61,0319LJS,STANDARD,108625,0,87171,21454,FIN,99.0
62,0321DRR,STANDARD,200142,0,94278,105864,FIN,121.0
63,0322RMS,STANDARD,89196,0,84386,4810,FIN,135.0
64,0323RFS,STANDARD,103071,0,96118,6953,FIN,18.0
65,0324LMR,STANDARD,98964,0,90261,8703,FIN,46.0
66,0326BJR,STANDARD,126571,0,108100,18471,FIN,727.0
67,0328MPR,STANDARD,120910,0,109225,11685,FIN,64.0
68,0329NMR,REBASE_RR,123767,0,117868,5899,FIN,0.0
69,0330RTR,STANDARD,166214,0,131314,34900,FIN,147.0
70,0331GRS,STANDARD,132910,0,117136,15774,FIN,161.0
71,0333MMS,STANDARD,103732,1063,97518,5151,FIN,0.0
72,0337BFS,STANDARD,140517,0,122850,17667,FIN,21.0
73,0338JBS,STANDARD,125785,0,112046,13739,FIN,26.0
74,0339NPR,REBASE_RR,104660,0,98582,6078,FIN,0.0
75,0340BAR,STANDARD,91035,0,81028,10007,FIN,23.0
76,0341LJS,STANDARD,112285,0,104957,7328,FIN,123.0
77,0342VNS,STANDARD,100142,0,82314,17828,FIN,11.0
78,0343PAS,STANDARD,131428,0,102189,29239,FIN,38.0
79,0345LAR,STANDARD,122964,868,108232,13864,FIN,0.0
80,0346GLS,STANDARD,116339,1868,110375,4096,FIN,0.0
81,0347DMR,STANDARD,131446,1618,112518,17310,FIN,0.0
82,0348GCR,STANDARD,145589,886,132875,11828,FIN,0.0
83,0349LLS,STANDARD,108392,368,85732,22292,FIN,0.0
84,0350MYR,STANDARD,122928,0,114511,8417,FIN,8.0
85,0351FIR,STANDARD,134000,1028,103947,29025,FIN,0.0
86,0352RNR,STANDARD,140910,420,103947,36543,FIN,0.0
87,0356DMS,STANDARD,129642,0,121528,8114,FIN,35.0
88,0401BDS,STANDARD,141392,0,139154,2238,FIN,68.0
89,0401TSS,STANDARD,2227464,2689,172518,2052257,FIN,0.0
90,0402LLS,STANDARD,160267,2832,141447,15988,FIN,0.0
91,0403DCR,STANDARD,133571,2904,123232,7435,FIN,0.0
92,0404CYS,STANDARD,126910,0,122904,4006,FIN,18.0
93,0404DER,STANDARD,124321,0,121690,2631,FIN,26.0
94,0405RCR,STANDARD,121607,0,119796,1811,FIN,72.0
95,0406BBS,STANDARD,142142,796,140375,971,FIN,0.0
96,0407LJR,STANDARD,144053,939,133947,9167,FIN,0.0
97,0408BCS,STANDARD,125535,0,95600,29935,FIN,47.0
98,0408SJS,STANDARD,185982,0,183957,2025,FIN,79.0
99,0409HCR,STANDARD,110714,0,109315,1399,FIN,299.0
100,0410FMS,STANDARD,140732,0,140100,632,FIN,15.0
101,0411VES,STANDARD,121964,0,109493,12471,FIN,229.0
102,0412ANS,STANDARD,142375,0,128065,14310,FIN,29.0
103,0413HFS,STANDARD,172910,761,156446,15703,FIN,0.0
104,0414PJS,STANDARD,149321,0,131136,18185,FIN,37.0
105,0414PVR,STANDARD,138964,0,137136,1828,FIN,1.0
106,0420MCR,STANDARD,156267,0,148922,7345,FIN,61.0
107,0501MBS,STANDARD,138357,0,122993,15364,FIN,493.0
108,0502LIR,STANDARD,124464,0,121600,2864,FIN,31.0
109,0503LCR,STANDARD,108607,0,104653,3954,FIN,20.0
110,0504BCS,STANDARD,123517,0,114207,9310,FIN,25.0
111,0505PPR,STANDARD,128375,3278,122161,2936,DEBUT,0.0
112,0507BDS,STANDARD,127607,0,122224,5383,FIN,56.0
113,0508SRR,STANDARD,126410,0,116957,9453,FIN,51.0
114,0510DFS,STANDARD,125589,0,121529,4060,FIN,215.0
115,0512RCR,STANDARD,124589,6083,111446,7060,FIN,0.0
116,0513EBS,STANDARD,164678,3368,114661,46649,FIN,0.0
117,0514LPS,STANDARD,120696,0,113493,7203,FIN,5.0
118,0515FAR,STANDARD,134464,0,134171,293,FIN,287.0
119,0626MCS,REBASE_RR,129642,0,129642,0,MIXTE,0.0
120,0629TCR,STANDARD,153017,82,146804,6131,FIN,0.0
121,0630RJR,STANDARD,110517,0,107707,2810,FIN,29.0
122,0631LHR,STANDARD,102625,0,100207,2418,FIN,29.0
123,0801HDR,REBASE_RR,109714,0,108225,1489,FIN,0.0
124,0802LAS,REBASE_RR,122000,0,120011,1989,FIN,0.0
125,0803DPS,STANDARD,137250,0,136082,1168,FIN,0.0
126,0804GOR,STANDARD,122571,0,121957,614,FIN,11.0
127,0805BMS,STANDARD,122071,0,120815,1256,FIN,15.0
128,0806KHS,REBASE_RR,113339,0,112511,828,FIN,0.0
129,0807OMR,STANDARD,97071,0,96386,685,FIN,63.0
130,0901SMR,REBASE_RR,138178,0,137154,1024,FIN,0.0
131,0903DJS,STANDARD,136785,0,135904,881,FIN,70.0
132,0904KJS,STANDARD,136857,64,132875,3918,FIN,0.0
133,0905SLR,STANDARD,126482,0,125368,1114,FIN,0.0

In [34]:
from pathlib import Path
import pandas as pd
import os

# ===== Dossier de sortie =====
desktop = Path.home() / "Desktop"
output_dir = desktop / "bb_rr_tronqués_v4"
output_dir.mkdir(exist_ok=True)

print(f"📁 Dossier de sortie : {output_dir}")

# ===== Boucle sur les fichiers tronqués =====
for _, row in df_offset_bb_rr.iterrows():

    pid = row["Numero_inclusion"]

    # récupérer chemin BB_RR depuis df_global
    ligne_global = df_global[df_global["Numero_inclusion"] == pid]
    if ligne_global.empty:
        continue

    chemin_bb_rr = ligne_global.iloc[0]["Chemin"]

    nb_avant = int(row["nb_avant_excel"])
    nb_apres = int(row["nb_apres_excel"])

    # ===== Lecture BB_RR =====
    try:
        df_rr = pd.read_csv(chemin_bb_rr)
    except Exception as e:
        print(f"❌ Lecture impossible {pid}: {e}")
        continue

    total = len(df_rr)

    # ===== Indices de coupe =====
    start = nb_avant
    end = total - nb_apres

    if start >= end:
        print(f"⚠️ Troncature invalide pour {pid} (start={start}, end={end})")
        continue

    df_rr_trunc = df_rr.iloc[start:end].reset_index(drop=True)

    if df_rr_trunc.empty:
        print(f"⚠️ {pid} → fichier vide après troncature")
        continue

    # ===== Nom fichier =====
    nom_fichier = f"offset_{pid}_{Path(chemin_bb_rr).name}"
    path_sortie = output_dir / nom_fichier

    # ===== Sauvegarde =====
    df_rr_trunc.to_csv(path_sortie, index=False)

    print(
        f"✅ {pid} | "
        f"avant={nb_avant}, après={nb_apres} | "
        f"{len(df_rr_trunc)} lignes → {path_sortie.name}"
    )

print("🎯 Troncature terminée")

📁 Dossier de sortie : C:\Users\judupont\Desktop\bb_rr_tronqués_v4
✅ 0101CAR | avant=0, après=3327 | 171833 lignes → offset_0101CAR_2019_04_04-08_34_38_BB_RR.csv
✅ 0101EMS | avant=136, après=2542 | 140375 lignes → offset_0101EMS_2019_10_22-09_42_52_BB_RR.csv
✅ 0102EMS | avant=0, après=0 | 87446 lignes → offset_0102EMS_2019_09_05-09_36_48_BB_RR.csv
✅ 0102PCR | avant=0, après=4703 | 132779 lignes → offset_0102PCR_2019_04_12-09_06_05_BB_RR.csv
✅ 0103BPS | avant=0, après=1328 | 124904 lignes → offset_0103BPS_2019_09_17-09_43_26_BB_RR.csv
✅ 0104FJS | avant=332, après=3328 | 110375 lignes → offset_0104FJS_2019_11_08-08_26_41_BB_RR.csv
✅ 0104IBS | avant=0, après=1739 | 123171 lignes → offset_0104IBS_2019_09_02-10_21_03_BB_RR.csv
✅ 0105PNR | avant=0, après=1311 | 127439 lignes → offset_0105PNR_2019_09_09-08_53_04_BB_RR.csv
✅ 0107DSS | avant=261, après=2721 | 108232 lignes → offset_0107DSS_2019_10_17-09_08_45_BB_RR.csv
✅ 0107LER | avant=0, après=2025 | 121010 lignes → offset_0107LER_2019_09_04-10_10_04_BB_RR.csv
✅ 0108MMS | avant=0, après=1453 | 104475 lignes → offset_0108MMS_2019_10_24-09_06_30_BB_RR.csv
✅ 0109GSS | avant=0, après=0 | 120964 lignes → offset_0109GSS_2019_11_14-09_36_14_BB_RR.csv
✅ 0109MJR | avant=0, après=1167 | 115565 lignes → offset_0109MJR_2019_09_13-09_33_09_BB_RR.csv
✅ 0110LPR | avant=0, après=0 | 149803 lignes → offset_0110LPR_2019_11_21-09_04_12_BB_RR.csv
✅ 0110RMS | avant=0, après=1345 | 104815 lignes → offset_0110RMS_2019_09_16-09_30_11_BB_RR.csv
✅ 0111MNR | avant=0, après=0 | 134678 lignes → offset_0111MNR_2019_11_22-09_17_01_BB_RR.csv
✅ 0111TAS | avant=0, après=811 | 103564 lignes → offset_0111TAS_2019_10_03-09_26_21_BB_RR.csv
✅ 0112BSR | avant=546, après=1757 | 146804 lignes → offset_0112BSR_2020_03_05-09_38_29_BB_RR.csv
✅ 0112DRR | avant=0, après=757 | 109618 lignes → offset_0112DRR_2019_11_06-09_35_42_BB_RR.csv
✅ 0113DGR | avant=0, après=0 | 107571 lignes → offset_0113DGR_2019_08_27-09_41_17_BB_RR.csv
✅ 0114LMS | avant=636, après=846 | 124303 lignes → offset_0114LMS_2020_09_04-09_43_24_BB_RR.csv
✅ 0114MLR | avant=0, après=1828 | 131779 lignes → offset_0114MLR_2019_10_15-10_35_01_BB_RR.csv
✅ 0115MHR | avant=0, après=739 | 132368 lignes → offset_0115MHR_2019_10_09-09_23_28_BB_RR.csv
✅ 0116CNR | avant=0, après=0 | 138517 lignes → offset_0116CNR_2019_10_04-09_24_16_BB_RR.csv
✅ 0116VAR | avant=0, après=1668 | 178939 lignes → offset_0116VAR_2020_06_04-08_27_42_BB_RR.csv
✅ 0117MSR | avant=528, après=864 | 121090 lignes → offset_0117MSR_2019_10_11-09_25_30_BB_RR.csv
✅ 0118TMS | avant=0, après=1649 | 128243 lignes → offset_0118TMS_2019_10_16-07_56_19_BB_RR.csv
✅ 0119BIR | avant=100, après=2150 | 110375 lignes → offset_0119BIR_2019_10_28-09_48_54_BB_RR.csv
✅ 0119LJS | avant=0, après=5507 | 145725 lignes → offset_0119LJS_2020_10_08-09_18_00_BB_RR.csv
✅ 0120ANS | avant=0, après=1756 | 106922 lignes → offset_0120ANS_2019_11_19-09_44_13_BB_RR.csv
✅ 0121MJR | avant=0, après=7828 | 164886 lignes → offset_0121MJR_2020_09_10-09_21_07_BB_RR.csv
✅ 0121RPS | avant=0, après=1096 | 135850 lignes → offset_0121RPS_2019_10_23-09_34_13_BB_RR.csv
✅ 0122BDS | avant=0, après=1399 | 98904 lignes → offset_0122BDS_2020_09_25-09_20_42_BB_RR.csv
✅ 0122VCR | avant=0, après=828 | 124832 lignes → offset_0122VCR_2019_11_05-09_18_30_BB_RR.csv
✅ 0123GVS | avant=0, après=1829 | 97421 lignes → offset_0123GVS_2019_11_08-09_23_05_BB_RR.csv
✅ 0123RMS | avant=0, après=2756 | 132511 lignes → offset_0123RMS_2020_09_24-09_19_20_BB_RR.csv
✅ 0124PAS | avant=0, après=2578 | 106725 lignes → offset_0124PAS_2019_11_15-09_27_24_BB_RR.csv
✅ 0126VLR | avant=0, après=1721 | 110546 lignes → offset_0126VLR_2019_12_02-09_03_50_BB_RR.csv
✅ 0127CMS | avant=171, après=0 | 113311 lignes → offset_0127CMS_2019_11_21-09_34_50_BB_RR.csv
✅ 0128ALS | avant=0, après=1774 | 105547 lignes → offset_0128ALS_2019_12_11-09_33_30_BB_RR.csv
✅ 0129APR | avant=0, après=60 | 173100 lignes → offset_0129APR_2019_12_18-09_38_27_BB_RR.csv
✅ 0130FAR | avant=0, après=4096 | 138064 lignes → offset_0130FAR_2020_02_11-09_47_09_BB_RR.csv
✅ 0132GAR | avant=0, après=1274 | 114404 lignes → offset_0132GAR_2021_02_08-10_03_14_BB_RR.csv
✅ 0133BPS | avant=0, après=917 | 121386 lignes → offset_0133BPS_2021_02_09-09_54_43_BB_RR.csv
✅ 0136CJR | avant=29, après=899 | 110375 lignes → offset_0136CJR_2021_12_10-10_17_58_BB_RR.csv
✅ 0138NWR | avant=0, après=2060 | 123225 lignes → offset_0138NWR_2022_04_04-09_02_10_BB_RR.csv
✅ 0139BMR | avant=296, après=2025 | 115732 lignes → offset_0139BMR_2023_02_17-10_05_43_BB_RR.csv
✅ 0140LMR | avant=0, après=954 | 161796 lignes → offset_0140LMR_2010_01_02-23_56_56_BB_RR.csv
✅ 0143EBR | avant=0, après=9900 | 142510 lignes → offset_0143EBR_2023_04_25-09_05_36_BB_RR.csv
✅ 0144ZGR | avant=0, après=2364 | 200368 lignes → offset_0144ZGR_2023_04_11-09_08_49_BB_RR.csv
✅ 0302ZMR | avant=47, après=6881 | 100732 lignes → offset_0302ZMR_2019_10_22-10_08_57_BB_RR.csv
✅ 0304VMR | avant=0, après=12293 | 120207 lignes → offset_0304VMR_2020_01_24-09_55_49_BB_RR.csv
✅ 0305LCR | avant=0, après=10721 | 107850 lignes → offset_0305LCR_2020_01_23-09_51_21_BB_RR (1).csv
✅ 0307SMR | avant=0, après=10471 | 134386 lignes → offset_0307SMR_2020_05_25-10_35_35_BB_RR.csv
✅ 0308RGR | avant=0, après=16114 | 91153 lignes → offset_0308RGR_2020_09_02__09_04_56_BR_RR (1).csv
✅ 0310ACS | avant=0, après=21989 | 138225 lignes → offset_0310ACS_2020_05_18-08_40_01_BB_RR (1).csv
✅ 0311CJS | avant=0, après=8435 | 143743 lignes → offset_0311CJS_2020_06_17__09_10_51_BR_RR.csv
✅ 0313FPR | avant=0, après=6560 | 95743 lignes → offset_0313FPR_2020_06_08-10_01_39_BB_RR.csv
✅ 0315VCS | avant=0, après=9686 | 97564 lignes → offset_0315VCS_2020_06_11-09_44_57_BB_RR.csv
✅ 0316TMS | avant=0, après=13685 | 120207 lignes → offset_0316TMS_2020_06_02-09_58_49_BB_RR.csv
✅ 0317LGS | avant=0, après=4096 | 112189 lignes → offset_0317LGS_2020_06_04-10_17_18_BB_RR.csv
✅ 0319LJS | avant=0, après=21454 | 87171 lignes → offset_0319LJS_2020_06_25__09_53_39_BR_RR.csv
✅ 0321DRR | avant=0, après=105864 | 94278 lignes → offset_0321DRR_2020_07_07__10_00_01_BR_RR.csv
✅ 0322RMS | avant=0, après=4810 | 84386 lignes → offset_0322RMS_2020_07_21__10_14_15_BR_RR.csv
✅ 0323RFS | avant=0, après=6953 | 96118 lignes → offset_0323RFS_2020_08_27__09_25_18_BR_RR.csv
✅ 0324LMR | avant=0, après=8703 | 90261 lignes → offset_0324LMR_2020_08_25__10_50_46_BR_RR.csv
✅ 0326BJR | avant=0, après=18471 | 108100 lignes → offset_0326BJR_2020_10_06__09_29_07_BR_RR.csv
✅ 0328MPR | avant=0, après=11685 | 109225 lignes → offset_0328MPR_2020_09_24__09_47_04_BR_RR.csv
✅ 0329NMR | avant=0, après=5899 | 117868 lignes → offset_0329NMR_2020_11_03__10_51_23_BR_RR.csv
✅ 0330RTR | avant=0, après=34900 | 131314 lignes → offset_0330RTR_2021_01_18__09_43_27_BR_RR.csv
✅ 0331GRS | avant=0, après=15774 | 117136 lignes → offset_0331GRS_2020_11_27__09_49_41_BR_RR.csv
✅ 0333MMS | avant=1063, après=5151 | 97518 lignes → offset_0333MMS_2021_06_25__09_23_00_BR_RR.csv
✅ 0337BFS | avant=0, après=17667 | 122850 lignes → offset_0337BFS_2021_09_03__09_48_21_BR_RR.csv
✅ 0338JBS | avant=0, après=13739 | 112046 lignes → offset_0338JBS_2021_10_22__09_30_26_BR_RR (1).csv
✅ 0339NPR | avant=0, après=6078 | 98582 lignes → offset_0339NPR_2021_12_02__14_45_00_BR_RR.csv
✅ 0340BAR | avant=0, après=10007 | 81028 lignes → offset_0340BAR_2021_12_14__13_46_23_BR_RR.csv
✅ 0341LJS | avant=0, après=7328 | 104957 lignes → offset_0341LJS_2022_02_15__09_52_03_BR_RR.csv
✅ 0342VNS | avant=0, après=17828 | 82314 lignes → offset_0342VNS_2022_03_08__10_03_11_BR_RR.csv
✅ 0343PAS | avant=0, après=29239 | 102189 lignes → offset_0343PAS_2022_04_01__09_38_38_BR_RR.csv
✅ 0345LAR | avant=868, après=13864 | 108232 lignes → offset_0345LAR_2022_11_04__09_32_11_BR_RR.csv
✅ 0346GLS | avant=1868, après=4096 | 110375 lignes → offset_0346GLS_2022_10_28__09_40_15_BR_RR.csv
✅ 0347DMR | avant=1618, après=17310 | 112518 lignes → offset_0347DMR_2022_11_18__09_36_29_BR_RR.csv
✅ 0348GCR | avant=886, après=11828 | 132875 lignes → offset_0348GCR_2022_11_15__09_30_10_BR_RR.csv
✅ 0349LLS | avant=368, après=22292 | 85732 lignes → offset_0349LLS_2022_11_21__09_29_39_BR_RR.csv
✅ 0350MYR | avant=0, après=8417 | 114511 lignes → offset_0350MYR_2022_12_13__09_34_08_BR_RR.csv
✅ 0351FIR | avant=1028, après=29025 | 103947 lignes → offset_0351FIR_2023_01_05__09_57_02_BR_RR.csv
✅ 0352RNR | avant=420, après=36543 | 103947 lignes → offset_0352RNR_2023_01_12__09_42_36_BR_RR.csv
✅ 0356DMS | avant=0, après=8114 | 121528 lignes → offset_0356DMS_2023_06_20__09_25_35_BR_RR.csv
✅ 0401BDS | avant=0, après=2238 | 139154 lignes → offset_0401BDS_2019_11_13__09_37_08_BR_RR.csv
✅ 0401TSS | avant=2689, après=2052257 | 172518 lignes → offset_0401TSS_2020_01_10-09_57_29_BB_RR.csv
✅ 0402LLS | avant=2832, après=15988 | 141447 lignes → offset_0402LLS_2020_02_07-09_30_21_BB_RR.csv
✅ 0403DCR | avant=2904, après=7435 | 123232 lignes → offset_0403DCR_2020_02_28-10_11_17_BB_RR.csv
✅ 0404CYS | avant=0, après=4006 | 122904 lignes → offset_0404CYS_2020_06_19-10_14_18_BB_RR.csv
✅ 0404DER | avant=0, après=2631 | 121690 lignes → offset_0404DER_2019_11_08__09_47_26_BR_RR.csv
✅ 0405RCR | avant=0, après=1811 | 119796 lignes → offset_0405RCR_2020_02_14__10_06_12_BR_RR.csv
✅ 0406BBS | avant=796, après=971 | 140375 lignes → offset_0406BBS_2019_12_18__11_01_15_BR_RR.csv
✅ 0407LJR | avant=939, après=9167 | 133947 lignes → offset_0407LJR_2020_07_02-09_52_07_BB_RR.csv
✅ 0408BCS | avant=0, après=29935 | 95600 lignes → offset_0408BCS_2020_08_06-10_25_47_BB_RR.csv
✅ 0408SJS | avant=0, après=2025 | 183957 lignes → offset_0408SJS_2019_11_27__10_38_19_BR_RR.csv
✅ 0409HCR | avant=0, après=1399 | 109315 lignes → offset_0409HCR_2020_01_06__10_24_59_BR_RR.csv
✅ 0410FMS | avant=0, après=632 | 140100 lignes → offset_0410FMS_2019_11_18__10_30_15_BR_RR.csv
✅ 0411VES | avant=0, après=12471 | 109493 lignes → offset_0411VES_2020_11_12-10_17_49_BB_RR.csv
✅ 0412ANS | avant=0, après=14310 | 128065 lignes → offset_0412ANS_2020_11_19-10_02_29_BB_RR.csv
✅ 0413HFS | avant=761, après=15703 | 156446 lignes → offset_0413HFS_2020_11_26-09_37_17_BB_RR.csv
✅ 0414PJS | avant=0, après=18185 | 131136 lignes → offset_0414PJS_2021_06_10-09_47_37_BB_RR.csv
✅ 0414PVR | avant=0, après=1828 | 137136 lignes → offset_0414PVR_2021_07_09__09_38_01_BR_RR.csv
✅ 0420MCR | avant=0, après=7345 | 148922 lignes → offset_0420MCR_2021_07_05__14_07_01_BR_RR.csv
✅ 0501MBS | avant=0, après=15364 | 122993 lignes → offset_0501MBS_2019_11_18-09_10_13_BB_RR - Copie.csv
✅ 0502LIR | avant=0, après=2864 | 121600 lignes → offset_0502LIR_2019_11_13-08_56_31_BB_RR.csv
✅ 0503LCR | avant=0, après=3954 | 104653 lignes → offset_0503LCR_2020_01_23-09_24_20_BB_RR.csv
✅ 0504BCS | avant=0, après=9310 | 114207 lignes → offset_0504BCS_2020_03_05-09_10_25_BB_RR.csv
✅ 0505PPR | avant=3278, après=2936 | 122161 lignes → offset_0505PPR_2020_02_14-09_12_56_BB_RR.csv
✅ 0507BDS | avant=0, après=5383 | 122224 lignes → offset_0507BDS_2020_09_24-09_15_56_BB_RR.csv
✅ 0508SRR | avant=0, après=9453 | 116957 lignes → offset_0508SRR_2020_05_12-09_15_51_BB_RR.csv
✅ 0510DFS | avant=0, après=4060 | 121529 lignes → offset_0510DFS_2020_11_17-09_13_35_BB_RR.csv
✅ 0512RCR | avant=6083, après=7060 | 111446 lignes → offset_0512RCR_Record 1_2022_02_15-14_05_19_BB_RR.csv
✅ 0513EBS | avant=3368, après=46649 | 114661 lignes → offset_0513EBS_Record 1_2022_03_15-09_12_51_BB_RR - Copie.csv
✅ 0514LPS | avant=0, après=7203 | 113493 lignes → offset_0514LPS_Record 1_2023_02_07-09_15_05_BB_RR.csv
✅ 0515FAR | avant=0, après=293 | 134171 lignes → offset_0515FAR_Record 1_2023_08_11-09_24_47_BB_RR.csv
✅ 0626MCS | avant=0, après=0 | 129642 lignes → offset_0626MCS_2020_10_29-10_17_45_BB_RR.csv
✅ 0629TCR | avant=82, après=6131 | 146804 lignes → offset_0629TCR_2020_11_17-09_49_55_BB_RR.csv
✅ 0630RJR | avant=0, après=2810 | 107707 lignes → offset_0630RJR_2020_11_16-10_07_29_BB_RR.csv
✅ 0631LHR | avant=0, après=2418 | 100207 lignes → offset_0631LHR_2020_11_18-09_33_29_BB_RR.csv
✅ 0801HDR | avant=0, après=1489 | 108225 lignes → offset_0801HDR_2022_12_07-11_15_45_BB_RR.csv
✅ 0802LAS | avant=0, après=1989 | 120011 lignes → offset_0802LAS_2022_12_12-11_03_54_BB_RR.csv
✅ 0803DPS | avant=0, après=1168 | 136082 lignes → offset_0803DPS_2023_03_01-10_20_00_BB_RR.csv
✅ 0804GOR | avant=0, après=614 | 121957 lignes → offset_0804GOR_2023_01_11-09_53_11_BB_RR.csv
✅ 0805BMS | avant=0, après=1256 | 120815 lignes → offset_0805BMS_2023_01_18-09_11_15_BB_RR.csv
✅ 0806KHS | avant=0, après=828 | 112511 lignes → offset_0806KHS_2023_03_27-08_28_46_BB_RR.csv
✅ 0807OMR | avant=0, après=685 | 96386 lignes → offset_0807OMR_2023_05_15-09_39_03_BB_RR.csv
✅ 0901SMR | avant=0, après=1024 | 137154 lignes → offset_0901SMR_2022_12_14-10_53_43_BB_RR.csv
✅ 0903DJS | avant=0, après=881 | 135904 lignes → offset_0903DJS_2023_03_08-10_03_10_BB_RR.csv
✅ 0904KJS | avant=64, après=3918 | 132875 lignes → offset_0904KJS_2023_03_22-09_03_56_BB_RR.csv
✅ 0905SLR | avant=0, après=1114 | 125368 lignes → offset_0905SLR_2023_04_05-09_51_00_BB_RR.csv
🎯 Troncature terminée

In [35]:
# ===== Paramètres =====
min_lignes = 70000

dossier = Path.home() / "Desktop" / "bb_rr_tronqués_v4"

print(f"📂 Dossier analysé : {dossier}")

supprimes = []
conserves = []

for fichier in dossier.glob("*.csv"):

    nom = fichier.name

    # ===== Lecture rapide =====
    try:
        n_lignes = sum(1 for _ in open(fichier, "r", encoding="utf-8")) - 1
    except Exception as e:
        print(f"❌ Lecture impossible {nom}: {e}")
        continue

    # ===== Exclusion fichiers trop courts =====
    if n_lignes < min_lignes:
        fichier.unlink()
        supprimes.append((nom, f"{n_lignes} lignes"))
        print(f"🗑️ {nom} → trop petit ({n_lignes} lignes)")
    else:
        conserves.append((nom, n_lignes))
        print(f"✅ {nom} → conservé ({n_lignes} lignes)")

print("\n====== RÉSUMÉ ======")
print(f"Fichiers supprimés : {len(supprimes)}")
print(f"Fichiers conservés : {len(conserves)}")

📂 Dossier analysé : C:\Users\judupont\Desktop\bb_rr_tronqués_v4
✅ offset_0101CAR_2019_04_04-08_34_38_BB_RR.csv → conservé (171833 lignes)
✅ offset_0101EMS_2019_10_22-09_42_52_BB_RR.csv → conservé (140375 lignes)
✅ offset_0102EMS_2019_09_05-09_36_48_BB_RR.csv → conservé (87446 lignes)
✅ offset_0102PCR_2019_04_12-09_06_05_BB_RR.csv → conservé (132779 lignes)
✅ offset_0103BPS_2019_09_17-09_43_26_BB_RR.csv → conservé (124904 lignes)
✅ offset_0104FJS_2019_11_08-08_26_41_BB_RR.csv → conservé (110375 lignes)
✅ offset_0104IBS_2019_09_02-10_21_03_BB_RR.csv → conservé (123171 lignes)
✅ offset_0105PNR_2019_09_09-08_53_04_BB_RR.csv → conservé (127439 lignes)
✅ offset_0107DSS_2019_10_17-09_08_45_BB_RR.csv → conservé (108232 lignes)
✅ offset_0107LER_2019_09_04-10_10_04_BB_RR.csv → conservé (121010 lignes)
✅ offset_0108MMS_2019_10_24-09_06_30_BB_RR.csv → conservé (104475 lignes)
✅ offset_0109GSS_2019_11_14-09_36_14_BB_RR.csv → conservé (120964 lignes)
✅ offset_0109MJR_2019_09_13-09_33_09_BB_RR.csv → conservé (115565 lignes)
✅ offset_0110LPR_2019_11_21-09_04_12_BB_RR.csv → conservé (149803 lignes)
✅ offset_0110RMS_2019_09_16-09_30_11_BB_RR.csv → conservé (104815 lignes)
✅ offset_0111MNR_2019_11_22-09_17_01_BB_RR.csv → conservé (134678 lignes)
✅ offset_0111TAS_2019_10_03-09_26_21_BB_RR.csv → conservé (103564 lignes)
✅ offset_0112BSR_2020_03_05-09_38_29_BB_RR.csv → conservé (146804 lignes)
✅ offset_0112DRR_2019_11_06-09_35_42_BB_RR.csv → conservé (109618 lignes)
✅ offset_0113DGR_2019_08_27-09_41_17_BB_RR.csv → conservé (107571 lignes)
✅ offset_0114LMS_2020_09_04-09_43_24_BB_RR.csv → conservé (124303 lignes)
✅ offset_0114MLR_2019_10_15-10_35_01_BB_RR.csv → conservé (131779 lignes)
✅ offset_0115MHR_2019_10_09-09_23_28_BB_RR.csv → conservé (132368 lignes)
✅ offset_0116CNR_2019_10_04-09_24_16_BB_RR.csv → conservé (138517 lignes)
✅ offset_0116VAR_2020_06_04-08_27_42_BB_RR.csv → conservé (178939 lignes)
✅ offset_0117MSR_2019_10_11-09_25_30_BB_RR.csv → conservé (121090 lignes)
✅ offset_0118TMS_2019_10_16-07_56_19_BB_RR.csv → conservé (128243 lignes)
✅ offset_0119BIR_2019_10_28-09_48_54_BB_RR.csv → conservé (110375 lignes)
✅ offset_0119LJS_2020_10_08-09_18_00_BB_RR.csv → conservé (145725 lignes)
✅ offset_0120ANS_2019_11_19-09_44_13_BB_RR.csv → conservé (106922 lignes)
✅ offset_0121MJR_2020_09_10-09_21_07_BB_RR.csv → conservé (164886 lignes)
✅ offset_0121RPS_2019_10_23-09_34_13_BB_RR.csv → conservé (135850 lignes)
✅ offset_0122BDS_2020_09_25-09_20_42_BB_RR.csv → conservé (98904 lignes)
✅ offset_0122VCR_2019_11_05-09_18_30_BB_RR.csv → conservé (124832 lignes)
✅ offset_0123GVS_2019_11_08-09_23_05_BB_RR.csv → conservé (97421 lignes)
✅ offset_0123RMS_2020_09_24-09_19_20_BB_RR.csv → conservé (132511 lignes)
✅ offset_0124PAS_2019_11_15-09_27_24_BB_RR.csv → conservé (106725 lignes)
✅ offset_0126VLR_2019_12_02-09_03_50_BB_RR.csv → conservé (110546 lignes)
✅ offset_0127CMS_2019_11_21-09_34_50_BB_RR.csv → conservé (113311 lignes)
✅ offset_0128ALS_2019_12_11-09_33_30_BB_RR.csv → conservé (105547 lignes)
✅ offset_0129APR_2019_12_18-09_38_27_BB_RR.csv → conservé (173100 lignes)
✅ offset_0130FAR_2020_02_11-09_47_09_BB_RR.csv → conservé (138064 lignes)
✅ offset_0132GAR_2021_02_08-10_03_14_BB_RR.csv → conservé (114404 lignes)
✅ offset_0133BPS_2021_02_09-09_54_43_BB_RR.csv → conservé (121386 lignes)
✅ offset_0136CJR_2021_12_10-10_17_58_BB_RR.csv → conservé (110375 lignes)
✅ offset_0138NWR_2022_04_04-09_02_10_BB_RR.csv → conservé (123225 lignes)
✅ offset_0139BMR_2023_02_17-10_05_43_BB_RR.csv → conservé (115732 lignes)
✅ offset_0140LMR_2010_01_02-23_56_56_BB_RR.csv → conservé (161796 lignes)
✅ offset_0143EBR_2023_04_25-09_05_36_BB_RR.csv → conservé (142510 lignes)
✅ offset_0144ZGR_2023_04_11-09_08_49_BB_RR.csv → conservé (200368 lignes)
✅ offset_0302ZMR_2019_10_22-10_08_57_BB_RR.csv → conservé (100732 lignes)
✅ offset_0304VMR_2020_01_24-09_55_49_BB_RR.csv → conservé (120207 lignes)
✅ offset_0305LCR_2020_01_23-09_51_21_BB_RR (1).csv → conservé (107850 lignes)
✅ offset_0307SMR_2020_05_25-10_35_35_BB_RR.csv → conservé (134386 lignes)
✅ offset_0308RGR_2020_09_02__09_04_56_BR_RR (1).csv → conservé (91153 lignes)
✅ offset_0310ACS_2020_05_18-08_40_01_BB_RR (1).csv → conservé (138225 lignes)
✅ offset_0311CJS_2020_06_17__09_10_51_BR_RR.csv → conservé (143743 lignes)
✅ offset_0313FPR_2020_06_08-10_01_39_BB_RR.csv → conservé (95743 lignes)
✅ offset_0315VCS_2020_06_11-09_44_57_BB_RR.csv → conservé (97564 lignes)
✅ offset_0316TMS_2020_06_02-09_58_49_BB_RR.csv → conservé (120207 lignes)
✅ offset_0317LGS_2020_06_04-10_17_18_BB_RR.csv → conservé (112189 lignes)
✅ offset_0319LJS_2020_06_25__09_53_39_BR_RR.csv → conservé (87171 lignes)
✅ offset_0321DRR_2020_07_07__10_00_01_BR_RR.csv → conservé (94278 lignes)
✅ offset_0322RMS_2020_07_21__10_14_15_BR_RR.csv → conservé (84386 lignes)
✅ offset_0323RFS_2020_08_27__09_25_18_BR_RR.csv → conservé (96118 lignes)
✅ offset_0324LMR_2020_08_25__10_50_46_BR_RR.csv → conservé (90261 lignes)
✅ offset_0326BJR_2020_10_06__09_29_07_BR_RR.csv → conservé (108100 lignes)
✅ offset_0328MPR_2020_09_24__09_47_04_BR_RR.csv → conservé (109225 lignes)
✅ offset_0329NMR_2020_11_03__10_51_23_BR_RR.csv → conservé (117868 lignes)
✅ offset_0330RTR_2021_01_18__09_43_27_BR_RR.csv → conservé (131314 lignes)
✅ offset_0331GRS_2020_11_27__09_49_41_BR_RR.csv → conservé (117136 lignes)
✅ offset_0333MMS_2021_06_25__09_23_00_BR_RR.csv → conservé (97518 lignes)
✅ offset_0337BFS_2021_09_03__09_48_21_BR_RR.csv → conservé (122850 lignes)
✅ offset_0338JBS_2021_10_22__09_30_26_BR_RR (1).csv → conservé (112046 lignes)
✅ offset_0339NPR_2021_12_02__14_45_00_BR_RR.csv → conservé (98582 lignes)
✅ offset_0340BAR_2021_12_14__13_46_23_BR_RR.csv → conservé (81028 lignes)
✅ offset_0341LJS_2022_02_15__09_52_03_BR_RR.csv → conservé (104957 lignes)
✅ offset_0342VNS_2022_03_08__10_03_11_BR_RR.csv → conservé (82314 lignes)
✅ offset_0343PAS_2022_04_01__09_38_38_BR_RR.csv → conservé (102189 lignes)
✅ offset_0345LAR_2022_11_04__09_32_11_BR_RR.csv → conservé (108232 lignes)
✅ offset_0346GLS_2022_10_28__09_40_15_BR_RR.csv → conservé (110375 lignes)
✅ offset_0347DMR_2022_11_18__09_36_29_BR_RR.csv → conservé (112518 lignes)
✅ offset_0348GCR_2022_11_15__09_30_10_BR_RR.csv → conservé (132875 lignes)
✅ offset_0349LLS_2022_11_21__09_29_39_BR_RR.csv → conservé (85732 lignes)
✅ offset_0350MYR_2022_12_13__09_34_08_BR_RR.csv → conservé (114511 lignes)
✅ offset_0351FIR_2023_01_05__09_57_02_BR_RR.csv → conservé (103947 lignes)
✅ offset_0352RNR_2023_01_12__09_42_36_BR_RR.csv → conservé (103947 lignes)
✅ offset_0356DMS_2023_06_20__09_25_35_BR_RR.csv → conservé (121528 lignes)
✅ offset_0401BDS_2019_11_13__09_37_08_BR_RR.csv → conservé (139154 lignes)
✅ offset_0401TSS_2020_01_10-09_57_29_BB_RR.csv → conservé (172518 lignes)
✅ offset_0402LLS_2020_02_07-09_30_21_BB_RR.csv → conservé (141447 lignes)
✅ offset_0403DCR_2020_02_28-10_11_17_BB_RR.csv → conservé (123232 lignes)
✅ offset_0404CYS_2020_06_19-10_14_18_BB_RR.csv → conservé (122904 lignes)
✅ offset_0404DER_2019_11_08__09_47_26_BR_RR.csv → conservé (121690 lignes)
✅ offset_0405RCR_2020_02_14__10_06_12_BR_RR.csv → conservé (119796 lignes)
✅ offset_0406BBS_2019_12_18__11_01_15_BR_RR.csv → conservé (140375 lignes)
✅ offset_0407LJR_2020_07_02-09_52_07_BB_RR.csv → conservé (133947 lignes)
✅ offset_0408BCS_2020_08_06-10_25_47_BB_RR.csv → conservé (95600 lignes)
✅ offset_0408SJS_2019_11_27__10_38_19_BR_RR.csv → conservé (183957 lignes)
✅ offset_0409HCR_2020_01_06__10_24_59_BR_RR.csv → conservé (109315 lignes)
✅ offset_0410FMS_2019_11_18__10_30_15_BR_RR.csv → conservé (140100 lignes)
✅ offset_0411VES_2020_11_12-10_17_49_BB_RR.csv → conservé (109493 lignes)
✅ offset_0412ANS_2020_11_19-10_02_29_BB_RR.csv → conservé (128065 lignes)
✅ offset_0413HFS_2020_11_26-09_37_17_BB_RR.csv → conservé (156446 lignes)
✅ offset_0414PJS_2021_06_10-09_47_37_BB_RR.csv → conservé (131136 lignes)
✅ offset_0414PVR_2021_07_09__09_38_01_BR_RR.csv → conservé (137136 lignes)
✅ offset_0420MCR_2021_07_05__14_07_01_BR_RR.csv → conservé (148922 lignes)
✅ offset_0501MBS_2019_11_18-09_10_13_BB_RR - Copie.csv → conservé (122993 lignes)
✅ offset_0502LIR_2019_11_13-08_56_31_BB_RR.csv → conservé (121600 lignes)
✅ offset_0503LCR_2020_01_23-09_24_20_BB_RR.csv → conservé (104653 lignes)
✅ offset_0504BCS_2020_03_05-09_10_25_BB_RR.csv → conservé (114207 lignes)
✅ offset_0505PPR_2020_02_14-09_12_56_BB_RR.csv → conservé (122161 lignes)
✅ offset_0507BDS_2020_09_24-09_15_56_BB_RR.csv → conservé (122224 lignes)
✅ offset_0508SRR_2020_05_12-09_15_51_BB_RR.csv → conservé (116957 lignes)
✅ offset_0510DFS_2020_11_17-09_13_35_BB_RR.csv → conservé (121529 lignes)
✅ offset_0512RCR_Record 1_2022_02_15-14_05_19_BB_RR.csv → conservé (111446 lignes)
✅ offset_0513EBS_Record 1_2022_03_15-09_12_51_BB_RR - Copie.csv → conservé (114661 lignes)
✅ offset_0514LPS_Record 1_2023_02_07-09_15_05_BB_RR.csv → conservé (113493 lignes)
✅ offset_0515FAR_Record 1_2023_08_11-09_24_47_BB_RR.csv → conservé (134171 lignes)
✅ offset_0626MCS_2020_10_29-10_17_45_BB_RR.csv → conservé (129642 lignes)
✅ offset_0629TCR_2020_11_17-09_49_55_BB_RR.csv → conservé (146804 lignes)
✅ offset_0630RJR_2020_11_16-10_07_29_BB_RR.csv → conservé (107707 lignes)
✅ offset_0631LHR_2020_11_18-09_33_29_BB_RR.csv → conservé (100207 lignes)
✅ offset_0801HDR_2022_12_07-11_15_45_BB_RR.csv → conservé (108225 lignes)
✅ offset_0802LAS_2022_12_12-11_03_54_BB_RR.csv → conservé (120011 lignes)
✅ offset_0803DPS_2023_03_01-10_20_00_BB_RR.csv → conservé (136082 lignes)
✅ offset_0804GOR_2023_01_11-09_53_11_BB_RR.csv → conservé (121957 lignes)
✅ offset_0805BMS_2023_01_18-09_11_15_BB_RR.csv → conservé (120815 lignes)
✅ offset_0806KHS_2023_03_27-08_28_46_BB_RR.csv → conservé (112511 lignes)
✅ offset_0807OMR_2023_05_15-09_39_03_BB_RR.csv → conservé (96386 lignes)
✅ offset_0901SMR_2022_12_14-10_53_43_BB_RR.csv → conservé (137154 lignes)
✅ offset_0903DJS_2023_03_08-10_03_10_BB_RR.csv → conservé (135904 lignes)
✅ offset_0904KJS_2023_03_22-09_03_56_BB_RR.csv → conservé (132875 lignes)
✅ offset_0905SLR_2023_04_05-09_51_00_BB_RR.csv → conservé (125368 lignes)

====== RÉSUMÉ ======
Fichiers supprimés : 0
Fichiers conservés : 134

# On peut passer au découpage!

In [36]:
# Calcul de la durée de l'écriture pour shift le debut du bloc 2, 7 minutes pour les candidats ayant un NR dans l'une des deux colonnes de calcul 

# ===== PARAMÈTRE =====
DUREE_MOYENNE_ECRITURE_SEC = 7 * 60  # 7 minutes

col_debut = "heure_anamnese_fin_v4"
col_fin   = "heure_rlri16imm_debut_v4"

df = df_excel_global.copy()

# ===== Détection valeur non horaire =====
def est_non_horaire(val):
    if pd.isna(val):
        return True
    if isinstance(val, str):
        v = val.strip().upper()
        return v in {"NR", "N/R", "NON RENSEIGNE", ""}
    return False

# ===== Conversion robuste vers Timestamp =====
def convertir_heure(val):
    if est_non_horaire(val):
        return pd.NaT

    # Excel numérique (fraction de jour)
    if isinstance(val, (int, float)):
        seconds = (float(val) * 24 * 3600) % (24 * 3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # datetime / Timestamp
    if isinstance(val, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=val.hour, minute=val.minute, second=val.second
        )

    # texte
    try:
        t = pd.to_datetime(str(val).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

# ===== Conversion des colonnes =====
df["_ecriture_debut_ts"] = df[col_debut].apply(convertir_heure)
df["_ecriture_fin_ts"]   = df[col_fin].apply(convertir_heure)

# ===== Calcul durée =====
def calcul_duree(row):
    debut = row["_ecriture_debut_ts"]
    fin   = row["_ecriture_fin_ts"]

    if pd.notna(debut) and pd.notna(fin):
        delta = (fin - debut).total_seconds()

        # sécurité : durée négative ou absurde
        if 0 <= delta < 3600:
            return int(delta)

    # fallback → durée moyenne
    return DUREE_MOYENNE_ECRITURE_SEC

df["duree_ecriture_sec"] = df.apply(calcul_duree, axis=1)

# ===== Diagnostic =====
nb_moyenne = (df["duree_ecriture_sec"] == DUREE_MOYENNE_ECRITURE_SEC).sum()

print("===== DURÉE ÉCRITURE CALCULÉE =====")
print(f"Total candidats : {len(df)}")
print("Le seul caniddat avec une assigantion de temps par défaut est le 0410FMS")

# ===== Nettoyage colonnes temporaires =====
df = df.drop(columns=["_ecriture_debut_ts", "_ecriture_fin_ts"])

# ===== Mise à jour dataframe principal =====
df_excel_global["duree_ecriture_sec"] = df["duree_ecriture_sec"]

display(
    df_excel_global[[
        "Numero_inclusion",
        col_debut,
        col_fin,
        "duree_ecriture_sec"
    ]]
)

===== DURÉE ÉCRITURE CALCULÉE =====
Total candidats : 134
Durées réelles calculées : 123
Durées remplacées par la moyenne (7 min) : 11

,Numero_inclusion,heure_anamnese_fin_v4,heure_rlri16imm_debut_v4,duree_ecriture_sec
0,0101CAR,2026-03-10 08:54:00,09:07:00,780
1,0102PCR,2026-03-10 09:20:00,09:30:00,600
2,0105PNR,2026-03-10 09:08:00,09:22:00,840
3,0104FJS,2026-03-10 08:44:00,08:50:00,360
4,0107DSS,2026-03-10 09:33:00,09:45:00,720
5,0109GSS,2026-03-10 09:46:00,09:56:00,600
6,0110LPR,2026-03-10 09:19:00,09:36:00,1020
7,0111MNR,2026-03-10 09:37:00,09:47:00,600
8,0112BSR,2026-03-10 10:10:00,10:25:00,900
9,0114LMS,2026-03-10 10:12:00,10:21:00,540
10,0116VAR,2026-03-10 10:00:00,10:18:00,1080
11,0119LJS,2026-03-10 09:51:00,10:06:00,900
12,0121MJR,2026-03-10 09:44:00,10:00:00,960
13,0122BDS,2026-03-10 09:47:00,09:55:00,480
14,0123RMS,2026-03-10 09:45:00,09:55:00,600
15,0302ZMR,2026-03-10 10:20:00,10:30:00,600
16,0304VMR,2026-03-10 10:15:00,10:25:00,600
17,0305LCR,2026-03-10 10:01:00,10:10:00,540
18,0307SMR,2026-03-10 10:56:00,11:06:00,600
19,0308RGR,2026-03-10 09:17:00,09:25:00,480
20,0311CJS,2026-03-10 09:35:00,09:50:00,900
21,0310ACS,2026-03-10 09:55:00,10:05:00,600
22,0315VCS,2026-03-10 10:00:00,10:10:00,600
23,0313FPR,2026-03-10 10:10:00,10:16:00,360
24,0316TMS,2026-03-10 10:05:00,10:18:00,780
25,0317LGS,2026-03-10 10:37:00,10:43:00,360
26,0319LJS,2026-03-10 10:02:00,10:10:00,480
27,0321DRR,2026-03-10 10:12:00,10:14:00,120
28,0323RFS,2026-03-10 09:35:00,09:40:00,300
29,0322RMS,2026-03-10 10:22:00,10:30:00,480
30,0324LMR,2026-03-10 11:00:00,11:05:00,300
31,0326BJR,2026-03-10 09:50:00,10:00:00,600
32,0328MPR,2026-03-10 10:00:00,10:05:00,300
33,0330RTR,2026-03-10 09:58:00,10:05:00,420
34,0329NMR,2026-03-10 10:05:00,10:16:00,660
35,0331GRS,2026-03-10 10:01:00,10:07:00,360
36,0333MMS,2026-03-10 09:36:00,09:45:00,540
37,0337BFS,2026-03-10 10:04:00,10:12:00,480
38,0338JBS,2026-03-10 09:41:00,09:50:00,540
39,0339NPR,2026-03-10 13:58:00,14:05:00,420
40,0340BAR,2026-03-10 14:00:00,14:06:00,360
41,0341LJS,2026-03-10 10:00:00,10:17:00,1020
42,0342VNS,2026-03-10 10:15:00,10:21:00,360
43,0343PAS,2026-03-10 09:55:00,10:05:00,600
44,0345LAR,2026-03-10 09:47:00,09:53:00,360
45,0349LLS,2026-03-10 09:42:00,09:45:00,180
46,0347DMR,2026-03-10 09:53:00,10:00:00,420
47,0346GLS,2026-03-10 09:53:00,10:02:00,540
48,0348GCR,2026-03-10 09:52:00,10:02:00,600
49,0350MYR,2026-03-10 09:45:00,09:50:00,300
50,0351FIR,2026-03-10 10:10:00,10:20:00,600
51,0352RNR,2026-03-10 09:56:00,10:05:00,540
52,0356DMS,2026-03-10 09:42:00,09:47:00,300
53,0401TSS,2026-03-10 10:21:00,10:42:00,1260
54,0402LLS,2026-03-10 10:04:00,10:11:00,420
55,0403DCR,2026-03-10 10:26:00,10:37:00,660
56,0404CYS,2026-03-10 10:37:00,10:47:00,600
57,0407LJR,2026-03-10 10:11:00,10:25:00,840
58,0408BCS,2026-03-10 10:39:00,10:57:00,1080
59,0413HFS,2026-03-10 10:09:00,10:28:00,1140
60,0411VES,2026-03-10 10:33:00,10:42:00,540
61,0412ANS,2026-03-10 10:28:00,10:38:00,600
62,0414PJS,2026-03-10 10:05:00,10:29:00,1440
63,0501MBS,2026-03-10 09:20:00,09:40:00,1200
64,0502LIR,2026-03-10 09:10:00,09:24:00,840
65,0503LCR,2026-03-10 09:36:00,09:45:00,540
66,0504BCS,2026-03-10 09:24:00,09:37:00,780
67,0505PPR,2026-03-10 09:30:00,09:30:00,0
68,0508SRR,2026-03-10 09:31:00,09:43:00,720
69,0507BDS,2026-03-10 09:40:00,09:44:00,240
70,0510DFS,2026-03-10 09:25:00,09:36:00,660
71,0512RCR,2026-03-10 14:25:00,14:31:00,360
72,0513EBS,2026-03-10 09:35:00,09:45:00,600
73,0514LPS,2026-03-10 09:35:00,09:44:00,540
74,0515FAR,2026-03-10 09:30:00,09:54:00,1440
75,0626MCS,2026-03-10 09:38:00,09:52:00,840
76,0630RJR,2026-03-10 10:30:00,10:37:00,420
77,0629TCR,2026-03-10 10:14:00,10:29:00,900
78,0631LHR,2026-03-10 09:52:00,10:04:00,720
79,0101EMS,2026-03-10 10:19:00,10:31:00,720
80,0102EMS,2026-03-10 09:46:00,09:56:00,600
81,0103BPS,2026-03-10 10:13:00,10:26:00,780
82,0104IBS,2026-03-10 10:50:00,11:04:00,840
83,0107LER,2026-03-10 10:30:00,10:40:00,600
84,0108MMS,2026-03-10 09:16:00,09:28:00,720
85,0109MJR,2026-03-10 09:49:00,10:00:00,660
86,0110RMS,2026-03-10 09:41:00,09:54:00,780
87,0111TAS,2026-03-10 09:40:00,09:47:00,420
88,0112DRR,2026-03-10 09:45:00,09:58:00,780
89,0113DGR,2026-03-10 09:56:00,10:03:00,420
90,0114MLR,2026-03-10 11:03:00,11:12:00,540
91,0115MHR,2026-03-10 09:54:00,10:08:00,840
92,0116CNR,2026-03-10 09:42:00,09:55:00,780
93,0117MSR,2026-03-10 09:42:00,09:56:00,840
94,0118TMS,2026-03-10 08:21:00,08:34:00,780
95,0119BIR,2026-03-10 10:02:00,10:15:00,780
96,0120ANS,2026-03-10 09:57:00,10:11:00,840
97,0121RPS,2026-03-10 10:02:00,10:14:00,720
98,0122VCR,2026-03-10 09:34:00,09:49:00,900
99,0123GVS,2026-03-10 09:35:00,09:46:00,660
100,0124PAS,2026-03-10 09:43:00,09:56:00,780
101,0126VLR,2026-03-10 09:23:00,09:37:00,840
102,0127CMS,2026-03-10 09:48:00,10:01:00,780
103,0128ALS,2026-03-10 09:44:00,09:56:00,720
104,0129APR,2026-03-10 10:16:00,10:30:00,840
105,0130FAR,2026-03-10 10:15:00,10:29:00,840
106,0132GAR,2026-03-10 10:20:00,10:32:00,720
107,0133BPS,2026-03-10 10:18:00,10:31:00,780
108,0136CJR,2026-03-10 10:33:00,10:40:00,420
109,0138NWR,2026-03-10 10:15:00,10:27:00,720
110,0139BMR,2026-03-10 10:19:00,10:26:00,420
111,0140LMR,2026-03-10 10:28:00,10:42:00,840
112,0143EBR,2026-03-10 10:32:00,10:37:00,300
113,0144ZGR,2026-03-10 10:41:00,11:08:00,1620
114,0801HDR,2026-03-10 10:30:00,10:36:00,360
115,0802LAS,2026-03-10 10:25:00,10:33:00,480
116,0804GOR,2026-03-10 10:16:00,10:23:00,420
117,0803DPS,2026-03-10 10:35:00,10:47:00,720
118,0805BMS,2026-03-10 09:29:00,09:41:00,720
119,0806KHS,2026-03-10 09:46:00,09:52:00,360
120,0807OMR,2026-03-10 09:48:00,09:53:00,300
121,0901SMR,2026-03-10 10:19:00,10:31:00,720
122,0903DJS,2026-03-10 10:26:00,10:39:00,780
123,0904KJS,2026-03-10 09:34:00,09:45:00,660
124,0905SLR,2026-03-10 10:12:00,10:22:00,600
125,0401BDS,2026-03-10 09:58:00,10:12:00,840
126,0404DER,2026-03-10 09:57:00,10:12:00,900
127,0405RCR,2026-03-10 10:20:00,10:36:00,960
128,0406BBS,2026-03-10 11:22:00,11:43:00,1260
129,0408SJS,2026-03-10 11:23:00,11:42:00,1140
130,0409HCR,2026-03-10 10:31:00,10:42:00,660
131,0410FMS,2026-03-10 10:47:00,10:03:00,420
132,0414PVR,2026-03-10 09:52:00,10:04:00,720
133,0420MCR,2026-03-10 14:31:00,14:45:00,840

In [38]:
def decouper_bb_rr_par_bloc(
    df_rr,
    duree_ecriture,
    duree_bloc1,
    duree_bloc2,
    duree_bloc3,
    delta
):
    df_rr = df_rr.copy()

    # ===== Timestamp propre =====
    df_rr["Timestamp"] = pd.to_datetime(
        df_rr["Timestamp"], dayfirst=True, errors="coerce"
    )
    df_rr = df_rr.dropna(subset=["Timestamp"])

    if df_rr.empty:
        return None

    # ===== Temps de référence =====
    t0 = df_rr["Timestamp"].min()
    t_fin_rr = df_rr["Timestamp"].max()

    # ===== Bornes temporelles =====
    fin_bloc1 = t0 + pd.Timedelta(seconds=max(0, duree_bloc1 - delta))
    debut_bloc2 = fin_bloc1 + pd.Timedelta(seconds=duree_ecriture)
    fin_bloc2 = debut_bloc2 + pd.Timedelta(seconds=duree_bloc2)
    fin_bloc3 = fin_bloc2 + pd.Timedelta(seconds=duree_bloc3)

    # Sécurité (ne jamais dépasser le fichier)
    fin_bloc3 = min(fin_bloc3, t_fin_rr)

    

    return {
        "bloc1": df_rr[
            (df_rr["Timestamp"] >= t0) &
            (df_rr["Timestamp"] < fin_bloc1)
        ],
        "bloc2": df_rr[
            (df_rr["Timestamp"] >= debut_bloc2) &
            (df_rr["Timestamp"] < fin_bloc2)
        ],
        "bloc3": df_rr[
            (df_rr["Timestamp"] >= fin_bloc2) &
            (df_rr["Timestamp"] < fin_bloc3)
        ],
        "bornes": {
            "t0": t0,
            "fin_bloc1": fin_bloc1,
            "debut_bloc2": debut_bloc2,
            "fin_bloc2": fin_bloc2,
            "fin_bloc3": fin_bloc3,
            "t_fin_rr": t_fin_rr
        }
    }

In [39]:
def convertir_et_normaliser_heure(x):
    """
    Convertit n'importe quel format d'heure Excel / texte / datetime en pd.Timestamp
    normalisé sur le 1900-01-01, ne gardant que l'heure, minute, seconde.
    """
    if pd.isna(x):
        return pd.NaT

    # Excel numérique → fraction de jour ou date complète
    if isinstance(x, (int, float)):
        seconds = (float(x) * 24 * 3600) % (24*3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # Timestamp ou datetime → on garde juste l'heure
    if isinstance(x, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=x.hour, minute=x.minute, second=x.second
        )

    # Texte
    try:
        t = pd.to_datetime(str(x).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

In [40]:
def get_durees_blocs(pid, feuille):
    """
    Récupère les durées pour les 3 blocs et la durée d'écriture à partir de df_excel_global
    pour un PID donné et une feuille donnée.
    
    La durée d'écriture sert à décaler le début du bloc 2.
    Si la durée n'est pas renseignée ou NR, on met 7 minutes (420 s) par défaut.
    """
    pid = str(pid).upper()
    
    # ===== Bloc 1 =====
    df_b1 = pd.DataFrame(resultats_bloc1[feuille]["df"])
    ligne = df_b1.loc[df_b1["Numero_inclusion"].str.upper() == pid]
    if ligne.empty:
        raise ValueError(f"PID {pid} absent du bloc 1 dans la feuille {feuille}")
    d1 = ligne["duree_bloc1"].values[0]

    # ===== Durée écriture =====
    # On part de df_excel_global
    ligne_excel = df_excel_global.loc[df_excel_global["Numero_inclusion"].str.upper() == pid]
    if ligne_excel.empty:
        val_ecriture = 420  # défaut si absent
    else:
        val_ecriture = ligne_excel["duree_ecriture_sec"].values[0]
        if pd.isna(val_ecriture) or val_ecriture < 0:
            val_ecriture = 420  # défaut pour NR ou vide

    # ===== Bloc 2 =====
    df_b2 = pd.DataFrame(resultats_bloc2[feuille]["df"])
    d2 = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, "duree_bloc2"].values[0]

    # ===== Bloc 3 =====
    df_b3 = pd.DataFrame(resultats_bloc3[feuille]["df"])
    d3 = df_b3.loc[df_b3["Numero_inclusion"].str.upper() == pid, "duree_bloc3"].values[0]

    return {
        "bloc1_sec": d1 * 60,
        "duree_ecriture_sec": val_ecriture,  # durée spécifique du candidat
        "bloc2_sec": d2 * 60,
        "bloc3_sec": d3 * 60,
    }

In [41]:
# ===== Dossiers =====
input_dir = os.path.join(os.path.expanduser("~"), "Desktop", "bb_rr_tronqués_v4")
output_dir = os.path.join(os.path.expanduser("~"), "Desktop", "bb_rr_tronque_blocs_v4")
os.makedirs(output_dir, exist_ok=True)

resultats_decoupage = {}

# ===== Boucle UNIQUEMENT sur les fichiers tronqués =====
for fichier in os.listdir(input_dir):

    if not fichier.lower().endswith(".csv"):
        continue

    chemin_bb_rr = os.path.join(input_dir, fichier)

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", fichier.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {fichier}")
        continue

    pid = match.group()

    # ===== Récupération de la feuille associée =====
    ligne = df_global.loc[df_global["Numero_inclusion"] == pid]
    if ligne.empty:
        print(f"⚠️ Feuille introuvable pour {pid}")
        continue

    feuille = ligne["Feuille"].values[0]

    print(f"\n--- Découpage {pid} ({feuille}) ---")

    # ===== Lecture BB_RR =====
    try:
        df_rr = pd.read_csv(chemin_bb_rr)
    except Exception as e:
        print(f"❌ Lecture impossible {pid} : {e}")
        continue

    # ===== Récupération des durées =====
    try:
        durees = get_durees_blocs(pid, feuille)
    except Exception as e:
        print(f"⚠️ Impossible de récupérer les durées pour {pid} ({feuille}) : {e}")
        continue

    delta_row = df_offset_bb_rr.loc[df_offset_bb_rr["Numero_inclusion"].str.upper() == pid.upper()]
    if delta_row.empty:
        delta_val = 0
    else:
        delta_val = float(delta_row["delta_retard_sec"].values[0])

    # ===== Découpage =====
    decoupe = decouper_bb_rr_par_bloc(
        df_rr=df_rr,
        duree_ecriture=durees["duree_ecriture_sec"],
        duree_bloc1=durees["bloc1_sec"],
        duree_bloc2=durees["bloc2_sec"],
        duree_bloc3=durees["bloc3_sec"],
        delta = delta_val
    )

    if decoupe is None:
        print(f"⚠️ Découpage vide pour {pid}")
        continue

    # ===== Sauvegarde par bloc =====
    for bloc in ["bloc1", "bloc2", "bloc3"]:
        df_bloc = decoupe[bloc]

        if df_bloc.empty:
            print(f"⚠️ {pid} {bloc} vide")
            continue

        nom_sortie = f"{pid}_{bloc}.csv"
        df_bloc.to_csv(
            os.path.join(output_dir, nom_sortie),
            index=False
        )

    # ===== Stockage mémoire =====
    resultats_decoupage[pid] = decoupe

    print(
        f"✔ {pid} | "
        f"B1={len(decoupe['bloc1'])} | "
        f"B2={len(decoupe['bloc2'])} | "
        f"B3={len(decoupe['bloc3'])}"
    )

print("\n✅ Découpage terminé")
print("📁 Résultats dans :", output_dir)

--- Découpage 0101CAR (APHM) ---
✔ 0101CAR | B1=20750 | B2=76071 | B3=61072

--- Découpage 0101EMS (LPC) ---
✔ 0101EMS | B1=38572 | B2=40714 | B3=48215

--- Découpage 0102EMS (LPC) ---
✔ 0102EMS | B1=9858 | B2=26786 | B3=40087

--- Découpage 0102PCR (APHM) ---
✔ 0102PCR | B1=14911 | B2=63215 | B3=43928

--- Découpage 0103BPS (LPC) ---
✔ 0103BPS | B1=31679 | B2=37500 | B3=41785

--- Découpage 0104FJS (APHM) ---
✔ 0104FJS | B1=18215 | B2=42857 | B3=42858

--- Découpage 0104IBS (LPC) ---
✔ 0104IBS | B1=31018 | B2=34286 | B3=42857

--- Découpage 0105PNR (APHM) ---
✔ 0105PNR | B1=16000 | B2=46072 | B3=50357

--- Découpage 0107DSS (APHM) ---
✔ 0107DSS | B1=25715 | B2=40714 | B3=28929

--- Découpage 0107LER (LPC) ---
✔ 0107LER | B1=21358 | B2=42857 | B3=46071

--- Découpage 0108MMS (LPC) ---
✔ 0108MMS | B1=10179 | B2=34286 | B3=47143

--- Découpage 0109GSS (APHM) ---
✔ 0109GSS | B1=10465 | B2=42857 | B3=56927

--- Découpage 0109MJR (LPC) ---
✔ 0109MJR | B1=16983 | B2=39643 | B3=47143

--- Découpage 0110LPR (APHM) ---
✔ 0110LPR | B1=15858 | B2=54643 | B3=61087

--- Découpage 0110RMS (LPC) ---
✔ 0110RMS | B1=11590 | B2=34286 | B3=45000

--- Découpage 0111MNR (APHM) ---
✔ 0111MNR | B1=21411 | B2=45000 | B3=57552

--- Découpage 0111TAS (LPC) ---
✔ 0111TAS | B1=14625 | B2=36429 | B3=45000

--- Découpage 0112BSR (APHM) ---
✔ 0112BSR | B1=33215 | B2=37500 | B3=60000

--- Découpage 0112DRR (LPC) ---
✔ 0112DRR | B1=9965 | B2=35357 | B3=50358

--- Découpage 0113DGR (LPC) ---
✔ 0113DGR | B1=15768 | B2=40715 | B3=43587

--- Découpage 0114LMS (APHM) ---
✔ 0114LMS | B1=30000 | B2=53572 | B3=31071

--- Découpage 0114MLR (LPC) ---
✔ 0114MLR | B1=29983 | B2=39643 | B3=52500

--- Découpage 0115MHR (LPC) ---
✔ 0115MHR | B1=32715 | B2=32143 | B3=52500

--- Découpage 0116CNR (LPC) ---
✔ 0116CNR | B1=19000 | B2=45000 | B3=60587

--- Découpage 0116VAR (APHM) ---
✔ 0116VAR | B1=35358 | B2=55715 | B3=68571

--- Découpage 0117MSR (LPC) ---
✔ 0117MSR | B1=17143 | B2=38572 | B3=50357

--- Découpage 0118TMS (LPC) ---
✔ 0118TMS | B1=26447 | B2=38572 | B3=49286

--- Découpage 0119BIR (LPC) ---
✔ 0119BIR | B1=13929 | B2=35357 | B3=47143

--- Découpage 0119LJS (APHM) ---
✔ 0119LJS | B1=35358 | B2=43929 | B3=50357

--- Découpage 0120ANS (LPC) ---
✔ 0120ANS | B1=13697 | B2=31071 | B3=47143

--- Découpage 0121MJR (APHM) ---
✔ 0121MJR | B1=24518 | B2=51429 | B3=71785

--- Découpage 0121RPS (LPC) ---
✔ 0121RPS | B1=29768 | B2=41786 | B3=51429

--- Découpage 0122BDS (APHM) ---
✔ 0122BDS | B1=28179 | B2=39643 | B3=22500

--- Découpage 0122VCR (LPC) ---
✔ 0122VCR | B1=16608 | B2=40714 | B3=51429

--- Découpage 0123GVS (LPC) ---
✔ 0123GVS | B1=12768 | B2=30000 | B3=42857

--- Découpage 0123RMS (APHM) ---
✔ 0123RMS | B1=27500 | B2=57857 | B3=36428

--- Découpage 0124PAS (LPC) ---
✔ 0124PAS | B1=16715 | B2=36429 | B3=39643

--- Découpage 0126VLR (LPC) ---
✔ 0126VLR | B1=20536 | B2=32143 | B3=42857

--- Découpage 0127CMS (LPC) ---
✔ 0127CMS | B1=13929 | B2=39642 | B3=45810

--- Découpage 0128ALS (LPC) ---
✔ 0128ALS | B1=11250 | B2=33214 | B3=48214

--- Découpage 0129APR (LPC) ---
✔ 0129APR | B1=40233 | B2=50357 | B3=67500

--- Découpage 0130FAR (LPC) ---
✔ 0130FAR | B1=29840 | B2=46071 | B3=47143

--- Découpage 0132GAR (LPC) ---
✔ 0132GAR | B1=17965 | B2=37500 | B3=46071

--- Découpage 0133BPS (LPC) ---
✔ 0133BPS | B1=24947 | B2=36429 | B3=46071

--- Découpage 0136CJR (LPC) ---
✔ 0136CJR | B1=16072 | B2=41786 | B3=45000

--- Découpage 0138NWR (LPC) ---
✔ 0138NWR | B1=13929 | B2=47143 | B3=49286

--- Découpage 0139BMR (LPC) ---
✔ 0139BMR | B1=13929 | B2=42857 | B3=51429

--- Découpage 0140LMR (LPC) ---
✔ 0140LMR | B1=24643 | B2=54643 | B3=67500

--- Découpage 0143EBR (LPC) ---
✔ 0143EBR | B1=26786 | B2=51429 | B3=58928

--- Découpage 0144ZGR (LPC) ---
✔ 0144ZGR | B1=33215 | B2=73929 | B3=64286

--- Découpage 0302ZMR (CAEN) ---
✔ 0302ZMR | B1=11786 | B2=39643 | B3=38572

--- Découpage 0304VMR (CAEN) ---
✔ 0304VMR | B1=20554 | B2=49286 | B3=39643

--- Découpage 0305LCR (CAEN) ---
✔ 0305LCR | B1=10340 | B2=48214 | B3=39643

--- Découpage 0307SMR (CAEN) ---
✔ 0307SMR | B1=21875 | B2=58928 | B3=42857

--- Découpage 0308RGR (CAEN) ---
✔ 0308RGR | B1=12928 | B2=42857 | B3=26785

--- Découpage 0310ACS (CAEN) ---
✔ 0310ACS | B1=18215 | B2=62143 | B3=47143

--- Découpage 0311CJS (CAEN) ---
✔ 0311CJS | B1=25875 | B2=50357 | B3=51429

--- Découpage 0313FPR (CAEN) ---
✔ 0313FPR | B1=8947 | B2=43929 | B3=36429

--- Découpage 0315VCS (CAEN) ---
✔ 0315VCS | B1=16125 | B2=45000 | B3=25714

--- Découpage 0316TMS (CAEN) ---
✔ 0316TMS | B1=6625 | B2=53571 | B3=46072

--- Découpage 0317LGS (CAEN) ---
✔ 0317LGS | B1=21108 | B2=47143 | B3=37500

--- Découpage 0319LJS (CAEN) ---
✔ 0319LJS | B1=8946 | B2=45000 | B3=24643

--- Découpage 0321DRR (CAEN) ---
✔ 0321DRR | B1=12839 | B2=42857 | B3=36428

--- Découpage 0322RMS (CAEN) ---
✔ 0322RMS | B1=8303 | B2=34285 | B3=33215

--- Découpage 0323RFS (CAEN) ---
✔ 0323RFS | B1=10392 | B2=51428 | B3=28929

--- Découpage 0324LMR (CAEN) ---
✔ 0324LMR | B1=9892 | B2=48214 | B3=26786

--- Découpage 0326BJR (CAEN) ---
✔ 0326BJR | B1=22375 | B2=50357 | B3=24643

--- Découpage 0328MPR (CAEN) ---
✔ 0328MPR | B1=13857 | B2=46071 | B3=43929

--- Découpage 0329NMR (CAEN) ---
✔ 0329NMR | B1=16071 | B2=50357 | B3=39643

--- Découpage 0330RTR (CAEN) ---
✔ 0330RTR | B1=15589 | B2=60000 | B3=48214

--- Découpage 0331GRS (CAEN) ---
✔ 0331GRS | B1=12125 | B2=56786 | B3=41786

--- Découpage 0333MMS (CAEN) ---
✔ 0333MMS | B1=12857 | B2=56786 | B3=18214

--- Découpage 0337BFS (CAEN) ---
✔ 0337BFS | B1=16767 | B2=54643 | B3=42857

--- Découpage 0338JBS (CAEN) ---
✔ 0338JBS | B1=11321 | B2=50357 | B3=40714

--- Découpage 0339NPR (CAEN) ---
✔ 0339NPR | B1=13928 | B2=40714 | B3=36429

--- Découpage 0340BAR (CAEN) ---
✔ 0340BAR | B1=14589 | B2=40715 | B3=19285

--- Découpage 0341LJS (CAEN) ---
✔ 0341LJS | B1=8517 | B2=39643 | B3=38571

--- Découpage 0342VNS (CAEN) ---
✔ 0342VNS | B1=12660 | B2=40714 | B3=22500

--- Découpage 0343PAS (CAEN) ---
✔ 0343PAS | B1=17535 | B2=36428 | B3=37500

--- Découpage 0345LAR (CAEN) ---
✔ 0345LAR | B1=15000 | B2=61072 | B3=25714

--- Découpage 0346GLS (CAEN) ---
✔ 0346GLS | B1=11785 | B2=49286 | B3=39643

--- Découpage 0347DMR (CAEN) ---
✔ 0347DMR | B1=16071 | B2=42857 | B3=46072

--- Découpage 0348GCR (CAEN) ---
✔ 0348GCR | B1=22500 | B2=62143 | B3=37500

--- Découpage 0349LLS (CAEN) ---
✔ 0349LLS | B1=12857 | B2=43929 | B3=25714

--- Découpage 0350MYR (CAEN) ---
✔ 0350MYR | B1=11642 | B2=51428 | B3=46072

--- Découpage 0351FIR (CAEN) ---
✔ 0351FIR | B1=12858 | B2=39643 | B3=40714

--- Découpage 0352RNR (CAEN) ---
✔ 0352RNR | B1=13929 | B2=42857 | B3=37500

--- Découpage 0356DMS (CAEN) ---
✔ 0356DMS | B1=17589 | B2=50357 | B3=48214

--- Découpage 0401BDS (CERCA) ---
✔ 0401BDS | B1=22358 | B2=52500 | B3=49285

--- Découpage 0401TSS (POITIERS) ---
✔ 0401TSS | B1=22500 | B2=56786 | B3=70714

--- Découpage 0402LLS (POITIERS) ---
✔ 0402LLS | B1=33215 | B2=49285 | B3=51429

--- Découpage 0403DCR (POITIERS) ---
✔ 0403DCR | B1=12858 | B2=43929 | B3=54643

--- Découpage 0404CYS (POITIERS) ---
✔ 0404CYS | B1=24322 | B2=58929 | B3=28928

--- Découpage 0404DER (CERCA) ---
✔ 0404DER | B1=10250 | B2=53571 | B3=41786

--- Découpage 0405RCR (CERCA) ---
✔ 0405RCR | B1=14786 | B2=47143 | B3=40714

--- Découpage 0406BBS (CERCA) ---
✔ 0406BBS | B1=21429 | B2=45000 | B3=51429

--- Découpage 0407LJR (POITIERS) ---
✔ 0407LJR | B1=19286 | B2=47143 | B3=52500

--- Découpage 0408BCS (POITIERS) ---
✔ 0408BCS | B1=14161 | B2=43928 | B3=18215

--- Découpage 0408SJS (CERCA) ---
✔ 0408SJS | B1=47875 | B2=57857 | B3=57857

--- Découpage 0409HCR (CERCA) ---
✔ 0409HCR | B1=6447 | B2=40714 | B3=50357

--- Découpage 0410FMS (CERCA) ---
✔ 0410FMS | B1=17947 | B2=113571 | B3=1081

--- Découpage 0411VES (POITIERS) ---
✔ 0411VES | B1=16268 | B2=31072 | B3=52500

--- Découpage 0412ANS (POITIERS) ---
✔ 0412ANS | B1=27340 | B2=42857 | B3=47143

--- Découpage 0413HFS (POITIERS) ---
✔ 0413HFS | B1=33215 | B2=51428 | B3=51429

--- Découpage 0414PJS (POITIERS) ---
✔ 0414PJS | B1=18625 | B2=56785 | B3=30000

--- Découpage 0414PVR (CERCA) ---
✔ 0414PVR | B1=14983 | B2=54643 | B3=54642

--- Découpage 0420MCR (CERCA) ---
✔ 0420MCR | B1=25697 | B2=46071 | B3=62143

--- Découpage 0501MBS (ROUEN) ---
✔ 0501MBS | B1=10483 | B2=48214 | B3=42858

--- Découpage 0502LIR (ROUEN) ---
✔ 0502LIR | B1=14447 | B2=42857 | B3=49286

--- Découpage 0503LCR (ROUEN) ---
✔ 0503LCR | B1=12500 | B2=39643 | B3=42857

--- Découpage 0504BCS (ROUEN) ---
✔ 0504BCS | B1=14554 | B2=37500 | B3=48214

--- Découpage 0505PPR (ROUEN) ---
✔ 0505PPR | B1=15000 | B2=56786 | B3=50357

--- Découpage 0507BDS (ROUEN) ---
✔ 0507BDS | B1=25786 | B2=40714 | B3=51429

--- Découpage 0508SRR (ROUEN) ---
✔ 0508SRR | B1=16233 | B2=41785 | B3=46072

--- Découpage 0510DFS (ROUEN) ---
✔ 0510DFS | B1=12233 | B2=48215 | B3=49285

--- Découpage 0512RCR (ROUEN) ---
✔ 0512RCR | B1=15000 | B2=42857 | B3=47143

--- Découpage 0513EBS (ROUEN) ---
✔ 0513EBS | B1=20358 | B2=41786 | B3=41785

--- Découpage 0514LPS (ROUEN) ---
✔ 0514LPS | B1=21340 | B2=35357 | B3=47143

--- Découpage 0515FAR (ROUEN) ---
✔ 0515FAR | B1=5590 | B2=43929 | B3=58928

--- Découpage 0626MCS (LAVERAN) ---
✔ 0626MCS | B1=22500 | B2=42858 | B3=49283

--- Découpage 0629TCR (LAVERAN) ---
✔ 0629TCR | B1=25715 | B2=62143 | B3=42857

--- Découpage 0630RJR (LAVERAN) ---
✔ 0630RJR | B1=24125 | B2=37500 | B3=38572

--- Découpage 0631LHR (LAVERAN) ---
✔ 0631LHR | B1=19840 | B2=28928 | B3=38572

--- Découpage 0801HDR (SAINTE-MARGUERITE) ---
✔ 0801HDR | B1=13929 | B2=47142 | B3=40715

--- Découpage 0802LAS (SAINTE-MARGUERITE) ---
✔ 0802LAS | B1=21429 | B2=49286 | B3=40714

--- Découpage 0803DPS (SAINTE-MARGUERITE) ---
✔ 0803DPS | B1=16072 | B2=56786 | B3=50357

--- Découpage 0804GOR (SAINTE-MARGUERITE) ---
✔ 0804GOR | B1=24447 | B2=40714 | B3=49286

--- Découpage 0805BMS (SAINTE-MARGUERITE) ---
✔ 0805BMS | B1=19018 | B2=42858 | B3=46071

--- Découpage 0806KHS (SAINTE-MARGUERITE) ---
✔ 0806KHS | B1=19286 | B2=38571 | B3=48214

--- Découpage 0807OMR (SAINTE-MARGUERITE) ---
✔ 0807OMR | B1=9590 | B2=39643 | B3=41785

--- Découpage 0901SMR (CGD) ---
✔ 0901SMR | B1=25715 | B2=46071 | B3=52500

--- Découpage 0903DJS (CGD) ---
✔ 0903DJS | B1=24465 | B2=49286 | B3=48214

--- Découpage 0904KJS (CGD) ---
✔ 0904KJS | B1=32143 | B2=43929 | B3=45000

--- Découpage 0905SLR (CGD) ---
✔ 0905SLR | B1=22500 | B2=46071 | B3=46072

✅ Découpage terminé
📁 Résultats dans : C:\Users\judupont\Desktop\bb_rr_tronque_blocs_v4

# DATA FRAME DIRECT 
lignes_globales = []

for pid, decoupe in resultats_decoupage.items():

    # ===== Condition =====
    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    # ===== Offset =====
    offset_sec = abs(
        df_controle_durees.loc[
            df_controle_durees["Numero_inclusion"] == pid,
            "ecart_sec"
        ].values[0]
    )

    bornes = decoupe["bornes"]

    for nom_bloc in ["bloc1", "bloc2", "bloc3"]:

        df_bloc = decoupe[nom_bloc]

        if df_bloc.empty:
            continue

        # =====================================================
        # CAS 1 : RR fourni par l'appareil (RtoR)
        # =====================================================
        if "RtoR" in df_bloc.columns:

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row["Timestamp"],
                    "RtoR": row["RtoR"],      
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 2 : RR calculé (temps_ms / rr_ms)
        # =====================================================
        elif {"temps_ms", "rr_ms"}.issubset(df_bloc.columns):

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row.get("Timestamp", pd.NaT),
                    "RtoR": row["rr_ms"] / 1000,  # ms → sec
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 3 : Timestamp seul
        # =====================================================
        else:
            for ts in df_bloc["Timestamp"]:
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": ts,
                    "RtoR": None,
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

df_rr_global = pd.DataFrame(lignes_globales)

# DATA FRAME IMBRIQUE
lignes_patients = []

for pid, decoupe in resultats_decoupage.items():

    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    lignes_patients.append({
        "Numero_inclusion": pid,
        "Condition": condition,
        "baseline": decoupe["bloc1"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc2": decoupe["bloc2"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc3": decoupe["bloc3"][["Timestamp", "RtoR"]].reset_index(drop=True),
    })

df_patients = pd.DataFrame(lignes_patients)

In [ ]:
## Traitment pour passer le fichier dans kubios