# Bibliotheque + lecture Excel

In [1]:
import pandas as pd 
import numpy as np 
import os
import re
import pandas as pd
from collections import defaultdict
import zipfile
from datetime import datetime, timedelta
from pathlib import Path
import datetime

In [2]:
df = pd.read_excel('AGING_Ceinture_Montre (avec groupe).xlsx',sheet_name=None)

C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\judupont\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
df.keys()

dict_keys(['APHM', 'CAEN', 'POITIERS', 'ROUEN', 'LAVERAN', 'LPC', 'SAINTE-MARGUERITE', 'CGD', 'CERCA', 'Effectifs ceinture', 'Effectifs montre', 'CODEBOOK '])

# Vérification blocs

In [4]:
def convertir_heure_excel_ou_texte(x):
    """
    Convertit une valeur Excel ou texte en datetime, en ne gardant que l'heure.
    """
    if pd.isna(x):
        return pd.NaT

    # Cas nombre Excel (jours depuis 1899-12-30)
    if isinstance(x, (int, float)):
        ts = pd.to_datetime(x, unit="D", origin="1899-12-30")
        return ts.replace(year=1900, month=1, day=1)  # ignore la vraie date

    x_str = str(x).strip()

    # Cas hh:mm ou hh:mm:ss
    for fmt in ("%H:%M:%S", "%H:%M"):
        try:
            ts = pd.to_datetime(x_str, format=fmt)
            return ts.replace(year=1900, month=1, day=1)  # force date fixe
        except Exception:
            continue

    # Cas général (Excel parfois avec date complète)
    try:
        ts = pd.to_datetime(x_str, errors="coerce")
        if pd.isna(ts):
            return pd.NaT
        return ts.replace(year=1900, month=1, day=1)  # ignore la date réelle
    except Exception:
        return pd.NaT

In [7]:
def analyser_feuille_bloc(
    df,
    nom_feuille,
    col_debut,
    col_fin,
    nom_bloc
):
    print(f"\n--- Feuille : {nom_feuille} | {nom_bloc} ---")

    col_id = "Numero_inclusion"

    # ===============================
    # 🔧 DEBUG : normalisation ID
    # ===============================
    df = df.copy()
    df[col_id] = df[col_id].astype(str).str.upper().str.strip()

    # ==================================================
    # Dictionnaire des colonnes atitrées manuellement 
    # ==================================================
    REGLES_CANDIDATS = {
        ("CAEN", "bloc3", "0303PAR"): {"col_debut": "heure_rappel_cond_v2"},

        ("CAEN", "bloc3", "0305LCR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2S", "0314CDS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0314CDS"): {"col_debut": "heure_fluence_sem_v2"},
        
        ("CAEN", "bloc2S", "0335JMS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0335JMS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc3", "0339NPR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2S", "0346GLS"): { "col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0346GLS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CAEN", "bloc2R", "0353LNR"): { "col_fin": "heure_fluence_sem_v2"},
        ("CAEN", "bloc3", "0353LNR"): {"col_debut": "heure_fluence_sem_v2"},

        ("POITIERS", "bloc2S", "0414PJS"): {"col_fin": "heure_fluence_sem_v2"},
        ("POITIERS", "bloc3", "0414PJS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CGD", "bloc2S", "0902SIS"): {"col_fin": "heure_fluence_sem_v2"},
        ("CGD", "bloc3", "0902SIS"): {"col_debut": "heure_fluence_sem_v2"},

        ("CGD", "bloc3", "0905SLR"): {"col_debut": "heure_nback_v2"},

        ("CGD", "bloc3", "0906DNR"): {"col_debut": "heure_fluence_sem_v2"},

        ("CERCA", "bloc3", "0414PVR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0419SRR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0420MCR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc2S", "0421ACS"): {"col_fin": "heure_nback_v2"},
        ("CERCA", "bloc3", "0421ACS"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0423RMR"): {"col_debut": "heure_nback_v2"},

        ("CERCA", "bloc3", "0424BLR"): {"col_debut": "heure_nback_v2"},
    }

    # ==========================================================
    # Colonnes effecives
    # ==========================================================
    df["_col_debut"] = col_debut
    df["_col_fin"] = col_fin

    # ==========================================================
    # RÈGLES GLOBALES
    # ==========================================================
    if nom_feuille == "SAINTE-MARGUERITE" and nom_bloc == "bloc2S":
        df["_col_fin"] = "heure_nback_v2"

    if nom_feuille == "SAINTE-MARGUERITE" and nom_bloc == "bloc3":
        df["_col_debut"] = "heure_nback_v2"

    # ==========================================================
    # RÈGLES SPÉCIFIQUES (écrasent le global)
    # ==========================================================
    print("\n🔎 Vérification règles spécifiques :")

    for (centre, bloc, candidat), regle in REGLES_CANDIDATS.items():

        if centre != nom_feuille or bloc != nom_bloc:
            continue

        mask = df[col_id] == candidat

        if mask.any():
            print(f"🔧 Règle appliquée pour {candidat}")
            if "col_debut" in regle:
                df.loc[mask, "_col_debut"] = regle["col_debut"]
            if "col_fin" in regle:
                df.loc[mask, "_col_fin"] = regle["col_fin"]
        else:
            print(f"⚠️ {candidat} non trouvé dans cette feuille")

    # ==========================================================
    # DEBUG COLONNES UTILISÉES
    # ==========================================================
    print("\n🔎 Colonnes finales utilisées (extrait) :")
    print(df[[col_id, "_col_debut", "_col_fin"]].head())

    # ==========================================================
    # 6️⃣ CONVERSION HEURES
    # ==========================================================
    df["_debut_ts"] = df.apply(
        lambda r: convertir_heure_excel_ou_texte(r[r["_col_debut"]]),
        axis=1
    )

    df["_fin_ts"] = df.apply(
        lambda r: convertir_heure_excel_ou_texte(r[r["_col_fin"]]),
        axis=1
    )
    # ===== DEBUG candidat spécifique =====
    print(
        df.loc[df["Numero_inclusion"] == "0101EMS",
           ["Numero_inclusion", "_col_debut", "_col_fin", "_debut_ts", "_fin_ts"]]
    )
    # ==========================================================
    # 7️⃣ CALCUL DURÉE
    # ==========================================================
    col_duree = f"duree_{nom_bloc}"
    col_rejet = f"rejeter_{nom_bloc}"

    df[col_duree] = (df["_fin_ts"] - df["_debut_ts"]).dt.total_seconds() / 60
    df.loc[df[col_duree] < 0, col_duree] += 24 * 60

    # ==========================================================
    # 8️⃣ STATISTIQUES
    # ==========================================================
    mask_manquant = df[col_duree].isna()
    mask_valide = df[col_duree].notna() & (df[col_duree] > 0)

    moyenne = df.loc[mask_valide, col_duree].mean()
    ecart_type = df.loc[mask_valide, col_duree].std()

    print(f"\nMoyenne = {moyenne:.2f} min")
    print(f"Écart-type = {ecart_type:.2f} min")

    borne_inf = moyenne - 2 * ecart_type

    df[col_rejet] = 0
    df.loc[mask_manquant, col_rejet] = 2

    mask_rejet = df[col_duree] < borne_inf

    if nom_bloc == "bloc1":
        mask_rejet = mask_rejet | (df[col_duree] < 10)

    df.loc[mask_valide & mask_rejet, col_rejet] = 1

    # ==========================================================
    # 9️⃣ DEBUG CANDIDATS PROBLÉMATIQUES
    # ==========================================================
    print("\n🔎 DEBUG Candidats spécifiques :")

    candidats_test = [r[2] for r in REGLES_CANDIDATS.keys()]
    candidats_test = list(set(candidats_test))

    print(
        df.loc[
            df[col_id].isin(candidats_test),
            [col_id, col_duree, col_rejet]
        ]
    )

    # ==========================================================
    # 10️⃣ NETTOYAGE
    # ==========================================================
    df = df.drop(columns=["_col_debut", "_col_fin", "_debut_ts", "_fin_ts"])

    print(f"\nRésumé {col_rejet} :")
    print(df[col_rejet].value_counts().sort_index())

    return {
        "df": df,
        "moyenne": moyenne,
        "ecart_type": ecart_type,
        "rejets": {
            "manquant": df.loc[df[col_rejet] == 2, col_id].tolist(),
            "rejetes": df.loc[df[col_rejet] == 1, col_id].tolist()
        }
    }

## Bloc 1

In [8]:
feuilles = [
    'APHM', 'CAEN', 'POITIERS', 'ROUEN',
    'LAVERAN', 'LPC', 'SAINTE-MARGUERITE',
    'CGD', 'CERCA'
]

resultats_bloc1 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc1[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_ceinture_v2",   
        col_fin="heure_fin_anamnese_v2",        
        nom_bloc="bloc1"
    )

============================================================

--- Feuille : APHM | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0101CAR  heure_ceinture_v2  heure_fin_anamnese_v2
1          0102PCR  heure_ceinture_v2  heure_fin_anamnese_v2
2          0103SHS  heure_ceinture_v2  heure_fin_anamnese_v2
3          0105PNR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0104FJS  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 25.36 min
Écart-type = 10.48 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    25
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0301GNR  heure_ceinture_v2  heure_fin_anamnese_v2
1          0302ZMR  heure_ceinture_v2  heure_fin_anamnese_v2
2          0303PAR  heure_ceinture_v2  heure_fin_anamnese_v2
3          0304VMR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0305LCR  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 18.15 min
Écart-type = 7.13 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
2           0303PAR         22.0              0
4           0305LCR         13.0              0
16          0314CDS         18.0              0
34          0335JMS         17.0              0
38          0339NPR         23.0              0
47          0346GLS         26.0              0
51          0353LNR         18.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    51
1     4
2     1
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0401TSS  heure_ceinture_v2  heure_fin_anamnese_v2
1          0402LLS  heure_ceinture_v2  heure_fin_anamnese_v2
2          0403DCR  heure_ceinture_v2  heure_fin_anamnese_v2
3          0405FCR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0404CYS  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 29.60 min
Écart-type = 7.20 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
13          0414PJS         31.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0501MBS  heure_ceinture_v2  heure_fin_anamnese_v2
1          0502LIR  heure_ceinture_v2  heure_fin_anamnese_v2
2          0503LCR  heure_ceinture_v2  heure_fin_anamnese_v2
3          0504BCS  heure_ceinture_v2  heure_fin_anamnese_v2
4          0505PPR  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 25.00 min
Écart-type = 7.96 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    14
2     1
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0626MCS  heure_ceinture_v2  heure_fin_anamnese_v2
1          0628DMR  heure_ceinture_v2  heure_fin_anamnese_v2
2          0630RJR  heure_ceinture_v2  heure_fin_anamnese_v2
3          0629TCR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0631LHR  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 19.80 min
Écart-type = 5.17 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0101EMS  heure_ceinture_v2  heure_fin_anamnese_v2
1          0102EMS  heure_ceinture_v2  heure_fin_anamnese_v2
2          0103BPS  heure_ceinture_v2  heure_fin_anamnese_v2
3          0104IBS  heure_ceinture_v2  heure_fin_anamnese_v2
4          0105HAR  heure_ceinture_v2  heure_fin_anamnese_v2
  Numero_inclusion         _col_debut               _col_fin  \
0          0101EMS  heure_ceinture_v2  heure_fin_anamnese_v2

            _debut_ts             _fin_ts
0 1900-01-01 10:10:00 1900-01-01 10:33:00

Moyenne = 14.88 min
Écart-type = 5.95 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    38
1     5
2     1
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0801HDR  heure_ceinture_v2  heure_fin_anamnese_v2
1          0802LAS  heure_ceinture_v2  heure_fin_anamnese_v2
2          0804GOR  heure_ceinture_v2  heure_fin_anamnese_v2
3          0803DPS  heure_ceinture_v2  heure_fin_anamnese_v2
4          0805BMS  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 20.12 min
Écart-type = 6.58 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc1, rejeter_bloc1]
Index: []

Résumé rejeter_bloc1 :
rejeter_bloc1
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0901SMR  heure_ceinture_v2  heure_fin_anamnese_v2
1          0903DJS  heure_ceinture_v2  heure_fin_anamnese_v2
2          0902SIS  heure_ceinture_v2  heure_fin_anamnese_v2
3          0906DNR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0904KJS  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 25.40 min
Écart-type = 16.55 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc1  rejeter_bloc1
2          0902SIS         32.0              0
3          0906DNR         51.0              0
5          0905SLR         14.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    5
2    1
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc1 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion         _col_debut               _col_fin
0          0401BDS  heure_ceinture_v2  heure_fin_anamnese_v2
1          0402TFR  heure_ceinture_v2  heure_fin_anamnese_v2
2          0404DER  heure_ceinture_v2  heure_fin_anamnese_v2
3          0405RCR  heure_ceinture_v2  heure_fin_anamnese_v2
4          0406BBS  heure_ceinture_v2  heure_fin_anamnese_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 90.89 min
Écart-type = 333.04 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc1  rejeter_bloc1
12          0414PVR         14.0              0
20          0419SRR          8.0              1
21          0420MCR         36.0              0
23          0421ACS         13.0              0
27          0423RMR         10.0              0
29          0424BLR         20.0              0

Résumé rejeter_bloc1 :
rejeter_bloc1
0    11
1     7
2    22
Name: count, dtype: int64

## Bloc 2

### Avec vidéo: de heure_rlri16imm_debut_V2 à heure_rappel_cond_v2

In [7]:
resultats_bloc2_R = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2_R[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_V2",  
        col_fin= "heure_rappel_cond_v2" ,  # Beaucoup de rejet car tous les S ont des NV car pas vu la vidéo         
        nom_bloc="bloc2R"
    )

============================================================

--- Feuille : APHM | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0101CAR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0102PCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0103SHS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0105PNR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0104FJS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 44.92 min
Écart-type = 7.48 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    13
2    12
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2R ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0353LNR

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0301GNR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0302ZMR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0303PAR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0304VMR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0305LCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 39.39 min
Écart-type = 5.17 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
2           0303PAR          43.0               0
4           0305LCR          44.0               0
16          0314CDS           NaN               2
34          0335JMS           NaN               2
38          0339NPR          34.0               0
47          0346GLS           NaN               2
51          0353LNR          39.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    27
1     1
2    28
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0401TSS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0402LLS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0403DCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0405FCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0404CYS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 41.80 min
Écart-type = 4.97 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
13          0414PJS           NaN               2

Résumé rejeter_bloc2R :
rejeter_bloc2R
0     5
2    10
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0501MBS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0502LIR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0503LCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0504BCS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0505PPR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 37.71 min
Écart-type = 3.50 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    7
2    8
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0626MCS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0628DMR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0630RJR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0629TCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0631LHR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 42.00 min
Écart-type = 10.71 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    4
2    1
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0101EMS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0102EMS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0103BPS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0104IBS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0105HAR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
  Numero_inclusion                _col_debut              _col_fin  \
0          0101EMS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2

            _debut_ts _fin_ts
0 1900-01-01 10:35:00     NaT

Moyenne = 39.44 min
Écart-type = 6.93 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    25
2    19
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0801HDR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0802LAS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0804GOR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0803DPS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0805BMS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 35.50 min
Écart-type = 3.32 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2R, rejeter_bloc2R]
Index: []

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    4
2    4
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0901SMR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0903DJS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0902SIS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0906DNR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0904KJS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 46.67 min
Écart-type = 6.43 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc2R  rejeter_bloc2R
2          0902SIS           NaN               2
3          0906DNR          54.0               0
5          0905SLR          44.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    3
2    3
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2R ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut              _col_fin
0          0401BDS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
1          0402TFR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
2          0404DER  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
3          0405RCR  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
4          0406BBS  heure_rlri16imm_debut_V2  heure_rappel_cond_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 41.55 min
Écart-type = 6.22 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2R  rejeter_bloc2R
12          0414PVR          43.0               0
20          0419SRR          34.0               0
21          0420MCR          36.0               0
23          0421ACS           NaN               2
27          0423RMR          42.0               0
29          0424BLR          39.0               0

Résumé rejeter_bloc2R :
rejeter_bloc2R
0    11
2    29
Name: count, dtype: int64

resultats_bloc2_R

### Sans vidéo: de heure_rlri16imm_debut_V2 à heure_nback_v2

In [8]:
resultats_bloc2_S = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc2_S[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_rlri16imm_debut_V2",
        col_fin="heure_nback_v2 (consigne)",
        nom_bloc="bloc2S"
    )

============================================================

--- Feuille : APHM | bloc2S ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0101CAR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0102PCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0103SHS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0105PNR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0104FJS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 46.44 min
Écart-type = 9.26 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    25
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0314CDS
🔧 Règle appliquée pour 0335JMS
🔧 Règle appliquée pour 0346GLS

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0301GNR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0302ZMR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0303PAR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0304VMR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0305LCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 40.08 min
Écart-type = 7.35 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
2           0303PAR           NaN               2
4           0305LCR           NaN               2
16          0314CDS          54.0               0
34          0335JMS          53.0               0
38          0339NPR           NaN               2
47          0346GLS          40.0               0
51          0353LNR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    49
1     2
2     5
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PJS

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0401TSS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0402LLS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0403DCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0405FCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0404CYS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 47.60 min
Écart-type = 7.54 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
13          0414PJS          49.0               0

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    15
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc2S ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0501MBS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0502LIR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0503LCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0504BCS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0505PPR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 40.27 min
Écart-type = 6.83 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc2S ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0626MCS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0628DMR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0630RJR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0629TCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0631LHR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 41.80 min
Écart-type = 9.86 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc2S ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0101EMS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0102EMS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0103BPS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0104IBS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0105HAR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
  Numero_inclusion                _col_debut                   _col_fin  \
0          0101EMS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)

            _debut_ts             _fin_ts
0 1900-01-01 10:35:00 1900-01-01 11:12:00

Moyenne = 38.23 min
Écart-type = 6.31 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    44
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc2S ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut        _col_fin
0          0801HDR  heure_rlri16imm_debut_V2  heure_nback_v2
1          0802LAS  heure_rlri16imm_debut_V2  heure_nback_v2
2          0804GOR  heure_rlri16imm_debut_V2  heure_nback_v2
3          0803DPS  heure_rlri16imm_debut_V2  heure_nback_v2
4          0805BMS  heure_rlri16imm_debut_V2  heure_nback_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 42.12 min
Écart-type = 7.36 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc2S, rejeter_bloc2S]
Index: []

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0902SIS

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0901SMR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0903DJS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0902SIS  heure_rlri16imm_debut_V2       heure_fluence_sem_v2
3          0906DNR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0904KJS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 40.25 min
Écart-type = 6.13 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc2S  rejeter_bloc2S
2          0902SIS          34.0               0
3          0906DNR           NaN               2
5          0905SLR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    4
2    2
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc2S ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0421ACS

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                _col_debut                   _col_fin
0          0401BDS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
1          0402TFR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
2          0404DER  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
3          0405RCR  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
4          0406BBS  heure_rlri16imm_debut_V2  heure_nback_v2 (consigne)
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 41.72 min
Écart-type = 5.93 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc2S  rejeter_bloc2S
12          0414PVR           NaN               2
20          0419SRR           NaN               2
21          0420MCR           NaN               2
23          0421ACS          36.0               0
27          0423RMR           NaN               2
29          0424BLR           NaN               2

Résumé rejeter_bloc2S :
rejeter_bloc2S
0    18
2    22
Name: count, dtype: int64

## Bloc 3

In [9]:
resultats_bloc3 = {}

for feuille in feuilles:
    print("\n" + "=" * 60)

    resultats_bloc3[feuille] = analyser_feuille_bloc(
        df=df[feuille],
        nom_feuille=feuille,
        col_debut="heure_nback_v2 (consigne)",   
        col_fin="heure_fin_tests_v2",        
        nom_bloc="bloc3"
    )

============================================================

--- Feuille : APHM | bloc3 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0101CAR  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0102PCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0103SHS  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0105PNR  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0104FJS  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 48.84 min
Écart-type = 8.85 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    24
1     1
Name: count, dtype: int64

============================================================

--- Feuille : CAEN | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0303PAR
🔧 Règle appliquée pour 0305LCR
🔧 Règle appliquée pour 0314CDS
🔧 Règle appliquée pour 0335JMS
🔧 Règle appliquée pour 0339NPR
🔧 Règle appliquée pour 0346GLS
🔧 Règle appliquée pour 0353LNR

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0301GNR  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0302ZMR  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0303PAR       heure_rappel_cond_v2  heure_fin_tests_v2
3          0304VMR  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0305LCR       heure_fluence_sem_v2  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 43.02 min
Écart-type = 10.68 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
2           0303PAR         22.0              0
4           0305LCR         40.0              0
16          0314CDS         19.0              1
34          0335JMS         18.0              1
38          0339NPR         29.0              0
47          0346GLS         25.0              0
51          0353LNR         21.0              1

Résumé rejeter_bloc3 :
rejeter_bloc3
0    52
1     3
2     1
Name: count, dtype: int64

============================================================

--- Feuille : POITIERS | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PJS

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0401TSS  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0402LLS  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0403DCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0405FCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0404CYS  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 49.80 min
Écart-type = 10.28 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
13          0414PJS         22.0              1

Résumé rejeter_bloc3 :
rejeter_bloc3
0    14
1     1
Name: count, dtype: int64

============================================================

--- Feuille : ROUEN | bloc3 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0501MBS  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0502LIR  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0503LCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0504BCS  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0505PPR  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 46.60 min
Écart-type = 8.76 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    15
Name: count, dtype: int64

============================================================

--- Feuille : LAVERAN | bloc3 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0626MCS  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0628DMR  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0630RJR  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0629TCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0631LHR  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 46.60 min
Écart-type = 6.31 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    5
Name: count, dtype: int64

============================================================

--- Feuille : LPC | bloc3 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0101EMS  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0102EMS  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0103BPS  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0104IBS  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0105HAR  heure_nback_v2 (consigne)  heure_fin_tests_v2
  Numero_inclusion                 _col_debut            _col_fin  \
0          0101EMS  heure_nback_v2 (consigne)  heure_fin_tests_v2

            _debut_ts             _fin_ts
0 1900-01-01 11:12:00 1900-01-01 11:54:00

Moyenne = 44.84 min
Écart-type = 5.81 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    44
Name: count, dtype: int64

============================================================

--- Feuille : SAINTE-MARGUERITE | bloc3 ---

🔎 Vérification règles spécifiques :

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion      _col_debut            _col_fin
0          0801HDR  heure_nback_v2  heure_fin_tests_v2
1          0802LAS  heure_nback_v2  heure_fin_tests_v2
2          0804GOR  heure_nback_v2  heure_fin_tests_v2
3          0803DPS  heure_nback_v2  heure_fin_tests_v2
4          0805BMS  heure_nback_v2  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 44.50 min
Écart-type = 8.21 min

🔎 DEBUG Candidats spécifiques :
Empty DataFrame
Columns: [Numero_inclusion, duree_bloc3, rejeter_bloc3]
Index: []

Résumé rejeter_bloc3 :
rejeter_bloc3
0    8
Name: count, dtype: int64

============================================================

--- Feuille : CGD | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0902SIS
🔧 Règle appliquée pour 0905SLR
🔧 Règle appliquée pour 0906DNR

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0901SMR  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0903DJS  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0902SIS       heure_fluence_sem_v2  heure_fin_tests_v2
3          0906DNR       heure_fluence_sem_v2  heure_fin_tests_v2
4          0904KJS  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 43.17 min
Écart-type = 13.41 min

🔎 DEBUG Candidats spécifiques :
  Numero_inclusion  duree_bloc3  rejeter_bloc3
2          0902SIS         17.0              0
3          0906DNR         44.0              0
5          0905SLR         48.0              0

Résumé rejeter_bloc3 :
rejeter_bloc3
0    6
Name: count, dtype: int64

============================================================

--- Feuille : CERCA | bloc3 ---

🔎 Vérification règles spécifiques :
🔧 Règle appliquée pour 0414PVR
🔧 Règle appliquée pour 0419SRR
🔧 Règle appliquée pour 0420MCR
🔧 Règle appliquée pour 0421ACS
🔧 Règle appliquée pour 0423RMR
🔧 Règle appliquée pour 0424BLR

🔎 Colonnes finales utilisées (extrait) :
  Numero_inclusion                 _col_debut            _col_fin
0          0401BDS  heure_nback_v2 (consigne)  heure_fin_tests_v2
1          0402TFR  heure_nback_v2 (consigne)  heure_fin_tests_v2
2          0404DER  heure_nback_v2 (consigne)  heure_fin_tests_v2
3          0405RCR  heure_nback_v2 (consigne)  heure_fin_tests_v2
4          0406BBS  heure_nback_v2 (consigne)  heure_fin_tests_v2
Empty DataFrame
Columns: [Numero_inclusion, _col_debut, _col_fin, _debut_ts, _fin_ts]
Index: []

Moyenne = 48.33 min
Écart-type = 4.93 min

🔎 DEBUG Candidats spécifiques :
   Numero_inclusion  duree_bloc3  rejeter_bloc3
12          0414PVR         49.0              0
20          0419SRR         42.0              0
21          0420MCR         46.0              0
23          0421ACS         43.0              0
27          0423RMR         50.0              0
29          0424BLR         49.0              0

Résumé rejeter_bloc3 :
rejeter_bloc3
0    23
1     1
2    16
Name: count, dtype: int64

# Nombre de candidats qui passent toutes les conditions

In [10]:
def candidats_valides_tous_blocs_depuis_resultats(
    feuille,
    resultats_blocs,
    col_id="Numero_inclusion"
):
    """
    Un candidat est conservé si nous pouvons calculer la durée de tous ses blocs et si celles-ci respectent les conditions suivantes :
    - bloc 1 > 10 min
    - bloc2R/S et bloc 3 > mean - 2σ min
    
    resultats_blocs = dict {
        "bloc1": resultats_bloc1,
        "bloc2S": resultats_bloc2_S,
        "bloc2R": resultats_bloc2_R,
        "bloc3": resultats_bloc3
    }
    """

    # Récupération du df de référence (bloc1 par ex)
    df_ref = resultats_blocs["bloc1"][feuille]["df"].copy()

    colonnes_rejet = []

    # Ajouter chaque colonne de rejet depuis chaque bloc
    for nom_bloc, res_bloc in resultats_blocs.items():
        col_rejet = f"rejeter_{nom_bloc}"
        if col_rejet not in res_bloc[feuille]["df"].columns:
            print(f"Colonne manquante : {col_rejet} dans {feuille}")
            return None

        df_ref[col_rejet] = res_bloc[feuille]["df"][col_rejet]
        colonnes_rejet.append(col_rejet)

    # Condition : tout à 0
    mask_valide = (df_ref[colonnes_rejet] == 0).all(axis=1)

    candidats_ok = df_ref.loc[mask_valide, col_id].tolist()
    candidats_rejetes = df_ref.loc[~mask_valide, col_id].tolist()

    print(f"\n=== {feuille} ===")
    print(f"Candidats valides sur TOUS les blocs : {len(candidats_ok)}")

    print("Liste des candidats conservés :")
    for pid in candidats_ok:
        print(f" - {pid}")

    return {
        "nb_valides": len(candidats_ok),
        "valides": candidats_ok,
        "rejetes": candidats_rejetes,
    }

In [11]:
resultats_globaux = {}

colonnes_blocs = [
    "rejeter_bloc1",
    "rejeter_bloc2S",
    "rejeter_bloc2R",
    "rejeter_bloc3"
]

for feuille in feuilles:
    print("\n" + "=" * 70)
    print(f"Analyse globale – Feuille : {feuille}")

    # ===== Base : bloc 1 =====
    df_global = resultats_bloc1[feuille]["df"][
        ["Numero_inclusion", "Condition", "rejeter_bloc1"]
    ].copy()

    # ===== Fusion bloc 2S =====
    df_global = df_global.merge(
        resultats_bloc2_S[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2S"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 2R =====
    df_global = df_global.merge(
        resultats_bloc2_R[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc2R"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Fusion bloc 3 =====
    df_global = df_global.merge(
        resultats_bloc3[feuille]["df"][
            ["Numero_inclusion", "rejeter_bloc3"]
        ],
        on="Numero_inclusion",
        how="left"
    )

    # ===== Affichage debug AVANT filtre =====
    print("\n📊 df_global AVANT fillna et filtres :")
    display(df_global)

    # ===== Sécurité : NaN → rejet (2) =====
    df_global[colonnes_blocs] = df_global[colonnes_blocs].fillna(2)

    # ===== Filtrage conditionnel S / R =====
    mask_S = (
        (df_global["Condition"] == "Standard") &
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2S"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    mask_R = (
        (df_global["Condition"] == "Réduction de la menace") &
        (df_global["rejeter_bloc1"] == 0) &
        (df_global["rejeter_bloc2R"] == 0) &
        (df_global["rejeter_bloc3"] == 0)
    )

    mask_valide = mask_S | mask_R

    # ===== Extraction =====
    candidats_valides = df_global.loc[
        mask_valide, "Numero_inclusion"
    ].tolist()

    candidats_rejetes = df_global.loc[
        ~mask_valide, "Numero_inclusion"
    ].tolist()

    # ===== Résumés =====
    print(f"\nNombre total de candidats : {len(df_global)}")
    print(f"Candidats VALIDES (selon Condition) : {len(candidats_valides)}")
    print(f"Candidats REJETÉS : {len(candidats_rejetes)}")

    print("\nCandidats valides par condition :")
    print(df_global.loc[mask_valide, "Condition"].value_counts())

    print("\nListe des candidats valides :")
    for pid in candidats_valides:
        print(f" - {pid}")

    # ===== Stockage =====
    resultats_globaux[feuille] = {
        "df": df_global,
        "valides": candidats_valides,
        "rejetes": candidats_rejetes,
        "n_valides": len(candidats_valides),
        "n_rejetes": len(candidats_rejetes),
    }

======================================================================
Analyse globale – Feuille : APHM

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0101CAR,Réduction de la menace,0,0,0,0
1,0102PCR,Réduction de la menace,0,0,0,0
2,0103SHS,Standard,0,0,2,0
3,0105PNR,Réduction de la menace,0,0,0,0
4,0104FJS,Standard,0,0,2,0
5,0106JLS,Standard,0,0,2,0
6,0107DSS,Standard,0,0,2,0
7,0108BFS,Standard,0,0,2,0
8,0109GSS,Standard,0,0,2,0
9,0110LPR,Réduction de la menace,0,0,0,0
10,0111MNR,Réduction de la menace,0,0,0,0
11,0112BSR,Réduction de la menace,0,0,0,0
12,0113BMR,Réduction de la menace,0,0,0,0
13,0114LMS,Standard,0,0,2,0
14,0115CJR,Réduction de la menace,0,0,0,0
15,0116VAR,Réduction de la menace,0,0,0,0
16,0117POS,Standard,0,0,2,0
17,0118TNS,Standard,0,0,2,0
18,0119LJS,Standard,0,0,2,0
19,0120LCR,Réduction de la menace,0,0,0,0
20,0121MJR,Réduction de la menace,0,0,0,0
21,0122BDS,Standard,0,0,2,1
22,0123RMS,Standard,0,0,2,0
23,0124BAR,Réduction de la menace,0,0,0,0
24,0125BMR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 25
Candidats VALIDES (selon Condition) : 24
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Réduction de la menace    13
Standard                  11
Name: count, dtype: int64

Liste des candidats valides :
 - 0101CAR
 - 0102PCR
 - 0103SHS
 - 0105PNR
 - 0104FJS
 - 0106JLS
 - 0107DSS
 - 0108BFS
 - 0109GSS
 - 0110LPR
 - 0111MNR
 - 0112BSR
 - 0113BMR
 - 0114LMS
 - 0115CJR
 - 0116VAR
 - 0117POS
 - 0118TNS
 - 0119LJS
 - 0120LCR
 - 0121MJR
 - 0123RMS
 - 0124BAR
 - 0125BMR

======================================================================
Analyse globale – Feuille : CAEN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0301GNR,Réduction de la menace,0,0,0,0
1,0302ZMR,Réduction de la menace,0,0,0,0
2,0303PAR,Réduction de la menace,0,2,0,0
3,0304VMR,Réduction de la menace,0,0,0,0
4,0305LCR,Réduction de la menace,0,2,0,0
5,0307SMR,Réduction de la menace,0,0,0,0
6,0306MDR,Réduction de la menace,0,0,0,0
7,0308RGR,Réduction de la menace,0,0,0,0
8,0309DBS,Standard,0,0,2,0
9,0311CJS,Standard,0,0,2,0
10,0310ACS,Standard,0,0,2,0
11,0315VCS,Standard,0,0,2,0
12,0318PMS,Standard,0,0,2,0
13,0313FPR,Réduction de la menace,0,0,0,0
14,0312JMS,Standard,0,0,2,0
15,0316TMS,Standard,0,0,2,0
16,0314CDS,Standard,0,0,2,1
17,0317LGS,Standard,0,0,2,0
18,0319LJS,Standard,0,0,2,0
19,0320DGS,Standard,0,0,2,0
20,0321DRR,Réduction de la menace,0,0,0,0
21,0323RFS,Standard,0,0,2,0
22,0322RMS,Standard,1,0,2,0
23,0324LMR,Réduction de la menace,1,0,0,0
24,0325LCR,Réduction de la menace,0,0,0,0
25,0327IAR,Réduction de la menace,0,0,0,0
26,0326BJR,Réduction de la menace,0,0,0,0
27,0328MPR,Réduction de la menace,0,0,0,0
28,0330RTR,Réduction de la menace,0,0,0,0
29,0329NMR,Réduction de la menace,0,0,0,0
30,0331GRS,Standard,0,0,2,0
31,0332MCR,Réduction de la menace,0,0,0,0
32,0333MMS,Standard,0,0,2,0
33,0334TVS,Standard,0,0,2,0
34,0335JMS,Standard,0,0,2,1
35,0336CBS,Standard,0,0,2,0
36,0337BFS,Standard,0,0,2,0
37,0338JBS,Standard,1,1,2,0
38,0339NPR,Réduction de la menace,0,2,0,0
39,0340BAR,Réduction de la menace,1,2,1,2
40,0341LJS,Standard,0,0,2,0
41,0342VNS,Standard,0,0,2,0
42,0343PAS,Standard,0,0,2,0
43,0344DBS,Standard,0,1,2,0
44,0345LAR,Réduction de la menace,2,0,0,0
45,0349LLS,Standard,0,0,2,0
46,0347DMR,Réduction de la menace,0,0,0,0
47,0346GLS,Standard,0,0,2,0
48,0348GCR,Réduction de la menace,0,0,0,0
49,0350MYR,Réduction de la menace,0,0,0,0
50,0351FIR,Réduction de la menace,0,0,0,0
51,0353LNR,Réduction de la menace,0,2,0,1
52,0352RNR,Réduction de la menace,0,0,0,0
53,0354GKR,Réduction de la menace,0,0,0,0
54,0355BAS,Standard,0,0,2,0
55,0356DMS,Standard,0,0,2,0

Nombre total de candidats : 56
Candidats VALIDES (selon Condition) : 47
Candidats REJETÉS : 9

Candidats valides par condition :
Condition
Réduction de la menace    24
Standard                  23
Name: count, dtype: int64

Liste des candidats valides :
 - 0301GNR
 - 0302ZMR
 - 0303PAR
 - 0304VMR
 - 0305LCR
 - 0307SMR
 - 0306MDR
 - 0308RGR
 - 0309DBS
 - 0311CJS
 - 0310ACS
 - 0315VCS
 - 0318PMS
 - 0313FPR
 - 0312JMS
 - 0316TMS
 - 0317LGS
 - 0319LJS
 - 0320DGS
 - 0321DRR
 - 0323RFS
 - 0325LCR
 - 0327IAR
 - 0326BJR
 - 0328MPR
 - 0330RTR
 - 0329NMR
 - 0331GRS
 - 0332MCR
 - 0333MMS
 - 0334TVS
 - 0336CBS
 - 0337BFS
 - 0339NPR
 - 0341LJS
 - 0342VNS
 - 0343PAS
 - 0349LLS
 - 0347DMR
 - 0346GLS
 - 0348GCR
 - 0350MYR
 - 0351FIR
 - 0352RNR
 - 0354GKR
 - 0355BAS
 - 0356DMS

======================================================================
Analyse globale – Feuille : POITIERS

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0401TSS,Standard,0,0,2,0
1,0402LLS,Standard,0,0,2,0
2,0403DCR,Réduction de la menace,0,0,0,0
3,0405FCR,Réduction de la menace,0,0,0,0
4,0404CYS,Standard,0,0,2,0
5,0406MCS,Standard,1,0,2,0
6,0407LJR,Réduction de la menace,0,0,0,0
7,0408BCS,Standard,0,0,2,0
8,0409PHR,Réduction de la menace,0,0,0,0
9,0410PGS,Standard,0,0,2,0
10,0413HFS,Standard,0,0,2,0
11,0411VES,Standard,0,0,2,0
12,0412ANS,Standard,0,0,2,0
13,0414PJS,Standard,0,0,2,1
14,0415VMR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 13
Candidats REJETÉS : 2

Candidats valides par condition :
Condition
Standard                  8
Réduction de la menace    5
Name: count, dtype: int64

Liste des candidats valides :
 - 0401TSS
 - 0402LLS
 - 0403DCR
 - 0405FCR
 - 0404CYS
 - 0407LJR
 - 0408BCS
 - 0409PHR
 - 0410PGS
 - 0413HFS
 - 0411VES
 - 0412ANS
 - 0415VMR

======================================================================
Analyse globale – Feuille : ROUEN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0501MBS,Standard,0,0,2,0
1,0502LIR,Réduction de la menace,0,0,0,0
2,0503LCR,Réduction de la menace,0,0,0,0
3,0504BCS,Standard,0,0,2,0
4,0505PPR,Réduction de la menace,0,0,0,0
5,0506VMS,Standard,0,0,2,0
6,0508SRR,Réduction de la menace,0,0,0,0
7,0507BDS,Standard,0,0,2,0
8,0509LGS,Standard,0,0,2,0
9,0510DFS,Standard,0,0,0,0
10,0511LCS,Standard,0,0,2,0
11,0512RCR,Réduction de la menace,0,0,0,0
12,0513EBS,Standard,0,0,2,0
13,0514LPS,Standard,2,0,2,0
14,0515FAR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 15
Candidats VALIDES (selon Condition) : 14
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Standard                  8
Réduction de la menace    6
Name: count, dtype: int64

Liste des candidats valides :
 - 0501MBS
 - 0502LIR
 - 0503LCR
 - 0504BCS
 - 0505PPR
 - 0506VMS
 - 0508SRR
 - 0507BDS
 - 0509LGS
 - 0510DFS
 - 0511LCS
 - 0512RCR
 - 0513EBS
 - 0515FAR

======================================================================
Analyse globale – Feuille : LAVERAN

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0626MCS,Standard,0,0,2,0
1,0628DMR,Réduction de la menace,0,0,0,0
2,0630RJR,Réduction de la menace,0,0,0,0
3,0629TCR,Réduction de la menace,0,0,0,0
4,0631LHR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 5
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 0

Candidats valides par condition :
Condition
Réduction de la menace    4
Standard                  1
Name: count, dtype: int64

Liste des candidats valides :
 - 0626MCS
 - 0628DMR
 - 0630RJR
 - 0629TCR
 - 0631LHR

======================================================================
Analyse globale – Feuille : LPC

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0101EMS,Standard,0,0,2,0
1,0102EMS,Standard,2,0,2,0
2,0103BPS,Standard,0,0,2,0
3,0104IBS,Standard,0,0,2,0
4,0105HAR,Réduction de la menace,1,0,0,0
5,0106DJR,Réduction de la menace,0,0,0,0
6,0107LER,Réduction de la menace,1,0,0,0
7,0108MMS,Standard,0,0,2,0
8,0109MJR,Réduction de la menace,0,0,0,0
9,0110RMS,Standard,0,0,2,0
10,0111TAS,Standard,1,0,2,0
11,0112DRR,Réduction de la menace,0,0,0,0
12,0113DGR,Réduction de la menace,0,0,0,0
13,0114MLR,Réduction de la menace,0,0,0,0
14,0115MHR,Réduction de la menace,0,0,0,0
15,0116CNR,Réduction de la menace,0,0,0,0
16,0117MSR,Réduction de la menace,0,0,0,0
17,0118TMS,Standard,0,0,2,0
18,0119BIR,Réduction de la menace,0,0,0,0
19,0120ANS,Standard,0,0,2,0
20,0121RPS,Standard,0,0,2,0
21,0122VCR,Réduction de la menace,0,0,0,0
22,0123GVS,Standard,0,0,2,0
23,0124PAS,Standard,0,0,2,0
24,0125AMR,Réduction de la menace,1,0,0,0
25,0126VLR,Réduction de la menace,0,0,0,0
26,0127CMS,Standard,0,0,2,0
27,0128ALS,Standard,0,0,2,0
28,0129APR,Réduction de la menace,0,0,0,0
29,0130FAR,Réduction de la menace,1,0,0,0
30,0131CPS,Standard,0,0,2,0
31,0132GAR,Réduction de la menace,0,0,0,0
32,0133BPS,Standard,0,0,2,0
33,0134IFR,Réduction de la menace,0,0,0,0
34,0135KLS,Standard,0,0,2,0
35,0136CJR,Réduction de la menace,0,0,0,0
36,0137BMS,Standard,0,0,2,0
37,0138NWR,Réduction de la menace,0,0,0,0
38,0139BMR,Réduction de la menace,0,0,0,0
39,0140LMR,Réduction de la menace,0,0,0,0
40,0141HJR,Réduction de la menace,0,0,0,0
41,0142LLS,Standard,0,0,2,0
42,0143EBR,Réduction de la menace,0,0,0,0
43,0144ZGR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 44
Candidats VALIDES (selon Condition) : 38
Candidats REJETÉS : 6

Candidats valides par condition :
Condition
Réduction de la menace    21
Standard                  17
Name: count, dtype: int64

Liste des candidats valides :
 - 0101EMS
 - 0103BPS
 - 0104IBS
 - 0106DJR
 - 0108MMS
 - 0109MJR
 - 0110RMS
 - 0112DRR
 - 0113DGR
 - 0114MLR
 - 0115MHR
 - 0116CNR
 - 0117MSR
 - 0118TMS
 - 0119BIR
 - 0120ANS
 - 0121RPS
 - 0122VCR
 - 0123GVS
 - 0124PAS
 - 0126VLR
 - 0127CMS
 - 0128ALS
 - 0129APR
 - 0131CPS
 - 0132GAR
 - 0133BPS
 - 0134IFR
 - 0135KLS
 - 0136CJR
 - 0137BMS
 - 0138NWR
 - 0139BMR
 - 0140LMR
 - 0141HJR
 - 0142LLS
 - 0143EBR
 - 0144ZGR

======================================================================
Analyse globale – Feuille : SAINTE-MARGUERITE

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0801HDR,Réduction de la menace,0,0,0,0
1,0802LAS,Standard,0,0,2,0
2,0804GOR,Réduction de la menace,0,0,0,0
3,0803DPS,Standard,0,0,2,0
4,0805BMS,Standard,0,0,2,0
5,0806KHS,Standard,0,0,2,0
6,0807OMR,Réduction de la menace,0,0,0,0
7,0808PJR,Réduction de la menace,0,0,0,0

Nombre total de candidats : 8
Candidats VALIDES (selon Condition) : 8
Candidats REJETÉS : 0

Candidats valides par condition :
Condition
Réduction de la menace    4
Standard                  4
Name: count, dtype: int64

Liste des candidats valides :
 - 0801HDR
 - 0802LAS
 - 0804GOR
 - 0803DPS
 - 0805BMS
 - 0806KHS
 - 0807OMR
 - 0808PJR

======================================================================
Analyse globale – Feuille : CGD

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0901SMR,Réduction de la menace,0,0,0,0
1,0903DJS,Standard,2,0,2,0
2,0902SIS,Standard,0,0,2,0
3,0906DNR,Réduction de la menace,0,2,0,0
4,0904KJS,Standard,0,0,2,0
5,0905SLR,Réduction de la menace,0,2,0,0

Nombre total de candidats : 6
Candidats VALIDES (selon Condition) : 5
Candidats REJETÉS : 1

Candidats valides par condition :
Condition
Réduction de la menace    3
Standard                  2
Name: count, dtype: int64

Liste des candidats valides :
 - 0901SMR
 - 0902SIS
 - 0906DNR
 - 0904KJS
 - 0905SLR

======================================================================
Analyse globale – Feuille : CERCA

📊 df_global AVANT fillna et filtres :

,Numero_inclusion,Condition,rejeter_bloc1,rejeter_bloc2S,rejeter_bloc2R,rejeter_bloc3
0,0401BDS,Standard,2,2,2,2
1,0402TFR,Réduction de la menace,2,2,2,2
2,0404DER,Réduction de la menace,2,2,2,2
3,0405RCR,Réduction de la menace,2,2,2,2
4,0406BBS,Standard,2,2,2,2
5,0407HMS,Standard,2,2,2,2
6,0408SJS,Standard,2,2,2,2
7,0409HCR,Réduction de la menace,2,2,2,2
8,0410FMS,Standard,2,2,2,2
9,0411NPR,Réduction de la menace,2,2,2,2
10,0412CMS,Standard,2,2,2,2
11,0413MMR,Réduction de la menace,0,0,0,0
12,0414PVR,Réduction de la menace,0,2,0,0
13,0415HJS,Standard,0,0,2,0
14,0416CPR,Réduction de la menace,1,0,0,0
15,0417FAS,Standard,0,0,2,0
16,0417KMS,Standard,0,0,2,0
17,0418MPR,Réduction de la menace,0,0,0,0
18,0418TJR,Réduction de la menace,1,0,0,0
19,0419CHR,Réduction de la menace,1,2,0,2
20,0419SRR,Réduction de la menace,1,2,0,0
21,0420MCR,Réduction de la menace,0,2,0,0
22,0420LMR,Réduction de la menace,0,0,0,0
23,0421ACS,Standard,0,0,2,0
24,0422LVR,Réduction de la menace,2,2,2,2
25,0422WCS,Standard,1,0,2,0
26,0423SVS,Standard,2,2,2,2
27,0423RMR,Réduction de la menace,0,2,0,0
28,0424GMS,Standard,2,2,2,2
29,0424BLR,Réduction de la menace,0,2,0,0
30,0425CDS,Standard,2,2,2,0
31,0426DGS,Standard,2,2,2,0
32,0432CGS,Standard,2,0,2,2
33,0433RMR,Réduction de la menace,2,0,2,0
34,0434GPS,Standard,2,0,2,0
35,0809VJR,Réduction de la menace,1,0,2,0
36,0810LCR,Réduction de la menace,1,0,2,1
37,0812DMS,Standard,2,0,2,0
38,0813PJS,Standard,2,0,2,0
39,0811MCS,Standard,2,0,2,0

Nombre total de candidats : 40
Candidats VALIDES (selon Condition) : 11
Candidats REJETÉS : 29

Candidats valides par condition :
Condition
Réduction de la menace    7
Standard                  4
Name: count, dtype: int64

Liste des candidats valides :
 - 0413MMR
 - 0414PVR
 - 0415HJS
 - 0417FAS
 - 0417KMS
 - 0418MPR
 - 0420MCR
 - 0420LMR
 - 0421ACS
 - 0423RMR
 - 0424BLR

In [12]:
total_valides = sum(
    res["n_valides"] for res in resultats_globaux.values()
)

print("=" * 70)
print(f"✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : {total_valides}")

======================================================================
✅ Nombre TOTAL de candidats valides (toutes feuilles confondues) : 165

# 165 candidats retenus

# Recherche des candidats et téléchargement de leur fichier V2 BB RR

In [13]:
import pandas as pd

# Afficher toutes les lignes
pd.set_option('display.max_rows', None)

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

# Afficher toute la largeur de chaque colonne
pd.set_option('display.max_colwidth', None)

## APHM

In [14]:
# ===== Racine APHM =====
racine_aphm = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"

# ===== Candidats valides =====
candidats_aphm = [c.upper() for c in resultats_globaux["APHM"]["valides"]]

# ===== Mapping PID → Condition =====
df_conditions = resultats_globaux["APHM"]["df"][[
    "Numero_inclusion",
    "Condition"
]].copy()

df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
df_conditions["Condition"] = df_conditions["Condition"].astype(str)

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows = []

for root, dirs, files in os.walk(racine_aphm):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== détection PID dans tout le chemin =====
        pid_trouve = None
        for pid in candidats_aphm:
            if pid in chemin_upper:
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        # ===== récupération de la condition =====
        condition = dict_condition.get(pid_trouve)

        if condition is None:
            print(f"⚠️ Condition manquante pour {pid_trouve} → ignoré")
            continue

        rows.append({
            "Numero_inclusion": pid_trouve,
            "Chemin": chemin,
            "Condition": condition,
            "Feuille": "APHM"
        })

# ===== DataFrame brut =====
df_aphm = pd.DataFrame(rows)

# ===== Suppression doublons =====
df_aphm_final = (
    df_aphm
    .assign(
        priorite_ceinture=df_aphm["Chemin"].str.contains("CEINTURE", case=False)
    )
    .sort_values(
        ["Numero_inclusion", "priorite_ceinture"],
        ascending=[True, False]
    )
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .drop(columns="priorite_ceinture")
    .reset_index(drop=True)
)

print(f"Candidats attendus APHM : {len(candidats_aphm)}")
print(f"Fichiers BB/BR_RR APHM V2 retenus : {len(df_aphm_final)}")

display(df_aphm_final)

Candidats attendus APHM : 24
Fichiers BB/BR_RR APHM V2 retenus : 24

,Numero_inclusion,Chemin,Condition,Feuille
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 06-07-2018 V2\Ceinture 0101CAR\2018_07_06-08_24_06_BB_RR.csv,Réduction de la menace,APHM
1,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 09-07-2018 V2\Ceinture 0102PCR\2018_07_09-08_57_05_BB_RR.csv,Réduction de la menace,APHM
2,0103SHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0103SHS\0103SHS 10-09-2018 V2\Ceinture 0103SHS\2018_09_10-09_03_59_BB_RR.csv,Standard,APHM
3,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 29-11-2018 V2\Ceinture 0104FJS\2018_11_29-08_27_38_BB_RR.csv,Standard,APHM
4,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 10-12-2018 V2\Ceinture 0105PNR\2018_12_10-08_23_34_BB_RR.csv,Réduction de la menace,APHM
5,0106JLS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0106JLS\0106JLS 03-01-2019 V2\Ceinture 0106JLS\2019_01_03-08_25_39_BB_RR.csv,Standard,APHM
6,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 14-01-2019 V2\Ceinture 0107DSS\2019_01_14-08_24_42_BB_RR.csv,Standard,APHM
7,0108BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0108BFS\0108BFS 17-01-2019 V2\Ceinture 0108BFS\2019_01_17-08_42_57_BB_RR.csv,Standard,APHM
8,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 18-02-2019 V2\Ceinture 0109GSS\2019_02_18-08_56_33_BB_RR.csv,Standard,APHM
9,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 26-02-2019 V2\Ceinture 0110LPR\2019_02_26-08_44_39_BB_RR.csv,Réduction de la menace,APHM
10,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 28-02-2019 V2\Ceinture 0111MNR\2019_02_28-08_59_20_BB_RR.csv,Réduction de la menace,APHM
11,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR 06-06-2019 V2\Ceinture 0112BSR\2019_06_06-08_27_12_BB_RR.csv,Réduction de la menace,APHM
12,0113BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0113BMR\0113BMR 20-06-2019 V2\Ceinture 0113BMR\2019_06_20-08_19_13_BB_RR.csv,Réduction de la menace,APHM
13,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS 27-06-2019 V2\Ceinture 0114LMS\2019_06_27-08_36_32_BB_RR.csv,Standard,APHM
14,0115CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0115CJR\0115CJR 27-08-2019 V2\Ceinture 0115CJR\2019_08_27-08_25_18_BB_RR.csv,Réduction de la menace,APHM
15,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR 29-08-2019 V2\Ceinture 0116VAR\2019_08_29-08_35_33_BB_RR.csv,Réduction de la menace,APHM
16,0117POS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0117POS\0117POS 05-09-2019 V2\Ceinture 0117POS\2019_09_05-08_21_04_BB_RR.csv,Standard,APHM
17,0118TNS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0118TNS\0118TNS 01-10-2019 V2\Ceinture 0118TNS\2019_10_01-08_36_12_BB_RR.csv,Standard,APHM
18,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS 07-11-2019 V2\Ceinture 0119LJS\2019_11_07-08_37_31_BB_RR.csv,Standard,APHM
19,0120LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0120LCR\0120LCR 06-12-2019 V2\Ceinture 0120LCR\2019_12_06-08_25_03_BB_RR.csv,Réduction de la menace,APHM
20,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR 12-12-2019 V2\Ceinture 0121MJR\2019_12_12-09_01_38_BB_RR.csv,Réduction de la menace,APHM
21,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS 20-12-2019 V2\Ceinture 0123RMS\2019_12_20-08_35_03_BB_RR.csv,Standard,APHM
22,0124BAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0124BAR\V2\ceinture\2020_01_07-09_42_26\2020_01_07-09_42_26_BB_RR.csv,Réduction de la menace,APHM
23,0125BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0125BMR\V2\CEINTURE\2020_01_14-11_26_44\2020_01_14-11_26_44_BB_RR.csv,Réduction de la menace,APHM

## CAEN

In [15]:
# ===== Racine et candidats CAEN =====
racine_caen = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN"
candidats_caen = [c.upper() for c in resultats_globaux["CAEN"]["valides"]]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["CAEN"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== Paths forcés pour candidats avec pattern différent =====
paths_forces = {
    "0302ZMR": r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0302ZMR\ceinture\2019_01_24-09_37_03 0302ZMR\2019_01_24-09_37_03_BB_RR.csv",
    "0304VMR": r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0304VMR\Ceinture\2019_03_25-09_49_47 0304VMR\2019_03_25-09_49_47_BB_RR.csv",
    "0334TVS": r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_01_09_40_22_0334TVS\2020_10_01__09_40_22_BR_RR.csv",
    "0339NPR": r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_02_25_09_34_13 0339PNR\2021_02_25__09_34_13_BR_RR.csv",
}

# ===== Pattern PID dans le chemin (hors paths forcés) =====
patterns_candidats = {
    pid: re.compile(rf"\b{pid}\b", re.IGNORECASE)
    for pid in candidats_caen if pid not in paths_forces
}

rows = []

# ===== Parcours des fichiers =====
for root, dirs, files in os.walk(racine_caen):
    for f in files:
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)

        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                rows.append({
                    "Numero_inclusion": pid,
                    "Chemin": chemin,
                    "Condition": dict_condition.get(pid),
                    "Feuille": "CAEN"
                })
                break

# ===== Ajout des candidats avec path forcé =====
for pid, chemin in paths_forces.items():
    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin,
        "Condition": dict_condition.get(pid),
        "Feuille": "CAEN"
    })

# ===== Suppression doublons =====
df_caen = pd.DataFrame(rows)

df_caen_final = (
    df_caen
    .assign(
        priorite_ceinture=df_caen["Chemin"].str.contains("ceinture", case=False)
    )
    .sort_values(
        ["Numero_inclusion", "priorite_ceinture"],
        ascending=[True, False]
    )
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .drop(columns="priorite_ceinture")
    .reset_index(drop=True)
)

# ===== Résumé =====
print(f"Candidats attendus CAEN : {len(candidats_caen)}")
print(f"Fichiers BB/BR_RR CAEN retenus : {len(df_caen_final)}")

display(df_caen_final)

# pour le 0323RFS il s'agit de la v4, supprimer plus tard

Candidats attendus CAEN : 47
Fichiers BB/BR_RR CAEN retenus : 47

,Numero_inclusion,Chemin,Condition,Feuille
0,0301GNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0301GNR\ceinture\2019_01_16-10_11_49 0301GNR\2019_01_16-10_11_49_BB_RR.csv,Réduction de la menace,CAEN
1,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0302ZMR\ceinture\2019_01_24-09_37_03 0302ZMR\2019_01_24-09_37_03_BB_RR.csv,Réduction de la menace,CAEN
2,0303PAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0303PAR\Ceinture\2019_03_14-09_58_28 0303PAR\2019_03_14-09_58_28_BB_RR.csv,Réduction de la menace,CAEN
3,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0304VMR\Ceinture\2019_03_25-09_49_47 0304VMR\2019_03_25-09_49_47_BB_RR.csv,Réduction de la menace,CAEN
4,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_04_25-10_01_08 0305LCR\2019_04_25-10_01_08_BB_RR.csv,Réduction de la menace,CAEN
5,0306MDR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_05_06-14_17_53 0306MDR\2019_05_06-14_17_53_BB_RR.csv,Réduction de la menace,CAEN
6,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_05_13-10_23_50 0307SMR\2019_05_13-10_23_50_BB_RR (1).csv,Réduction de la menace,CAEN
7,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_06_25-10_55_55 0308RGR\2019_06_25-10_55_55_BB_RR.csv,Réduction de la menace,CAEN
8,0309DBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_06_27-13_19_31 0309DBS\2019_06_27-13_19_31_BB_RR.csv,Standard,CAEN
9,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_03-09_56_22 0310ACS\2019_07_03-09_56_22_BB_RR.csv,Standard,CAEN
10,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_03-13_38_29 0311CJS\2019_07_03-13_38_29_BB_RR.csv,Standard,CAEN
11,0312JMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_22-10_00_05 0312JMS\2019_07_22-10_00_05_BB_RR.csv,Standard,CAEN
12,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_23-14_27_14 0313FPR\2019_07_23-14_27_14_BB_RR.csv,Réduction de la menace,CAEN
13,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_08_29-09_50_18 0315VCS\2019_08_29-09_50_18_BB_RR (1).csv,Standard,CAEN
14,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_03-09_46_13 0316TMS\2019_09_03-09_46_13_BB_RR (1).csv,Standard,CAEN
15,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_05-09_39_02 0317LGS\2019_09_05-09_39_02_BB_RR (1).csv,Standard,CAEN
16,0318PMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_06-10_21_56 0318PMS\2019_09_06-10_21_56_BB_RR (1).csv,Standard,CAEN
17,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_24-10_11_52 0319LJS\2019_09_24-10_11_52_BB_RR (1).csv,Standard,CAEN
18,0320DGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_01-10_20_37 0320DGS\2019_10_01-10_20_37_BB_RR.csv,Standard,CAEN
19,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_08-10_34_34 0321DRR\2019_10_08-10_34_34_BB_RR.csv,Réduction de la menace,CAEN
20,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_27_09_25_18 0323RFS\2020_08_27__09_25_18_BR_RR.csv,Standard,CAEN
21,0325LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_15-10_23_10 0325LCR\2019_11_15-10_23_10_BB_RR (1).csv,Réduction de la menace,CAEN
22,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_22-10_00_52 0326BJR\2019_11_22-10_00_52_BB_RR.csv,Réduction de la menace,CAEN
23,0327IAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_25-09_56_16 0327IAR\2019_11_25-09_56_16_BB_RR.csv,Réduction de la menace,CAEN
24,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_12_05-09_47_22 0328MPR\2019_12_05-09_47_22_BB_RR.csv,Réduction de la menace,CAEN
25,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_28-09_53_10 0329NMR\2020_01_28-09_53_10_BB_RR.csv,Réduction de la menace,CAEN
26,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_31-09_46_05 0330RTR\2020_01_31-09_46_05_BB_RR.csv,Réduction de la menace,CAEN
27,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_02_11-14_54_58 0331GRS\2020_02_11-14_54_58_BB_RR.csv,Standard,CAEN
28,0332MCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_03_06-09_57_45 0332MCR\2020_03_06-09_57_45_BB_RR (1).csv,Réduction de la menace,CAEN
29,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_25_09_39_30 0333MMS\2020_09_25__09_39_30_BR_RR.csv,Standard,CAEN
30,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_01_09_40_22_0334TVS\2020_10_01__09_40_22_BR_RR.csv,Standard,CAEN
31,0336CBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_16_09_43_10 0336CBS\2020_10_16__09_43_10_BR_RR.csv,Standard,CAEN
32,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_24_09_24_38 0337BFS\2020_11_24__09_24_38_BR_RR.csv,Standard,CAEN
33,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_02_25_09_34_13 0339PNR\2021_02_25__09_34_13_BR_RR.csv,Réduction de la menace,CAEN
34,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_05_17_09_42_15 0341LJS\2021_05_17__09_42_15_BR_RR.csv,Standard,CAEN
35,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_01_09_36_33 0342VNS\2021_06_01__09_36_33_BR_RR.csv,Standard,CAEN
36,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_08_09_37_22 0343PAS\2021_06_08__09_37_22_BR_RR.csv,Standard,CAEN
37,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_01_28_09_25_45 0346GLS\2022_01_28__09_25_45_BR_RR.csv,Standard,CAEN
38,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_01_31_10_04_24 0347DMR\2022_01_31__10_04_24_BR_RR.csv,Réduction de la menace,CAEN
39,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_01_10_21_15 0348GCR\2022_02_01__10_21_15_BR_RR.csv,Réduction de la menace,CAEN
40,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_21_09_57_05 0349LLS\2022_02_21__09_57_05_BR_RR.csv,Standard,CAEN
41,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_18_09_47_48 0350MYR\2022_03_18__09_47_48_BR_RR.csv,Réduction de la menace,CAEN
42,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_25_10_02_19 0351FIR\2022_03_25__10_02_19_BR_RR.csv,Réduction de la menace,CAEN
43,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_04_15_10_01_17 0352RNR\2022_04_15__10_01_17_BR_RR.csv,Réduction de la menace,CAEN
44,0354GKR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_06_27_09_30_41 0354GKR\2022_06_27__09_30_41_BR_RR.csv,Réduction de la menace,CAEN
45,0355BAS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_06_30_09_43_08 0355BAS\2022_06_30__09_43_08_BR_RR.csv,Standard,CAEN
46,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_09_22_09_44_11 0356DMS\2022_09_22__09_44_11_BR_RR.csv,Standard,CAEN

## POITIERS

In [16]:
# ===== Racine POITIERS =====
racine_poitiers = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY"

# ===== Candidats valides =====
candidats_poitiers = [c.upper() for c in resultats_globaux["POITIERS"]["valides"]]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["POITIERS"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== Regex POITIERS (TRONQUÉE → clé pour 0408) =====
# ex : 0408BCS → match "0408 BC"
patterns_candidats = {
    pid: re.compile(
        rf"{pid[:4]}\s*-?\s*{pid[4:6]}",
        re.IGNORECASE
    )
    for pid in candidats_poitiers
}

fichiers_par_candidat = defaultdict(list)

for root, dirs, files in os.walk(racine_poitiers):

    if "V2" not in root.upper():
        continue

    for f in files:
        if not f.lower().endswith(".csv"):
            continue

        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)

        for pid, pat in patterns_candidats.items():
            if pat.search(chemin):
                fichiers_par_candidat[pid].append(chemin)
                break

# ===== Sélection finale + DataFrame =====
rows = []

for pid, fichiers in fichiers_par_candidat.items():

    fichiers = sorted(set(fichiers))  # sécurité doublons exacts

    # priorité CEINTURE
    ceinture = [f for f in fichiers if "ceinture" in f.lower()]
    chemin_final = ceinture[0] if ceinture else fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Condition": dict_condition.get(pid),
        "Feuille": "POITIERS"
    })

df_poitiers_final = pd.DataFrame(rows)

# ===== Vérifications =====
print(f"Candidats attendus POITIERS : {len(candidats_poitiers)}")
print(f"Fichiers BB/BR_RR POITIERS retenus : {len(df_poitiers_final)}")

manquants = sorted(set(candidats_poitiers) - set(df_poitiers_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats POITIERS sont présents")

display(df_poitiers_final)

Candidats attendus POITIERS : 13
Fichiers BB/BR_RR POITIERS retenus : 13
✅ Tous les candidats POITIERS sont présents

,Numero_inclusion,Chemin,Condition,Feuille
0,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V2\0401TSS ceinture\No Team Assigned\2019_04_05-09_52_46\2019_04_05-09_52_46_BB_RR.csv,Standard,POITIERS
1,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS- V2\0402LLS- ceinture\No Team Assigned\2019_04_12-11_01_28\2019_04_12-11_01_28_BB_RR.csv,Standard,POITIERS
2,0403DCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0403 DC\0403DCR-V2\0403DCR- ceinture\No Team Assigned\2019_05_24-09_36_16\2019_05_24-09_36_16_BB_RR.csv,Réduction de la menace,POITIERS
3,0404CYS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0404 CY\0404CYS-V2\0404YC-ceinture\2019_07_19-10_32_55\2019_07_19-10_32_55_BB_RR.csv,Standard,POITIERS
4,0405FCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0405 FC\0405 FCR-V2\0405FCR- ceinture\No Team Assigned\2019_07_04-09_33_11\2019_07_04-09_33_11_BB_RR.csv,Réduction de la menace,POITIERS
5,0407LJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0407 LJ\0407LJR-V2\0407LJ-ceinture\No Team Assigned\2019_09_19-09_38_39\2019_09_19-09_38_39_BB_RR.csv,Réduction de la menace,POITIERS
6,0408BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0408 BC\0408 BC V2\0408BC-ceinture\No Team Assigned\2019_11_22-09_28_20\2019_11_22-09_28_20_BB_RR.csv,Standard,POITIERS
7,0409PHR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0409 PH\0409 PH- V2\0409PHR ceinture\No Team Assigned\2019_11_29-09_34_34\2019_11_29-09_34_34_BB_RR.csv,Réduction de la menace,POITIERS
8,0410PGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0410 PG\0410 PGS - V2\ceinture\No Team Assigned\2020_01_09-10_03_29\2020_01_09-10_03_29_BB_RR.csv,Standard,POITIERS
9,0411VES,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0411 VE\0411 VES-V2\0411VE ceinture\No Team Assigned\2020_02_20-09_42_09\2020_02_20-09_42_09_BB_RR.csv,Standard,POITIERS
10,0412ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0412 AN\0412 ANS-V2\0412AN ceinture\No Team Assigned\2020_02_21-13_33_48\2020_02_21-13_33_48_BB_RR.csv,Standard,POITIERS
11,0413HFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0413 HF\0413 HFS-V2\0413HF ceinture\No Team Assigned\2020_03_06-09_57_03\2020_03_06-09_57_03_BB_RR.csv,Standard,POITIERS
12,0415VMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0415 VM\0415 VMR-V2\0415VMR- ceinture V2\No Team Assigned\2020_10_02-09_44_24\2020_10_02-09_44_24_BB_RR.csv,Réduction de la menace,POITIERS

## ROUEN

In [17]:
# ===== Racine ROUEN =====
racine_rouen = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER"

# ===== Candidats valides =====
candidats_rouen = [c.upper() for c in resultats_globaux["ROUEN"]["valides"]]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["ROUEN"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== paramètres poids =====
POIDS_MIN = 3000 * 1024
POIDS_MAX = 8000 * 1024

# ===== pattern numéro (ex : 05-12) =====
patterns_candidats = [
    (pid, re.compile(rf"{pid[:2]}-{pid[2:4]}", re.IGNORECASE))
    for pid in candidats_rouen
]

# ===== pattern date =====
date_pattern = re.compile(r"(\d{4}_\d{2}_\d{2}[-_]\d{2}_\d{2}_\d{2})")

# ===== collecte brute =====
fichiers_dict = defaultdict(list)

for root, dirs, files in os.walk(racine_rouen):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue

        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)

        # ---- filtre poids pour eviter les doublons ----
        try:
            taille = os.path.getsize(chemin)
        except OSError:
            continue

        if not (POIDS_MIN <= taille <= POIDS_MAX):
            continue

        # ---- identification candidat ----
        pid_trouve = None
        for pid, pat in patterns_candidats:
            if pat.search(chemin):
                pid_trouve = pid
                break

        if not pid_trouve:
            continue

        # ---- date ----
        m = date_pattern.search(chemin)
        date_str = m.group(1) if m else "inconnue"

        fichiers_dict[(pid_trouve, date_str)].append(chemin)

# ===== Sélection finale + DataFrame =====
rows = []

for (pid, date_str), fichiers in fichiers_dict.items():

    fichiers = sorted(set(fichiers)) 
    chemin_final = fichiers[0]

    rows.append({
        "Numero_inclusion": pid,
        "Chemin": chemin_final,
        "Condition": dict_condition.get(pid),
        "Feuille": "ROUEN"
    })

df_rouen_final = pd.DataFrame(rows)

# ===== Résumé & contrôle =====
print(f"Candidats attendus ROUEN : {len(candidats_rouen)}")
print(f"Fichiers BB/BR_RR ROUEN retenus : {len(df_rouen_final)}")

manquants = sorted(set(candidats_rouen) - set(df_rouen_final["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats ROUEN manquants :", manquants)
else:
    print("✅ Tous les candidats ROUEN sont présents")

display(df_rouen_final)

# 0515 FAR date et heure correspondent pas et temps d'experience ne correspond pas non plus a la durée excel : on le rejette

Candidats attendus ROUEN : 14
Fichiers BB/BR_RR ROUEN retenus : 12
⚠️ Candidats ROUEN manquants : ['0501MBS', '0503LCR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0502LIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-02-LI-R\V2\CEINTURE\2019_02_28-09_42_09_BB_RR.csv,Réduction de la menace,ROUEN
1,0504BCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-04-BC-S\V2\ceinture 05-04-BC-S\2019_04_23-09_59_09\2019_04_23-09_59_09_BB_RR.csv,Standard,ROUEN
2,0505PPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-05-PP-R\V2\CEINTURE\2019_05_23-09_48_02_BB_RR.csv,Réduction de la menace,ROUEN
3,0506VMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-06-VM-S\V2\CEINTURE 05-06-VM-S\2019_05_27-09_37_10_BB_RR.csv,Standard,ROUEN
4,0507BDS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-07-BD-S\V2\CEINTURE\2019_06_24-09_49_35_BB_RR.csv,Standard,ROUEN
5,0508SRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-08-SR-R\V2\CEINTURE V2\2019_07_25-09_37_55_BB_RR.csv,Réduction de la menace,ROUEN
6,0509LGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-09-LC-S\V2\CEINTURE\2019_10_17-09_30_14_BB_RR.csv,Standard,ROUEN
7,0510DFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-10-DF-S\V2\CEINTURE\2020_02_20-09_49_46_BB_RR.csv,Standard,ROUEN
8,0511LCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-11-LC-S\05-11-LC-S-V2\CEINTURE\2021_01_07-10_11_23_BB_RR.csv,Standard,ROUEN
9,0512RCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-12-RC-R\V2\CEINTURE\Record 2_2021_05_04-08_47_59_BB_RR (1).csv,Réduction de la menace,ROUEN
10,0513EBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-13-EB-S\V2\CEINTURE\Record 1_2021_06_18-09_23_29_BB_RR.csv,Standard,ROUEN
11,0515FAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-ROUEN\HANNIER\HANNIER\05-15-FA-R\V2\CEINTURE\Record 1_2010_01_01-00_44_35_BB_RR.csv,Réduction de la menace,ROUEN

## LAVERAN

In [18]:
# ===== Racine LAVERAN =====
racine_laveran = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran"
)

# ===== Candidats attendus =====
candidats_laveran = [c.upper() for c in resultats_globaux["LAVERAN"]["valides"]]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["LAVERAN"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows = []

for root, dirs, files in os.walk(racine_laveran):

    if "V2" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification du candidat =====
        pid = None
        for c in candidats_laveran:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid),
            "Feuille": "LAVERAN"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================

df_laveran_final = pd.DataFrame(rows)

df_laveran_final = (
    df_laveran_final
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================

print("\n====================================")
print(f"Candidats attendus LAVERAN : {len(candidats_laveran)}")
print(f"Fichiers retenus LAVERAN    : {len(df_laveran_final)}")

manquants = sorted(
    set(candidats_laveran) - set(df_laveran_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LAVERAN manquants :", manquants)
else:
    print("✅ Tous les candidats LAVERAN sont présents")

display(df_laveran_final)

OK [0626MCS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V2\ceinture\2020_01_21-09_12_01\2020_01_21-09_12_01_BB_RR.csv
OK [0628DMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0628DMR\V2\ceinture\2020_01_30-10_11_25\2020_01_30-10_11_25_BB_RR.csv
OK [0629TCR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\V2\ceinture\No Team Assigned\2020_02_04-09_40_12\2020_02_04-09_40_12_BB_RR.csv
OK [0630RJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V2\ceinture\No Team Assigned\2020_02_20-10_24_36\2020_02_20-10_24_36_BB_RR.csv
OK [0631LHR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\V2\ceinture\2020_02_25-10_54_51\2020_02_25-10_54_51_BB_RR.csv

====================================
Candidats attendus LAVERAN : 5
Fichiers retenus LAVERAN    : 5
✅ Tous les candidats LAVERAN sont présents

,Numero_inclusion,Chemin,Condition,Feuille
0,0626MCS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0626MCS\V2\ceinture\2020_01_21-09_12_01\2020_01_21-09_12_01_BB_RR.csv,Standard,LAVERAN
1,0628DMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0628DMR\V2\ceinture\2020_01_30-10_11_25\2020_01_30-10_11_25_BB_RR.csv,Réduction de la menace,LAVERAN
2,0629TCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0629TCR\V2\ceinture\No Team Assigned\2020_02_04-09_40_12\2020_02_04-09_40_12_BB_RR.csv,Réduction de la menace,LAVERAN
3,0630RJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0630RJR\0630RJR_V2\ceinture\No Team Assigned\2020_02_20-10_24_36\2020_02_20-10_24_36_BB_RR.csv,Réduction de la menace,LAVERAN
4,0631LHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0631LHR\V2\ceinture\2020_02_25-10_54_51\2020_02_25-10_54_51_BB_RR.csv,Réduction de la menace,LAVERAN

## LPC

In [19]:
# ===== Racine LPC =====
racine_lpc = r"C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging"

# ===== Candidats attendus =====
candidats_lpc = [c.upper() for c in resultats_globaux["LPC"]["valides"]]

# ==========================================================
# CORRECTION MANUELLE DES PID (Excel → Arborescence)
# ==========================================================
CORRESPONDANCE_IDS = {
    "0117MSR": "0117MMR"
}

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["LPC"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== paramètres poids =====
POIDS_MIN = 2000 * 1024   # 2 Mo
POIDS_MAX = 8000 * 1024   # 8 Mo

# ===== date dans nom de fichier =====
date_pattern = re.compile(r"(\d{4}_\d{2}_\d{2}-\d{2}_\d{2}_\d{2})")

# ===== collecte brute =====
fichiers_dict = defaultdict(list)

for root, dirs, files in os.walk(racine_lpc):

    if "V2" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ---- filtre poids ----
        try:
            taille = os.path.getsize(chemin)
        except OSError:
            continue

        if not (POIDS_MIN <= taille <= POIDS_MAX):
            continue

        # ---- identification candidat ----
        pid = None
        for c in candidats_lpc:

            # ID réel à chercher dans l'arborescence
            id_recherche = CORRESPONDANCE_IDS.get(c, c)

            if id_recherche in chemin_upper:
                pid = c  
                break

        if not pid:
            continue

        # ---- date ----
        m = date_pattern.search(f)
        date_str = m.group(1) if m else "inconnue"

        fichiers_dict[(pid, date_str)].append(chemin)

# ===== DataFrame + Suppression des doublons =====
rows = []

for (pid, date_str), fichiers in fichiers_dict.items():

    fichiers = sorted(set(fichiers))
    chemin_final = fichiers[0]

    rows.append({
        "Numero_inclusion": pid,  # toujours ID Excel
        "Chemin": chemin_final,
        "Condition": dict_condition.get(pid),
        "Feuille": "LPC"
    })

df_lpc_final = pd.DataFrame(rows)

# ===== Affichage =====
print(f"Candidats attendus LPC : {len(candidats_lpc)}")
print(f"Fichiers BB/BR_RR retenus : {len(df_lpc_final)}")

manquants = sorted(
    set(candidats_lpc) - set(df_lpc_final["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC sont présents")

display(df_lpc_final)

Candidats attendus LPC : 38
Fichiers BB/BR_RR retenus : 25
⚠️ Candidats LPC manquants : ['0132GAR', '0133BPS', '0134IFR', '0135KLS', '0136CJR', '0137BMS', '0138NWR', '0139BMR', '0140LMR', '0141HJR', '0142LLS', '0143EBR', '0144ZGR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Ceinture\2019_01_22-10_10_43\2019_01_22-10_10_43_BB_RR.csv,Standard,LPC
1,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Ceinture\2018_12_11-10_08_18\2018_12_11-10_08_18_BB_RR.csv,Standard,LPC
2,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Ceinture\2018_11_28-09_57_59\2018_11_28-09_57_59_BB_RR.csv,Standard,LPC
3,0106DJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0106DJR\V2\Ceinture\2018_12_19-10_05_30\2018_12_19-10_05_30_BB_RR.csv,Réduction de la menace,LPC
4,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V2\Ceinture\2019_01_24-09_57_32_BB_RR.csv,Standard,LPC
5,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Ceinture\2018_12_13-09_37_28_BB_RR.csv,Réduction de la menace,LPC
6,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Ceinture\2018_12_14-09_38_18_BB_RR.csv,Standard,LPC
7,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V2\Ceinture\No Team Assigned\2019_02_06-09_34_41\2019_02_06-09_34_41_BB_RR.csv,Réduction de la menace,LPC
8,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Ceinture\2018_11_27-09_37_54_BB_RR.csv,Réduction de la menace,LPC
9,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Ceinture\2019_01_07-09_59_01_BB_RR.csv,Réduction de la menace,LPC
10,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\ceinture\2019_01_11-09_39_28_BB_RR.csv,Réduction de la menace,LPC
11,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Ceinture\2019_01_10-09_44_24_BB_RR.csv,Réduction de la menace,LPC
12,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Ceinture\2019_01_14-09_44_07_BB_RR.csv,Réduction de la menace,LPC
13,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Ceinture\2019_01_16-09_38_48_BB_RR.csv,Standard,LPC
14,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Ceinture\2019_01_28-09_32_53_BB_RR.csv,Réduction de la menace,LPC
15,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Ceinture\2019_02_04-09_42_53_BB_RR.csv,Standard,LPC
16,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Ceinture\2019_01_23-09_26_50_BB_RR.csv,Standard,LPC
17,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Ceinture\2019_02_01-09_34_26_BB_RR.csv,Réduction de la menace,LPC
18,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Ceinture\2019_02_08-09_25_58_BB_RR.csv,Standard,LPC
19,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Ceinture\2019_02_15-10_26_07_BB_RR.csv,Standard,LPC
20,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Ceinture\2019_03_08-09_35_44_BB_RR.csv,Réduction de la menace,LPC
21,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Ceinture\2019_02_21-09_34_58_BB_RR.csv,Standard,LPC
22,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Ceinture\2019_03_13-09_40_25_BB_RR.csv,Standard,LPC
23,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Ceinture\No Team Assigned\2019_03_14-09_42_22\2019_03_14-09_42_22_BB_RR.csv,Réduction de la menace,LPC
24,0131CPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0131CPS\V2\Ceinture\2019_12_09-10_03_43\2019_12_09-10_03_43_BB_RR.csv,Standard,LPC

In [20]:
# ===== Racines =====
racines = [
    r"C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire",
    r"C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo"
]

# ===== Candidats à garder =====
candidats_a_garder = [
    c.upper() for c in resultats_globaux["LPC"]["valides"][25:]
]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["LPC"]["df"][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

# ===== Paramètres poids =====
POIDS_MIN = 2000 * 1024   # 2 Mo
POIDS_MAX = 8000 * 1024   # 8 Mo

# ===== Collecte DataFrame =====
rows = []

for racine in racines:
    print(f"\n--- Scan de : {racine}")

    for root, dirs, files in os.walk(racine):

        if "V2" not in root.upper():
            continue

        for f in files:

            if not f.lower().endswith(".csv"):
                continue
            if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
                continue

            chemin = os.path.join(root, f)

            # ---- filtre poids ----
            try:
                taille = os.path.getsize(chemin)
            except OSError:
                continue

            if not (POIDS_MIN <= taille <= POIDS_MAX):
                continue

            # ---- identification candidat ----
            pid = None
            chemin_upper = chemin.upper()
            for c in candidats_a_garder:
                if c in chemin_upper:
                    pid = c
                    break

            if not pid:
                continue

            rows.append({
                "Numero_inclusion": pid,
                "Chemin": chemin,
                "Condition": dict_condition.get(pid),
                "Feuille": "LPC"
            })

            print(f"OK [{pid}] :", chemin)

# ===== Création DataFrame =====
df_lpc2 = pd.DataFrame(rows)

# ===== Déduplication =====
df_lpc2 = df_lpc2.drop_duplicates(
    subset="Numero_inclusion",
    keep="first"
).reset_index(drop=True)

# ===== Résumé & contrôles =====
print("\n====================================")
print(f"Candidats attendus LPC (partie 2) : {len(candidats_a_garder)}")
print(f"Fichiers retenus                  : {len(df_lpc2)}")

manquants = sorted(
    set(candidats_a_garder) - set(df_lpc2["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats LPC manquants :", manquants)
else:
    print("✅ Tous les candidats LPC sont présents")

display(df_lpc2)

--- Scan de : C:\Users\judupont\Desktop\data_aging_11_2025_copie\LNSC\LNSC\DESHAYES\DATA_Ancillaire

--- Scan de : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo
OK [0132GAR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Ceinture\2020_02_19-09_57_21\2020_02_19-09_57_21_BB_RR.csv
OK [0133BPS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Ceinture\No Team Assigned\2020_02_26-10_04_01\2020_02_26-10_04_01_BB_RR.csv
OK [0134IFR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\ceinture\No Team Assigned\2020_03_03-09_35_14\2020_03_03-09_35_14_BB_RR.csv
OK [0135KLS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\ceinture\No Team Assigned\2021_03_03-08_43_04\2021_03_03-08_43_04_BB_RR.csv
OK [0136CJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\CEINTURE\No Team Assigned\2021_04_02-09_00_53\2021_04_02-09_00_53_BB_RR.csv
OK [0137BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\CEINTURE\No Team Assigned\2021_04_12-09_58_17\2021_04_12-09_58_17_BB_RR (1).csv
OK [0137BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\CEINTURE\No Team Assigned\2021_04_12-09_58_17\2021_04_12-09_58_17_BB_RR.csv
OK [0138NWR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\ceinture\No Team Assigned\2021_06_02-10_11_00\2021_06_02-10_11_00_BB_RR.csv
OK [0144ZGR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\ceinture\No Team Assigned\2022_06_29-10_04_46\2022_06_29-10_04_46_BB_RR.csv
OK [0140LMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V2 0140LMR\CEINTURE\No Team Assigned\2022_01_13-09_40_17\2022_01_13-09_40_17_BB_RR.csv
OK [0143EBR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR V2\ceinture\No Team Assigned\2022_04_27-11_02_28\2022_04_27-11_02_28_BB_RR.csv

====================================
Candidats attendus LPC (partie 2) : 13
Fichiers retenus                  : 10
⚠️ Candidats LPC manquants : ['0139BMR', '0141HJR', '0142LLS']

,Numero_inclusion,Chemin,Condition,Feuille
0,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Ceinture\2020_02_19-09_57_21\2020_02_19-09_57_21_BB_RR.csv,Réduction de la menace,LPC
1,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Ceinture\No Team Assigned\2020_02_26-10_04_01\2020_02_26-10_04_01_BB_RR.csv,Standard,LPC
2,0134IFR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\ceinture\No Team Assigned\2020_03_03-09_35_14\2020_03_03-09_35_14_BB_RR.csv,Réduction de la menace,LPC
3,0135KLS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\ceinture\No Team Assigned\2021_03_03-08_43_04\2021_03_03-08_43_04_BB_RR.csv,Standard,LPC
4,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\CEINTURE\No Team Assigned\2021_04_02-09_00_53\2021_04_02-09_00_53_BB_RR.csv,Réduction de la menace,LPC
5,0137BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\CEINTURE\No Team Assigned\2021_04_12-09_58_17\2021_04_12-09_58_17_BB_RR (1).csv,Standard,LPC
6,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\ceinture\No Team Assigned\2021_06_02-10_11_00\2021_06_02-10_11_00_BB_RR.csv,Réduction de la menace,LPC
7,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\ceinture\No Team Assigned\2022_06_29-10_04_46\2022_06_29-10_04_46_BB_RR.csv,Réduction de la menace,LPC
8,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V2 0140LMR\CEINTURE\No Team Assigned\2022_01_13-09_40_17\2022_01_13-09_40_17_BB_RR.csv,Réduction de la menace,LPC
9,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR V2\ceinture\No Team Assigned\2022_04_27-11_02_28\2022_04_27-11_02_28_BB_RR.csv,Réduction de la menace,LPC

## SAINTE-MARGUERITE

In [21]:
# ===== Racine SAINTE-MARGUERITE =====
racine_st_marguerite = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite"
)

# ===== Candidats attendus =====
candidats_sm = [
    c.upper() for c in resultats_globaux["SAINTE-MARGUERITE"]["valides"]
]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["SAINTE-MARGUERITE"]["df"][
    ["Numero_inclusion", "Condition"]
].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows_sm = []

# =========================================================
# BOUCLE PRINCIPALE
# =========================================================
for root, dirs, files in os.walk(racine_st_marguerite):

    if "V2" not in root.upper():
        continue

    for f in files:

        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification du candidat =====
        pid = None
        for c in candidats_sm:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_sm.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid),
            "Feuille": "SAINTE-MARGUERITE"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_sm = pd.DataFrame(rows_sm)

df_sm = (
    df_sm
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus SAINTE-MARGUERITE : {len(candidats_sm)}")
print(f"Fichiers retenus                     : {len(df_sm)}")

manquants = sorted(
    set(candidats_sm) - set(df_sm["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats SAINTE-MARGUERITE sont présents")

display(df_sm)

OK [0801HDR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V2\CEINTURE_0801HDR_V2\No Team Assigned\2022_03_23-09_34_20\2022_03_23-09_34_20_BB_RR.csv
OK [0802LAS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V2\CEINTURE_0802LAS_V2\No Team Assigned\2022_03_21-15_42_25\2022_03_21-15_42_25_BB_RR.csv
OK [0803DPS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS - V2\CEINTURE_0803DPS_V2\No Team Assigned\2022_03_30-09_33_44\2022_03_30-09_33_44_BB_RR.csv
OK [0804GOR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR - V2\CEINTURE_0804GOR_V2\No Team Assigned\2022_04_13-09_22_46\2022_04_13-09_22_46_BB_RR.csv
OK [0805BMS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V2\CEINTURE_0805BMS_V2\2022_04_15-10_15_16_BB_RR.csv
OK [0806KHS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\V2\0806KHS - V2\CEINTURE_0806KHS_V2\No Team Assigned\2022_06_02-09_36_37\2022_06_02-09_36_37_BB_RR.csv
OK [0807OMR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V2\0807OMR - V2\CEINTURE_0807OMR_V2\No Team Assigned\2022_06_24-09_39_18\2022_06_24-09_39_18_BB_RR.csv
OK [0808PJR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0808PJR\0808PJR-V2\ceinture\No Team Assigned\2022_07_15-10_23_12\2022_07_15-10_23_12_BB_RR.csv

====================================
Candidats attendus SAINTE-MARGUERITE : 8
Fichiers retenus                     : 8
✅ Tous les candidats SAINTE-MARGUERITE sont présents

,Numero_inclusion,Chemin,Condition,Feuille
0,0801HDR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0801HDR\0801HDR - V2\CEINTURE_0801HDR_V2\No Team Assigned\2022_03_23-09_34_20\2022_03_23-09_34_20_BB_RR.csv,Réduction de la menace,SAINTE-MARGUERITE
1,0802LAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0802LAS\0802LAS - V2\CEINTURE_0802LAS_V2\No Team Assigned\2022_03_21-15_42_25\2022_03_21-15_42_25_BB_RR.csv,Standard,SAINTE-MARGUERITE
2,0803DPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0803DPS\0803DPS - V2\CEINTURE_0803DPS_V2\No Team Assigned\2022_03_30-09_33_44\2022_03_30-09_33_44_BB_RR.csv,Standard,SAINTE-MARGUERITE
3,0804GOR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0804GOR\0804GOR - V2\CEINTURE_0804GOR_V2\No Team Assigned\2022_04_13-09_22_46\2022_04_13-09_22_46_BB_RR.csv,Réduction de la menace,SAINTE-MARGUERITE
4,0805BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0805BMS\0805BMS - V2\CEINTURE_0805BMS_V2\2022_04_15-10_15_16_BB_RR.csv,Standard,SAINTE-MARGUERITE
5,0806KHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0806KHS\V2\0806KHS - V2\CEINTURE_0806KHS_V2\No Team Assigned\2022_06_02-09_36_37\2022_06_02-09_36_37_BB_RR.csv,Standard,SAINTE-MARGUERITE
6,0807OMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0807OMR\V2\0807OMR - V2\CEINTURE_0807OMR_V2\No Team Assigned\2022_06_24-09_39_18\2022_06_24-09_39_18_BB_RR.csv,Réduction de la menace,SAINTE-MARGUERITE
7,0808PJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_StMarguerite\0808PJR\0808PJR-V2\ceinture\No Team Assigned\2022_07_15-10_23_12\2022_07_15-10_23_12_BB_RR.csv,Réduction de la menace,SAINTE-MARGUERITE

## CGD

In [23]:
# ===== Racine CGD =====
racine_cgd = (
    r"C:\Users\judupont\Desktop\AGING_19_01_2026"
    r"\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD"
)

# ===== Candidats attendus =====
candidats_cgd = [
    c.upper() for c in resultats_globaux["CGD"]["valides"]
]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux["CGD"]["df"][
    ["Numero_inclusion", "Condition"]
].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()

dict_condition = dict(
    zip(df_conditions["Numero_inclusion"], df_conditions["Condition"])
)

rows_cgd = []

for root, dirs, files in os.walk(racine_cgd):

    if "V2" not in root.upper():
        continue

    for f in files:

        # CSV BB/BR_RR uniquement
        if not f.lower().endswith(".csv"):
            continue
        if not re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            continue

        chemin = os.path.join(root, f)
        chemin_upper = chemin.upper()

        # ===== identification du candidat =====
        pid = None
        for c in candidats_cgd:
            if c in chemin_upper:
                pid = c
                break

        if not pid:
            continue

        rows_cgd.append({
            "Numero_inclusion": pid,
            "Chemin": chemin,
            "Condition": dict_condition.get(pid),
            "Feuille": "CGD"
        })

        print(f"OK [{pid}] :", chemin)

# =========================================================
# DATAFRAME + SUPPRESSION DES DOUBLONS
# =========================================================
df_cgd = pd.DataFrame(rows_cgd)

df_cgd = (
    df_cgd
    .drop_duplicates(subset="Numero_inclusion", keep="first")
    .reset_index(drop=True)
)

# =========================================================
# AFFICHAGE
# =========================================================
print("\n====================================")
print(f"Candidats attendus CGD : {len(candidats_cgd)}")
print(f"Fichiers retenus CGD   : {len(df_cgd)}")

manquants = sorted(
    set(candidats_cgd) - set(df_cgd["Numero_inclusion"])
)

if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CGD sont présents")

display(df_cgd)

OK [0902SIS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS_V2\CEINTURE 0102SIS_V2\No Team Assigned\2022_05_19-09_43_14\2022_05_19-09_43_14_BB_RR.csv
OK [0904KJS] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS - V2\CEINTURE_0904KJS_V2\No Team Assigned\2022_06_27-10_13_51\2022_06_27-10_13_51_BB_RR.csv
OK [0905SLR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V2\ceinture\No Team Assigned\2022_07_04-10_05_54\2022_07_04-10_05_54_BB_RR.csv
OK [0906DNR] : C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0906DNR\0906DNR_V2\ceinture\No Team Assigned\2022_07_06-10_13_33\2022_07_06-10_13_33_BB_RR.csv

====================================
Candidats attendus CGD : 5
Fichiers retenus CGD   : 4
⚠️ Candidats manquants : ['0901SMR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0902SIS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0902SIS\0902SIS_V2\CEINTURE 0102SIS_V2\No Team Assigned\2022_05_19-09_43_14\2022_05_19-09_43_14_BB_RR.csv,Standard,CGD
1,0904KJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0904KJS\0904KJS - V2\CEINTURE_0904KJS_V2\No Team Assigned\2022_06_27-10_13_51\2022_06_27-10_13_51_BB_RR.csv,Standard,CGD
2,0905SLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0905SLR\0905SLR-V2\ceinture\No Team Assigned\2022_07_04-10_05_54\2022_07_04-10_05_54_BB_RR.csv,Réduction de la menace,CGD
3,0906DNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_CGD\0906DNR\0906DNR_V2\ceinture\No Team Assigned\2022_07_06-10_13_33\2022_07_06-10_13_33_BB_RR.csv,Réduction de la menace,CGD

## CERCA

In [25]:
# ===== Racine CERCA =====
racine_cerca = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS"

# ===== Candidats CERCA =====
candidats_cerca = [c.upper() for c in resultats_globaux['CERCA']['valides']]

# ===== Dictionnaire PID → Condition =====
df_conditions = resultats_globaux['CERCA']['df'][["Numero_inclusion", "Condition"]].copy()
df_conditions["Numero_inclusion"] = df_conditions["Numero_inclusion"].str.upper()
dict_condition = dict(zip(df_conditions["Numero_inclusion"], df_conditions["Condition"]))

# ===== Pattern candidats =====
patterns_candidats = {num: re.compile(rf"\b{num}\b", re.IGNORECASE) for num in candidats_cerca}

# ===== Collecte brute =====
fichiers_cerca = []

for root, dirs, files in os.walk(racine_cerca):
    if "V2" not in root.upper():
        continue

    for f in files:
        chemin = os.path.join(root, f)

        # Cas 1 : CSV classique
        if f.lower().endswith(".csv") and re.search(r"(BB_RR|BR_RR)", f, re.IGNORECASE):
            for num, pat in patterns_candidats.items():
                if pat.search(chemin):
                    fichiers_cerca.append(chemin)
                    break

        # Cas 2 : CSV dans zip
        elif f.lower().endswith(".zip"):
            try:
                with zipfile.ZipFile(chemin, 'r') as zf:
                    for name in zf.namelist():
                        if not name.lower().endswith(".csv"):
                            continue
                        if not re.search(r"(BB_RR|BR_RR)", name, re.IGNORECASE):
                            continue
                        full_path = f"{chemin}|{name}"  # garder le zip + fichier interne
                        for num, pat in patterns_candidats.items():
                            if pat.search(full_path):
                                fichiers_cerca.append(full_path)
                                break
            except zipfile.BadZipFile:
                print(f"⚠️ Zip corrompu : {chemin}")

# ===== DataFrame =====
rows = []

for num in candidats_cerca:
    fichiers_candidat = [f for f in fichiers_cerca if num in f]
    if fichiers_candidat:
        # Priorité aux fichiers contenant "ceinture"
        ceinture = [f for f in fichiers_candidat if "ceinture" in f.lower()]
        chemin_final = ceinture[0] if ceinture else fichiers_candidat[0]

        rows.append({
            "Numero_inclusion": num,
            "Chemin": chemin_final,
            "Condition": dict_condition.get(num),
            "Feuille": "CERCA"
        })

df_cerca = pd.DataFrame(rows)

# ===== Ajout manuel du candidat 0417KMS =====
chemin_0417KMS = r"C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\LEJEUNE\LEJEUNE\0417KMS\Ceinture\2022_11_24__09_03_09_BR_RR.csv"
if "0417KMS" in candidats_cerca and "0417KMS" not in df_cerca["Numero_inclusion"].values:
    df_cerca = pd.concat([
        df_cerca,
        pd.DataFrame([{
            "Numero_inclusion": "0417KMS",
            "Chemin": chemin_0417KMS,
            "Condition": dict_condition.get("0417KMS"),
            "Feuille": "CERCA"
        }])
    ], ignore_index=True)
    print("✅ Ajout manuel du candidat 0417KMS")

# ===== Résumé & contrôle =====
print(f"Candidats attendus CERCA : {len(candidats_cerca)}")
print(f"Fichiers BB/BR_RR retenus CERCA : {len(df_cerca)}")

manquants = sorted(set(candidats_cerca) - set(df_cerca["Numero_inclusion"]))
if manquants:
    print("⚠️ Candidats manquants :", manquants)
else:
    print("✅ Tous les candidats CERCA sont présents")

display(df_cerca)

✅ Ajout manuel du candidat 0417KMS
Candidats attendus CERCA : 11
Fichiers BB/BR_RR retenus CERCA : 8
⚠️ Candidats manquants : ['0420LMR', '0423RMR', '0424BLR']

,Numero_inclusion,Chemin,Condition,Feuille
0,0413MMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0413MMR\V2\Ceinture\2019_12_18__08_20_29_BR_RR.csv,Réduction de la menace,CERCA
1,0414PVR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Camille GUILLOU\0414PVR\V2\Ceinture\2020_01_07__09_15_42_BR_RR.csv.zip|2020_01_07__09_15_42_BR_RR.csv,Réduction de la menace,CERCA
2,0415HJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0415HJS\V2\Ceinture\2020_02_11__09_43_13_BR_RR.csv,Standard,CERCA
3,0417FAS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0417FAS\V2\Ceinture\2020_02_12__10_41_16_BR_RR.csv,Standard,CERCA
4,0418MPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0418MPR\V2\Ceinture\2020_02_13__09_33_23_BR_RR.csv,Réduction de la menace,CERCA
5,0420MCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0420MCR\V2\Ceinture\2020_02_28__09_44_26_BR_RR.csv,Réduction de la menace,CERCA
6,0421ACS,C:\Users\judupont\Desktop\AGING_19_01_2026\CERCA\GUILLOU\GUILLOU\CeRCA POITIERS\Alizé GRANGE\0421ACS\V2\Ceinture\2020_03_04__10_12_00_BR_RR.csv,Standard,CERCA
7,0417KMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\LEJEUNE\LEJEUNE\0417KMS\Ceinture\2022_11_24__09_03_09_BR_RR.csv,Standard,CERCA

## CONCATENATION

In [26]:
# ===== Liste des DataFrames par feuille =====
dfs = [
    df_aphm,  
    df_caen_final,
    df_poitiers_final,     
    df_rouen_final,
    df_laveran_final,
    df_lpc_final,         
    df_lpc2,
    df_sm,          
    df_cgd,         
    df_cerca      
]

# ===== Normalisation des colonnes =====
for i, df in enumerate(dfs):
    # Certains DF ont "PID" au lieu de "Numero_inclusion"
    if "PID" in df.columns:
        df.rename(columns={"PID": "Numero_inclusion"}, inplace=True)
    # Assurer que la colonne Condition existe
    if "Condition" not in df.columns:
        df["Condition"] = None
    # On garde uniquement les colonnes essentielles
    df = df[["Numero_inclusion", "Chemin", "Feuille", "Condition"]]
    dfs[i] = df

# ===== Concatenation =====
df_global = pd.concat(dfs, ignore_index=True)

# ===== Suppression des doublons par Numero_inclusion =====
df_global = df_global.drop_duplicates(subset=["Numero_inclusion"], keep="first")

# ===== Tri par Numero_inclusion =====
df_global = df_global.sort_values("Numero_inclusion").reset_index(drop=True)

# ===== Résumé =====
print(f"Total candidats uniques : {df_global['Numero_inclusion'].nunique()}")
print(f"Total fichiers conservés : {len(df_global)}")
display(df_global)

Total candidats uniques : 156
Total fichiers conservés : 156

,Numero_inclusion,Chemin,Feuille,Condition
0,0101CAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0101CAR\0101CAR 06-07-2018 V2\Ceinture 0101CAR\2018_07_06-08_24_06_BB_RR.csv,APHM,Réduction de la menace
1,0101EMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0101EMS\V2\Ceinture\2019_01_22-10_10_43\2019_01_22-10_10_43_BB_RR.csv,LPC,Standard
2,0102PCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0102PCR\0102PCR 09-07-2018 V2\Ceinture 0102PCR\2018_07_09-08_57_05_BB_RR.csv,APHM,Réduction de la menace
3,0103BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0103BPS\V2\Ceinture\2018_12_11-10_08_18\2018_12_11-10_08_18_BB_RR.csv,LPC,Standard
4,0103SHS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0103SHS\0103SHS 10-09-2018 V2\Ceinture 0103SHS\2018_09_10-09_03_59_BB_RR.csv,APHM,Standard
5,0104FJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0104FJS\0104FJS 29-11-2018 V2\Ceinture 0104FJS\2018_11_29-08_27_38_BB_RR.csv,APHM,Standard
6,0104IBS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0104IBS\V2\Ceinture\2018_11_28-09_57_59\2018_11_28-09_57_59_BB_RR.csv,LPC,Standard
7,0105PNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0105PNR\0105PNR 10-12-2018 V2\Ceinture 0105PNR\2018_12_10-08_23_34_BB_RR.csv,APHM,Réduction de la menace
8,0106DJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0106DJR\V2\Ceinture\2018_12_19-10_05_30\2018_12_19-10_05_30_BB_RR.csv,LPC,Réduction de la menace
9,0106JLS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0106JLS\0106JLS 03-01-2019 V2\Ceinture 0106JLS\2019_01_03-08_25_39_BB_RR.csv,APHM,Standard
10,0107DSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0107DSS\0107DSS 14-01-2019 V2\Ceinture 0107DSS\2019_01_14-08_24_42_BB_RR.csv,APHM,Standard
11,0108BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0108BFS\0108BFS 17-01-2019 V2\Ceinture 0108BFS\2019_01_17-08_42_57_BB_RR.csv,APHM,Standard
12,0108MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0108MMS\V2\Ceinture\2019_01_24-09_57_32_BB_RR.csv,LPC,Standard
13,0109GSS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0109GSS\0109GSS 18-02-2019 V2\Ceinture 0109GSS\2019_02_18-08_56_33_BB_RR.csv,APHM,Standard
14,0109MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0109MJR\V2\Ceinture\2018_12_13-09_37_28_BB_RR.csv,LPC,Réduction de la menace
15,0110LPR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0110LPR\0110LPR 26-02-2019 V2\Ceinture 0110LPR\2019_02_26-08_44_39_BB_RR.csv,APHM,Réduction de la menace
16,0110RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0110RMS\V2\Ceinture\2018_12_14-09_38_18_BB_RR.csv,LPC,Standard
17,0111MNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0111MNR\0111MNR 28-02-2019 V2\Ceinture 0111MNR\2019_02_28-08_59_20_BB_RR.csv,APHM,Réduction de la menace
18,0112BSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0112BSR\0112BSR 06-06-2019 V2\Ceinture 0112BSR\2019_06_06-08_27_12_BB_RR.csv,APHM,Réduction de la menace
19,0112DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0112DRR\V2\Ceinture\No Team Assigned\2019_02_06-09_34_41\2019_02_06-09_34_41_BB_RR.csv,LPC,Réduction de la menace
20,0113BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0113BMR\0113BMR 20-06-2019 V2\Ceinture 0113BMR\2019_06_20-08_19_13_BB_RR.csv,APHM,Réduction de la menace
21,0113DGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0113DGR\V2\Ceinture\2018_11_27-09_37_54_BB_RR.csv,LPC,Réduction de la menace
22,0114LMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0114LMS\0114LMS 27-06-2019 V2\Ceinture 0114LMS\2019_06_27-08_36_32_BB_RR.csv,APHM,Standard
23,0114MLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0114MLR\V2\Ceinture\2019_01_07-09_59_01_BB_RR.csv,LPC,Réduction de la menace
24,0115CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0115CJR\0115CJR 27-08-2019 V2\Ceinture 0115CJR\2019_08_27-08_25_18_BB_RR.csv,APHM,Réduction de la menace
25,0115MHR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0115MHR\V2\ceinture\2019_01_11-09_39_28_BB_RR.csv,LPC,Réduction de la menace
26,0116CNR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0116CNR\V2\Ceinture\2019_01_10-09_44_24_BB_RR.csv,LPC,Réduction de la menace
27,0116VAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0116VAR\0116VAR 29-08-2019 V2\Ceinture 0116VAR\2019_08_29-08_35_33_BB_RR.csv,APHM,Réduction de la menace
28,0117MSR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0117MMR\V2\Ceinture\2019_01_14-09_44_07_BB_RR.csv,LPC,Réduction de la menace
29,0117POS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0117POS\0117POS 05-09-2019 V2\Ceinture 0117POS\2019_09_05-08_21_04_BB_RR.csv,APHM,Standard
30,0118TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0118TMS\V2\Ceinture\2019_01_16-09_38_48_BB_RR.csv,LPC,Standard
31,0118TNS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0118TNS\0118TNS 01-10-2019 V2\Ceinture 0118TNS\2019_10_01-08_36_12_BB_RR.csv,APHM,Standard
32,0119BIR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0119BIR\V2\Ceinture\2019_01_28-09_32_53_BB_RR.csv,LPC,Réduction de la menace
33,0119LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0119LJS\0119LJS 07-11-2019 V2\Ceinture 0119LJS\2019_11_07-08_37_31_BB_RR.csv,APHM,Standard
34,0120ANS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0120ANS\V2\Ceinture\2019_02_04-09_42_53_BB_RR.csv,LPC,Standard
35,0120LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0120LCR\0120LCR 06-12-2019 V2\Ceinture 0120LCR\2019_12_06-08_25_03_BB_RR.csv,APHM,Réduction de la menace
36,0121MJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0121MJR\0121MJR 12-12-2019 V2\Ceinture 0121MJR\2019_12_12-09_01_38_BB_RR.csv,APHM,Réduction de la menace
37,0121RPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0121RPS\V2\Ceinture\2019_01_23-09_26_50_BB_RR.csv,LPC,Standard
38,0122VCR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0122VCR\V2\Ceinture\2019_02_01-09_34_26_BB_RR.csv,LPC,Réduction de la menace
39,0123GVS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0123GVS\V2\Ceinture\2019_02_08-09_25_58_BB_RR.csv,LPC,Standard
40,0123RMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0123RMS\0123RMS 20-12-2019 V2\Ceinture 0123RMS\2019_12_20-08_35_03_BB_RR.csv,APHM,Standard
41,0124BAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0124BAR\V2\ceinture\2020_01_07-09_42_26\2020_01_07-09_42_26_BB_RR.csv,APHM,Réduction de la menace
42,0124PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0124PAS\V2\Ceinture\2019_02_15-10_26_07_BB_RR.csv,LPC,Standard
43,0125BMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PATIENTS\TOUS_patients_APHM_laveran\0125BMR\V2\CEINTURE\2020_01_14-11_26_44\2020_01_14-11_26_44_BB_RR.csv,APHM,Réduction de la menace
44,0126VLR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0126VLR\V2\Ceinture\2019_03_08-09_35_44_BB_RR.csv,LPC,Réduction de la menace
45,0127CMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0127CMS\V2\Ceinture\2019_02_21-09_34_58_BB_RR.csv,LPC,Standard
46,0128ALS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0128ALS\V2\Ceinture\2019_03_13-09_40_25_BB_RR.csv,LPC,Standard
47,0129APR,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0129APR\V2\Ceinture\No Team Assigned\2019_03_14-09_42_22\2019_03_14-09_42_22_BB_RR.csv,LPC,Réduction de la menace
48,0131CPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LNSC\DESHAYES\DESHAYES\DATA_Aging\0131CPS\V2\Ceinture\2019_12_09-10_03_43\2019_12_09-10_03_43_BB_RR.csv,LPC,Standard
49,0132GAR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0132GAR\V2\Ceinture\2020_02_19-09_57_21\2020_02_19-09_57_21_BB_RR.csv,LPC,Réduction de la menace
50,0133BPS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0133BPS-0157BPS\V2\Ceinture\No Team Assigned\2020_02_26-10_04_01\2020_02_26-10_04_01_BB_RR.csv,LPC,Standard
51,0134IFR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0134IFR\V2\ceinture\No Team Assigned\2020_03_03-09_35_14\2020_03_03-09_35_14_BB_RR.csv,LPC,Réduction de la menace
52,0135KLS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0135KLS\0135KLS_0163KLS_V2\ceinture\No Team Assigned\2021_03_03-08_43_04\2021_03_03-08_43_04_BB_RR.csv,LPC,Standard
53,0136CJR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0136CJR\0136CJR-V2\CEINTURE\No Team Assigned\2021_04_02-09_00_53\2021_04_02-09_00_53_BB_RR.csv,LPC,Réduction de la menace
54,0137BMS,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0137BMS-V2\CEINTURE\No Team Assigned\2021_04_12-09_58_17\2021_04_12-09_58_17_BB_RR (1).csv,LPC,Standard
55,0138NWR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0138NWR\0138NWR-V2\ceinture\No Team Assigned\2021_06_02-10_11_00\2021_06_02-10_11_00_BB_RR.csv,LPC,Réduction de la menace
56,0140LMR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0168LMR 0140LMR\V2 0140LMR\CEINTURE\No Team Assigned\2022_01_13-09_40_17\2022_01_13-09_40_17_BB_RR.csv,LPC,Réduction de la menace
57,0143EBR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0171EBR _ 0143EBR\0143EBR V2\ceinture\No Team Assigned\2022_04_27-11_02_28\2022_04_27-11_02_28_BB_RR.csv,LPC,Réduction de la menace
58,0144ZGR,C:\Users\judupont\Desktop\AGING_19_01_2026\LPC\GAUTHIER\GAUTHIER\PARTICIPANTS\participants_partie 2_labo\0144ZGR\0144ZGR_V2\ceinture\No Team Assigned\2022_06_29-10_04_46\2022_06_29-10_04_46_BB_RR.csv,LPC,Réduction de la menace
59,0301GNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0301GNR\ceinture\2019_01_16-10_11_49 0301GNR\2019_01_16-10_11_49_BB_RR.csv,CAEN,Réduction de la menace
60,0302ZMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0302ZMR\ceinture\2019_01_24-09_37_03 0302ZMR\2019_01_24-09_37_03_BB_RR.csv,CAEN,Réduction de la menace
61,0303PAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0303PAR\Ceinture\2019_03_14-09_58_28 0303PAR\2019_03_14-09_58_28_BB_RR.csv,CAEN,Réduction de la menace
62,0304VMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\fichiers ancien serveur\0304VMR\Ceinture\2019_03_25-09_49_47 0304VMR\2019_03_25-09_49_47_BB_RR.csv,CAEN,Réduction de la menace
63,0305LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_04_25-10_01_08 0305LCR\2019_04_25-10_01_08_BB_RR.csv,CAEN,Réduction de la menace
64,0306MDR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_05_06-14_17_53 0306MDR\2019_05_06-14_17_53_BB_RR.csv,CAEN,Réduction de la menace
65,0307SMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_05_13-10_23_50 0307SMR\2019_05_13-10_23_50_BB_RR (1).csv,CAEN,Réduction de la menace
66,0308RGR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_06_25-10_55_55 0308RGR\2019_06_25-10_55_55_BB_RR.csv,CAEN,Réduction de la menace
67,0309DBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_06_27-13_19_31 0309DBS\2019_06_27-13_19_31_BB_RR.csv,CAEN,Standard
68,0310ACS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_03-09_56_22 0310ACS\2019_07_03-09_56_22_BB_RR.csv,CAEN,Standard
69,0311CJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_03-13_38_29 0311CJS\2019_07_03-13_38_29_BB_RR.csv,CAEN,Standard
70,0312JMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_22-10_00_05 0312JMS\2019_07_22-10_00_05_BB_RR.csv,CAEN,Standard
71,0313FPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_07_23-14_27_14 0313FPR\2019_07_23-14_27_14_BB_RR.csv,CAEN,Réduction de la menace
72,0315VCS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_08_29-09_50_18 0315VCS\2019_08_29-09_50_18_BB_RR (1).csv,CAEN,Standard
73,0316TMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_03-09_46_13 0316TMS\2019_09_03-09_46_13_BB_RR (1).csv,CAEN,Standard
74,0317LGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_05-09_39_02 0317LGS\2019_09_05-09_39_02_BB_RR (1).csv,CAEN,Standard
75,0318PMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_06-10_21_56 0318PMS\2019_09_06-10_21_56_BB_RR (1).csv,CAEN,Standard
76,0319LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_09_24-10_11_52 0319LJS\2019_09_24-10_11_52_BB_RR (1).csv,CAEN,Standard
77,0320DGS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_01-10_20_37 0320DGS\2019_10_01-10_20_37_BB_RR.csv,CAEN,Standard
78,0321DRR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_10_08-10_34_34 0321DRR\2019_10_08-10_34_34_BB_RR.csv,CAEN,Réduction de la menace
79,0323RFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_08_27_09_25_18 0323RFS\2020_08_27__09_25_18_BR_RR.csv,CAEN,Standard
80,0325LCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_15-10_23_10 0325LCR\2019_11_15-10_23_10_BB_RR (1).csv,CAEN,Réduction de la menace
81,0326BJR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_22-10_00_52 0326BJR\2019_11_22-10_00_52_BB_RR.csv,CAEN,Réduction de la menace
82,0327IAR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_11_25-09_56_16 0327IAR\2019_11_25-09_56_16_BB_RR.csv,CAEN,Réduction de la menace
83,0328MPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2019_12_05-09_47_22 0328MPR\2019_12_05-09_47_22_BB_RR.csv,CAEN,Réduction de la menace
84,0329NMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_28-09_53_10 0329NMR\2020_01_28-09_53_10_BB_RR.csv,CAEN,Réduction de la menace
85,0330RTR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_01_31-09_46_05 0330RTR\2020_01_31-09_46_05_BB_RR.csv,CAEN,Réduction de la menace
86,0331GRS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_02_11-14_54_58 0331GRS\2020_02_11-14_54_58_BB_RR.csv,CAEN,Standard
87,0332MCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_03_06-09_57_45 0332MCR\2020_03_06-09_57_45_BB_RR (1).csv,CAEN,Réduction de la menace
88,0333MMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_09_25_09_39_30 0333MMS\2020_09_25__09_39_30_BR_RR.csv,CAEN,Standard
89,0334TVS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_01_09_40_22_0334TVS\2020_10_01__09_40_22_BR_RR.csv,CAEN,Standard
90,0336CBS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_10_16_09_43_10 0336CBS\2020_10_16__09_43_10_BR_RR.csv,CAEN,Standard
91,0337BFS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2020_11_24_09_24_38 0337BFS\2020_11_24__09_24_38_BR_RR.csv,CAEN,Standard
92,0339NPR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_02_25_09_34_13 0339PNR\2021_02_25__09_34_13_BR_RR.csv,CAEN,Réduction de la menace
93,0341LJS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_05_17_09_42_15 0341LJS\2021_05_17__09_42_15_BR_RR.csv,CAEN,Standard
94,0342VNS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_01_09_36_33 0342VNS\2021_06_01__09_36_33_BR_RR.csv,CAEN,Standard
95,0343PAS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2021_06_08_09_37_22 0343PAS\2021_06_08__09_37_22_BR_RR.csv,CAEN,Standard
96,0346GLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_01_28_09_25_45 0346GLS\2022_01_28__09_25_45_BR_RR.csv,CAEN,Standard
97,0347DMR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_01_31_10_04_24 0347DMR\2022_01_31__10_04_24_BR_RR.csv,CAEN,Réduction de la menace
98,0348GCR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_01_10_21_15 0348GCR\2022_02_01__10_21_15_BR_RR.csv,CAEN,Réduction de la menace
99,0349LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_02_21_09_57_05 0349LLS\2022_02_21__09_57_05_BR_RR.csv,CAEN,Standard
100,0350MYR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_18_09_47_48 0350MYR\2022_03_18__09_47_48_BR_RR.csv,CAEN,Réduction de la menace
101,0351FIR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_03_25_10_02_19 0351FIR\2022_03_25__10_02_19_BR_RR.csv,CAEN,Réduction de la menace
102,0352RNR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_04_15_10_01_17 0352RNR\2022_04_15__10_01_17_BR_RR.csv,CAEN,Réduction de la menace
103,0354GKR,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_06_27_09_30_41 0354GKR\2022_06_27__09_30_41_BR_RR.csv,CAEN,Réduction de la menace
104,0355BAS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_06_30_09_43_08 0355BAS\2022_06_30__09_43_08_BR_RR.csv,CAEN,Standard
105,0356DMS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-CAEN\ALLAIN\ALLAIN\CEINTURE\2022_09_22_09_44_11 0356DMS\2022_09_22__09_44_11_BR_RR.csv,CAEN,Standard
106,0401TSS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0401 TS\0401TSS - V2\0401TSS ceinture\No Team Assigned\2019_04_05-09_52_46\2019_04_05-09_52_46_BB_RR.csv,POITIERS,Standard
107,0402LLS,C:\Users\judupont\Desktop\AGING_19_01_2026\CHU-POITIERS\MARTIN DE MONTAUDRY\MARTIN DE MONTAUDRY\0402 LL\0402LLS- V2\0402LLS- ceinture\No Team Assigned\2019_04_12-11_01_28\2019_04_12-11_01_28_BB_RR.csv,POITIERS,Standard

In [27]:
# CONSERVATION DES FEUILLES ET CONDITIONS DANS UN FICHIER TXT 

chemin_txt = r"C:\Users\judupont\Desktop\df_global.txt"

df_global.to_csv(
    chemin_txt,
    sep="\t",
    index=False,
    encoding="utf-8-sig"
)

print(f"📄 df_global sauvegardé : {chemin_txt}")

📄 df_global sauvegardé : C:\Users\judupont\Desktop\df_global.txt

# Verification que le temps d'experience et le temps du fichier BB_RR correspondent : offset

In [28]:
def convertir_heure_en_secondes(x):
    if pd.isna(x):
        return None

    if isinstance(x, (int, float)):
        seconds = float(x) * 24 * 3600
        return seconds % (24 * 3600)

    try:
        t = pd.to_datetime(str(x).strip()).time()
        return t.hour * 3600 + t.minute * 60 + t.second
    except Exception:
        return None


# ===== NORMALISATION GLOBALE =====
df_global["Numero_inclusion"] = (
    df_global["Numero_inclusion"]
    .astype(str)
    .str.strip()
    .str.upper()
)

set_global = set(df_global["Numero_inclusion"])


dfs_excel = []

for feuille, data in resultats_bloc1.items():

    df_excel = data["df"].copy()

    # ===== NORMALISATION DES NOMS =====
    df_excel["Numero_inclusion"] = (
        df_excel["Numero_inclusion"]
        .astype(str)
        .str.strip()
        .str.upper()
    )

    df_excel = df_excel[
        df_excel["Numero_inclusion"].isin(set_global)
    ]

    if df_excel.empty:
        continue

    # ===== Conversion heures =====
    df_excel["heure_debut_sec"] = df_excel["heure_ceinture_v2"].apply(convertir_heure_en_secondes)
    df_excel["heure_fin_sec"] = df_excel["heure_fin_tests_v2"].apply(convertir_heure_en_secondes)

    # ===== Calcul de la durée de la visite =====
    df_excel["duree_experience_sec"] = (
        df_excel["heure_fin_sec"] - df_excel["heure_debut_sec"]
    )

    df_excel.loc[
        df_excel["duree_experience_sec"] < 0,
        "duree_experience_sec"
    ] += 24 * 3600

    df_excel["Feuille"] = feuille
    dfs_excel.append(df_excel)


if dfs_excel:
    df_excel_global = pd.concat(dfs_excel, ignore_index=True)
else:
    df_excel_global = pd.DataFrame()
    
print(f"Lignes Excel retenues : {len(df_excel_global)}")
display(df_excel_global[[
    "Numero_inclusion",
    "Feuille",
    "duree_experience_sec"
]])

Lignes Excel retenues : 156

    Numero_inclusion            Feuille  duree_experience_sec
0            0101CAR               APHM                  9480
1            0102PCR               APHM                  7620
2            0103SHS               APHM                  5580
3            0105PNR               APHM                  7260
4            0104FJS               APHM                  9720
5            0106JLS               APHM                  7560
6            0107DSS               APHM                  7260
7            0108BFS               APHM                  7920
8            0109GSS               APHM                  7560
9            0110LPR               APHM                  8160
10           0111MNR               APHM                  7860
11           0112BSR               APHM                  9240
12           0113BMR               APHM                  7620
13           0114LMS               APHM                  6420
14           0115CJR               APHM                  6120
15           0116VAR               APHM                  8760
16           0117POS               APHM                  6660
17           0118TNS               APHM                  6780
18           0119LJS               APHM                  6600
19           0120LCR               APHM                  7500
20           0121MJR               APHM                  7080
21           0123RMS               APHM                  6960
22           0124BAR               APHM                  7380
23           0125BMR               APHM                  7920
24           0301GNR               CAEN                  7620
25           0302ZMR               CAEN                  6420
26           0303PAR               CAEN                  5820
27           0304VMR               CAEN                  7800
28           0305LCR               CAEN                  6480
29           0307SMR               CAEN                  7380
30           0306MDR               CAEN                  6420
31           0308RGR               CAEN                  6960
32           0309DBS               CAEN                  7680
33           0311CJS               CAEN                  7140
34           0310ACS               CAEN                  7620
35           0315VCS               CAEN                  6120
36           0318PMS               CAEN                  5400
37           0313FPR               CAEN                  6540
38           0312JMS               CAEN                  6300
39           0316TMS               CAEN                  5460
40           0317LGS               CAEN                  5580
41           0319LJS               CAEN                  5940
42           0320DGS               CAEN                  5160
43           0321DRR               CAEN                  5820
44           0323RFS               CAEN                  6000
45           0325LCR               CAEN                  6000
46           0327IAR               CAEN                  6240
47           0326BJR               CAEN                  6480
48           0328MPR               CAEN                  6480
49           0330RTR               CAEN                  6780
50           0329NMR               CAEN                  6900
51           0331GRS               CAEN                  5280
52           0332MCR               CAEN                  7260
53           0333MMS               CAEN                  5580
54           0334TVS               CAEN                  5400
55           0336CBS               CAEN                  7140
56           0337BFS               CAEN                  8880
57           0339NPR               CAEN                  6180
58           0341LJS               CAEN                  5760
59           0342VNS               CAEN                  6720
60           0343PAS               CAEN                  4980
61           0349LLS               CAEN                  6660
62           0347DMR               CAEN                  6480
63           0346GLS               CAEN                  5460
64           0348GCR               CAEN                  7140
65           0350MYR               CAEN                  6360
66           0351FIR               CAEN                  6480
67           0352RNR               CAEN                  5940
68           0354GKR               CAEN                  6600
69           0355BAS               CAEN                  6240
70           0356DMS               CAEN                  6060
71           0401TSS           POITIERS                  8640
72           0402LLS           POITIERS                  7440
73           0403DCR           POITIERS                  7620
74           0405FCR           POITIERS                  8640
75           0404CYS           POITIERS                  9300
76           0407LJR           POITIERS                  8580
77           0408BCS           POITIERS                  8160
78           0409PHR           POITIERS                  8700
79           0410PGS           POITIERS                  8400
80           0413HFS           POITIERS                  7800
81           0411VES           POITIERS                  7440
82           0412ANS           POITIERS                  7080
83           0415VMR           POITIERS                  6480
84           0502LIR              ROUEN                  7320
85           0504BCS              ROUEN                  6840
86           0505PPR              ROUEN                  7020
87           0506VMS              ROUEN                  7080
88           0508SRR              ROUEN                  6600
89           0507BDS              ROUEN                  7800
90           0509LGS              ROUEN                  7620
91           0510DFS              ROUEN                  6540
92           0511LCS              ROUEN                  7980
93           0512RCR              ROUEN                  6660
94           0513EBS              ROUEN                  6120
95           0515FAR              ROUEN                  6720
96           0626MCS            LAVERAN                  6540
97           0628DMR            LAVERAN                  7980
98           0630RJR            LAVERAN                  5520
99           0629TCR            LAVERAN                  8040
100          0631LHR            LAVERAN                  5820
101          0101EMS                LPC                  6240
102          0103BPS                LPC                  5160
103          0104IBS                LPC                  5640
104          0106DJR                LPC                  6600
105          0108MMS                LPC                  5400
106          0109MJR                LPC                  6480
107          0110RMS                LPC                  5580
108          0112DRR                LPC                  5460
109          0113DGR                LPC                  6420
110          0114MLR                LPC                  6960
111          0115MHR                LPC                  6660
112          0116CNR                LPC                  7140
113          0117MSR                LPC                  6900
114          0118TMS                LPC                  7080
115          0119BIR                LPC                  6240
116          0120ANS                LPC                  5700
117          0121RPS                LPC                  5520
118          0122VCR                LPC                  8100
119          0123GVS                LPC                  5040
120          0124PAS                LPC                  5280
121          0126VLR                LPC                  5880
122          0127CMS                LPC                  5400
123          0128ALS                LPC                  5820
124          0129APR                LPC                  8820
125          0131CPS                LPC                  5340
126          0132GAR                LPC                  5580
127          0133BPS                LPC                  5700
128          0134IFR                LPC                  5520
129          0135KLS                LPC                  5580
130          0136CJR                LPC                  5820
131          0137BMS                LPC                  6000
132          0138NWR                LPC                  6720
133          0140LMR                LPC                  7140
134          0143EBR                LPC                  7020
135          0144ZGR                LPC                  9000
136          0801HDR  SAINTE-MARGUERITE                  7500
137          0802LAS  SAINTE-MARGUERITE                  6840
138          0804GOR  SAINTE-MARGUERITE                  6420
139          0803DPS  SAINTE-MARGUERITE                  7800
140          0805BMS  SAINTE-MARGUERITE                  5640
141          0806KHS  SAINTE-MARGUERITE                  5760
142          0807OMR  SAINTE-MARGUERITE                  6180
143          0808PJR  SAINTE-MARGUERITE                  7020
144          0902SIS                CGD                  5040
145          0906DNR                CGD                  9900
146          0904KJS                CGD                  6180
147          0905SLR                CGD                  6720
148          0413MMR              CERCA                  6840
149          0414PVR              CERCA                  6840
150          0415HJS              CERCA                  5940
151          0417FAS              CERCA                  6300
152          0417KMS              CERCA                  6000
153          0418MPR              CERCA                  7320
154          0420MCR              CERCA                  7440
155          0421ACS              CERCA                  5520

In [29]:
# ==== Conversion Date dans Excel ====
df_excel_global["Date_v2_dt"] = pd.to_datetime(
    df_excel_global["Date_v2"], errors="coerce"
).dt.date

# ==== Candidats à ignorer pour la date (verifier à la main) ====
ignore_date_check = [
   "0403DCR", "0502LIR", "0507BDS", "0124BAR", "0125BMR", "0131CPS", "0414PVR"
]

rows_rr = []

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin = row["Chemin"]

    # ---- récupérer ligne Excel ----
    ligne_excel = df_excel_global[df_excel_global["Numero_inclusion"] == pid]
    if ligne_excel.empty:
        continue

    date_v2 = ligne_excel.iloc[0]["Date_v2_dt"]
    duree_excel_sec = ligne_excel.iloc[0]["duree_experience_sec"]

    # ---- lecture CSV BB_RR (ZIP ou non) ----
    try:
        if ".ZIP|" in chemin.upper():
            zip_path, inner_csv = chemin.split("|", 1)

            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_rr = pd.read_csv(f)

        else:
            df_rr = pd.read_csv(chemin)

    except Exception as e:
        print(f"⚠️ Lecture impossible RR pour {pid} : {e}")
        continue

    if "Timestamp" not in df_rr.columns:
        continue

    # ---- conversion timestamp CSV ----
    df_rr["Timestamp_dt"] = pd.to_datetime(
        df_rr["Timestamp"].astype(str).str.split(".").str[0],
        dayfirst=True,
        errors="coerce"
    )

    df_rr = df_rr.dropna(subset=["Timestamp_dt"])

    # ---- filtrage date ----
    if pid not in ignore_date_check and pd.notna(date_v2):
        df_rr = df_rr[df_rr["Timestamp_dt"].dt.date == date_v2]

    if df_rr.empty:
        continue

    # ---- durée RR ----
    t_min = df_rr["Timestamp_dt"].dt.floor("s").min()
    t_max = df_rr["Timestamp_dt"].dt.floor("s").max()
    duree_rr_sec = (t_max - t_min).total_seconds()

    rows_rr.append({
        "Numero_inclusion": pid,
        "duree_rr_sec": duree_rr_sec,
        "duree_excel_sec": duree_excel_sec,
        "nb_points": len(df_rr),
    })

df_rr_global = pd.DataFrame(rows_rr)

print(f"RR calculés : {len(df_rr_global)}")

display(df_rr_global)

RR calculés : 154

    Numero_inclusion  duree_rr_sec  duree_excel_sec  nb_points
0            0101CAR        9577.0             9480     171017
1            0101EMS        6311.0             6240     112696
2            0102PCR        7770.0             7620     138750
3            0103BPS        5227.0             5160      93339
4            0103SHS        5672.0             5580     101285
5            0104FJS        9913.0             9720     177017
6            0104IBS        5740.0             5640     102500
7            0105PNR        7475.0             7260     133482
8            0106DJR        6666.0             6600     119035
9            0106JLS        7691.0             7560     137339
10           0107DSS        7345.0             7260     131160
11           0108BFS        8092.0             7920     144500
12           0108MMS        6974.0             5400     124535
13           0109GSS        7872.0             7560     140571
14           0109MJR        6455.0             6480     115267
15           0110LPR        8296.0             8160     148142
16           0110RMS        5614.0             5580     100250
17           0111MNR        7978.0             7860     142464
18           0112BSR        9426.0             9240     168321
19           0112DRR        5472.0             5460      97714
20           0113BMR        7785.0             7620     139017
21           0113DGR        6472.0             6420     115571
22           0114LMS        6509.0             6420     116232
23           0114MLR        7079.0             6960     126410
24           0115CJR        6365.0             6120     113660
25           0115MHR        6694.0             6660     119535
26           0116CNR        7146.0             7140     127607
27           0116VAR        8813.0             8760     157375
28           0117MSR        6973.0             6900     124517
29           0117POS        6849.0             6660     122303
30           0118TMS        7121.0             7080     127160
31           0118TNS        6922.0             6780     123607
32           0119BIR        6234.0             6240     111321
33           0119LJS        6849.0             6600     122303
34           0120ANS        5761.0             5700     102875
35           0120LCR        7781.0             7500     138946
36           0121MJR        7369.0             7080     131589
37           0121RPS        5525.0             5520      98660
38           0122VCR        8317.0             8100     148517
39           0123GVS        5091.0             5040      90910
40           0123RMS        7194.0             6960     128464
41           0124BAR        7385.0             7380     131875
42           0124PAS        5321.0             5280      95017
43           0125BMR        8085.0             7920     144375
44           0126VLR        5884.0             5880     105071
45           0127CMS        5479.0             5400      97839
46           0128ALS        5903.0             5820     105410
47           0129APR        8904.0             8820     159000
48           0131CPS        5379.0             5340      96053
49           0132GAR        5758.0             5580     102821
50           0133BPS        5789.0             5700     103375
51           0134IFR        5590.0             5520      99821
52           0135KLS        5459.0             5580      97482
53           0136CJR        5859.0             5820     104625
54           0137BMS        6092.0             6000     108785
55           0138NWR        6779.0             6720     121053
56           0140LMR        7183.0             7140     128267
57           0143EBR        7176.0             7020     128142
58           0144ZGR        9064.0             9000     161857
59           0301GNR        8447.0             7620     150839
60           0302ZMR        6586.0             6420     117607
61           0303PAR        6018.0             5820     107464
62           0304VMR        8028.0             7800     143357
63           0305LCR        6990.0             6480     124821
64           0306MDR        6642.0             6420     118607
65           0307SMR        7668.0             7380     136928
66           0308RGR        7297.0             6960     130303
67           0309DBS        8006.0             7680     142964
68           0310ACS        7734.0             7620     138107
69           0311CJS        7392.0             7140     132000
70           0312JMS        6635.0             6300     118482
71           0313FPR        6677.0             6540     119232
72           0315VCS        6661.0             6120     118946
73           0316TMS        6071.0             5460     108410
74           0317LGS        6560.0             5580     117142
75           0318PMS        5823.0             5400     103982
76           0319LJS        6244.0             5940     111500
77           0320DGS        5414.0             5160      96678
78           0321DRR        6207.0             5820     110839
79           0325LCR        6800.0             6000     121428
80           0326BJR        6633.0             6480     118446
81           0327IAR        6801.0             6240     121446
82           0328MPR        7334.0             6480     130964
83           0329NMR        7589.0             6900     135517
84           0330RTR        7603.0             6780     135767
85           0331GRS        5625.0             5280     100446
86           0332MCR        8584.0             7260     153285
87           0333MMS        6587.0             5580     117625
88           0334TVS        5800.0             5400     103571
89           0336CBS        7926.0             7140     141535
90           0337BFS        9641.0             8880     172160
91           0339NPR        6748.0             6180     120500
92           0341LJS        6626.0             5760     118321
93           0342VNS        7199.0             6720     128553
94           0343PAS        5942.0             4980     106107
95           0346GLS        7925.0             5460     141517
96           0347DMR        7007.0             6480     125125
97           0348GCR        7401.0             7140     132160
98           0349LLS        7167.0             6660     127982
99           0350MYR        6946.0             6360     124035
100          0351FIR        8118.0             6480     144964
101          0352RNR        6440.0             5940     115000
102          0354GKR        8035.0             6600     143482
103          0355BAS        6942.0             6240     123964
104          0356DMS        6385.0             6060     114017
105          0401TSS        9384.0             8640     167571
106          0402LLS        9033.0             7440     161303
107          0403DCR        9355.0             7620     167053
108          0404CYS        9514.0             9300     169892
109          0405FCR        9679.0             8640     172839
110          0407LJR        9020.0             8580     161071
111          0408BCS        9903.0             8160     176839
112          0409PHR        9286.0             8700     165821
113          0410PGS        9817.0             8400     175303
114          0411VES        8857.0             7440     158160
115          0412ANS        7664.0             7080     136857
116          0413HFS        8419.0             7800     150339
117          0413MMR           5.0             6840         89
118          0414PVR        6821.0             6840     121803
119          0415HJS        6784.0             5940     121142
120          0415VMR        7152.0             6480     127714
121          0417FAS        7451.0             6300     133053
122          0417KMS        6876.0             6000     122785
123          0418MPR         100.0             7320       1785
124          0420MCR        7242.0             7440     129321
125          0421ACS        5614.0             5520     100250
126          0502LIR        8798.0             7320     157107
127          0504BCS        7842.0             6840     140035
128          0505PPR        7293.0             7020     130232
129          0506VMS        8456.0             7080     151000
130          0507BDS        9576.0             7800     171000
131          0508SRR        6887.0             6600     122982
132          0509LGS        8405.0             7620     150089
133          0510DFS        6753.0             6540     120589
134          0511LCS        8443.0             7980     150767
135          0512RCR        7229.0             6660     129089
136          0513EBS        6036.0             6120     107785
137          0626MCS        7003.0             6540     125053
138          0628DMR        8077.0             7980     144232
139          0629TCR        8187.0             8040     146196
140          0630RJR        5548.0             5520      99071
141          0631LHR        6307.0             5820     112625
142          0801HDR        7358.0             7500     131392
143          0802LAS           2.0             6840         35
144          0803DPS        7633.0             7800     136303
145          0804GOR        6689.0             6420     119446
146          0805BMS        5708.0             5640     101928
147          0806KHS        5943.0             5760     106125
148          0807OMR        6253.0             6180     111660
149          0808PJR        6975.0             7020     124553
150          0902SIS        5166.0             5040      92250
151          0904KJS        6242.0             6180     111464
152          0905SLR        6928.0             6720     123714
153          0906DNR        9914.0             9900     177035

In [30]:
excel_ids = set(df_excel_global["Numero_inclusion"])
rr_ids = set(df_rr_global["Numero_inclusion"])

manquants_dans_rr = excel_ids - rr_ids
manquants_dans_excel = rr_ids - excel_ids

print("Présents dans Excel mais pas dans RR :", manquants_dans_rr)
print("Présents dans RR mais pas dans Excel :", manquants_dans_excel)
print("Manquants dans RR :", sorted(excel_ids - rr_ids))
print("Manquants dans Excel :", sorted(rr_ids - excel_ids))

Présents dans Excel mais pas dans RR : {'0323RFS', '0515FAR'}
Présents dans RR mais pas dans Excel : set()
Manquants dans RR : ['0323RFS', '0515FAR']
Manquants dans Excel : []

# D'ou vient l'écart ? L'offest doit etre appliqué en debut, en fin, au milieu?

In [31]:
def sec_to_datetime(sec, date_ref):
    return datetime.combine(
        date_ref.date(),
        datetime.min.time()
    ) + timedelta(seconds=int(sec))

resultats_offset = []

# Ces candidats ont leur temps de début d'enregistrement décaler de pile 1h mais la durée de leur visite est la meme que celle de l'acquisiton
# donc on peut décaler artificiellement leur heure de début pour qu'elle soit identique a celle indiquée sur le Excel
candidats_rebase_excel = {
    "0136CJR",    
    "0341LJS",
    "0512RCR"
}

for _, row in df_global.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()
    chemin_bb_rr = row["Chemin"]

    # ===== Lecture BB_RR (ZIP ou non) =====
    try:
        if ".ZIP|" in chemin_bb_rr.upper():
            zip_path, inner_csv = chemin_bb_rr.split("|", 1)
            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_rr = pd.read_csv(f)
        else:
            df_rr = pd.read_csv(chemin_bb_rr)
    except Exception as e:
        print(f"⚠️ Lecture BB_RR impossible pour {pid} : {e}")
        continue

    if "Timestamp" not in df_rr.columns:
        continue

    # ===== Parsing timestamp =====
    df_rr["Timestamp"] = pd.to_datetime(
        df_rr["Timestamp"].astype(str).str.split(".").str[0],
        dayfirst=True,
        errors="coerce"
    )
    df_rr = df_rr.dropna(subset=["Timestamp"])
    if df_rr.empty:
        continue

    t_min = df_rr["Timestamp"].min()
    t_max = df_rr["Timestamp"].max()

    # ===== Excel =====
    ligne_excel = df_excel_global.loc[
        df_excel_global["Numero_inclusion"] == pid
    ]
    if ligne_excel.empty:
        continue

    duree_excel_sec = ligne_excel["duree_experience_sec"].values[0]
    if pd.isna(duree_excel_sec):
        continue

    # ===== Cas spécial : rebase Excel sur RR =====
    if pid in candidats_rebase_excel:
        h_debut = t_min
        h_fin = h_debut + pd.to_timedelta(duree_excel_sec, unit="s")
        mode = "REBASE_RR"
        # 🔹 delta_retard_sec pour info, même si rebase
        delta_retard_sec = 0
    else:
        h_debut_sec = ligne_excel["heure_debut_sec"].values[0]
        h_fin_sec = ligne_excel["heure_fin_sec"].values[0]
        if pd.isna(h_debut_sec) or pd.isna(h_fin_sec):
            continue

        h_debut = sec_to_datetime(h_debut_sec, t_min)
        h_fin   = sec_to_datetime(h_fin_sec, t_min)
        mode = "STANDARD"

        # 🔥 Calcul du delta retard sec comme pour les EDA
        delta_retard_sec = max((t_min - h_debut).total_seconds(), 0)

    # ===== Comptages =====
    nb_avant = (df_rr["Timestamp"] < h_debut).sum()
    nb_dans = ((df_rr["Timestamp"] >= h_debut) & (df_rr["Timestamp"] <= h_fin)).sum()
    nb_apres = (df_rr["Timestamp"] > h_fin).sum()
    total = len(df_rr)

    # ===== Diagnostic =====
    if nb_apres > nb_avant:
        origine = "FIN"
    elif nb_avant > nb_apres:
        origine = "DEBUT"
    else:
        origine = "MIXTE"

    resultats_offset.append({
        "Numero_inclusion": pid,
        "nb_total_points": total,
        "nb_avant_excel": nb_avant,
        "nb_dans_excel": nb_dans,
        "nb_apres_excel": nb_apres,
        "delta_retard_sec": delta_retard_sec  
    })

df_offset_bb_rr = pd.DataFrame(resultats_offset)

print(f"Offsets BB_RR calculés : {len(df_offset_bb_rr)}")
display(df_offset_bb_rr)

Offsets BB_RR calculés : 156

,Numero_inclusion,nb_total_points,nb_avant_excel,nb_dans_excel,nb_apres_excel,delta_retard_sec
0,0101CAR,171017,0,169189,1828,6.0
1,0101EMS,112696,0,110671,2025,43.0
2,0102PCR,138750,0,135993,2757,5.0
3,0103BPS,93339,0,91832,1507,18.0
4,0103SHS,101285,0,98600,2685,59.0
5,0104FJS,177017,0,172904,4113,38.0
6,0104IBS,102500,11,100732,1757,0.0
7,0105PNR,133482,0,129046,4436,34.0
8,0106DJR,119035,0,116261,2774,90.0
9,0106JLS,137339,0,134314,3025,39.0
10,0107DSS,131160,314,129661,1185,0.0
11,0108BFS,144500,1118,141446,1936,0.0
12,0108MMS,124535,0,95868,28667,32.0
13,0109GSS,140571,0,134422,6149,33.0
14,0109MJR,115267,0,115225,42,28.0
15,0110LPR,148142,0,145029,3113,39.0
16,0110RMS,100250,0,99332,918,18.0
17,0111MNR,142464,0,140011,2453,20.0
18,0112BSR,168321,0,164797,3524,12.0
19,0112DRR,97714,0,96779,935,41.0
20,0113BMR,139017,0,135850,3167,13.0
21,0113DGR,115571,100,114661,810,0.0
22,0114LMS,116232,0,114082,2150,32.0
23,0114MLR,126410,0,124279,2131,1.0
24,0115CJR,113660,743,109303,3614,0.0
25,0115MHR,119535,0,118439,1096,28.0
26,0116CNR,127607,0,127082,525,24.0
27,0116VAR,157375,0,155850,1525,33.0
28,0117MSR,124517,0,123100,1417,7.0
29,0117POS,122303,0,118868,3435,4.0
30,0118TMS,127160,0,125582,1578,48.0
31,0118TNS,123607,850,121089,1668,0.0
32,0119BIR,111321,0,110493,828,53.0
33,0119LJS,122303,0,117314,4989,31.0
34,0120ANS,102875,0,100850,2025,53.0
35,0120LCR,138946,0,133886,5060,3.0
36,0121MJR,131589,0,125761,5828,38.0
37,0121RPS,98660,0,97689,971,50.0
38,0122VCR,148517,0,144190,4327,26.0
39,0123GVS,90910,29,90018,863,0.0
40,0123RMS,128464,0,124243,4221,3.0
41,0124BAR,131875,0,131332,543,26.0
42,0124PAS,95017,0,94171,846,7.0
43,0125BMR,144375,0,140654,3721,44.0
44,0126VLR,105071,0,104225,846,44.0
45,0127CMS,97839,28,96447,1364,0.0
46,0128ALS,105410,0,103493,1917,25.0
47,0129APR,159000,0,157118,1882,22.0
48,0131CPS,96053,0,94600,1453,43.0
49,0132GAR,102821,0,99279,3542,21.0
50,0133BPS,103375,0,101779,1596,1.0
51,0134IFR,99821,0,98332,1489,14.0
52,0135KLS,97482,0,97482,0,64.0
53,0136CJR,104625,0,103940,685,0.0
54,0137BMS,108785,761,107161,863,0.0
55,0138NWR,121053,2136,118917,0,0.0
56,0140LMR,128267,0,127207,1060,17.0
57,0143EBR,128142,0,124868,3274,28.0
58,0144ZGR,161857,0,159904,1953,46.0
59,0301GNR,150839,0,133064,17775,169.0
60,0302ZMR,117607,0,114600,3007,3.0
61,0303PAR,107464,0,103439,4025,28.0
62,0304VMR,143357,0,137386,5971,107.0
63,0305LCR,124821,0,114511,10310,68.0
64,0306MDR,118607,0,112636,5971,113.0
65,0307SMR,136928,0,128760,8168,170.0
66,0308RGR,130303,0,122243,8060,115.0
67,0309DBS,142964,0,134458,8506,151.0
68,0310ACS,138107,0,132475,5632,202.0
69,0311CJS,132000,0,124850,7150,149.0
70,0312JMS,118482,0,110279,8203,125.0
71,0313FPR,119232,0,114404,4828,134.0
72,0315VCS,118946,0,108975,9971,18.0
73,0316TMS,108410,832,97518,10060,0.0
74,0317LGS,117142,0,99618,17524,2.0
75,0318PMS,103982,0,95439,8543,56.0
76,0319LJS,111500,0,105153,6347,52.0
77,0320DGS,96678,0,91493,5185,37.0
78,0321DRR,110839,458,103946,6435,0.0
79,0323RFS,103071,50028,53043,0,0.0
80,0325LCR,121428,0,106975,14453,10.0
81,0326BJR,118446,0,113725,4721,112.0
82,0327IAR,121446,0,110082,11364,76.0
83,0328MPR,130964,0,115332,15632,22.0
84,0329NMR,135517,0,121975,13542,70.0
85,0330RTR,135767,0,120993,14774,5.0
86,0331GRS,100446,0,93261,7185,58.0
87,0332MCR,153285,0,128850,24435,45.0
88,0333MMS,117625,0,98046,19579,90.0
89,0334TVS,103571,0,94975,8596,82.0
90,0336CBS,141535,0,126261,15274,70.0
91,0337BFS,172160,0,156831,15329,98.0
92,0339NPR,120500,0,106921,13579,193.0
93,0341LJS,118321,0,102868,15453,0.0
94,0342VNS,128553,0,119421,9132,33.0
95,0343PAS,106107,0,88546,17561,22.0
96,0346GLS,141517,0,95636,45881,105.0
97,0347DMR,125125,635,115732,8758,0.0
98,0348GCR,132160,0,127243,4917,15.0
99,0349LLS,127982,0,117778,10204,65.0
100,0350MYR,124035,0,112725,11310,48.0
101,0351FIR,144964,1796,115732,27436,0.0
102,0352RNR,115000,0,105778,9222,17.0
103,0354GKR,143482,0,116064,27418,101.0
104,0355BAS,123964,0,110225,13739,68.0
105,0356DMS,114017,867,108232,4918,0.0
106,0401TSS,167571,2386,154303,10882,0.0
107,0402LLS,161303,1636,132875,26792,0.0
108,0403DCR,167053,1850,136089,29114,0.0
109,0404CYS,169892,83,166089,3720,0.0
110,0405FCR,172839,1939,154304,16596,0.0
111,0407LJR,161071,2511,153232,5328,0.0
112,0408BCS,176839,1779,145732,29328,0.0
113,0409PHR,165821,2600,155375,7846,0.0
114,0410PGS,175303,2690,150017,22596,0.0
115,0411VES,158160,0,131636,26524,69.0
116,0412ANS,136857,207,126447,10203,0.0
117,0413HFS,150339,2082,139304,8953,0.0
118,0413MMR,89,89,0,0,0.0
119,0414PVR,121803,0,121404,399,42.0
120,0415HJS,121142,0,105850,15292,13.0
121,0415VMR,127714,0,115297,12417,24.0
122,0417FAS,133053,0,111154,21899,76.0
123,0417KMS,122785,0,106993,15792,9.0
124,0418MPR,1785,0,1785,0,23.0
125,0420MCR,129321,0,128118,1203,266.0
126,0421ACS,100250,0,98582,1668,0.0
127,0502LIR,157107,0,130565,26542,9.0
128,0504BCS,140035,1975,122161,15899,0.0
129,0505PPR,130232,0,125333,4899,2.0
130,0506VMS,151000,0,126261,24739,10.0
131,0507BDS,171000,0,138671,32329,35.0
132,0508SRR,122982,2225,117875,2882,0.0
133,0509LGS,150089,0,135832,14257,14.0
134,0510DFS,120589,243,116804,3542,0.0
135,0511LCS,150767,653,142518,7596,0.0
136,0512RCR,129089,0,118939,10150,0.0
137,0513EBS,107785,0,105564,2221,209.0
138,0515FAR,146785,146785,0,0,0.0
139,0626MCS,125053,0,115707,9346,61.0
140,0628DMR,144232,618,142518,1096,0.0
141,0629TCR,146196,0,143368,2828,12.0
142,0630RJR,99071,0,97939,1132,36.0
143,0631LHR,112625,154,103946,8525,0.0
144,0801HDR,131392,0,123939,7453,560.0
145,0802LAS,35,0,0,35,21745.0
146,0803DPS,136303,0,135296,1007,224.0
147,0804GOR,119446,2386,114660,2400,0.0
148,0805BMS,101928,0,100439,1489,16.0
149,0806KHS,106125,1475,102875,1775,0.0
150,0807OMR,111660,0,110047,1613,18.0
151,0808PJR,124553,0,121940,2613,192.0
152,0902SIS,92250,0,89761,2489,14.0
153,0904KJS,111464,0,109458,2006,51.0
154,0905SLR,123714,1172,120018,2524,0.0
155,0906DNR,177035,0,175136,1899,93.0

In [32]:
# ===== Dossier de sortie =====
desktop = Path.home() / "Desktop"
output_dir = desktop / "bb_rr_tronqués_v2"
output_dir.mkdir(exist_ok=True)

print(f"📁 Dossier de sortie : {output_dir}")

# ===== Boucle troncature =====
for _, row in df_offset_bb_rr.iterrows():

    pid = str(row["Numero_inclusion"]).strip().upper()

    # récupérer chemin BB_RR depuis df_global
    ligne_global = df_global[df_global["Numero_inclusion"] == pid]
    if ligne_global.empty:
        continue

    chemin_bb_rr = ligne_global.iloc[0]["Chemin"]

    nb_avant = int(row["nb_avant_excel"])
    nb_apres = int(row["nb_apres_excel"])

    # ===== Lecture BB_RR (ZIP ou non) =====
    try:
        if ".ZIP|" in chemin_bb_rr.upper():
            zip_path, inner_csv = chemin_bb_rr.split("|", 1)

            with zipfile.ZipFile(zip_path, "r") as z:
                with z.open(inner_csv) as f:
                    df_rr = pd.read_csv(f)
        else:
            df_rr = pd.read_csv(chemin_bb_rr)

    except Exception as e:
        print(f"❌ Lecture impossible {pid}: {e}")
        continue

    total = len(df_rr)

    # ===== Indices de coupe =====
    start = nb_avant
    end = total - nb_apres

    if start >= end:
        print(f"⚠️ Troncature invalide pour {pid} (start={start}, end={end})")
        continue

    df_rr_trunc = df_rr.iloc[start:end].reset_index(drop=True)

    if df_rr_trunc.empty:
        print(f"⚠️ {pid} → fichier vide après troncature")
        continue

    # ===== Nom fichier de sortie =====
    if ".ZIP|" in chemin_bb_rr.upper():
        nom_base = Path(inner_csv).name
    else:
        nom_base = Path(chemin_bb_rr).name

    nom_fichier = f"offset_{pid}_{nom_base}"
    path_sortie = output_dir / nom_fichier

    # ===== Sauvegarde =====
    df_rr_trunc.to_csv(path_sortie, index=False)

    print(
        f"✅ {pid} | "
        f"avant={nb_avant}, après={nb_apres} | "
        f"{len(df_rr_trunc)} lignes → {path_sortie.name}"
    )

print("🎯 Troncature terminée")

📁 Dossier de sortie : C:\Users\judupont\Desktop\bb_rr_tronqués_v2
✅ 0101CAR | avant=0, après=1828 | 169189 lignes → offset_0101CAR_2018_07_06-08_24_06_BB_RR.csv
✅ 0101EMS | avant=0, après=2025 | 110671 lignes → offset_0101EMS_2019_01_22-10_10_43_BB_RR.csv
✅ 0102PCR | avant=0, après=2757 | 135993 lignes → offset_0102PCR_2018_07_09-08_57_05_BB_RR.csv
✅ 0103BPS | avant=0, après=1507 | 91832 lignes → offset_0103BPS_2018_12_11-10_08_18_BB_RR.csv
✅ 0103SHS | avant=0, après=2685 | 98600 lignes → offset_0103SHS_2018_09_10-09_03_59_BB_RR.csv
✅ 0104FJS | avant=0, après=4113 | 172904 lignes → offset_0104FJS_2018_11_29-08_27_38_BB_RR.csv
✅ 0104IBS | avant=11, après=1757 | 100732 lignes → offset_0104IBS_2018_11_28-09_57_59_BB_RR.csv
✅ 0105PNR | avant=0, après=4436 | 129046 lignes → offset_0105PNR_2018_12_10-08_23_34_BB_RR.csv
✅ 0106DJR | avant=0, après=2774 | 116261 lignes → offset_0106DJR_2018_12_19-10_05_30_BB_RR.csv
✅ 0106JLS | avant=0, après=3025 | 134314 lignes → offset_0106JLS_2019_01_03-08_25_39_BB_RR.csv
✅ 0107DSS | avant=314, après=1185 | 129661 lignes → offset_0107DSS_2019_01_14-08_24_42_BB_RR.csv
✅ 0108BFS | avant=1118, après=1936 | 141446 lignes → offset_0108BFS_2019_01_17-08_42_57_BB_RR.csv
✅ 0108MMS | avant=0, après=28667 | 95868 lignes → offset_0108MMS_2019_01_24-09_57_32_BB_RR.csv
✅ 0109GSS | avant=0, après=6149 | 134422 lignes → offset_0109GSS_2019_02_18-08_56_33_BB_RR.csv
✅ 0109MJR | avant=0, après=42 | 115225 lignes → offset_0109MJR_2018_12_13-09_37_28_BB_RR.csv
✅ 0110LPR | avant=0, après=3113 | 145029 lignes → offset_0110LPR_2019_02_26-08_44_39_BB_RR.csv
✅ 0110RMS | avant=0, après=918 | 99332 lignes → offset_0110RMS_2018_12_14-09_38_18_BB_RR.csv
✅ 0111MNR | avant=0, après=2453 | 140011 lignes → offset_0111MNR_2019_02_28-08_59_20_BB_RR.csv
✅ 0112BSR | avant=0, après=3524 | 164797 lignes → offset_0112BSR_2019_06_06-08_27_12_BB_RR.csv
✅ 0112DRR | avant=0, après=935 | 96779 lignes → offset_0112DRR_2019_02_06-09_34_41_BB_RR.csv
✅ 0113BMR | avant=0, après=3167 | 135850 lignes → offset_0113BMR_2019_06_20-08_19_13_BB_RR.csv
✅ 0113DGR | avant=100, après=810 | 114661 lignes → offset_0113DGR_2018_11_27-09_37_54_BB_RR.csv
✅ 0114LMS | avant=0, après=2150 | 114082 lignes → offset_0114LMS_2019_06_27-08_36_32_BB_RR.csv
✅ 0114MLR | avant=0, après=2131 | 124279 lignes → offset_0114MLR_2019_01_07-09_59_01_BB_RR.csv
✅ 0115CJR | avant=743, après=3614 | 109303 lignes → offset_0115CJR_2019_08_27-08_25_18_BB_RR.csv
✅ 0115MHR | avant=0, après=1096 | 118439 lignes → offset_0115MHR_2019_01_11-09_39_28_BB_RR.csv
✅ 0116CNR | avant=0, après=525 | 127082 lignes → offset_0116CNR_2019_01_10-09_44_24_BB_RR.csv
✅ 0116VAR | avant=0, après=1525 | 155850 lignes → offset_0116VAR_2019_08_29-08_35_33_BB_RR.csv
✅ 0117MSR | avant=0, après=1417 | 123100 lignes → offset_0117MSR_2019_01_14-09_44_07_BB_RR.csv
✅ 0117POS | avant=0, après=3435 | 118868 lignes → offset_0117POS_2019_09_05-08_21_04_BB_RR.csv
✅ 0118TMS | avant=0, après=1578 | 125582 lignes → offset_0118TMS_2019_01_16-09_38_48_BB_RR.csv
✅ 0118TNS | avant=850, après=1668 | 121089 lignes → offset_0118TNS_2019_10_01-08_36_12_BB_RR.csv
✅ 0119BIR | avant=0, après=828 | 110493 lignes → offset_0119BIR_2019_01_28-09_32_53_BB_RR.csv
✅ 0119LJS | avant=0, après=4989 | 117314 lignes → offset_0119LJS_2019_11_07-08_37_31_BB_RR.csv
✅ 0120ANS | avant=0, après=2025 | 100850 lignes → offset_0120ANS_2019_02_04-09_42_53_BB_RR.csv
✅ 0120LCR | avant=0, après=5060 | 133886 lignes → offset_0120LCR_2019_12_06-08_25_03_BB_RR.csv
✅ 0121MJR | avant=0, après=5828 | 125761 lignes → offset_0121MJR_2019_12_12-09_01_38_BB_RR.csv
✅ 0121RPS | avant=0, après=971 | 97689 lignes → offset_0121RPS_2019_01_23-09_26_50_BB_RR.csv
✅ 0122VCR | avant=0, après=4327 | 144190 lignes → offset_0122VCR_2019_02_01-09_34_26_BB_RR.csv
✅ 0123GVS | avant=29, après=863 | 90018 lignes → offset_0123GVS_2019_02_08-09_25_58_BB_RR.csv
✅ 0123RMS | avant=0, après=4221 | 124243 lignes → offset_0123RMS_2019_12_20-08_35_03_BB_RR.csv
✅ 0124BAR | avant=0, après=543 | 131332 lignes → offset_0124BAR_2020_01_07-09_42_26_BB_RR.csv
✅ 0124PAS | avant=0, après=846 | 94171 lignes → offset_0124PAS_2019_02_15-10_26_07_BB_RR.csv
✅ 0125BMR | avant=0, après=3721 | 140654 lignes → offset_0125BMR_2020_01_14-11_26_44_BB_RR.csv
✅ 0126VLR | avant=0, après=846 | 104225 lignes → offset_0126VLR_2019_03_08-09_35_44_BB_RR.csv
✅ 0127CMS | avant=28, après=1364 | 96447 lignes → offset_0127CMS_2019_02_21-09_34_58_BB_RR.csv
✅ 0128ALS | avant=0, après=1917 | 103493 lignes → offset_0128ALS_2019_03_13-09_40_25_BB_RR.csv
✅ 0129APR | avant=0, après=1882 | 157118 lignes → offset_0129APR_2019_03_14-09_42_22_BB_RR.csv
✅ 0131CPS | avant=0, après=1453 | 94600 lignes → offset_0131CPS_2019_12_09-10_03_43_BB_RR.csv
✅ 0132GAR | avant=0, après=3542 | 99279 lignes → offset_0132GAR_2020_02_19-09_57_21_BB_RR.csv
✅ 0133BPS | avant=0, après=1596 | 101779 lignes → offset_0133BPS_2020_02_26-10_04_01_BB_RR.csv
✅ 0134IFR | avant=0, après=1489 | 98332 lignes → offset_0134IFR_2020_03_03-09_35_14_BB_RR.csv
✅ 0135KLS | avant=0, après=0 | 97482 lignes → offset_0135KLS_2021_03_03-08_43_04_BB_RR.csv
✅ 0136CJR | avant=0, après=685 | 103940 lignes → offset_0136CJR_2021_04_02-09_00_53_BB_RR.csv
✅ 0137BMS | avant=761, après=863 | 107161 lignes → offset_0137BMS_2021_04_12-09_58_17_BB_RR (1).csv
✅ 0138NWR | avant=2136, après=0 | 118917 lignes → offset_0138NWR_2021_06_02-10_11_00_BB_RR.csv
✅ 0140LMR | avant=0, après=1060 | 127207 lignes → offset_0140LMR_2022_01_13-09_40_17_BB_RR.csv
✅ 0143EBR | avant=0, après=3274 | 124868 lignes → offset_0143EBR_2022_04_27-11_02_28_BB_RR.csv
✅ 0144ZGR | avant=0, après=1953 | 159904 lignes → offset_0144ZGR_2022_06_29-10_04_46_BB_RR.csv
✅ 0301GNR | avant=0, après=17775 | 133064 lignes → offset_0301GNR_2019_01_16-10_11_49_BB_RR.csv
✅ 0302ZMR | avant=0, après=3007 | 114600 lignes → offset_0302ZMR_2019_01_24-09_37_03_BB_RR.csv
✅ 0303PAR | avant=0, après=4025 | 103439 lignes → offset_0303PAR_2019_03_14-09_58_28_BB_RR.csv
✅ 0304VMR | avant=0, après=5971 | 137386 lignes → offset_0304VMR_2019_03_25-09_49_47_BB_RR.csv
✅ 0305LCR | avant=0, après=10310 | 114511 lignes → offset_0305LCR_2019_04_25-10_01_08_BB_RR.csv
✅ 0306MDR | avant=0, après=5971 | 112636 lignes → offset_0306MDR_2019_05_06-14_17_53_BB_RR.csv
✅ 0307SMR | avant=0, après=8168 | 128760 lignes → offset_0307SMR_2019_05_13-10_23_50_BB_RR (1).csv
✅ 0308RGR | avant=0, après=8060 | 122243 lignes → offset_0308RGR_2019_06_25-10_55_55_BB_RR.csv
✅ 0309DBS | avant=0, après=8506 | 134458 lignes → offset_0309DBS_2019_06_27-13_19_31_BB_RR.csv
✅ 0310ACS | avant=0, après=5632 | 132475 lignes → offset_0310ACS_2019_07_03-09_56_22_BB_RR.csv
✅ 0311CJS | avant=0, après=7150 | 124850 lignes → offset_0311CJS_2019_07_03-13_38_29_BB_RR.csv
✅ 0312JMS | avant=0, après=8203 | 110279 lignes → offset_0312JMS_2019_07_22-10_00_05_BB_RR.csv
✅ 0313FPR | avant=0, après=4828 | 114404 lignes → offset_0313FPR_2019_07_23-14_27_14_BB_RR.csv
✅ 0315VCS | avant=0, après=9971 | 108975 lignes → offset_0315VCS_2019_08_29-09_50_18_BB_RR (1).csv
✅ 0316TMS | avant=832, après=10060 | 97518 lignes → offset_0316TMS_2019_09_03-09_46_13_BB_RR (1).csv
✅ 0317LGS | avant=0, après=17524 | 99618 lignes → offset_0317LGS_2019_09_05-09_39_02_BB_RR (1).csv
✅ 0318PMS | avant=0, après=8543 | 95439 lignes → offset_0318PMS_2019_09_06-10_21_56_BB_RR (1).csv
✅ 0319LJS | avant=0, après=6347 | 105153 lignes → offset_0319LJS_2019_09_24-10_11_52_BB_RR (1).csv
✅ 0320DGS | avant=0, après=5185 | 91493 lignes → offset_0320DGS_2019_10_01-10_20_37_BB_RR.csv
✅ 0321DRR | avant=458, après=6435 | 103946 lignes → offset_0321DRR_2019_10_08-10_34_34_BB_RR.csv
✅ 0323RFS | avant=50028, après=0 | 53043 lignes → offset_0323RFS_2020_08_27__09_25_18_BR_RR.csv
✅ 0325LCR | avant=0, après=14453 | 106975 lignes → offset_0325LCR_2019_11_15-10_23_10_BB_RR (1).csv
✅ 0326BJR | avant=0, après=4721 | 113725 lignes → offset_0326BJR_2019_11_22-10_00_52_BB_RR.csv
✅ 0327IAR | avant=0, après=11364 | 110082 lignes → offset_0327IAR_2019_11_25-09_56_16_BB_RR.csv
✅ 0328MPR | avant=0, après=15632 | 115332 lignes → offset_0328MPR_2019_12_05-09_47_22_BB_RR.csv
✅ 0329NMR | avant=0, après=13542 | 121975 lignes → offset_0329NMR_2020_01_28-09_53_10_BB_RR.csv
✅ 0330RTR | avant=0, après=14774 | 120993 lignes → offset_0330RTR_2020_01_31-09_46_05_BB_RR.csv
✅ 0331GRS | avant=0, après=7185 | 93261 lignes → offset_0331GRS_2020_02_11-14_54_58_BB_RR.csv
✅ 0332MCR | avant=0, après=24435 | 128850 lignes → offset_0332MCR_2020_03_06-09_57_45_BB_RR (1).csv
✅ 0333MMS | avant=0, après=19579 | 98046 lignes → offset_0333MMS_2020_09_25__09_39_30_BR_RR.csv
✅ 0334TVS | avant=0, après=8596 | 94975 lignes → offset_0334TVS_2020_10_01__09_40_22_BR_RR.csv
✅ 0336CBS | avant=0, après=15274 | 126261 lignes → offset_0336CBS_2020_10_16__09_43_10_BR_RR.csv
✅ 0337BFS | avant=0, après=15329 | 156831 lignes → offset_0337BFS_2020_11_24__09_24_38_BR_RR.csv
✅ 0339NPR | avant=0, après=13579 | 106921 lignes → offset_0339NPR_2021_02_25__09_34_13_BR_RR.csv
✅ 0341LJS | avant=0, après=15453 | 102868 lignes → offset_0341LJS_2021_05_17__09_42_15_BR_RR.csv
✅ 0342VNS | avant=0, après=9132 | 119421 lignes → offset_0342VNS_2021_06_01__09_36_33_BR_RR.csv
✅ 0343PAS | avant=0, après=17561 | 88546 lignes → offset_0343PAS_2021_06_08__09_37_22_BR_RR.csv
✅ 0346GLS | avant=0, après=45881 | 95636 lignes → offset_0346GLS_2022_01_28__09_25_45_BR_RR.csv
✅ 0347DMR | avant=635, après=8758 | 115732 lignes → offset_0347DMR_2022_01_31__10_04_24_BR_RR.csv
✅ 0348GCR | avant=0, après=4917 | 127243 lignes → offset_0348GCR_2022_02_01__10_21_15_BR_RR.csv
✅ 0349LLS | avant=0, après=10204 | 117778 lignes → offset_0349LLS_2022_02_21__09_57_05_BR_RR.csv
✅ 0350MYR | avant=0, après=11310 | 112725 lignes → offset_0350MYR_2022_03_18__09_47_48_BR_RR.csv
✅ 0351FIR | avant=1796, après=27436 | 115732 lignes → offset_0351FIR_2022_03_25__10_02_19_BR_RR.csv
✅ 0352RNR | avant=0, après=9222 | 105778 lignes → offset_0352RNR_2022_04_15__10_01_17_BR_RR.csv
✅ 0354GKR | avant=0, après=27418 | 116064 lignes → offset_0354GKR_2022_06_27__09_30_41_BR_RR.csv
✅ 0355BAS | avant=0, après=13739 | 110225 lignes → offset_0355BAS_2022_06_30__09_43_08_BR_RR.csv
✅ 0356DMS | avant=867, après=4918 | 108232 lignes → offset_0356DMS_2022_09_22__09_44_11_BR_RR.csv
✅ 0401TSS | avant=2386, après=10882 | 154303 lignes → offset_0401TSS_2019_04_05-09_52_46_BB_RR.csv
✅ 0402LLS | avant=1636, après=26792 | 132875 lignes → offset_0402LLS_2019_04_12-11_01_28_BB_RR.csv
✅ 0403DCR | avant=1850, après=29114 | 136089 lignes → offset_0403DCR_2019_05_24-09_36_16_BB_RR.csv
✅ 0404CYS | avant=83, après=3720 | 166089 lignes → offset_0404CYS_2019_07_19-10_32_55_BB_RR.csv
✅ 0405FCR | avant=1939, après=16596 | 154304 lignes → offset_0405FCR_2019_07_04-09_33_11_BB_RR.csv
✅ 0407LJR | avant=2511, après=5328 | 153232 lignes → offset_0407LJR_2019_09_19-09_38_39_BB_RR.csv
✅ 0408BCS | avant=1779, après=29328 | 145732 lignes → offset_0408BCS_2019_11_22-09_28_20_BB_RR.csv
✅ 0409PHR | avant=2600, après=7846 | 155375 lignes → offset_0409PHR_2019_11_29-09_34_34_BB_RR.csv
✅ 0410PGS | avant=2690, après=22596 | 150017 lignes → offset_0410PGS_2020_01_09-10_03_29_BB_RR.csv
✅ 0411VES | avant=0, après=26524 | 131636 lignes → offset_0411VES_2020_02_20-09_42_09_BB_RR.csv
✅ 0412ANS | avant=207, après=10203 | 126447 lignes → offset_0412ANS_2020_02_21-13_33_48_BB_RR.csv
✅ 0413HFS | avant=2082, après=8953 | 139304 lignes → offset_0413HFS_2020_03_06-09_57_03_BB_RR.csv
⚠️ Troncature invalide pour 0413MMR (start=89, end=89)
✅ 0414PVR | avant=0, après=399 | 121404 lignes → offset_0414PVR_2020_01_07__09_15_42_BR_RR.csv
✅ 0415HJS | avant=0, après=15292 | 105850 lignes → offset_0415HJS_2020_02_11__09_43_13_BR_RR.csv
✅ 0415VMR | avant=0, après=12417 | 115297 lignes → offset_0415VMR_2020_10_02-09_44_24_BB_RR.csv
✅ 0417FAS | avant=0, après=21899 | 111154 lignes → offset_0417FAS_2020_02_12__10_41_16_BR_RR.csv
✅ 0417KMS | avant=0, après=15792 | 106993 lignes → offset_0417KMS_2022_11_24__09_03_09_BR_RR.csv
✅ 0418MPR | avant=0, après=0 | 1785 lignes → offset_0418MPR_2020_02_13__09_33_23_BR_RR.csv
✅ 0420MCR | avant=0, après=1203 | 128118 lignes → offset_0420MCR_2020_02_28__09_44_26_BR_RR.csv
✅ 0421ACS | avant=0, après=1668 | 98582 lignes → offset_0421ACS_2020_03_04__10_12_00_BR_RR.csv
✅ 0502LIR | avant=0, après=26542 | 130565 lignes → offset_0502LIR_2019_02_28-09_42_09_BB_RR.csv
✅ 0504BCS | avant=1975, après=15899 | 122161 lignes → offset_0504BCS_2019_04_23-09_59_09_BB_RR.csv
✅ 0505PPR | avant=0, après=4899 | 125333 lignes → offset_0505PPR_2019_05_23-09_48_02_BB_RR.csv
✅ 0506VMS | avant=0, après=24739 | 126261 lignes → offset_0506VMS_2019_05_27-09_37_10_BB_RR.csv
✅ 0507BDS | avant=0, après=32329 | 138671 lignes → offset_0507BDS_2019_06_24-09_49_35_BB_RR.csv
✅ 0508SRR | avant=2225, après=2882 | 117875 lignes → offset_0508SRR_2019_07_25-09_37_55_BB_RR.csv
✅ 0509LGS | avant=0, après=14257 | 135832 lignes → offset_0509LGS_2019_10_17-09_30_14_BB_RR.csv
✅ 0510DFS | avant=243, après=3542 | 116804 lignes → offset_0510DFS_2020_02_20-09_49_46_BB_RR.csv
✅ 0511LCS | avant=653, après=7596 | 142518 lignes → offset_0511LCS_2021_01_07-10_11_23_BB_RR.csv
✅ 0512RCR | avant=0, après=10150 | 118939 lignes → offset_0512RCR_Record 2_2021_05_04-08_47_59_BB_RR (1).csv
✅ 0513EBS | avant=0, après=2221 | 105564 lignes → offset_0513EBS_Record 1_2021_06_18-09_23_29_BB_RR.csv
⚠️ Troncature invalide pour 0515FAR (start=146785, end=146785)
✅ 0626MCS | avant=0, après=9346 | 115707 lignes → offset_0626MCS_2020_01_21-09_12_01_BB_RR.csv
✅ 0628DMR | avant=618, après=1096 | 142518 lignes → offset_0628DMR_2020_01_30-10_11_25_BB_RR.csv
✅ 0629TCR | avant=0, après=2828 | 143368 lignes → offset_0629TCR_2020_02_04-09_40_12_BB_RR.csv
✅ 0630RJR | avant=0, après=1132 | 97939 lignes → offset_0630RJR_2020_02_20-10_24_36_BB_RR.csv
✅ 0631LHR | avant=154, après=8525 | 103946 lignes → offset_0631LHR_2020_02_25-10_54_51_BB_RR.csv
✅ 0801HDR | avant=0, après=7453 | 123939 lignes → offset_0801HDR_2022_03_23-09_34_20_BB_RR.csv
⚠️ Troncature invalide pour 0802LAS (start=0, end=0)
✅ 0803DPS | avant=0, après=1007 | 135296 lignes → offset_0803DPS_2022_03_30-09_33_44_BB_RR.csv
✅ 0804GOR | avant=2386, après=2400 | 114660 lignes → offset_0804GOR_2022_04_13-09_22_46_BB_RR.csv
✅ 0805BMS | avant=0, après=1489 | 100439 lignes → offset_0805BMS_2022_04_15-10_15_16_BB_RR.csv
✅ 0806KHS | avant=1475, après=1775 | 102875 lignes → offset_0806KHS_2022_06_02-09_36_37_BB_RR.csv
✅ 0807OMR | avant=0, après=1613 | 110047 lignes → offset_0807OMR_2022_06_24-09_39_18_BB_RR.csv
✅ 0808PJR | avant=0, après=2613 | 121940 lignes → offset_0808PJR_2022_07_15-10_23_12_BB_RR.csv
✅ 0902SIS | avant=0, après=2489 | 89761 lignes → offset_0902SIS_2022_05_19-09_43_14_BB_RR.csv
✅ 0904KJS | avant=0, après=2006 | 109458 lignes → offset_0904KJS_2022_06_27-10_13_51_BB_RR.csv
✅ 0905SLR | avant=1172, après=2524 | 120018 lignes → offset_0905SLR_2022_07_04-10_05_54_BB_RR.csv
✅ 0906DNR | avant=0, après=1899 | 175136 lignes → offset_0906DNR_2022_07_06-10_13_33_BB_RR.csv
🎯 Troncature terminée

In [33]:
# ===== Paramètres =====
min_lignes = 70000
candidats_a_exclure = ["0323FRS", "0515FAR"]  # liste de candidats à exclure 0323 c'est la v4 et 0515 valerus abberantes 

dossier = Path.home() / "Desktop" / "bb_rr_tronqués_v2"
print(f"📂 Dossier analysé : {dossier}")

supprimes = []
conserves = []

for fichier in dossier.glob("*.csv"):
    nom = fichier.name

    # ===== Exclusion candidat spécifique =====
    if any(candidat in nom for candidat in candidats_a_exclure):
        fichier.unlink()
        supprimes.append((nom, "candidat exclu"))
        print(f"🗑️ {nom} → candidat exclu")
        continue

    # ===== Lecture rapide =====
    try:
        n_lignes = sum(1 for _ in open(fichier, "r", encoding="utf-8")) - 1
    except Exception as e:
        print(f"❌ Lecture impossible {nom}: {e}")
        continue

    # ===== Exclusion fichiers trop courts =====
    if n_lignes < min_lignes:
        fichier.unlink()
        supprimes.append((nom, f"{n_lignes} lignes"))
        print(f"❌ {nom} → trop petit ({n_lignes} lignes)")
    else:
        conserves.append((nom, n_lignes))
        print(f"✅ {nom} → conservé ({n_lignes} lignes)")

print("\n====== RÉSUMÉ ======")
print(f"Fichiers supprimés : {len(supprimes)}")
print(f"Fichiers conservés : {len(conserves)}")

📂 Dossier analysé : C:\Users\judupont\Desktop\bb_rr_tronqués_v2
✅ offset_0101CAR_2018_07_06-08_24_06_BB_RR.csv → conservé (169189 lignes)
✅ offset_0101EMS_2019_01_22-10_10_43_BB_RR.csv → conservé (110671 lignes)
✅ offset_0102PCR_2018_07_09-08_57_05_BB_RR.csv → conservé (135993 lignes)
✅ offset_0103BPS_2018_12_11-10_08_18_BB_RR.csv → conservé (91832 lignes)
✅ offset_0103SHS_2018_09_10-09_03_59_BB_RR.csv → conservé (98600 lignes)
✅ offset_0104FJS_2018_11_29-08_27_38_BB_RR.csv → conservé (172904 lignes)
✅ offset_0104IBS_2018_11_28-09_57_59_BB_RR.csv → conservé (100732 lignes)
✅ offset_0105PNR_2018_12_10-08_23_34_BB_RR.csv → conservé (129046 lignes)
✅ offset_0106DJR_2018_12_19-10_05_30_BB_RR.csv → conservé (116261 lignes)
✅ offset_0106JLS_2019_01_03-08_25_39_BB_RR.csv → conservé (134314 lignes)
✅ offset_0107DSS_2019_01_14-08_24_42_BB_RR.csv → conservé (129661 lignes)
✅ offset_0108BFS_2019_01_17-08_42_57_BB_RR.csv → conservé (141446 lignes)
✅ offset_0108MMS_2019_01_24-09_57_32_BB_RR.csv → conservé (95868 lignes)
✅ offset_0109GSS_2019_02_18-08_56_33_BB_RR.csv → conservé (134422 lignes)
✅ offset_0109MJR_2018_12_13-09_37_28_BB_RR.csv → conservé (115225 lignes)
✅ offset_0110LPR_2019_02_26-08_44_39_BB_RR.csv → conservé (145029 lignes)
✅ offset_0110RMS_2018_12_14-09_38_18_BB_RR.csv → conservé (99332 lignes)
✅ offset_0111MNR_2019_02_28-08_59_20_BB_RR.csv → conservé (140011 lignes)
✅ offset_0112BSR_2019_06_06-08_27_12_BB_RR.csv → conservé (164797 lignes)
✅ offset_0112DRR_2019_02_06-09_34_41_BB_RR.csv → conservé (96779 lignes)
✅ offset_0113BMR_2019_06_20-08_19_13_BB_RR.csv → conservé (135850 lignes)
✅ offset_0113DGR_2018_11_27-09_37_54_BB_RR.csv → conservé (114661 lignes)
✅ offset_0114LMS_2019_06_27-08_36_32_BB_RR.csv → conservé (114082 lignes)
✅ offset_0114MLR_2019_01_07-09_59_01_BB_RR.csv → conservé (124279 lignes)
✅ offset_0115CJR_2019_08_27-08_25_18_BB_RR.csv → conservé (109303 lignes)
✅ offset_0115MHR_2019_01_11-09_39_28_BB_RR.csv → conservé (118439 lignes)
✅ offset_0116CNR_2019_01_10-09_44_24_BB_RR.csv → conservé (127082 lignes)
✅ offset_0116VAR_2019_08_29-08_35_33_BB_RR.csv → conservé (155850 lignes)
✅ offset_0117MSR_2019_01_14-09_44_07_BB_RR.csv → conservé (123100 lignes)
✅ offset_0117POS_2019_09_05-08_21_04_BB_RR.csv → conservé (118868 lignes)
✅ offset_0118TMS_2019_01_16-09_38_48_BB_RR.csv → conservé (125582 lignes)
✅ offset_0118TNS_2019_10_01-08_36_12_BB_RR.csv → conservé (121089 lignes)
✅ offset_0119BIR_2019_01_28-09_32_53_BB_RR.csv → conservé (110493 lignes)
✅ offset_0119LJS_2019_11_07-08_37_31_BB_RR.csv → conservé (117314 lignes)
✅ offset_0120ANS_2019_02_04-09_42_53_BB_RR.csv → conservé (100850 lignes)
✅ offset_0120LCR_2019_12_06-08_25_03_BB_RR.csv → conservé (133886 lignes)
✅ offset_0121MJR_2019_12_12-09_01_38_BB_RR.csv → conservé (125761 lignes)
✅ offset_0121RPS_2019_01_23-09_26_50_BB_RR.csv → conservé (97689 lignes)
✅ offset_0122VCR_2019_02_01-09_34_26_BB_RR.csv → conservé (144190 lignes)
✅ offset_0123GVS_2019_02_08-09_25_58_BB_RR.csv → conservé (90018 lignes)
✅ offset_0123RMS_2019_12_20-08_35_03_BB_RR.csv → conservé (124243 lignes)
✅ offset_0124BAR_2020_01_07-09_42_26_BB_RR.csv → conservé (131332 lignes)
✅ offset_0124PAS_2019_02_15-10_26_07_BB_RR.csv → conservé (94171 lignes)
✅ offset_0125BMR_2020_01_14-11_26_44_BB_RR.csv → conservé (140654 lignes)
✅ offset_0126VLR_2019_03_08-09_35_44_BB_RR.csv → conservé (104225 lignes)
✅ offset_0127CMS_2019_02_21-09_34_58_BB_RR.csv → conservé (96447 lignes)
✅ offset_0128ALS_2019_03_13-09_40_25_BB_RR.csv → conservé (103493 lignes)
✅ offset_0129APR_2019_03_14-09_42_22_BB_RR.csv → conservé (157118 lignes)
✅ offset_0131CPS_2019_12_09-10_03_43_BB_RR.csv → conservé (94600 lignes)
✅ offset_0132GAR_2020_02_19-09_57_21_BB_RR.csv → conservé (99279 lignes)
✅ offset_0133BPS_2020_02_26-10_04_01_BB_RR.csv → conservé (101779 lignes)
✅ offset_0134IFR_2020_03_03-09_35_14_BB_RR.csv → conservé (98332 lignes)
✅ offset_0135KLS_2021_03_03-08_43_04_BB_RR.csv → conservé (97482 lignes)
✅ offset_0136CJR_2021_04_02-09_00_53_BB_RR.csv → conservé (103940 lignes)
✅ offset_0137BMS_2021_04_12-09_58_17_BB_RR (1).csv → conservé (107161 lignes)
✅ offset_0138NWR_2021_06_02-10_11_00_BB_RR.csv → conservé (118917 lignes)
✅ offset_0140LMR_2022_01_13-09_40_17_BB_RR.csv → conservé (127207 lignes)
✅ offset_0143EBR_2022_04_27-11_02_28_BB_RR.csv → conservé (124868 lignes)
✅ offset_0144ZGR_2022_06_29-10_04_46_BB_RR.csv → conservé (159904 lignes)
✅ offset_0301GNR_2019_01_16-10_11_49_BB_RR.csv → conservé (133064 lignes)
✅ offset_0302ZMR_2019_01_24-09_37_03_BB_RR.csv → conservé (114600 lignes)
✅ offset_0303PAR_2019_03_14-09_58_28_BB_RR.csv → conservé (103439 lignes)
✅ offset_0304VMR_2019_03_25-09_49_47_BB_RR.csv → conservé (137386 lignes)
✅ offset_0305LCR_2019_04_25-10_01_08_BB_RR.csv → conservé (114511 lignes)
✅ offset_0306MDR_2019_05_06-14_17_53_BB_RR.csv → conservé (112636 lignes)
✅ offset_0307SMR_2019_05_13-10_23_50_BB_RR (1).csv → conservé (128760 lignes)
✅ offset_0308RGR_2019_06_25-10_55_55_BB_RR.csv → conservé (122243 lignes)
✅ offset_0309DBS_2019_06_27-13_19_31_BB_RR.csv → conservé (134458 lignes)
✅ offset_0310ACS_2019_07_03-09_56_22_BB_RR.csv → conservé (132475 lignes)
✅ offset_0311CJS_2019_07_03-13_38_29_BB_RR.csv → conservé (124850 lignes)
✅ offset_0312JMS_2019_07_22-10_00_05_BB_RR.csv → conservé (110279 lignes)
✅ offset_0313FPR_2019_07_23-14_27_14_BB_RR.csv → conservé (114404 lignes)
✅ offset_0315VCS_2019_08_29-09_50_18_BB_RR (1).csv → conservé (108975 lignes)
✅ offset_0316TMS_2019_09_03-09_46_13_BB_RR (1).csv → conservé (97518 lignes)
✅ offset_0317LGS_2019_09_05-09_39_02_BB_RR (1).csv → conservé (99618 lignes)
✅ offset_0318PMS_2019_09_06-10_21_56_BB_RR (1).csv → conservé (95439 lignes)
✅ offset_0319LJS_2019_09_24-10_11_52_BB_RR (1).csv → conservé (105153 lignes)
✅ offset_0320DGS_2019_10_01-10_20_37_BB_RR.csv → conservé (91493 lignes)
✅ offset_0321DRR_2019_10_08-10_34_34_BB_RR.csv → conservé (103946 lignes)
❌ offset_0323RFS_2020_08_27__09_25_18_BR_RR.csv → trop petit (53043 lignes)
✅ offset_0325LCR_2019_11_15-10_23_10_BB_RR (1).csv → conservé (106975 lignes)
✅ offset_0326BJR_2019_11_22-10_00_52_BB_RR.csv → conservé (113725 lignes)
✅ offset_0327IAR_2019_11_25-09_56_16_BB_RR.csv → conservé (110082 lignes)
✅ offset_0328MPR_2019_12_05-09_47_22_BB_RR.csv → conservé (115332 lignes)
✅ offset_0329NMR_2020_01_28-09_53_10_BB_RR.csv → conservé (121975 lignes)
✅ offset_0330RTR_2020_01_31-09_46_05_BB_RR.csv → conservé (120993 lignes)
✅ offset_0331GRS_2020_02_11-14_54_58_BB_RR.csv → conservé (93261 lignes)
✅ offset_0332MCR_2020_03_06-09_57_45_BB_RR (1).csv → conservé (128850 lignes)
✅ offset_0333MMS_2020_09_25__09_39_30_BR_RR.csv → conservé (98046 lignes)
✅ offset_0334TVS_2020_10_01__09_40_22_BR_RR.csv → conservé (94975 lignes)
✅ offset_0336CBS_2020_10_16__09_43_10_BR_RR.csv → conservé (126261 lignes)
✅ offset_0337BFS_2020_11_24__09_24_38_BR_RR.csv → conservé (156831 lignes)
✅ offset_0339NPR_2021_02_25__09_34_13_BR_RR.csv → conservé (106921 lignes)
✅ offset_0341LJS_2021_05_17__09_42_15_BR_RR.csv → conservé (102868 lignes)
✅ offset_0342VNS_2021_06_01__09_36_33_BR_RR.csv → conservé (119421 lignes)
✅ offset_0343PAS_2021_06_08__09_37_22_BR_RR.csv → conservé (88546 lignes)
✅ offset_0346GLS_2022_01_28__09_25_45_BR_RR.csv → conservé (95636 lignes)
✅ offset_0347DMR_2022_01_31__10_04_24_BR_RR.csv → conservé (115732 lignes)
✅ offset_0348GCR_2022_02_01__10_21_15_BR_RR.csv → conservé (127243 lignes)
✅ offset_0349LLS_2022_02_21__09_57_05_BR_RR.csv → conservé (117778 lignes)
✅ offset_0350MYR_2022_03_18__09_47_48_BR_RR.csv → conservé (112725 lignes)
✅ offset_0351FIR_2022_03_25__10_02_19_BR_RR.csv → conservé (115732 lignes)
✅ offset_0352RNR_2022_04_15__10_01_17_BR_RR.csv → conservé (105778 lignes)
✅ offset_0354GKR_2022_06_27__09_30_41_BR_RR.csv → conservé (116064 lignes)
✅ offset_0355BAS_2022_06_30__09_43_08_BR_RR.csv → conservé (110225 lignes)
✅ offset_0356DMS_2022_09_22__09_44_11_BR_RR.csv → conservé (108232 lignes)
✅ offset_0401TSS_2019_04_05-09_52_46_BB_RR.csv → conservé (154303 lignes)
✅ offset_0402LLS_2019_04_12-11_01_28_BB_RR.csv → conservé (132875 lignes)
✅ offset_0403DCR_2019_05_24-09_36_16_BB_RR.csv → conservé (136089 lignes)
✅ offset_0404CYS_2019_07_19-10_32_55_BB_RR.csv → conservé (166089 lignes)
✅ offset_0405FCR_2019_07_04-09_33_11_BB_RR.csv → conservé (154304 lignes)
✅ offset_0407LJR_2019_09_19-09_38_39_BB_RR.csv → conservé (153232 lignes)
✅ offset_0408BCS_2019_11_22-09_28_20_BB_RR.csv → conservé (145732 lignes)
✅ offset_0409PHR_2019_11_29-09_34_34_BB_RR.csv → conservé (155375 lignes)
✅ offset_0410PGS_2020_01_09-10_03_29_BB_RR.csv → conservé (150017 lignes)
✅ offset_0411VES_2020_02_20-09_42_09_BB_RR.csv → conservé (131636 lignes)
✅ offset_0412ANS_2020_02_21-13_33_48_BB_RR.csv → conservé (126447 lignes)
✅ offset_0413HFS_2020_03_06-09_57_03_BB_RR.csv → conservé (139304 lignes)
✅ offset_0414PVR_2020_01_07__09_15_42_BR_RR.csv → conservé (121404 lignes)
✅ offset_0415HJS_2020_02_11__09_43_13_BR_RR.csv → conservé (105850 lignes)
✅ offset_0415VMR_2020_10_02-09_44_24_BB_RR.csv → conservé (115297 lignes)
✅ offset_0417FAS_2020_02_12__10_41_16_BR_RR.csv → conservé (111154 lignes)
✅ offset_0417KMS_2022_11_24__09_03_09_BR_RR.csv → conservé (106993 lignes)
❌ offset_0418MPR_2020_02_13__09_33_23_BR_RR.csv → trop petit (1785 lignes)
✅ offset_0420MCR_2020_02_28__09_44_26_BR_RR.csv → conservé (128118 lignes)
✅ offset_0421ACS_2020_03_04__10_12_00_BR_RR.csv → conservé (98582 lignes)
✅ offset_0502LIR_2019_02_28-09_42_09_BB_RR.csv → conservé (130565 lignes)
✅ offset_0504BCS_2019_04_23-09_59_09_BB_RR.csv → conservé (122161 lignes)
✅ offset_0505PPR_2019_05_23-09_48_02_BB_RR.csv → conservé (125333 lignes)
✅ offset_0506VMS_2019_05_27-09_37_10_BB_RR.csv → conservé (126261 lignes)
✅ offset_0507BDS_2019_06_24-09_49_35_BB_RR.csv → conservé (138671 lignes)
✅ offset_0508SRR_2019_07_25-09_37_55_BB_RR.csv → conservé (117875 lignes)
✅ offset_0509LGS_2019_10_17-09_30_14_BB_RR.csv → conservé (135832 lignes)
✅ offset_0510DFS_2020_02_20-09_49_46_BB_RR.csv → conservé (116804 lignes)
✅ offset_0511LCS_2021_01_07-10_11_23_BB_RR.csv → conservé (142518 lignes)
✅ offset_0512RCR_Record 2_2021_05_04-08_47_59_BB_RR (1).csv → conservé (118939 lignes)
✅ offset_0513EBS_Record 1_2021_06_18-09_23_29_BB_RR.csv → conservé (105564 lignes)
✅ offset_0626MCS_2020_01_21-09_12_01_BB_RR.csv → conservé (115707 lignes)
✅ offset_0628DMR_2020_01_30-10_11_25_BB_RR.csv → conservé (142518 lignes)
✅ offset_0629TCR_2020_02_04-09_40_12_BB_RR.csv → conservé (143368 lignes)
✅ offset_0630RJR_2020_02_20-10_24_36_BB_RR.csv → conservé (97939 lignes)
✅ offset_0631LHR_2020_02_25-10_54_51_BB_RR.csv → conservé (103946 lignes)
✅ offset_0801HDR_2022_03_23-09_34_20_BB_RR.csv → conservé (123939 lignes)
✅ offset_0803DPS_2022_03_30-09_33_44_BB_RR.csv → conservé (135296 lignes)
✅ offset_0804GOR_2022_04_13-09_22_46_BB_RR.csv → conservé (114660 lignes)
✅ offset_0805BMS_2022_04_15-10_15_16_BB_RR.csv → conservé (100439 lignes)
✅ offset_0806KHS_2022_06_02-09_36_37_BB_RR.csv → conservé (102875 lignes)
✅ offset_0807OMR_2022_06_24-09_39_18_BB_RR.csv → conservé (110047 lignes)
✅ offset_0808PJR_2022_07_15-10_23_12_BB_RR.csv → conservé (121940 lignes)
✅ offset_0902SIS_2022_05_19-09_43_14_BB_RR.csv → conservé (89761 lignes)
✅ offset_0904KJS_2022_06_27-10_13_51_BB_RR.csv → conservé (109458 lignes)
✅ offset_0905SLR_2022_07_04-10_05_54_BB_RR.csv → conservé (120018 lignes)
✅ offset_0906DNR_2022_07_06-10_13_33_BB_RR.csv → conservé (175136 lignes)

====== RÉSUMÉ ======
Fichiers supprimés : 2
Fichiers conservés : 151

# On peut passer au découpage!

In [35]:
'''
Nous pouvons désormais appliquer le découpage présenté au début de ce rapport (figures 2 et 3).
La procédure est la suivante :
— Bloc 1 : commence à la première ligne du fichier tronqué, pour les deux types de signaux. Nous
partons du début et ajoutons la durée du bloc 1, calculée en amont.
— Bloc 2 : ne débute pas immédiatement après la fin du bloc 1. Pour la visite 2, il commence
après le visionnage de la vidéo, et pour la visite 4, après l’exercice d’écriture. Nous décalons
donc le début du bloc 2 de ces durées, puis nous ajoutons la durée du bloc 2.
— Bloc 3 : commence immédiatement à la fin du bloc 2 pour tous les fichiers. Nous ajoutons
simplement la durée du bloc 3.
'''

def decouper_bb_rr_par_bloc(
    df_rr,
    duree_bloc1,
    duree_video,
    duree_bloc2,
    duree_bloc3,
    delta
):
    df_rr = df_rr.copy()

    # ===== Timestamp propre =====
    df_rr["Timestamp"] = pd.to_datetime(
        df_rr["Timestamp"], dayfirst=True, errors="coerce"
    )
    df_rr = df_rr.dropna(subset=["Timestamp"])

    if df_rr.empty:
        return None

    # ===== Temps de référence =====
    t0 = df_rr["Timestamp"].min()
    t_fin_rr = df_rr["Timestamp"].max()

    # ===== Bornes temporelles =====
    fin_bloc1 = t0 + pd.Timedelta(seconds=max(0, duree_bloc1 - delta))
    debut_bloc2 = fin_bloc1 + pd.Timedelta(seconds=duree_video)
    fin_bloc2 = debut_bloc2 + pd.Timedelta(seconds=duree_bloc2)
    fin_bloc3 = fin_bloc2 + pd.Timedelta(seconds=duree_bloc3)

    # Sécurité (ne jamais dépasser le fichier)
    fin_bloc3 = min(fin_bloc3, t_fin_rr)

    

    return {
        "bloc1": df_rr[
            (df_rr["Timestamp"] >= t0) &
            (df_rr["Timestamp"] < fin_bloc1)
        ],
        "bloc2": df_rr[
            (df_rr["Timestamp"] >= debut_bloc2) &
            (df_rr["Timestamp"] < fin_bloc2)
        ],
        "bloc3": df_rr[
            (df_rr["Timestamp"] >= fin_bloc2) &
            (df_rr["Timestamp"] < fin_bloc3)
        ],
        "bornes": {
            "t0": t0,
            "fin_bloc1": fin_bloc1,
            "debut_bloc2": debut_bloc2,
            "fin_bloc2": fin_bloc2,
            "fin_bloc3": fin_bloc3,
            "t_fin_rr": t_fin_rr
        }
    }

In [36]:
def convertir_et_normaliser_heure(x):
    """
    Convertit n'importe quel format d'heure Excel / texte / datetime en pd.Timestamp
    normalisé sur le 1900-01-01, ne gardant que l'heure, minute, seconde.
    """
    if pd.isna(x):
        return pd.NaT

    # Excel numérique → fraction de jour ou date complète
    if isinstance(x, (int, float)):
        seconds = (float(x) * 24 * 3600) % (24*3600)
        return pd.Timestamp("1900-01-01") + pd.to_timedelta(seconds, unit="s")

    # Timestamp ou datetime → on garde juste l'heure
    if isinstance(x, (pd.Timestamp, datetime.datetime)):
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=x.hour, minute=x.minute, second=x.second
        )

    # Texte
    try:
        t = pd.to_datetime(str(x).strip(), errors="coerce")
        if pd.isna(t):
            return pd.NaT
        return pd.Timestamp(
            year=1900, month=1, day=1,
            hour=t.hour, minute=t.minute, second=t.second
        )
    except Exception:
        return pd.NaT

In [37]:
def get_durees_blocs(pid, feuille):
    """
    Récupère les durées pour les 3 blocs et la vidéo pour un Numero_inclusion donné et une feuille donnée.
    Applique un correctif spécifique pour 0101EMS car il ya un problème dans la conversion en temps d'une de ses cases
    """
    pid = str(pid).upper()

    # ===== Bloc 1 =====
    df_b1 = pd.DataFrame(resultats_bloc1[feuille]["df"])
    ligne = df_b1.loc[df_b1["Numero_inclusion"].str.upper() == pid]

    if ligne.empty:
        raise ValueError(f"PID {pid} absent du bloc 1 dans la feuille {feuille}")

    d1 = ligne["duree_bloc1"].values[0]
    condition = ligne["Condition"].values[0]

    # ===== Durée vidéo =====
    t_fin_anamnese = convertir_et_normaliser_heure(
        ligne["heure_fin_anamnese_v2"].values[0]
    )
    t_debut_rlri = convertir_et_normaliser_heure(
        ligne["heure_rlri16imm_debut_V2"].values[0]
    )

    if pd.notna(t_fin_anamnese) and pd.notna(t_debut_rlri):
        delta = (t_debut_rlri - t_fin_anamnese) / pd.Timedelta(seconds=1)  # en secondes
        if delta < 0:
            delta += 24*3600
    else:
        delta = 0
    duree_video_sec = delta

    # ===== Bloc 2 =====
    if condition == "Standard":
        df_b2 = pd.DataFrame(resultats_bloc2_S[feuille]["df"])
        duree_col = "duree_bloc2S"
    else:
        df_b2 = pd.DataFrame(resultats_bloc2_R[feuille]["df"])
        duree_col = "duree_bloc2R"

    # ===== Récupérer d2 normalement =====
    d2 = df_b2.loc[df_b2["Numero_inclusion"].str.upper() == pid, duree_col].values[0]

    # ===== Bloc 3 =====
    df_b3 = pd.DataFrame(resultats_bloc3[feuille]["df"])
    d3 = df_b3.loc[df_b3["Numero_inclusion"].str.upper() == pid, "duree_bloc3"].values[0]

    return {
        "bloc1_sec": d1 * 60,
        "video_sec": duree_video_sec,
        "bloc2_sec": d2 * 60,
        "bloc3_sec": d3 * 60,
        "condition": condition
    }

In [38]:
# ===== Dossiers =====
input_dir = os.path.join(os.path.expanduser("~"), "Desktop", "bb_rr_tronqués_v2")
output_dir = os.path.join(os.path.expanduser("~"), "Desktop", "bb_rr_tronque_blocs_v2")
os.makedirs(output_dir, exist_ok=True)

resultats_decoupage = {}

# ===== Boucle UNIQUEMENT sur les fichiers tronqués =====
for fichier in os.listdir(input_dir):

    if not fichier.lower().endswith(".csv"):
        continue

    chemin_bb_rr = os.path.join(input_dir, fichier)

    # ===== Extraction PID depuis le nom =====
    match = re.search(r"\d{4}[A-Z]{3}", fichier.upper())
    if not match:
        print(f"⚠️ PID introuvable dans {fichier}")
        continue

    pid = match.group()

    # ===== Récupération de la feuille associée =====
    ligne = df_global.loc[df_global["Numero_inclusion"] == pid]
    if ligne.empty:
        print(f"⚠️ Feuille introuvable pour {pid}")
        continue

    feuille = ligne["Feuille"].values[0]

    print(f"\n--- Découpage {pid} ({feuille}) ---")

    # ===== Lecture BB_RR =====
    try:
        df_rr = pd.read_csv(chemin_bb_rr)
    except Exception as e:
        print(f"❌ Lecture impossible {pid} : {e}")
        continue

    # ===== Récupération des durées =====
    try:
        durees = get_durees_blocs(pid, feuille)
    except Exception as e:
        print(f"⚠️ Impossible de récupérer les durées pour {pid} ({feuille}) : {e}")
        continue

    delta_row = df_offset_bb_rr.loc[df_offset_bb_rr["Numero_inclusion"].str.upper() == pid.upper()]
    if delta_row.empty:
        delta_val = 0
    else:
        delta_val = float(delta_row["delta_retard_sec"].values[0])
        
    # ===== Découpage =====
    decoupe = decouper_bb_rr_par_bloc(
        df_rr=df_rr,
        duree_bloc1=durees["bloc1_sec"],
        duree_video=durees["video_sec"],
        duree_bloc2=durees["bloc2_sec"],
        duree_bloc3=durees["bloc3_sec"],
        delta = delta_val
    )

    if decoupe is None:
        print(f"⚠️ Découpage vide pour {pid}")
        continue

    # ===== Sauvegarde par bloc =====
    for bloc in ["bloc1", "bloc2", "bloc3"]:
        df_bloc = decoupe[bloc]

        if df_bloc.empty:
            print(f"⚠️ {pid} {bloc} vide")
            continue

        nom_sortie = f"{pid}_{bloc}.csv"
        df_bloc.to_csv(
            os.path.join(output_dir, nom_sortie),
            index=False
        )

    # ===== Stockage mémoire =====
    resultats_decoupage[pid] = decoupe

    print(
        f"✔ {pid} | "
        f"B1={len(decoupe['bloc1'])} | "
        f"B2={len(decoupe['bloc2'])} | "
        f"B3={len(decoupe['bloc3'])}"
    )

print("\n✅ Découpage terminé")
print("📁 Résultats dans :", output_dir)

--- Découpage 0101CAR (APHM) ---
✔ 0101CAR | B1=27750 | B2=68572 | B3=64286

--- Découpage 0101EMS (LPC) ---
✔ 0101EMS | B1=23875 | B2=39643 | B3=45000

--- Découpage 0102PCR (APHM) ---
✔ 0102PCR | B1=28840 | B2=45000 | B3=53572

--- Découpage 0103BPS (LPC) ---
✔ 0103BPS | B1=12536 | B2=36428 | B3=41786

--- Découpage 0103SHS (APHM) ---
✔ 0103SHS | B1=10733 | B2=40714 | B3=46072

--- Découpage 0104FJS (APHM) ---
✔ 0104FJS | B1=30393 | B2=66429 | B3=73928

--- Découpage 0104IBS (LPC) ---
✔ 0104IBS | B1=17143 | B2=34286 | B3=45000

--- Découpage 0105PNR (APHM) ---
✔ 0105PNR | B1=26179 | B2=43929 | B3=50357

--- Découpage 0106DJR (LPC) ---
✔ 0106DJR | B1=17679 | B2=40714 | B3=50357

--- Découpage 0106JLS (APHM) ---
✔ 0106JLS | B1=17518 | B2=72857 | B3=42857

--- Découpage 0107DSS (APHM) ---
✔ 0107DSS | B1=20358 | B2=61071 | B3=47143

--- Découpage 0108BFS (APHM) ---
✔ 0108BFS | B1=17143 | B2=53571 | B3=69643

--- Découpage 0108MMS (LPC) ---
✔ 0108MMS | B1=10143 | B2=36428 | B3=48215

--- Découpage 0109GSS (APHM) ---
✔ 0109GSS | B1=26197 | B2=51428 | B3=54643

--- Découpage 0109MJR (LPC) ---
✔ 0109MJR | B1=13429 | B2=39643 | B3=52500

--- Découpage 0110LPR (APHM) ---
✔ 0110LPR | B1=28233 | B2=48214 | B3=61072

--- Découpage 0110RMS (LPC) ---
✔ 0110RMS | B1=10393 | B2=42857 | B3=45000

--- Découpage 0111MNR (APHM) ---
✔ 0111MNR | B1=29643 | B2=48214 | B3=53571

--- Découpage 0112BSR (APHM) ---
✔ 0112BSR | B1=64072 | B2=36429 | B3=56786

--- Découpage 0112DRR (LPC) ---
✔ 0112DRR | B1=9983 | B2=33214 | B3=45000

--- Découpage 0113BMR (APHM) ---
✔ 0113BMR | B1=24411 | B2=50357 | B3=52500

--- Découpage 0113DGR (LPC) ---
✔ 0113DGR | B1=20358 | B2=39643 | B3=41785

--- Découpage 0114LMS (APHM) ---
✔ 0114LMS | B1=21929 | B2=40714 | B3=49286

--- Découpage 0114MLR (LPC) ---
✔ 0114MLR | B1=19268 | B2=42858 | B3=55714

--- Découpage 0115CJR (APHM) ---
✔ 0115CJR | B1=10715 | B2=47143 | B3=41786

--- Découpage 0115MHR (LPC) ---
✔ 0115MHR | B1=19858 | B2=41785 | B3=48215

--- Découpage 0116CNR (LPC) ---
✔ 0116CNR | B1=12429 | B2=43929 | B3=62142

--- Découpage 0116VAR (APHM) ---
✔ 0116VAR | B1=40125 | B2=45000 | B3=62143

--- Découpage 0117MSR (LPC) ---
✔ 0117MSR | B1=21304 | B2=40714 | B3=54643

--- Découpage 0117POS (APHM) ---
✔ 0117POS | B1=23500 | B2=47143 | B3=47143

--- Découpage 0118TMS (LPC) ---
✔ 0118TMS | B1=30215 | B2=39643 | B3=55714

--- Découpage 0118TNS (APHM) ---
✔ 0118TNS | B1=27858 | B2=38571 | B3=53572

--- Découpage 0119BIR (LPC) ---
✔ 0119BIR | B1=15125 | B2=40714 | B3=47143

--- Découpage 0119LJS (APHM) ---
✔ 0119LJS | B1=21947 | B2=42857 | B3=50357

--- Découpage 0120ANS (LPC) ---
✔ 0120ANS | B1=16197 | B2=33215 | B3=50357

--- Découpage 0120LCR (APHM) ---
✔ 0120LCR | B1=34233 | B2=42857 | B3=51428

--- Découpage 0121MJR (APHM) ---
✔ 0121MJR | B1=20750 | B2=42858 | B3=54642

--- Découpage 0121RPS (LPC) ---
✔ 0121RPS | B1=11965 | B2=37500 | B3=47143

--- Découpage 0122VCR (LPC) ---
✔ 0122VCR | B1=29536 | B2=47143 | B3=60000

--- Découpage 0123GVS (LPC) ---
✔ 0123GVS | B1=13929 | B2=35357 | B3=40714

--- Découpage 0123RMS (APHM) ---
✔ 0123RMS | B1=22447 | B2=56786 | B3=43929

--- Découpage 0124BAR (APHM) ---
✔ 0124BAR | B1=17750 | B2=48215 | B3=54642

--- Découpage 0124PAS (LPC) ---
✔ 0124PAS | B1=12733 | B2=37500 | B3=43928

--- Découpage 0125BMR (APHM) ---
✔ 0125BMR | B1=29215 | B2=58929 | B3=45000

--- Découpage 0126VLR (LPC) ---
✔ 0126VLR | B1=20643 | B2=34286 | B3=41785

--- Découpage 0127CMS (LPC) ---
✔ 0127CMS | B1=16072 | B2=37500 | B3=42857

--- Découpage 0128ALS (LPC) ---
✔ 0128ALS | B1=12411 | B2=38572 | B3=52500

--- Découpage 0129APR (LPC) ---
✔ 0129APR | B1=29608 | B2=56786 | B3=61071

--- Découpage 0131CPS (LPC) ---
✔ 0131CPS | B1=12090 | B2=39643 | B3=41786

--- Découpage 0132GAR (LPC) ---
✔ 0132GAR | B1=12483 | B2=35357 | B3=42857

--- Découpage 0133BPS (LPC) ---
✔ 0133BPS | B1=16054 | B2=35358 | B3=49285

--- Découpage 0134IFR (LPC) ---
✔ 0134IFR | B1=12608 | B2=36428 | B3=42857

--- Découpage 0135KLS (LPC) ---
✔ 0135KLS | B1=16000 | B2=38571 | B3=41838

--- Découpage 0136CJR (LPC) ---
✔ 0136CJR | B1=11786 | B2=41785 | B3=42858

--- Découpage 0137BMS (LPC) ---
✔ 0137BMS | B1=13929 | B2=40715 | B3=51428

--- Découpage 0138NWR (LPC) ---
✔ 0138NWR | B1=12858 | B2=46071 | B3=54630

--- Découpage 0140LMR (LPC) ---
✔ 0140LMR | B1=23268 | B2=46071 | B3=51429

--- Découpage 0143EBR (LPC) ---
✔ 0143EBR | B1=15572 | B2=47143 | B3=54643

--- Découpage 0144ZGR (LPC) ---
✔ 0144ZGR | B1=28108 | B2=64285 | B3=61072

--- Découpage 0301GNR (CAEN) ---
✔ 0301GNR | B1=19483 | B2=51428 | B3=53572

--- Découpage 0302ZMR (CAEN) ---
✔ 0302ZMR | B1=10661 | B2=47143 | B3=49286

--- Découpage 0303PAR (CAEN) ---
✔ 0303PAR | B1=23072 | B2=46072 | B3=23571

--- Découpage 0304VMR (CAEN) ---
✔ 0304VMR | B1=23804 | B2=49286 | B3=48214

--- Découpage 0305LCR (CAEN) ---
✔ 0305LCR | B1=12715 | B2=47143 | B3=42857

--- Découpage 0306MDR (CAEN) ---
✔ 0306MDR | B1=11911 | B2=48214 | B3=48214

--- Découpage 0307SMR (CAEN) ---
✔ 0307SMR | B1=23750 | B2=40714 | B3=57857

--- Découpage 0308RGR (CAEN) ---
✔ 0308RGR | B1=25804 | B2=34286 | B3=50357

--- Découpage 0309DBS (CAEN) ---
✔ 0309DBS | B1=29447 | B2=54643 | B3=47143

--- Découpage 0310ACS (CAEN) ---
✔ 0310ACS | B1=21036 | B2=54643 | B3=56786

--- Découpage 0311CJS (CAEN) ---
✔ 0311CJS | B1=23054 | B2=47143 | B3=54643

--- Découpage 0312JMS (CAEN) ---
✔ 0312JMS | B1=10625 | B2=50358 | B3=49285

--- Découpage 0313FPR (CAEN) ---
✔ 0313FPR | B1=14750 | B2=41786 | B3=51428

--- Découpage 0315VCS (CAEN) ---
✔ 0315VCS | B1=13608 | B2=49285 | B3=46072

--- Découpage 0316TMS (CAEN) ---
✔ 0316TMS | B1=11786 | B2=36428 | B3=48214

--- Découpage 0317LGS (CAEN) ---
✔ 0317LGS | B1=13893 | B2=40715 | B3=45000

--- Découpage 0318PMS (CAEN) ---
✔ 0318PMS | B1=15072 | B2=37500 | B3=42857

--- Découpage 0319LJS (CAEN) ---
✔ 0319LJS | B1=14072 | B2=42857 | B3=48214

--- Découpage 0320DGS (CAEN) ---
✔ 0320DGS | B1=10054 | B2=36429 | B3=43929

--- Découpage 0321DRR (CAEN) ---
✔ 0321DRR | B1=12858 | B2=39643 | B3=42857

--- Découpage 0325LCR (CAEN) ---
✔ 0325LCR | B1=12679 | B2=39642 | B3=48215

--- Découpage 0326BJR (CAEN) ---
✔ 0326BJR | B1=17286 | B2=45000 | B3=45000

--- Découpage 0327IAR (CAEN) ---
✔ 0327IAR | B1=9358 | B2=37500 | B3=53571

--- Découpage 0328MPR (CAEN) ---
✔ 0328MPR | B1=18893 | B2=39643 | B3=49285

--- Découpage 0329NMR (CAEN) ---
✔ 0329NMR | B1=23393 | B2=45000 | B3=48215

--- Découpage 0330RTR (CAEN) ---
✔ 0330RTR | B1=21340 | B2=41786 | B3=50357

--- Découpage 0331GRS (CAEN) ---
✔ 0331GRS | B1=10750 | B2=37500 | B3=45000

--- Découpage 0332MCR (CAEN) ---
✔ 0332MCR | B1=24911 | B2=40714 | B3=55714

--- Découpage 0333MMS (CAEN) ---
✔ 0333MMS | B1=16607 | B2=49285 | B3=32143

--- Découpage 0334TVS (CAEN) ---
✔ 0334TVS | B1=21035 | B2=35357 | B3=38572

--- Découpage 0336CBS (CAEN) ---
✔ 0336CBS | B1=23392 | B2=45000 | B3=57858

--- Découpage 0337BFS (CAEN) ---
✔ 0337BFS | B1=43250 | B2=51428 | B3=58929

--- Découpage 0339NPR (CAEN) ---
✔ 0339NPR | B1=21196 | B2=36429 | B3=31071

--- Découpage 0341LJS (CAEN) ---
✔ 0341LJS | B1=19285 | B2=35357 | B3=47143

--- Découpage 0342VNS (CAEN) ---
✔ 0342VNS | B1=26196 | B2=41786 | B3=50357

--- Découpage 0343PAS (CAEN) ---
✔ 0343PAS | B1=15678 | B2=38571 | B3=33214

--- Découpage 0346GLS (CAEN) ---
✔ 0346GLS | B1=25982 | B2=42857 | B3=26786

--- Découpage 0347DMR (CAEN) ---
✔ 0347DMR | B1=18214 | B2=39643 | B3=48214

--- Découpage 0348GCR (CAEN) ---
✔ 0348GCR | B1=34017 | B2=55715 | B3=30000

--- Découpage 0349LLS (CAEN) ---
✔ 0349LLS | B1=26696 | B2=39643 | B3=51428

--- Découpage 0350MYR (CAEN) ---
✔ 0350MYR | B1=15214 | B2=39643 | B3=49285

--- Découpage 0351FIR (CAEN) ---
✔ 0351FIR | B1=27857 | B2=36429 | B3=48214

--- Découpage 0352RNR (CAEN) ---
✔ 0352RNR | B1=15767 | B2=38571 | B3=45000

--- Découpage 0354GKR (CAEN) ---
✔ 0354GKR | B1=24982 | B2=37500 | B3=46072

--- Découpage 0355BAS (CAEN) ---
✔ 0355BAS | B1=18071 | B2=40714 | B3=51429

--- Découpage 0356DMS (CAEN) ---
✔ 0356DMS | B1=16071 | B2=40714 | B3=51429

--- Découpage 0401TSS (POITIERS) ---
✔ 0401TSS | B1=26786 | B2=63214 | B3=63214

--- Découpage 0402LLS (POITIERS) ---
✔ 0402LLS | B1=23572 | B2=58929 | B3=49286

--- Découpage 0403DCR (POITIERS) ---
✔ 0403DCR | B1=31072 | B2=41786 | B3=52500

--- Découpage 0404CYS (POITIERS) ---
✔ 0404CYS | B1=36429 | B2=60000 | B3=67500

--- Découpage 0405FCR (POITIERS) ---
✔ 0405FCR | B1=30000 | B2=47143 | B3=65357

--- Découpage 0407LJR (POITIERS) ---
✔ 0407LJR | B1=36429 | B2=46071 | B3=57857

--- Découpage 0408BCS (POITIERS) ---
✔ 0408BCS | B1=40715 | B2=50357 | B3=53572

--- Découpage 0409PHR (POITIERS) ---
✔ 0409PHR | B1=26786 | B2=51429 | B3=66428

--- Découpage 0410PGS (POITIERS) ---
✔ 0410PGS | B1=43929 | B2=61072 | B3=43928

--- Découpage 0411VES (POITIERS) ---
✔ 0411VES | B1=38411 | B2=39643 | B3=47142

--- Découpage 0412ANS (POITIERS) ---
✔ 0412ANS | B1=33215 | B2=39642 | B3=51429

--- Découpage 0413HFS (POITIERS) ---
✔ 0413HFS | B1=36429 | B2=49286 | B3=52500

--- Découpage 0414PVR (CERCA) ---
✔ 0414PVR | B1=14250 | B2=46071 | B3=52500

--- Découpage 0415HJS (CERCA) ---
✔ 0415HJS | B1=12625 | B2=41786 | B3=51429

--- Découpage 0415VMR (POITIERS) ---
✔ 0415VMR | B1=21000 | B2=37500 | B3=49286

--- Découpage 0417FAS (CERCA) ---
✔ 0417FAS | B1=22215 | B2=38572 | B3=49285

--- Découpage 0417KMS (CERCA) ---
✔ 0417KMS | B1=11625 | B2=40714 | B3=53572

--- Découpage 0420MCR (CERCA) ---
✔ 0420MCR | B1=33822 | B2=38571 | B3=49286

--- Découpage 0421ACS (CERCA) ---
✔ 0421ACS | B1=13929 | B2=38571 | B3=46072

--- Découpage 0502LIR (ROUEN) ---
✔ 0502LIR | B1=24483 | B2=40714 | B3=52500

--- Découpage 0504BCS (ROUEN) ---
✔ 0504BCS | B1=34286 | B2=40714 | B3=45000

--- Découpage 0505PPR (ROUEN) ---
✔ 0505PPR | B1=25679 | B2=36428 | B3=54643

--- Découpage 0506VMS (ROUEN) ---
✔ 0506VMS | B1=13750 | B2=48214 | B3=58928

--- Découpage 0507BDS (ROUEN) ---
✔ 0507BDS | B1=40090 | B2=45000 | B3=53571

--- Découpage 0508SRR (ROUEN) ---
✔ 0508SRR | B1=25715 | B2=36428 | B3=48215

--- Découpage 0509LGS (ROUEN) ---
✔ 0509LGS | B1=38322 | B2=37500 | B3=58929

--- Découpage 0510DFS (ROUEN) ---
✔ 0510DFS | B1=20358 | B2=47143 | B3=48214

--- Découpage 0511LCS (ROUEN) ---
✔ 0511LCS | B1=33215 | B2=34286 | B3=73928

--- Découpage 0512RCR (ROUEN) ---
✔ 0512RCR | B1=24643 | B2=39643 | B3=47143

--- Découpage 0513EBS (ROUEN) ---
✔ 0513EBS | B1=23054 | B2=37500 | B3=45000

--- Découpage 0626MCS (LAVERAN) ---
✔ 0626MCS | B1=23554 | B2=41786 | B3=49286

--- Découpage 0628DMR (LAVERAN) ---
✔ 0628DMR | B1=22500 | B2=53571 | B3=57858

--- Découpage 0629TCR (LAVERAN) ---
✔ 0629TCR | B1=25500 | B2=55714 | B3=55715

--- Découpage 0630RJR (LAVERAN) ---
✔ 0630RJR | B1=11143 | B2=38572 | B3=42857

--- Découpage 0631LHR (LAVERAN) ---
✔ 0631LHR | B1=21429 | B2=32142 | B3=43929

--- Découpage 0801HDR (SAINTE-MARGUERITE) ---
✔ 0801HDR | B1=20000 | B2=33214 | B3=47143

--- Découpage 0803DPS (SAINTE-MARGUERITE) ---
✔ 0803DPS | B1=11000 | B2=60000 | B3=64286

--- Découpage 0804GOR (SAINTE-MARGUERITE) ---
✔ 0804GOR | B1=22500 | B2=37500 | B3=36429

--- Découpage 0805BMS (SAINTE-MARGUERITE) ---
✔ 0805BMS | B1=15786 | B2=34286 | B3=47143

--- Découpage 0806KHS (SAINTE-MARGUERITE) ---
✔ 0806KHS | B1=12858 | B2=49286 | B3=39643

--- Découpage 0807OMR (SAINTE-MARGUERITE) ---
✔ 0807OMR | B1=18965 | B2=40715 | B3=42857

--- Découpage 0808PJR (SAINTE-MARGUERITE) ---
✔ 0808PJR | B1=21215 | B2=40714 | B3=54643

--- Découpage 0902SIS (CGD) ---
✔ 0902SIS | B1=34036 | B2=36428 | B3=18214

--- Découpage 0904KJS (CGD) ---
✔ 0904KJS | B1=20518 | B2=39643 | B3=48214

--- Découpage 0905SLR (CGD) ---
✔ 0905SLR | B1=15000 | B2=47143 | B3=51428

--- Découpage 0906DNR (CGD) ---
✔ 0906DNR | B1=52983 | B2=57857 | B3=47143

✅ Découpage terminé
📁 Résultats dans : C:\Users\judupont\Desktop\bb_rr_tronque_blocs_v2

# DATA FRAME DIRECT 
lignes_globales = []

for pid, decoupe in resultats_decoupage.items():

    # ===== Condition =====
    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    # ===== Offset =====
    offset_sec = abs(
        df_controle_durees.loc[
            df_controle_durees["Numero_inclusion"] == pid,
            "ecart_sec"
        ].values[0]
    )

    bornes = decoupe["bornes"]

    for nom_bloc in ["bloc1", "bloc2", "bloc3"]:

        df_bloc = decoupe[nom_bloc]

        if df_bloc.empty:
            continue

        # =====================================================
        # CAS 1 : RR fourni par l'appareil (RtoR)
        # =====================================================
        if "RtoR" in df_bloc.columns:

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row["Timestamp"],
                    "RtoR": row["RtoR"],      
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 2 : RR calculé (temps_ms / rr_ms)
        # =====================================================
        elif {"temps_ms", "rr_ms"}.issubset(df_bloc.columns):

            for _, row in df_bloc.iterrows():
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": row.get("Timestamp", pd.NaT),
                    "RtoR": row["rr_ms"] / 1000,  # ms → sec
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

        # =====================================================
        # CAS 3 : Timestamp seul
        # =====================================================
        else:
            for ts in df_bloc["Timestamp"]:
                lignes_globales.append({
                    "Numero_inclusion": pid,
                    "Condition": condition,
                    "Bloc": nom_bloc,
                    "Timestamp": ts,
                    "RtoR": None,
                    "offset_sec": offset_sec,
                    "t0": bornes["t0"],
                    "fin_bloc": bornes.get(f"fin_{nom_bloc}")
                })

df_rr_global = pd.DataFrame(lignes_globales)

# DATA FRAME IMBRIQUE
lignes_patients = []

for pid, decoupe in resultats_decoupage.items():

    durees = get_durees_blocs(pid, "APHM")
    condition = durees["condition"]

    lignes_patients.append({
        "Numero_inclusion": pid,
        "Condition": condition,
        "baseline": decoupe["bloc1"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc2": decoupe["bloc2"][["Timestamp", "RtoR"]].reset_index(drop=True),
        "bloc3": decoupe["bloc3"][["Timestamp", "RtoR"]].reset_index(drop=True),
    })

df_patients = pd.DataFrame(lignes_patients)

In [ ]:
## Traitment pour passer le fichier dans kubios